### ISSUE TITLE
EPUB 3.3 Recommendation with Candidate Corrections  2024-10-17 > 2024-12-19

### ISSUE THREAD

**Issue by iherman** [w3ctag/design-reviews#1006]
こんにちは TAG-さん!

The Publishing Maintenance Working Group[1] has just published an updated version of the EPUB 3.3
Recommendation with Candidate Corrections:

- https://www.w3.org/TR/2024/REC-epub-33-20241017/

The Working Group would ask for an official horizontal review concentrating on the candidate 
changes before going to the Proposed Corrections phase (which also involves an AC review).
 (The "base" version of the Recommendation has already been reviewed by the TAG.)

The candidate changes, with a reference to the relevant issue discussions, are:

- https://www.w3.org/TR/2024/REC-epub-33-20241017/#change_1
- https://www.w3.org/TR/2024/REC-epub-33-20241017/#change_2
- https://www.w3.org/TR/2024/REC-epub-33-20241017/#change_3
- https://www.w3.org/TR/2024/REC-epub-33-20241017/#change_4

See also the change log [2].

For information, the Working Group would like to issue a Proposed Corrections version 
before the end of the current year. We would appreciate it if your review would be done within
that timeframe.

[1] https://www.w3.org/groups/wg/pm
[2] https://www.w3.org/TR/2024/REC-epub-33-20241017/#change-log

**Comment by hadleybeeman** [comment]
Thank you for bringing this our way. We've filed a (PR regarding one minor point on white space)[https://github.com/whatwg/infra/pull/649]. However on the whole, we don't think there are any architectural concerns here. Thanks for flying TAG.
