### ISSUE TITLE
Customizable select element

### ISSUE THREAD

**Issue by josepharhar** [w3ctag/design-reviews#1007]
こんにちは TAG-さん!

I'm requesting a TAG review of customizable select element.

Customizable select is an HTML parser change and a CSS property to make the select element render additional content and be fully stylable. Here is a basic example:

```html
<select>
  <button>
    <selectedoption></selectedoption>
  </button>
  <option><img src="...">Orange</option>
  <option><img src="...">Banana</option>
</select>
<style>
select, ::picker(select) {
  appearance: base-select;
}
</style>
```

  - Explainer¹: https://open-ui.org/components/customizableselect/
  - Specification: List of spec PRs in the issue description here: https://github.com/whatwg/html/issues/9799
  - WPT Tests: https://wpt.fyi/results/html/semantics/forms/the-select-element/customizable-select
  - User research:
  - Security and Privacy self-review²: TODO
  - GitHub repo:
    - https://github.com/whatwg/html
    - https://github.com/w3c/csswg-drafts
    - https://github.com/openui/open-ui
  - Primary contacts:
      - Joey Arhar (@josepharhar) Google
  - Organization/project driving the specification: Google, Microsoft, OpenUI community group
  - Multi-stakeholder support³:
    - Chromium comments: Yes
    - Mozilla comments: https://github.com/mozilla/standards-positions/issues/1060
    - WebKit comments: https://github.com/WebKit/standards-positions/issues/386
    - Feedback from developers is present in most of the OpenUI issues about this project: https://github.com/openui/open-ui/issues?q=is%3Aissue+label%3Aselect
  - Status/issue trackers for implementations⁴: https://chromestatus.com/feature/5737365999976448

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines:
  - The group where the work on this specification is currently being done: WHATWG, CSSWG, and OpenUI CG
  - The group where standardization of this work is intended to be done (if different from the current group): WHATWG and CSSWG
  - Major unresolved issues with or opposition to this specification:
  - This work is being funded by: Google

**Comment by jyasskin** [comment]
We're excited to see `<select>` become customizable. We were slightly concerned about the prospect of nested interactive content, but we see that you're paying attention to the problem in https://github.com/whatwg/html/issues/10317. It seems like this is being discussed among all the right people, so we have no further concerns. Good luck rolling this out!
