### ISSUE TITLE
 Vision for W3C: request horizontal architectural review and wide TAG review

### ISSUE THREAD

**Issue by tantek** [w3ctag/design-reviews#1008]
こんにちは TAG-さん!

I'm requesting a TAG review of  Vision for W3C, which does not contain any technical features, thus any fields below relating to technical features or technical implementation have been marked N/A.

The W3C Vision articulates W3C’s mission, what W3C is, what it does and why that matters, and the values and principles by which it operates and makes decisions.

  - Explainer¹: https://www.w3.org/wiki/AB/2025_Priorities#Vision
  - Specification: https://www.w3.org/TR/w3c-vision/
  - WPT Tests: N/A
  - User research: N/A
  - Security and Privacy self-review²: N/A
  - GitHub repo: https://github.com/w3c/AB-public/tree/main/Vision
  - Primary contacts:
      - Tantek Çelik (@tantek), Mozilla, Primary Editor
      - Max Gendler (@mgendler), The News Corporation , VisionTF Chair
  - Organization/project driving the specification: W3C Advisory Board
  - Multi-stakeholder support³: 
    - Chromium comments: N/A
    - Mozilla comments: N/A
    - WebKit comments: N/A
    - Open issues: https://github.com/w3c/AB-public/issues/
  - Status/issue trackers for implementations⁴: N/A

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: 2024-11-20 (28 days standard minimum horizontal review period)
  - The group where the work on this specification is currently being done: https://www.w3.org/wiki/AB/VisionTF
  - The group where standardization of this work is intended to be done: https://www.w3.org/wiki/AB
  - Major unresolved issues with or opposition to this specification: https://github.com/w3c/AB-public/issues?q=is%3Aissue+is%3Aopen+label%3A%22Project+Vision%22+-label%3ADefer
  - This work is being funded by: Individual VisionTF and AB Members time

You should also know that...

This document builds on the basis of the Technical Architecture Group’s excellent [Ethical Web Principles](https://www.w3.org/TR/ethical-web-principles/). It is not intended to supplant that work nor redefine it, but fit into the same framework and promote many of the same goals.

------------------------------------------------------------------------------------

**Comment by jyasskin** [comment]
We're going to need more time to finish our review. We currently have some draft points, which we're going to file as individual issues in https://github.com/w3c/AB-public/issues?q=is%3Aissue+is%3Aopen+label%3A%22Project+Vision%22, and then we're planning to find TAG consensus on how serious they are by Dec 5.
