### ISSUE TITLE
CSS :open pseudo-class

### ISSUE THREAD

**Issue by josepharhar** [w3ctag/design-reviews#1010]
こんにちは TAG-さん!

I'm requesting a TAG review of CSS :open pseudo-class.

This pseudo-class applies to HTML elements which have an "open" state. For `<details>`, this is when the element is expanded. For `<dialog>`, this is when the element is showing. For `<select>`, this is when the picker is showing.

  - Explainer¹: none
  - Specification: https://drafts.csswg.org/selectors-4/#open-state
  - WPT Tests: https://wpt.fyi/results/css/selectors/open-closed-pseudo.html
  - User research: none
  - Security and Privacy self-review²:
  - GitHub repo: https://github.com/w3c/csswg-drafts/
  - Primary contacts:
      - Joey Arhar @josepharhar Google
  - Organization/project driving the specification: Google
  - Multi-stakeholder support³:
    - Chromium comments: yes
    - Mozilla comments: https://github.com/mozilla/standards-positions/issues/1085
    - WebKit comments: https://github.com/WebKit/standards-positions/issues/413
  - Status/issue trackers for implementations⁴: https://chromestatus.com/feature/5085419215781888

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines:
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if different from the current group):
  - Major unresolved issues with or opposition to this specification: https://github.com/w3c/csswg-drafts/issues/11039
  - This work is being funded by: Google

**Comment by plinss** [comment]
We looked at this in a breakout today and don't see any issues. Closing as satisfied.

We did note https://github.com/w3c/csswg-drafts/issues/11039 and agree that if `:not(:open)` is equivalent to `:closed` then `:closed` isn't necessary and probably should be removed. However if it's possible that an element could be in a state that's neither open or closed, then they're not exactly equivalent and `:closed` has a purpose.

Thanks for flying TAG.
