### ISSUE TITLE
[Handwriting] Add Handwriting CSS Value

### ISSUE THREAD

**Issue by gastonrod** [w3ctag/design-reviews#1018]
こんにちは TAG-さん!

I'm requesting an early TAG design review of the `handwriting` keyword for the `touch-action` CSS attribute.

This feature introduces a new web standard that simplifies enabling or disabling handwriting input across multiple platforms. By specifying a new keyword in the [touch-action](https://w3c.github.io/pointerevents/#the-touch-action-css-property) CSS property, developers can now easily indicate whether an element or its subtree should allow handwriting input.

  - Explainer: [MSEdgeExplainers/Handwriting/HandwritingIntentCSSValue.md](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/Handwriting/HandwritingIntentCSSValue.md)
  - User research: Handwriting capabilities are being implemented at the moment and when they are shipped developers will need a way to handle their enablement. Once implemented, these capabilities will be enabled by default and users will need a mechanism to disable it.
  - Security and Privacy self-review: Since the proposed property should not interact with other HTML or IDL attributes, DOM properties, or JavaScript APIs in an interesting way, and the property doesn't reflect whether a user agent supports or has enabled handwriting input, it shouldn't be possible to use this for fingerprinting. As of writing this, we are not aware of any way the proposed property could be used towards nefarious means since it's merely a hint for the browser to allow handwriting input and the handwriting state doesn't expose anything about the user nor their device. There are no known security impacts of the features in this specification.
  - GitHub repo: [MicrosoftEdge/MSEdgeExplainers](https://github.com/MicrosoftEdge/MSEdgeExplainers)
  - Primary contacts:
      - Gaston Rodriguez (@[gastonrod](https://github.com/gastonrod)), Microsoft
      - Adam Ettenberger (@[adettenb](https://github.com/adettenb)), Microsoft
      - Olga Gerchikov (@[ogerchikov](https://github.com/ogerchikov)), Microsoft
  - Organization/project driving the design: Microsoft
  - Multi-stakeholder feedback³:
    - Chromium comments: A new chrome Status will be created as soon as I get the needed permissions. Ongoing discussion can be found in the explainer, here are some links [[1](https://github.com/w3c/pointerevents/issues/516)] [[2](https://www.w3.org/2024/11/06-pointerevents-minutes.html)] [[3](https://github.com/w3c/pointerevents/issues/512)]

Further details:

  - [X] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): [W3C Web Incubator Community Group](https://wicg.io/), [Pointer Events Working Group](https://w3c.github.io/pointerevents/)
  - The group where standardization of this work is intended to be done ("unknown" if not known): [Pointer Events Working Group](https://w3c.github.io/pointerevents/) 
  - Existing major pieces of multi-implementer review or discussion of this design: Linked under **Multi-stakeholder feedback -> Chromium comments**
  - Major unresolved issues with or opposition to this design: 
      -  touch-action in its current state may not be flexible enough for developers needs.
      -  The property name, while clearly communicated in the Spec, isn't specific to touch behaviors as it includes stylus/pen actions as well.
      -  Developers may want granular control over input type in addition to "actions".
      -  Developers may want granular control to specify "action" precedence (handwriting then scrolling, or vice versa).
      -  Concerns with how handwriting and panning can intuitively co-exist, since it's possible a scrollable page with touch-action: handwriting pan-y may be unable to be panned. e.g., when the entire document is editable.
  - This work is being funded by: Microsoft

You should also know that...

Feedback from many working groups will likely be required to achieve consensus on the shipping of this feature, as it may affect pointer events, CSS and HTML.

**Comment by jyasskin** [comment]
What's the adoption state here? I see enough Chrome interest to justify adopting this into the WICG, so ideally you'd have moved it there before filing this TAG review. But I also see discussion inside the Pointer Events WG: is it far enough along that the WG would support adopting it?

**Comment by gastonrod** [comment]
There is currently no code implemented for the feature. We are adding a use counter to try to measure how many webpages would be affected by the shipping of this proposal as-is, and I'm working on a prototype PR for chrome.
The [first proposal](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/Handwriting/explainer.md) we created was to add an HTML tag to control the enablement of handwriting on elements, but we received some feedback on why using touch action could be a better way of (dis)abling handwriting. We are currently exploring both options and trying to get consensus on what the best mechanism would be to implement to control this feature, which is why I'm submitting the proposal for an early TAG review and will be shortly posting this issue to the [editing](https://github.com/w3c/editing/issues) and [html](https://github.com/whatwg/html/issues) working groups. A discussion is already ongoing on the pointer events WG.

**Comment by jyasskin** [comment]
Sorry, I meant the state of adoption by community and working groups. https://www.chromium.org/blink/launching-features/#start-incubating:~:text=incubation%20venue mentions proposing the work to an incubation venue _before_ filing the TAG review.

**Comment by gastonrod** [comment]
I see, I know starting a TAG review this early isn’t what is recommended by the docs, but since this proposal will likely need input from multiple groups I was recommended to get TAG involved sooner as it could help steer us toward a better solution and catch any big architectural concerns early. Let me know if there are other considerations I should keep in mind, or if you'd prefer we shelf this until the discussion happens in the WGs.

**Comment by slightlyoff** [comment]
hey @jyasskin; I think the intent here is to get this into WICG or similar, but I've never understood our guidance in the Blink launch process to gate requesting TAG feedback on repo location, *particularly* for early reads.

Happy to work with you and @chrishtr to clarify on the Blink side.

@gastonrod: thanks for filing this. I think it's good advice to request moving to a more formal incubation venue, but hopefully that won't block this thread.

**Comment by martinthomson** [comment]
Thanks for bring it to us.  We've discussed the feature and it seems like -- while this is a niche sort of thing to want to do -- there are cases where this could be useful.

The design appears to be consistent with the design of touch-action.  We do think that it would be better to clarify the interaction of `handwriting` with other actions that are available.  In many cases, pointer devices (like fingers) are unable to distinguish between a writing and panning mode, so having `touch-action: pan-??? handwriting` doesn't make a lot of sense for those common devices.

We also encourage you to consult with the CSS working group on this, following [our design principle](https://w3ctag.github.io/design-principles/#specs-include-guidance).
