### ISSUE TITLE
Performance APIs, Security and Privacy

### ISSUE THREAD

**Issue by mnot** [w3ctag/design-reviews#120]
Ilya Grigorik wrote up a collection of thoughts about security and privacy as they relate to the design of performance APIs (mostly, the RUM-related ones). After some encouragement, he's started working on it as a Note:
  https://w3c.github.io/perf-security-privacy/

**Comment by plinss** [comment]
Discussed at 2016-07-29 telcon, will invite Ilya to a future call to discuss this and the possibility of merging it into our API design guide.

**Comment by hadleybeeman** [comment]
@igrigorik, would you like to dial into our f2f today to discuss this?

**Comment by igrigorik** [comment]
Probably not.. short notice. What time, what's the context of the discussion? Is it a general overview of the note Mark linked above?

**Comment by travisleithead** [comment]
I think what we'd like to discuss is your thoughts on integrating your document into the TAG's design principles doc. If you can share your thoughts here in the issue, then perhaps we don't even need a call ;)

**Comment by igrigorik** [comment]
@travisleithead ah, interesting. On the surface, no objections.. but what's actually involved in making that happen? There are a few updates I'd like to make to that doc, but need to find the time first.. :-)

**Comment by plinss** [comment]
@igrigorik, following up, are you available to join our call next week (March 8, 1pm PST)? Or do you need more time to update the doc first?

**Comment by igrigorik** [comment]
@plinss apologies, out next week. When's the call after next? We don't need to block on me updating the doc.

**Comment by plinss** [comment]
We're discussing shifting the call times after next week (when DST starts in the US), most likely time slot at this point is Tuesdays @ 8am PDT. We can always schedule a one-off time slot if needed to accommodate.

**Comment by igrigorik** [comment]
8AM is fine. Let me know once you guys have the next date pinned down.

**Comment by plinss** [comment]
@igrigorik Are you still available 8AM PDT tomorrow (Mar 14)?

**Comment by travisleithead** [comment]
Thanks @igrigorik for joining our call. I've created the above issue in design-principles for us to get started.

**Comment by torgo** [comment]
We've moved the work so closing this issue.
