### ISSUE TITLE
Media Capture From DOM Element

### ISSUE THREAD

**Issue by dontcallmedom** [w3ctag/design-reviews#130]
The WebRTC and Device & Sensors Working Group would like the TAG review of [Media Capture From DOM Element](https://w3c.github.io/mediacapture-fromelement/), an API to produce a `MediaStream` from media elements and from canvas elements.

**Comment by torgo** [comment]
Taken up in Boston 2017 f2f (who says the TAG can't work quickly?).

**Comment by torgo** [comment]
@dontcallmedom sorry this has taken so long - is there anything you would like to highlight to us?

**Comment by dontcallmedom** [comment]
I can't think of anything in particular, but this spec closes the loop as far as the media workflow in the Web platform goes (i.e. it allows to turn a media element into a new mediastream), so it's probably worth looking at it with the full chain in mind:
gUM/MSE/Blob/URL → Media Element → MediaStream From Element → Media Recorder 🔁

**Comment by cynthia** [comment]
Brought up at the London F2F - one bit we would like note is that spec doesn't seem to have any normative text on what implementations should do when attempting to stream from a media element with content protection.

It would be great if you could also give us an explainer for the spec.

**Comment by cynthia** [comment]
Did a quick review - all the issues that I believe the TAG would like to bring up are already on the group's tracker, and the one that I realized should be brought up has been raised as w3c/mediacapture-fromelement#65.

Will discuss in today's call.

**Comment by plinss** [comment]
Discussed 2017-09-12
