### ISSUE TITLE
MediaStream Recorder

### ISSUE THREAD

**Issue by dontcallmedom** [w3ctag/design-reviews#131]
The WebRTC and Device & Sensors Working Group would like the TAG review of [MediaStream Recording](https://w3c.github.io/mediacapture-record/MediaRecorder.html), an API to save a `MediaStream` (obtained either from a local or a remote source) as a blob.

**Comment by travisleithead** [comment]
Quick off the cuff remarks:
* Would like to see an explainer collating the scenarios, how to use them, and example code for each
* This spec seems like the perfect target to re-use the ReadableStream concept and harmonize/unify the way that conversions are handled. Streams already have a model for how data is extracted/converted from them, which would potentially simplify this spec a lot.

**Comment by slightlyoff** [comment]
CC: @domenic for discussion for `ReadableStream`

Also, it's a real pain that `Blob` and `ArrayBuffer` interop is so poor.

**Comment by domenic** [comment]
Completely agreed on ReadableStream. I put up a draft of how that could work at https://domenic.github.io/streaming-mediastreams/ a while ago. @miguelao and I are definitely interested in exploring this, but my understanding is that given Firefox was already shipping this the priority was on just stabilizing that before exploring a "v2" that is properly layered on streams.

**Comment by dbaron** [comment]
The TAG just looked at this in our face-to-face today.

One other thought from me is that the examples could use a little more prose.  For example, in [the second example](https://w3c.github.io/mediacapture-record/MediaRecorder.html#example2):
* how does the `video` element relate to what's going on?
* what controls the object lifetimes, i.e., when does the MediaRecorder become GC-able?

We're still interested in seeing work using ReadableStream here, perhaps as a return value from `start()`.

**Comment by torgo** [comment]
We note the ongoing work to address the issues we raised. We'd still like to see an explainer doc. 
/w3c/mediacapture-record/#86 Also we'd like to see some action on the issue of integrating with readable streams /w3c/mediacapture-record/#87 @dontcallmedom can you let us know what's going on on those so we can close this off? kthxbye.

**Comment by dontcallmedom** [comment]
@yellowdoge can you comment on your plans for https://github.com/w3c/mediacapture-record/issues/86 and https://github.com/w3c/mediacapture-record/issues/87 ?

**Comment by travisleithead** [comment]
@dontcallmedom @yellowdoge, @alvestrand
We reviewed both open issues on today's call. Looks like w3c/mediacapture-record#86 has been addressed to our satisfaction, and w3c/mediacapture-record#87 is longer-term (for a v2 of the spec), we're going to go ahead and close this review issue. (When a v2 of media recorder comes along, please loop us in with another review request!) Thanks!
