### ISSUE TITLE
Audio Output Device APIs

### ISSUE THREAD

**Issue by dontcallmedom** [w3ctag/design-reviews#132]
The WebRTC and Device & Sensors Working Groups would like the TAG review of [Audio Output Devices API](https://w3c.github.io/mediacapture-output/), an API to render audio from media elements and `AudioContext`s to a specific audio output device.

**Comment by travisleithead** [comment]
Some comments:
* `sinkId` name doesn't seem to match-up with the property used to identify the output devices (`deviceId`) from `MediaDeviceInfo`
* For `AudioContext`, no mention of how to handle the various update/devices disconnected and reconnected scenarios mentioned in section 2.3
* Section 2.1 (describing the attribute `sinkId` should have some prose describing what the value is that is returned (in the default case at a minimum: which I think is the empty string).
* Section 4's pre-defined Identifiers adds an alias to the empty string value with "id_multimedia". I wonder for clarity if this should just be the default value.

**Comment by travisleithead** [comment]
Also, we would really like to see an explainer document with some same code examples of use.

**Comment by travisleithead** [comment]
Taken up in TAG Tokyo F2F: 

@dontcallmedom I think we're essential done with this review given the comments above. Would you like to file these as issues in the Audio Output API issue tracker, or just refer to this issue?

**Comment by dontcallmedom** [comment]
Issues filed

**Comment by travisleithead** [comment]
I reviewed the issues and followup resolutions and don't have any objections. LGTM!

**Comment by torgo** [comment]
Agreed to close at Tokyo f2f. Thank you for shopping TAG.

**Comment by dontcallmedom** [comment]
@travisleithead @torgo it doesn't look like we're likely to get progress on https://github.com/w3c/mediacapture-output/issues/61 in the short term (explainer doc) - but we otherwise believe the document is ready to go to CR - any objection from the TAG on proceeding with our transition request with that issue left open?

**Comment by dontcallmedom** [comment]
ignore this, it turns out we did get the explainer in after all
