### ISSUE TITLE
MediaStream Image Capture

### ISSUE THREAD

**Issue by dontcallmedom** [w3ctag/design-reviews#133]
The WebRTC and Device & Sensors Working Groups would like the TAG review of [MediaStream Image Capture](https://w3c.github.io/mediacapture-image/), an API to capture still pictures from a `MediaStream` generating camera.

**Comment by travisleithead** [comment]
The ergonomics of the API seem aligned with good principles. E.g.:
* Uses Promises for potentially long-running operations.

Exposes ImageCapture as an "add-on" object to a MediaStreamTrack (a new constructable interface:
* Why make this a separate constructable object, with the reflective 'videoStreamTrack' member? Could this be streamlined into the MediaStreamTrack as a partial interface to it instead? 
* Seems like 'getPhotoCapabilities' and the MediaStreamTrack's 'getCapabilities' are nearly the same. Is there a reason to have the separate method and property list?

Is 'grabFrame' really necessary? Isn't this already possible using a video/canvas element?

Consider allowing a DOMPoint in places where a Point2D dictionary could be used (DOMPoint from http://www.w3.org/TR/geometry-1/#DOMPoint). The DOMPoint handles points in 3d space, but the 'z' and 'w' coordinates are not required, and this may be useful for platform consistency.

**Comment by travisleithead** [comment]
Should do a re-review at next F2F to see how the spec has been developing.

**Comment by torgo** [comment]
Discussed at Tokyo f2f…

**Comment by triblondon** [comment]
Discussed at London F2F

**Comment by torgo** [comment]
Agreed to close at f2f. @travisleithead will follow up on remaining issue w3c/mediacapture-image#142 .
