### ISSUE TITLE
WASM JS API review

### ISSUE THREAD

**Issue by slightlyoff** [w3ctag/design-reviews#151]
Note: not using the template as this is an unsolicited feedback proposal.

The WASM community is narrowing in on a JS API for loading Web Assembly modules which is is a long way from the other types and conventions we use in the rest of the platform. I suggest we reach out ASAP and try to learn as much as we can about their needs and use-cases and work to suggest alternatives:

https://github.com/WebAssembly/design/issues/972

/cc @s3ththompson @flagxor @annevk @domenic @jakearchibald

**Comment by hadleybeeman** [comment]
Discussed at Boston f2f. @slightlyoff to take forward. https://pad.w3ctag.org/p/2017-02-08-minutes.md

**Comment by slightlyoff** [comment]
Marking as a dupe of #167.
