### ISSUE TITLE
Review Screen Orientation spec prior to CR-entry

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/design-reviews#157]
for @LJWatson:

Hello TAG,

The WebPlat WG would welcome your review of the [Screen Orientation API](https://www.w3.org/TR/screen-orientation/), as we prepare to move it to CR.

We'd appreciate your comments by 12th May if that's possible? [Github is preferred for comments](https://github.com/w3c/screen-orientation), but if you could ping me an email to let me know when you're done it'll help me keep track of everything.

Thanks.
Léonie

**Comment by LJWatson** [comment]
Ping @Torgo @Cynthia @TravisLeithead for an update? Thanks

**Comment by cynthia** [comment]
I'll have this reviewed and on the agenda for this week's call.

**Comment by LJWatson** [comment]
Ping @Cynthia?

**Comment by cynthia** [comment]
Guilty. :(

**Comment by LJWatson** [comment]
We originally wanted feedback by 12th May. Feedback ASAP now would be welcome. Thanks.

**Comment by cynthia** [comment]
Sorry that this took so long - we reviewed this during our London F2F, and overall we think the spec looks good as it is.

There is one corner case that came to mind that wasn't quite clear if the spec covered - will open that in the issue tracker on your side.
