### ISSUE TITLE
Request for TAG review of CSS Timing Functions spec

### ISSUE THREAD

**Issue by suzyh** [w3ctag/design-reviews#161]
Hello TAG!

I'm requesting a TAG review of:

  - Name: CSS Timing Functions level 1
  - Specification URL: https://www.w3.org/TR/css-timing-1/
  - Explainer, Requirements Doc, or Example code: ?
  - Primary contacts: birtles, shans

Further details (optional):

You should also know that...
I am not actually involved in writing this spec, so can't really give much useful info here. My understanding is that this spec grew out of animations and transitions, but some parts of it (particularly the frames timing function) are new.

We'd prefer the TAG provide feedback as (please select one):

  - [x] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by dbaron** [comment]
This was just split out of transitions; the only new thing is `frames()`.  I think everything else has been shipping for half a decade.

**Comment by dbaron** [comment]
/cc @birtles @shans.

The TAG has been talking about this, and there seems to be a bit of concern about the `frames()` name given the other uses of the term, e.g., in `requestAnimationFrame` and frames as produced for the screen, and also `@keyframes`.

We're wondering if there are other naming options, and would like to ask the CSS WG to reconsider the name if that's possible.

Thanks for bringing this up for review!
