### ISSUE TITLE
ReadableStream pipeTo() and pipeThrough()

### ISSUE THREAD

**Issue by domenic** [w3ctag/design-reviews#164]
Hello TAG!

I'm requesting a TAG review of:

  - Name: ReadableStream pipeTo() and pipeThrough()
  - Specification URL:
    - https://streams.spec.whatwg.org/#rs-pipe-to
    - https://streams.spec.whatwg.org/#rs-pipe-through
  - Explainer, Requirements Doc, or Example code:
    - This section contains a high-level overview: https://streams.spec.whatwg.org/#pipe-chains
    - Some additional examples: https://streams.spec.whatwg.org/#example-basic-pipe-to
    - A related FAQ: https://github.com/whatwg/streams/blob/master/FAQ.md#whats-with-pipeto-vs-pipethrough
   - Requirements document: https://github.com/whatwg/streams/blob/master/Requirements.md#composing-streams
  - Primary contacts: @domenic, @tyoshino, @ricea

Further details (optional):

  - Relevant time constraints or deadlines: We are hoping to launch in Blink in M59, for which the branch point is in a couple weeks
  - [ ] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/): not really applicable here
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

This feature is closely related to writable streams, #163.

We'd prefer the TAG provide feedback as (please select one):

  - [x] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by dbaron** [comment]
This link (the third) seemed to be the most useful first explainer:
> A related FAQ: https://github.com/whatwg/streams/blob/master/FAQ.md#whats-with-pipeto-vs-pipethrough

**Comment by triblondon** [comment]
We're happy with this, clearly explained, well named.  @travisleithead wants to take a closer look at the streams spec in general but we're happy to close the review at this point.  Thanks for bringing it to us, we really appreciate the opportunity to review.
