### ISSUE TITLE
Repo should be renamed (and templates updated) to reflect consulting role of the TAG

### ISSUE THREAD

**Issue by slightlyoff** [w3ctag/design-reviews#168]
The world "review" incorrectly describes what we do when we do it well: instead of reviewing finished (or near-finished) designs, our work here is most effective when we consult with teams designing features as soon as their design "hangs together".

Therefore, I propose we change the name of this repo to `design-consulting-and-review`.

**Comment by torgo** [comment]
I support that change.

**Comment by triblondon** [comment]
It's a little unwieldy.  Remember the wise teachings of The Guide:

> Ford flipped the switch which he saw was now marked ‘Mode Execute Ready’ instead of the now old-fashioned ‘Access Standby’ which had so long ago replaced the appallingly stone-aged ‘Off’.

If we have a problem with 'review', maybe we should remove that word.  It *is* specs that we examine, so removing that seems counter-intuitive to me.  How about 'spec-feedback'?

**Comment by bkardell** [comment]
Fwiw, ”Feedback"  reads mostly as also more passive and late to me. Consult/consultation seems to better indicate the point/collaboration/advice I think @slightoff was making.  Sorry I hate to add potentially worthless bikeshedding, but I've always thought this had been kind of weird so I'm glad to see it come up.

**Comment by triblondon** [comment]
OK, "spec-consults"?

**Comment by mnot** [comment]
`spec-pwc`

**Comment by torgo** [comment]
I took an action today to change it to 'design-review'.
