### ISSUE TITLE
TAG review for script type=module

### ISSUE THREAD

**Issue by KenjiBaheux** [w3ctag/design-reviews#180]
Hello TAG!

I'm requesting a TAG review of:

  - Name: ```<script type="module">```
  - Specification URL: [script module in HTML WhatWG](https://html.spec.whatwg.org/multipage/scripting.html#the-script-element:module-script) and [TC39 - modules](https://tc39.github.io/ecma262/#sec-modules)
  - Primary contacts: @domenic 

Further details (optional):
  - Relevant time constraints or deadlines: [a few weeks from now]
 
We'd prefer the TAG provide feedback as (please select one):
  - [X] leave review feedback as a comment in this issue and @-notify @domenic

**Comment by torgo** [comment]
Can you provide a little more detail and back-story or links to the back-story on this? /cc  @domenic

**Comment by dbaron** [comment]
A link to [the relevant part of the multipage HTML spec](https://html.spec.whatwg.org/multipage/scripting.html#the-script-element) may be helpful for some.

`<script type=module>` and `<script nomodule>` seem reasonable at first glance as a thing, but, as Dan said, it would be useful to have a bit more background about modules to get up to speed.  Is there some sort of explainer or introductory document?

**Comment by domenic** [comment]
https://blog.whatwg.org/js-modules is probably the kind of backstory that would help? Let me know what else you could be looking for.

**Comment by torgo** [comment]
from today's TAG call: Comment from @cynthia : the type modules doesn't look like a valid mime type...  (see comment in blog post) - i tend to agree with this remark (From: https://blog.whatwg.org/js-modules#comment-162659 )

**Comment by domenic** [comment]
Please see the reply in https://blog.whatwg.org/js-modules#comment-162666 and the linked discussion.

**Comment by slightlyoff** [comment]
We re-read the TC39 and HTML bits of this at today's F2F and are glad to see it moving forward. 
Our only note is that it seems sad for the `crossorigin` attribute to pick up different meanings based on script type, but understand why not introducing a new attribute was preferable.

@domenic: thanks for clarifying the mimetype question; the blog post was super helpful too.

In short, looks good to us!

:shipit:
