### ISSUE TITLE
Consider template change to add link to WPTs for far-along specs

### ISSUE THREAD

**Issue by slightlyoff** [w3ctag/design-reviews#181]
We tend to request example code and explainers, seems like we should probably also ask for links to web platform tests (if any). Thoughts?

**Comment by torgo** [comment]
Yes agreed - Alex can you do it? :)

**Comment by torgo** [comment]
Peter did it. We rock.

**Comment by dbaron** [comment]
It was fixed in ebf4c82bb4774eea3b7cf0da436d105d0f0f35ff.
