### ISSUE TITLE
Request to review Image Decode API

### ISSUE THREAD

**Issue by vmpstr** [w3ctag/design-reviews#182]
Hello TAG!

I'm requesting a TAG review of:

  - Name: Image Decode API
  - Specification URL: https://html.spec.whatwg.org/multipage/embedded-content.html#dom-img-decode
  - Discussion: https://github.com/whatwg/html/issues/2037
  - Primary contacts: vmpstr, domenic

We'd prefer the TAG provide feedback as (please select one):

  - [x] leave review feedback as a comment in this issue and @-notify vmpstr and domenic

**Comment by dbaron** [comment]
We had some discussion of this in [today's TAG meeting](https://github.com/w3ctag/meetings/blob/gh-pages/2017/telcons/07-05-agenda.md) in order to assign the issue.  Two themes came up:
* how much variation between implementations there is in when decoding happens, and whether this restricts things current implementations do or whether the API makes assumptions about certain implementation strategies that might not match all implementations (or encourages developers to make such assumptions)
  * it seems at first glance like it may mostly be good, although I'm a little worried about the requirement that *all* frames of an animated image be decoded, given that it seems like something that implementations may well want to optimize for large animated images in low-ish memory situations
* how this ties to the [Extensible Web Manifesto](https://extensiblewebmanifesto.org/), and whether it helps to explain `<img>` or whether it could be done differently in a way that does

**Comment by vmpstr** [comment]
To your first point:

With encoded images, every implementation needs to have a decoding step. Some implementation defer this decode until the image needs to be displayed (such as the case in Chrome and Safari for example). In those situations this API provides a good hint to the implementer that the image needs to be displayed soon, so it's a good signal to start the decode now and issue a callback when that's done. If implementations exists that do the decode at the time of rasterizing the content (ie no caching happens), then this provides a hint that could technically be ignored, although it might help prioritizing which decode needs to happen sooner rather than later.

For the animated case, the requirement is that the frames are available but not necessarily that they need be decoded. That is, essentially "onload" has to fire and then the first frame of the animated image is decoded before the callback is issued. Calling this API does not require that every frame needs to be decoded, for the reasons that you mention (it may not feasible in low memory situations).

I'll defer to @domenic for the second point.

**Comment by dbaron** [comment]
Quoting https://github.com/w3ctag/design-reviews/issues/182#issuecomment-313245241 :
> For the animated case, the requirement is that the frames are available but not necessarily that they need be decoded. That is, essentially "onload" has to fire and then the first frame of the animated image is decoded before the callback is issued. Calling this API does not require that every frame needs to be decoded, for the reasons that you mention (it may not feasible in low memory situations).

Where does the spec say this?  To me, the current spec text seems to say the opposite, since it says:
> Decode the image's media data entirely into its bitmap form, suitable for rapid painting to the screen.

and I don't see any exceptions for only decoding the first (or current?) frame of the animated image.

Also, is it possible for the current frame of an animated image to change between the call to decode() and the "end of the next update the rendering step in the event loop"?  If so, which frame should be guaranteed to be decoded?

**Comment by dbaron** [comment]
Also, the spec could probably be clearer that implementations that decode when rasterizing can ignore the hint.

**Comment by domenic** [comment]
> how this ties to the [Extensible Web Manifesto](https://extensiblewebmanifesto.org/), and whether it helps to explain `<img>` or whether it could be done differently in a way that does

I think this API is somewhat orthogonal to the issue you hint at. If I am guessing right, you're thinking about how in a perfectly-layered system, we'd be able to explain `<img>` as a series of APIs: e.g., fetch() -> encoded bytes -> decoded bytes -> rasterize to new bytes -> paint rasterized bytes. And the encoded bytes -> decoded bytes API would indeed probably use the function name "decode()".

What we're doing here is something a bit different, which is more of a hint to the browser to get ready, because we plan on needing rasterization/paint within the next frame. Indeed one of the original name suggestions was `ensureReady()`, but that was deemed too vague and confusing over the simplicitly of `decode()`.

I think the web community should definitely work on a bytes -> bytes decoding API in the future. This API is meant for a different purpose, however, of ensuring the existing somewhat-opaque pipeline gets all the information it can to give good performance.

**Comment by vmpstr** [comment]
> Where does the spec say this? To me, the current spec text seems to say the opposite, since it says:

You're right that this is unclear in the spec. The text is really only talking about static images and the only reference to animated images is in the note, which hints at the fact that although the first frame could be already decoded, all frames should be available. @domenic, do you think we could elaborate on animated images more?

> Also, is it possible for the current frame of an animated image to change between the call to decode() and the "end of the next update the rendering step in the event loop"? If so, which frame should be guaranteed to be decoded?

This is unspecified... It seems a bit like a misuse of the API, since the point at which the frames advance in an animated image is outside of the author's control. It seems similar to calling a decode() on a static image that is already displayed on the screen. At that point, the decode is not necessary, since the image is already rasterized on screen. Similarly, when an animated image is in the dom, the implementers have full knowledge of what frames are expected to appear and when they need to appear so calling decode on it is questionable. To put it differently, it's not clear to me what reasonable action the author can take in the promise resolution callback that would aid the browser in ensuring frames appear quickly.

FWIW, a possible implementation could decode the current frame at the time of the decode() call, whether or not that's the frame that is current at the time of the promise resolution.

The intent of the API, which is what the examples demonstrate, is to give the authors tools to "prepare" the image before inserting it into the dom; to indicate to the browser that this image is about to be in a state that needs to be rasterized. For animated images outside of the dom, this means the first frame needs to be decoded. For animated images in the dom, the browser has more knowledge than the author about which frames need to be rasterized.

**Comment by domenic** [comment]
> [@domenic](https://github.com/domenic), do you think we could elaborate on animated images more?

Sure, a PR would be fine for this. I do think however the current spec has enough leeway for appropriate quality-of-implementation choices.

**Comment by tomByrer** [comment]
I assume that Progressive JPEGs would be handled the same as animated images, since they have a 'frame' of sorts?  Might want to mention that in the spec either way.

**Comment by vmpstr** [comment]
Since the decode call implies a load (ie all of the data becomes available), it means that the final version of the image is decoded (ie, no progressive frames). The difference is that contrary to animated images, the progressive frames don't actually need to be displayed, so because of the load event, the decode causes the full image to be decoded

**Comment by dbaron** [comment]
Discussed briefly in today's TAG meeting:

Brief discussion of the [naming tradeoff](https://github.com/w3ctag/design-reviews/issues/182#issuecomment-313493800) above.

Brief discussion of download-but-not-display use cases, and also maybe an actual decode API, which we agree or separate from what this spec is doing.

**Comment by cynthia** [comment]
Taken up at the London F2F.

We can definitely see the usecases for this, and this seems like a pretty useful addition (being able to fetch and pre-decode the image before it has been attached to the document, and perform this decoding process outside of the main thread) to the platform.

The main concern we have is something that @dbaron mentioned above - and that is the fact while this is API is useful, we are wondering if this is working around limitations on the primitives we have available in the web platforms.

A small nit would be that the naming doesn't quite do what it suggest it does - and in the event we get an actual image decode API we would have allocated the name slot for this.

**Comment by triblondon** [comment]
Discussed at TAG F2F Nice edition.  We are still concerned about naming.  Principally:

* [Earlier](https://github.com/w3ctag/design-reviews/issues/182#issuecomment-313493800) @domenic acknowledged the utility of future additions to the platform that might provide greater granularity, and if that were done, then it would make sense for a method called `decode` to *just do decoding* and not the other stuff which we are currently bundling into this method. Doesn't claiming the method name now potentially leave us with a more difficult naming issue in future?
* From a developer perspective, it seems like the prior suggestion of `ensureReady()` or `ready()` is actually a better description of what this method does, and we tend to favour that over describing the current proposal as 'decode'.

**Comment by domenic** [comment]
Umm... did you miss my point that any such future additions will not, in any sense, ever be on HTMLImageElement.prototype?

**Comment by triblondon** [comment]
Nope

**Comment by annevk** [comment]
If you didn't miss that point, why did you say:

> Doesn't claiming the method name now potentially leave us with a more difficult naming issue in future?

This API is explicitly for decoding the data (to be) hold by the `img` element. If we later get an API that decodes image data into `ImageBitmap` objects or some such it would live somewhere else and I don't really see how confusion could arise.

**Comment by torgo** [comment]
@domenic @annevk can you please dial it back a bit? We are trying to make good-faith progress on this issue and your snark doesn't help things. We have a [code of conduct](https://github.com/w3ctag/w3ctag.github.io/blob/master/about/tagcodeofconduct.md). Please see bullet point 6.

**Comment by annevk** [comment]
I'm sorry I caused offense, none was intended. I was confused by that question in conjunction with the rather brief "Nope".

**Comment by triblondon** [comment]
I am disengaging from this thread.  Other TAG members may be available to engage if you want to continue to discuss our feedback.

**Comment by domenic** [comment]
I'm happy to disengage as well.

**Comment by vmpstr** [comment]
I'm sorry that this thread went off-track. Chromium has a similar [code of conduct](https://chromium.googlesource.com/chromium/src/+/master/CODE_OF_CONDUCT.md) and we take it seriously. Hopefully we can get past this and get the discussion back on track.

-----

The reason we propose this method be called "decode" is simply because that's the main operation that it performs. This is separate from any other possible operation such as layout or rasterization. It prepares the image content into a format suitable for rasterization (a.k.a. decode). It is true that it also implies a load, but that's an ergonomics issue. Decoding a partial image which is in the process of being loaded is often times wasted work, since the decode is essentially invalidated by the next packet of data received. It's certainly reasonable to say that a decode should be issued from an onload handler to avoid this. We decided against this, because requesting a decode on an image that isn't loaded is likely not the intent of the developer. To put it differently, it's very unlikely that the developer really did intend to call a decode on a partially loaded image. Thus, bundling this seemed like an elegant solution to avoid any foot-guns.

The problem that I see with something like "ready" is that it is less precise. It's unclear from the name alone what readiness of an image means. Could it mean layout and rasterization as well? Or could it simply be equivalent to just load? Additionally, a decode is understood (and specced) to be available for the next raf. After that, it may be evicted from any decoding caches. With a ready signal, it's harder to argue or understand that an image is ready one frame but may become not ready in the next few frames. Adding something like a "ready attribute" to indicate whether the image is available is hard, since the pipeline is typically decoupled. That is, keeping the ready attribute in sync with the decoding caches can be inefficient and prone to errors.

As mentioned previously, this is an action on HTMLImageElement.prototype. As such it's independent of any separate future features, such as a Decoder which would presumably have its own set of functions named appropriately for the work that it does.

**Comment by domenic** [comment]
I'm also sorry that I got frustrated and expressed it in a way that caused offense. As @annevk and @vmpstr have mentioned, I believe the naming concerns have been addressed previously, so I am hopeful that we can work toward better understanding there. I'm happy to discuss this as necessary until everyone is on the same page.

**Comment by cynthia** [comment]
I think for this feature, the naming is already too late to bikeshed further as it is shipping in multiple implementations - the actual API for decoding an image missing from the web platform is something that came up in the last F2F and will be dealt with elsewhere. (Where that will be, that is still unclear. :( )

For now I don't think there is much the TAG can do here. Apologies this discussion derailed - hope we won't have a situation like this again. Thanks again for bringing this up with us.
