### ISSUE TITLE
Add request for links to WPT tests in issue template

### ISSUE THREAD

**Issue by slightlyoff** [w3ctag/design-reviews#191]
Per a conversation with @foolip, perhaps we should ask folks asking for review to include a link to their Web Platform Tests if they have a formal spec (not an Explainer). Thoughts?

**Comment by travisleithead** [comment]
+1. Just don't want to have this be **required** let's add it.

**Comment by plinss** [comment]
Discussed 2017-09-05 telcon, will add

**Comment by plinss** [comment]
Added in ebf4c82
