### ISSUE TITLE
Request review for Scroll Boundary Behavior

### ISSUE THREAD

**Issue by majido** [w3ctag/design-reviews#193]
Hello TAG!

I'm requesting a TAG review of:

  - Name: scroll-boundary-behavior
  - Specification URL: https://wicg.github.io/scroll-boundary-behavior/
  - Explainer, Requirements Doc, or Example code: https://github.com/WICG/scroll-boundary-behavior
  - Tests: not available but we have [plans](https://bugs.chromium.org/p/chromium/issues/detail?id=762054) to upstream existing tests.
  - Primary contacts: @bgirard, @majido

Further details (optional):

  - Relevant time constraints or deadlines: We like to ship this feature in Chrome M63 (feature freeze in 24 days)
  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://github.com/wicg/scroll-boundary-behavior/blob/master/security-privacy-questionnaire.md).
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

The current design is the result of discussion with various CSSWG and WICG members. 
You can see relevant discussion on this CSSWG [github issue](https://github.com/w3c/csswg-drafts/issues/769) and WICG [discourse thread](https://discourse.wicg.io/t/generic-scroll-chaining-prevention-mechanism-or-expand-standardize-ms-scroll-chaining/1811).

We have a working prototype implemented in [Chromium](https://groups.google.com/a/chromium.org/d/msg/blink-dev/OqBNF2efmFA/3ByBUKyaCgAJ) behind web platform experimental features flags. The API has received positive feedback from [Edge](https://github.com/w3c/csswg-drafts/issues/769#issuecomment-270228948)  and [Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=951793#c11) and addresses a real need from web developers [here](https://github.com/w3c/csswg-drafts/issues/769#issuecomment-279832555) and [here](https://github.com/w3c/csswg-drafts/issues/769#issuecomment-288878908). 

We'd prefer the TAG provide feedback as (please select one):

  - [] open issues in our Github repo for each point of feedback
  - [] open a single issue in our Github repo for the entire review
  - [x] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by dbaron** [comment]
We discussed this very briefly in the TAG meeting this morning and again in more depth in a breakout this afternoon.  A few points came up:

* Are there events that allow a page to detect and act on overscroll behavior?  (perhaps a separate point, but worth looking into)
* Should this be a new property, or should this be a new part of the value on 'overflow'?  It wasn't clear to us which is the right thing; in CSS this is often decided by whether the pieces should cascade together or separately.
* Another related question is whether there should be logical (inline-direction and block-direction rather than x and y) versions of these -- and also whether there should be logical versions of overflow-x and overflow-y.  https://drafts.csswg.org/css-logical/ doesn't have those, though.

**Comment by majido** [comment]
Thanks for the feedback. Here is our initial thinking about these.

*Are there events that allow a page to detect and act on overscroll behavior? (perhaps a separate point, but worth looking into)*
**Response**: No currently there is no event that covers overscroll but this CSS property is complementary to something like that and does not preclude it. We have chosen to focus our effort on CSS property first as it does not require implementors to introduce a new blocking events in the  performance sensitive machinery of scrolling. 

I don't think however that there is a major issue with having a non-blocking event. Also there is already a [scroll customization effort](https://github.com/w3c/css-houdini-drafts/blob/master/scroll-customization-api/explainer.md) that aims to create low-level primitive that explain scrolling. I think that spec is an appropriate venue to explore the idea of adding an event if there is enough interest.

*Should this be a new property, or should this be a new part of the value on 'overflow'? It wasn't clear to us which is the right thing; in CSS this is often decided by whether the pieces should cascade together or separately.*
**Response**: I can imagine situations where there is a need to control SBB (scroll-boundary-behavior) independent of the overflow. For example a pull-to-refresh component is only interested in controlling the SBB but shouldn't need to control the viewpoer overflow. Another example is a page that wants to set SBB for all scrollers to be `contain` using a `*{}` rule but does not necessarily want to control the overflow that way (this later one seems a bit far fetched).

Also we have the precedent of `scroll-behavior` here which is an independent property. I think `scroll-behavior` plays a similar role as `scroll-boundary-behavior` which is why it is good to be consistent here. However I am not able to find the rationale for that particular decision.

*Another related question is whether there should be logical (inline-direction and block-direction rather than x and y) versions of these -- and also whether there should be logical versions of overflow-x and overflow-y. https://drafts.csswg.org/css-logical/ doesn't have those, though.*
**Response**: `scroll-boundary-behavior-{x,y}` was chosen to match `overflow-{x,y}`. I think it is reasonable to have logical directions but I suggest doing so in conjunction with adding them to overflow.
I think it is important to ensure consistency here.

**Comment by tantek** [comment]
subscribe

**Comment by majido** [comment]
FYI, there was some discussion and we reached consensus to use a slightly shorter name `overscroll-behavior` instead of `scroll-boundary-behavior`.

**Comment by dbaron** [comment]
... and [the spec has moved](https://wicg.github.io/overscroll-behavior/).

**Comment by majido** [comment]
Thanks @dbaron for pointing that out. I should have mentioned this as well but I was incorrectly assuming that GH redirects the links after repo rename. It actually does so for the repo itself but not for the associated gh-pages. 

Is there any concern or question regarding [the above answers](https://github.com/w3ctag/design-reviews/issues/193#issuecomment-337021324)? Btw here is a [blog post](https://developers.google.com/web/updates/2017/11/overscroll-behavior) with more examples and demo of the feature.

**Comment by plinss** [comment]
Discussed in out 2017-11-21 telcon and generally approved. Our primary concern at this point is where this fits in to Houdini scrolling APIs, e.g. how can this behavior be explained in terms of the lower-level API? how does the scrolling API provide the missing pieces to implement functionality like "pull-to-refresh"? We accept this property is but one part of a larger picture, we just want to see the rest...
