### ISSUE TITLE
Request review for PauseFrame API

### ISSUE THREAD

**Issue by jkarlin** [w3ctag/design-reviews#196]
Hello TAG!

I'm requesting a TAG review of:

  - Name: PauseFrame API
  - Specification URL: none yet
  - Explainer, Requirements Doc, or Example code: [Explainer](https://github.com/jkarlin/pause-frame)
  - Tests: none yet
  - Primary contacts: jkarlin

Further details (optional):

  - Relevant time constraints or deadlines: This is early stage, but in an ideal world would ship by end of 2017.
  - [X] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://github.com/jkarlin/pause-frame/blob/master/security-privacy.txt).
  - [X] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

We'd prefer the TAG provide feedback as (please select one):

  - [X] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by triblondon** [comment]
Overall impression: A number of us think this is a great idea.  Others feel its a bit of a blunt instrument.  We're wondering about:

* CSS hover effects - do they continue in a paused frame?
* Does a frame know it's been paused (after unpausing).  Obviously it could be 
* Queue could grow very large while frame is paused?
* Interaction with service workers?
* Interaction with Houdini?
* Naming: Pause and Frame are terms related to animation, is that confusing?  We acknowledge that it's not a name that is in the API itself.
* Can a page pause itself?

Some of these issues have already been raised on the tracker, but I've gather them here as a collective set of TAG feedback.  Hope this is useful and we look forward to hearing more.

**Comment by jkarlin** [comment]
Thanks so much! I'm slow to respond for the next week or two but will dig into the issues asap.

**Comment by triblondon** [comment]
@jkarlin friendly ping.  If you don't have any feedback on our review shall we close?

**Comment by jkarlin** [comment]
Yes, thank you very much for the feedback!
