### ISSUE TITLE
JavaScript module import()

### ISSUE THREAD

**Issue by domenic** [w3ctag/design-reviews#200]
Hello TAG!

I'm requesting a TAG review of:

  - Name: JavaScript module import()
  - Specification URL: [ECMAScript spec](https://tc39.github.io/proposal-dynamic-import/), [HTML spec rough draft](https://github.com/tc39/proposal-dynamic-import/blob/master/HTML%20Integration.md), [HTML spec integration pull request](https://github.com/whatwg/html/pull/3044).
  - Explainer, Requirements Doc, or Example code: https://github.com/tc39/proposal-dynamic-import/blob/master/README.md
  - Tests: https://github.com/w3c/web-platform-tests/tree/master/html/semantics/scripting-1/the-script-element/module/dynamic-import (more being written as we speak)
  - Primary contacts: @domenic @nyaxt @gsathya

Further details (optional):

  - Relevant time constraints or deadlines: we plan to land this in Chrome 63, which has a feature freeze on the 29th. However we can disable the feature remotely if something catastrophic is discovered in the TAG review after this date.
  - [x] I have read and filled out the [Self-Review Questionnaire on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://docs.google.com/document/d/1XeAYIhwG3MSJ-A9YozU2M1OSeHacPcIYvY3T2BxpMsI/edit?usp=sharing).
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [x] leave review feedback as a comment in this issue

**Comment by cynthia** [comment]
Taken up in Nice F2F.

We've collectively looked into this, and this proposal looks good to us - and we are excited to see this in the platform. Thanks a lot for the review request!
