### ISSUE TITLE
saveData attribute in Network Information API

### ISSUE THREAD

**Issue by bengreenstein** [w3ctag/design-reviews#204]
Dear Sirs and Madam of TAG!

I'm requesting a TAG review of:

  - Name: saveData attribute in Network Information API
  - Specification URL: https://wicg.github.io/netinfo/#-dfn-savedata-dfn-attribute
  - Explainer, Requirements Doc, or Example code: https://github.com/WICG/netinfo/issues/42
  - Primary contacts: bengreenstein, tarunban

Further details (optional):

  - Relevant time constraints or deadlines: We'd like to ship in Chrome M64
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our Github repo for each point of feedback
  - [x] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by slightlyoff** [comment]
Overall I like this. Having this available at the network level seems great.

I do continue to be worried about the design of Client Hints overall; not having this information in the intial request hobbles what servers can reasonably do, inducing the to cookie users or create redirects for the purposes of just getting this information.

**Comment by torgo** [comment]
@travisleithead "anything you should be able to see at the network level that is not security sensitive should be reflected back to page content - you should not have to go through round-trips. Same data is being sent through client hints header. This tells javascript code the same thing the server could have learned. So :+1:"

**Comment by dbaron** [comment]
It's a little worrying that http://httpwg.org/http-extensions/client-hints.html#save-data and https://wicg.github.io/netinfo/#-dfn-savedata-dfn-attribute seem to be specifying the same material.  (Or are they?)  Seems like one spec should be canonical for each thing -- but if the save data features are split between two specs they should definitely point to each other clearly.

**Comment by torgo** [comment]
Some concerns from @cynthia on privacy considerations.

**Comment by igrigorik** [comment]
@dbaron we moved Save-Data header definition from IETF doc into NetInfo spec in recent update. New IETF draft hasn't been published yet, hence the duplication.. but that won't be the case soon.

**Comment by torgo** [comment]
Some discussion on this on [today's call](https://cryptpad.w3ctag.org/code/#/1/view/JIfaYB9XX22X9dEncdbsuw/YiicWJAmk9GY+V-p73QUNfJs87Ext1J52w8CXxGtm1U/).

**Comment by torgo** [comment]
Agreed to discuss at f2f and hopefully we can get you on the phone for that discussion @igrigorik. Will be Jan 31 - Feb 2 (London).

**Comment by davidmurdoch** [comment]
Will this property be exposed to CSS media queries? I'd love to be able to do:

```
<picture>
    <source type="image/webp" srcset="/img-low-quality.webp" media="(save-data: on)">
    <source type="image/webp" srcset="/img.webp">
    <img src="/img.jpg">
</picture>
```

**Comment by torgo** [comment]
Discussed at [London F2F day 3](https://github.com/w3ctag/meetings/tree/gh-pages/2018/01-london).

**Comment by triblondon** [comment]
TAG review comments:

* Fingerprinting potential by correlating patterns of savedata status across multiple origins (ie I will exhibit the same pattern of moving from good to poor service areas on all websites I am visiting over the same period)
    * Meta-point: dynamic hint variables can provide trackable profiles when monitored over time.
* Not clear whether this is informed by exactly the same data source as the CH header, and we feel they should be the same spec if they are the same thing.

**Comment by triblondon** [comment]
TAG review conclusion:

* Fingerprinting issues are still a source of concern, even given the text in the spec.  We note that the WebRTC vulnerability identified in the spec has been fixed following [previous TAG feedback to that group](https://github.com/w3ctag/design-reviews/issues/14#issuecomment-203995268).
* Some TAG members take the view that the considerations given to privacy are not adequate and that the group should consider further work on mitigating the fingerprinting potential, but we do not have consensus on this.

**Comment by Malvoz** [comment]
@davidmurdoch 

> Will this property be exposed to CSS media queries

There is a proposal in https://github.com/w3c/csswg-drafts/issues/2370.
