### ISSUE TITLE
Consider general storage observer that works for cookies

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/design-reviews#210]
As discussed in https://github.com/w3ctag/design-reviews/issues/189, cookies are a very unique form of storage in our platform. The issue 189 was a review for IndexedDB Observers, and the TAG thought about how a unified "observer" across all storage items might work. 

Cookies didn't really fit the model, but they clearly could use a similar observer-type thing (so devs can see when cookie values change). 

Note, there are new API proposals around cookies that should be reviewed, e.g., https://github.com/WICG/async-cookies-api

**Comment by travisleithead** [comment]
Forgot to add this additional cookie proposal (https://patrickkettner.github.io/cookie-change-events/) though it doesn't help non-UI thread consumers.

**Comment by triblondon** [comment]
TAG London F2F discussion summary (extensive discussion!)

* While we see the logic for a generalised storage observer abstraction over localstorage, cookies, filesystem and other storage backends, we don't think one is feasible.
* We would like to strongly encourage the development of a better API for cookies.  We note the existence of WICG's and @patrickkettner's proposals and we'd love to see one or both of these for TAG review soon.
* Getting, setting and observing cookies are desirable features in service workers, and we'd like to see that functionality supported by a new cookie API.
