### ISSUE TITLE
TAG review of Web Audio API (round two)

### ISSUE THREAD

**Issue by svgeesus** [w3ctag/design-reviews#212]
Dear Sirs and Madam of TAG!

I'm requesting a TAG review of:

  - Name: **Web Audio API**
  - Specification URL: https://webaudio.github.io/web-audio-api/
  - GitHub repo: https://github.com/WebAudio/web-audio-api
  - Explainer, Requirements Doc, or Example code: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_Web_Audio_API
  - Tests: https://github.com/w3c/web-platform-tests/tree/master/webaudio
  - Primary contacts: @rtoy, @padenot

Further details (optional):

  - Relevant time constraints or deadlines: we hope to go to CR early December, ie in four weeks. 
  - [X] I have read and filled out the [Self-Review Questionnaire on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://webaudio.github.io/web-audio-api/#Security-Privacy-Considerations).
  - [X] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

The [previous TAG review](https://github.com/w3ctag/design-reviews/blob/master/2013/07/WebAudio.md)  of this specification is still relevant; please let us know if we failed to address any point in that review. Domenic continued to provide guidance on [issues raised](https://github.com/WebAudio/web-audio-api/issues?utf8=%E2%9C%93&q=label%3ATAG%20) from that earlier review. So this is a request for a second round of review to cover more recent developments and ensure we got everything right from the first round.

The major change since that earlier review is the extensibility point. We switched from [ScriptProcessorNode](https://webaudio.github.io/web-audio-api/#the-scriptprocessornode-interface-deprecated) (running on the main thread, now deprecated) to [Audio worklets](https://webaudio.github.io/web-audio-api/#AudioWorklet) which are of course derived from the TAG/CSS Houdini Worklet. Plus a lot of detailed spec improvements and clarifications. [Complete changes list](https://github.com/WebAudio/web-audio-api/commits/gh-pages).

Tests are being ported into WPT from the Mozilla and Chrome tests; this only started a couple of weeks ago but will fill up in the coming weeks.

We'd prefer the TAG provide feedback as (please select one):

  - [X] open issues in our Github repo for each point of feedback, using the TAG label
  - [ ] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

--------------------------

_Please preview the issue and check that the links work before submitting_

For background, some decent explainers:

  https://github.com/w3c/ServiceWorker/blob/master/explainer.md
  https://github.com/zkoch/paymentrequest/blob/gh-pages/docs/explainer.md
  https://github.com/WICG/IntersectionObserver/blob/gh-pages/explainer.md (although this one includes IDL, which an explainer should not)

**Comment by dbaron** [comment]
WebAudio/web-audio-api#1471 was raised as worth discussing

**Comment by torgo** [comment]
@slightlyoff to leave some feedback on their WebAudio/web-audio-api#1471.

**Comment by torgo** [comment]
We discussed with chairs at [london f2f](https://github.com/w3ctag/meetings/tree/gh-pages/2018/01-london). We are happy with current state of things. Thanks for flying TAG.
