### ISSUE TITLE
Dusting off Web Speech API?

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/design-reviews#214]
Hello TAG!

In a side-conversation with Brian Kardell, he suggested we (the TAG) take another look at the [old] Speech API. It turns out to be partially implemented in all browsers, but this spec seems to have never graduated to a REC.

I'm raising this issue for the TAG to think about whether we want to get involved in doing anything about this feature or not. This feature predates the extensible web manifesto, and is thus pretty high-level, but has a variety of interop problems.

  - Name: Web Speech API
  - Specification URL: https://w3c.github.io/speech-api/webspeechapi.html
  - Explainer, Requirements Doc, or Example code: nope
  - Tests: https://github.com/w3c/web-platform-tests/tree/master/speech-api
  - Primary contacts: ?? (Brian Kardell)

Further details (optional):

  - Relevant time constraints or deadlines: no deadline/timeframe
  - [ ] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](url).
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

Brian has done a series on this API on his site. Here's the relevant links:
* [Intro: The History and State of Speech](https://bkardell.com/blog/The-History-Of-Speech.html)
* [Part I: Greetings, Professor Falken](https://bkardell.com/blog/Greetings-Professor-Falken.html)
* [Part II: You Don't Say](https://bkardell.com/blog/Basic-Voice-Speaker.html)
* [Part III: Listen up](https://bkardell.com/blog/Listen-Up.html)
* [Part IV: Thoughts on Voice Recognition](https://bkardell.com/blog/Voice-Recognition-Thoughts.html)

[ Edited by @dbaron to change http: links to https: per @bkardell's [request](https://github.com/w3ctag/design-reviews/issues/214#issuecomment-388403151) ]

**Comment by nigelmegitt** [comment]
A data point on this: accessibility applications that want to use text to speech could really use a "proper" Web Speech API. In particular the ability to connect the audio output of the speech synthesiser as an input into Web Audio would be extremely helpful. I've actually run up against this specific limitation in implementation work and it has blocked implementation of some features. 

Conversely it is possible to "work around" this by making remote calls to a server to generate audio resources that are then played back some time, but that potentially has privacy implications relative to doing all processing client-side.

**Comment by bkardell** [comment]
If that feels like a lot of reading, I did two chapters sessions on these available as videos as well. I think the presentations themselves are like 10-15 min, then the rest of those is further discussion in the room from attendees... if these are helpful at all

https://youtu.be/gJ0gYki6F9k - tts
https://youtu.be/cxDMhqsMPds - sts

**Comment by torgo** [comment]
Discussed in [London f2f meeting](https://github.com/w3ctag/meetings/tree/gh-pages/2018/01-london).

**Comment by plinss** [comment]
Also, related past work: https://drafts.csswg.org/css-speech-1/

**Comment by torgo** [comment]
We discussed possibly funneling this discussion into a WICG post. @travisleithead to action.

**Comment by travisleithead** [comment]
See notes at our [Day 1 London meeting](https://cryptpad.w3ctag.org/code/#/1/view/JLx5LPxpDmvzEa7730rfnw/ZVd5WIy41f1Y9BJK3cbCV52GeHXJns6dKakxw1DQM1M/)

**Comment by guest271314** [comment]
There are several issues with the current implementation of Web Speech API that have encountered; which can list here, if that contribution is welcome; in brief:

- SpeechRecognition
From perspective here, the most egregious current issue is Chromium/Chrome recording the user and sending that recording to a remote server relevant to the browsers' implementation of `SpeechRecognition` https://bugs.chromium.org/p/chromium/issues/detail?id=816095. Not sure how to address that specification-wise other than to make it clear that the STT should occur within code shipped with the browser or not at all; not at a potentially undisclosed third-party external web service; where the service could very well be retaining and using users' recorded voices to further the parent company proprietary aims; without any compensation for the use of users' voice, if such retention and further use is occurring at all (silent as to that at the filed issue); while simultaneously marketing and promoting their "assistant"  service to compete with *mazon services.

- SSML parsing
Another issue is the implementation of SSML parsing, where the technological capability is present to achieve SSML parsing at the browser, though not implemented, for reasons attributed to other priorities. https://bugs.chromium.org/p/chromium/issues/detail?id=806592, https://bugs.chromium.org/p/chromium/issues/detail?id=88072, https://bugs.chromium.org/p/chromium/issues/detail?id=795371. 

- Web Platform Tests
And tests not being incorporated into WPT. The first of several which can include at WPT https://github.com/w3c/web-platform-tests/pull/9642, based on testing done while composing https://github.com/guest271314/SpeechSynthesisSSMLParser, when it became clear that SSML parsing was not a priority for Web Speech API implementation, while simultaneously a priority as to companies marketing products which do parse SSML as an external web service.

**Comment by bkardell** [comment]
Noticed that the links to my blog posts above are http:// can we change those to https:// ?

**Comment by travisleithead** [comment]
As discussed at a recent teleconference--dropped some thoughts on speech recognition into the w3c/strategy repo. That seems like a better long-term home for this issue. Will discuss on an upcoming telecon whether to close this issue or not.

**Comment by travisleithead** [comment]
Paris F2F- TAG agrees, closing this in favor of tracking issue w3c/strategy#71
