### ISSUE TITLE
Picture-in-Picture (PiP)

### ISSUE THREAD

**Issue by beaufortfrancois** [w3ctag/design-reviews#226]
Hello TAG!

I'm requesting a TAG review of:

  - Name: Picture-in-Picture (PiP)
  - Specification URL: https://wicg.github.io/picture-in-picture/
  - Explainer, Requirements Doc, or Example code: https://github.com/WICG/picture-in-picture/blob/master/explainer.md
  - Tests: Not yet available
  - Primary contacts: @beaufortfrancois, @mounirlamouri

Further details:

  - Relevant time constraints or deadlines: N/A
  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://github.com/WICG/picture-in-picture/pull/41).
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

The API is available in Chrome behind a switch. `--enable-blink-features=PictureInPictureAPI`
Implementation bugs are tracked [here](https://bugs.chromium.org/p/chromium/issues/list?q=component:Blink>Media>PictureInPicture).

We'd prefer the TAG provide feedback as:

  - [ ] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [x] leave review feedback as a comment in this issue and notify @beaufortfrancois and @mounirlamouri

**Comment by torgo** [comment]
Taken up at [london f2f](https://github.com/w3ctag/meetings/tree/gh-pages/2018/01-london).

**Comment by beaufortfrancois** [comment]
Feel free to ping us anytime during the discussion if you have any questions.

**Comment by torgo** [comment]
Discussed in break-out on [day 3](https://cryptpad.w3ctag.org/code/#/1/view/aKq0ReU4W-mXj41lUT-3vg/dI-xTXvZMBs7RQSJ3-4DUyakfqXphWl0FwXaKcla0tY/) of our f2f...

**Comment by triblondon** [comment]
Points from TAG discussion, @cynthia will discuss with the group

* Why just video?  We see use cases for canvas or even arbitrary HTML content
   * Aircraft/train journey map / journey metrics
   * Heads up display for games / apps
* Top and Start props in explainer missing from spec
* Noted that requires user interaction

**Comment by beaufortfrancois** [comment]
I've just updated the explainer (IDL and example) to reflect the current state of the specification. Sorry for the confusion. https://github.com/WICG/picture-in-picture/pull/51

The S&P questionnaire has been filled at the same time as this TAG review request and is available at https://github.com/WICG/picture-in-picture/blob/master/security-privacy-questionnaire.md

Use cases for canvas and HTML content are exciting indeed. There are many security aspects that would need to be addressed though. What we'd like first is a minimal viable product and iterate from it.
See https://wicg.github.io/picture-in-picture/#security-considerations

**Comment by beaufortfrancois** [comment]
@cynthia @triblondon @torgo Is there anything else we can do on our side to help?

**Comment by cynthia** [comment]
@beaufortfrancois Apologies for the silence, can I spend a day to digest the updates and discuss this in a upcoming call if there is anything that needs to be revisited?

(Otherwise, we will revisit this in a call and close if it is a LGTM for the group.)

**Comment by beaufortfrancois** [comment]
No problem. Just wanted to make sure there wasn't anything blocking from our side.

**Comment by beaufortfrancois** [comment]
@cynthia Did you have a chance to look at it?

**Comment by cynthia** [comment]
@beaufortfrancois Yes, I had one last bit that got delayed (the S&P questionnaire) and all of this looks good to me. The canvas use case is something that honestly we didn't think about, but I think it would be a good start to let content authors test the waters and iterate after the MVP is out.

I'll bring this up in a upcoming call and see if there are any issues that I missed during the review. (always good to have a second pair of eyes)

Thanks a lot for your patience and cooperation! We really appreciate it.

**Comment by beaufortfrancois** [comment]
@cynthia Thank you!

Hopefully [2018-03-13-telcon](https://github.com/w3ctag/design-reviews/milestone/151) will include Picture-in-Picture.

**Comment by cynthia** [comment]
@beaufortfrancois
Taken up in 2018-03-13 telco. We're happy to see this new feature as a part of the platform, and if you do expand on it (which we would love to see happen) please let us know. Thanks again for raising the review!

**Comment by beaufortfrancois** [comment]
For future reference, here are the meeting notes: https://github.com/w3ctag/meetings/blob/gh-pages/2018/telcons/03-13-minutes.md
