### ISSUE TITLE
Web Components Guidelines Doc? 

### ISSUE THREAD

**Issue by torgo** [w3ctag/design-reviews#227]
Should the TAG work on a web components design documentation? Could we make use of existing community-developed best practices? Do we have enough useful thinking on this topic to write something that would be useful to the wider community? This issue is intended to collect ideas and feedback on this topic.

**Comment by torgo** [comment]
Discussed at [Tokyo F2F](https://github.com/w3ctag/meetings/blob/gh-pages/2018/04-tokyo/agenda.md) and we agreed that inputting into a document in MDN might be a better plan.

**Comment by kenchris** [comment]
There is a Gold Standard here with a lot of good points: https://github.com/webcomponents/gold-standard/wiki

Rob Dodson also wrote a few documents:
https://github.com/webcomponents/webcomponents.github.io/wiki/BestPractices
http://robdodson.me/interoperable-custom-elements/

Also, https://github.com/mateusortiz/webcomponents-the-right-way

**Comment by torgo** [comment]
Kenneth to put together a strawman doc.

**Comment by kenchris** [comment]
https://docs.google.com/document/d/1mT5xD3kDQURKy5CYTackQDxvRhGMCcn-EfBR6zATX1k/edit#

**Comment by torgo** [comment]
We agreed to try to get more feedback and bump discussion to 5-29.

**Comment by kenchris** [comment]
https://kenchris.github.io/web-components-guidelines/

**Comment by kenchris** [comment]
Moving to TAG GitHub, as webcomponents-design-guidelines/

**Comment by JanMiksovsky** [comment]
@kenchris Was just made aware of this thread by @slightlyoff. Depending on your goals and plans, we'd probably like to be involved in helping draft guidelines for web components. Can you elaborate a bit on those, either here or in mail to jan@component.kitchen?

We wrote the Gold Standard checklist in early 2015 and tried at that point to solicit help fleshing out the list, solidifying the recommendations, and promoting those guidelines — but found very few people who were interested in the topic and willing to actually help. It appears there's more interest now.

**Comment by kenchris** [comment]
Hi there @JanMiksovsky - we already made some recommendations that were reviewed by the TAG team.

You can find the live document here: https://w3ctag.github.io/webcomponents-design-guidelines/ and files issues and ideas here: https://github.com/w3ctag/webcomponents-design-guidelines/issues

The goal was to create some guidelines on how to construct web components in such a way that they could later be adopted by standards (ie. merged into HTML spec with non-hyphenated name).

We also linked to the Goal Standard in the document :-) Any comments and PR's are welcome.

**Comment by torgo** [comment]
We've done this and published a finding. New issues can be registered in the issues list for that doc here: https://github.com/w3ctag/webcomponents-design-guidelines/issues
