### ISSUE TITLE
BCP56bis

### ISSUE THREAD

**Issue by mnot** [w3ctag/design-reviews#232]
[BCP56](https://datatracker.ietf.org/doc/html/rfc3205) defined best practice for how standards-based protocols that wanted to use HTTP "as a substrate" should do so, and was informed by efforts at the time -- being ~2001, [IPP](https://en.wikipedia.org/wiki/Internet_Printing_Protocol).

Since then, things moved on quite a bit, and it's started to become *really* common for people to build APIs on HTTP, and then want to standardise them. However, the common practice of using something like OpenAPI/Swagger to define a bunch of fixed paths isn't really suitable for standards use, both because of clashes with ArchWWW as well as [BCP190](https://datatracker.ietf.org/doc/rfc7320/).

So, I started a revision, [BCP56bis](http://httpwg.org/http-extensions/draft-ietf-httpbis-bcp56bis.html), which tries to guide people towards best (or at least least harmful) practices. That has been adopted by the HTTP Working Group (so I'm acting as an editor on this draft, not a chair).

It's important to understand the audience here -- a typical IETF protocol that wants to use HTTP is more often than not being put together by people who are NOT Web developers, and don't even have a minimal amount of knowledge about how the Web actually works internalised.

This is a work-in-progress (see [open issues](https://github.com/httpwg/http-extensions/labels/bcp56bis)), but I thought the TAG might be interested in providing feedback.

I'm happy to answer questions here, or you can open issues on our repo (one GitHub issue per, and note the contribution policy).

Thanks!

**Comment by mnot** [comment]
P.S. as a general heads-up; the HTTP WG has also opened up the [HTTP "core" documents](https://github.com/httpwg/http-core) for revision (but NOT a new version of HTTP), so if TAG folks know of things that need clarifying / correcting / etc., now's the time.

**Comment by cynthia** [comment]
Non-technical aspect of the review - since this seems to be targeted at a much wider audience than most documents that IETF produces (e.g. RFC7540 is most likely to be read by client library developers and server developers), I **really** think it would be best if some of the wording could be smoothened out to use simple/common English.

I have no idea of the process nor how to edit and RFC, but if you need help I can help out with that bit.

**Comment by torgo** [comment]
Summarising our discussion on this at the [Tokyo F2F](https://cryptpad.w3ctag.org/code/#/1/view/TutVXt+MSZTzQmuNeMrHXg/exTf44AJ0kJSdxfe2TNzKjYoYFos1cbxppVwfGztRtM/): 

1. lack of an explainer

2. what has changed between this and bcp56? (see point 1)

3. stronger on https? e.g. "any new http-based protocol should be https especially when protocols are using authentication tokens."

4. the language should be simplified to enable this to have a wider audience (Sangwhan to elaborate).

5. having a specific section on options might be good.  (e.g. "don't use options")

6. There should there be more discussion on other methods - currently only in-depth discussion on GET. 

7. Section 4.12 "some considerations include" is vague. Whole section needs to contain more concrete advice. More examples needed.

8. perhaps adding a mention of variants.

9. Linkage to [data-on-the-web best practices](ttps://www.w3.org/TR/dwbp/)?

**Comment by cynthia** [comment]
> The audience is specifically IETF document authors -- see writeup above and Introduction.

IETF document authors may not necessarily be native English speakers, and the content of the document seems helpful as a reference even when building HTTP based protocols that aren't necessarily supposed to be standardized.

**Comment by mnot** [comment]
@cynthia happy to take issues or PRs; the draft source is in Markdown here:
  https://github.com/httpwg/http-extensions/blob/master/draft-ietf-httpbis-bcp56bis.md

**Comment by hadleybeeman** [comment]
As requested, @mnot — [Data on the Web best practices](https://www.w3.org/TR/dwbp/). We were thinking of it fitting as another use of HTTP (that isn't web browsing).

Apologies for the delay in getting back to you!

**Comment by mnot** [comment]
Hi, this is marked "pending external feedback" and I'm not sure why -- are you waiting for something from me?

**Comment by plinss** [comment]
During review we noticed that a number of RFC6919 terms are used throughout the document, perhaps consider adding a normative reference?

**Comment by mnot** [comment]
RFC6919 is a joke.

**Comment by plinss** [comment]
:sunglasses:

**Comment by plinss** [comment]
Reviewed and discussed at the Seattle f2f, we don't have any further comments at this time. Sangwhan may still submit some PRs regarding language.

Feel free to re-open if you want us to review a future version.

Thank you for flying TAG.
