### ISSUE TITLE
Keyboard Map

### ISSUE THREAD

**Issue by garykac** [w3ctag/design-reviews#238]
今晩はTAG！

I'm requesting a TAG review of:

  - Name: Keyboard Map
  - Specification URL: https://wicg.github.io/keyboard-map/
  - Explainer, Requirements Doc, or Example code: [Explainer](https://github.com/WICG/keyboard-map/blob/master/explainer.md)
  - Tests: not available yet
  - Primary contacts: garykac

Further details (optional):

  - Relevant time constraints or deadlines: [please provide]
  - [X] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://github.com/WICG/keyboard-map/blob/master/tag-security-privacy.md).
  - [X] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

The problem this API is solving was pointed out as missing feature in a [Mozilla Hacks post](https://hacks.mozilla.org/2017/03/internationalize-your-keyboard-controls/) from last year (in the "What's missing?" section).

We'd prefer the TAG provide feedback as (please select one):

  - [X] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by torgo** [comment]
Discussed at [Tokyo F2f](https://cryptpad.w3ctag.org/code/#/1/view/iUUIKSEXfj1mA1q69PCW8g/xPzPIHA3P9LXPKF-Jb3g-MO075a2Vc6YRjs9ZjGHo2w/).

**Comment by travisleithead** [comment]
Glanced through the explainer, which is very nice. Thanks!

**Comment by torgo** [comment]
Discussed at Tokyo f2f: https://cryptpad.w3ctag.org/code/#/1/view/TutVXt+MSZTzQmuNeMrHXg/exTf44AJ0kJSdxfe2TNzKjYoYFos1cbxppVwfGztRtM/

**Comment by cynthia** [comment]
@garykac, Thanks for bringing this up. We covered this during a breakout session in Tokyo, and have raised issues that were brought up on the spec side issue tracker as requested.

**Comment by torgo** [comment]
Waiting for feedback. @garykac can you let us know what the likely response to our feedback will be?  Specifically your issues 7, 8, 9, 14 and 15? Thanks!

**Comment by garykac** [comment]
I've update the spec/explainer and added comments to those issues. Please let me know if you need additional info.

**Comment by cynthia** [comment]
@garykac Thanks a lot. Will take a look.

**Comment by plinss** [comment]
@garykac We'll be discussing this on https://meet.jit.si/w3ctag at [08:00 PDT on May 15](https://www.timeanddate.com/worldclock/converter.html?iso=20180515T150000&p1=224), hopefully you can join us.

**Comment by torgo** [comment]
Just noting retroactively that we agreed to close this as satisfied in the [May 15 2018 telecon](https://github.com/w3ctag/meetings/blob/gh-pages/2018/telcons/05-15-minutes.md).
