### ISSUE TITLE
Priority Hints API

### ISSUE THREAD

**Issue by domfarolino** [w3ctag/design-reviews#241]
Hello TAG！

I'm requesting a TAG review of:

  - Name: Priority Hints API
  - Specification URL: https://github.com/WICG/priority-hints/
  - Explainer, Requirements Doc, or Example code: https://github.com/WICG/priority-hints/blob/master/EXPLAINER.md, https://wicg.github.io/priority-hints/
  - Tests: None yet
  - Primary contacts: addyosmani, domfarolino, yoavweiss, kenjibaheux

Further details (optional):

  - [ ] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](url).
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

Chrome implementation [has started](https://chromium-review.googlesource.com/c/chromium/src/+/988955), and will first appear under an experimental flag.

We'd prefer the TAG provide feedback as:

  - [x] open issues in our GitHub repo for each point of feedback

**Comment by lknik** [comment]
Very interesting. Looks good, backwards-compat and all.

Can I ask to fill security and privacy questionnaire? Some comments on hot:
- this will decrease browser fingerprintability
- will increase website fingerprintability (e.g. when browsing via Tor or something).

Otherwise, I believe Firefox is using some form of this already, am I right? Specifically making ads/scripts to be fetched at the very end.

**Comment by domfarolino** [comment]
> this will decrease the risk of browser fingerprintability

Could you explain this point? I actually feel like this may increase browser fingerprintability right? Seems like it would increase the surface area for feature (and by extension, browser) detection.

RE website fingerprintability, I assume this is because to an observer, the network traffic to/from sites using Priority Hints might have a more distinguishable pattern, given the way/order in which resources are requested? Makes sense to me, but I think it is almost insignificant since each browser would likely respond to the hints in a slightly different way, so an observer would need to know the UA involved as well.

RE Firefox, I have no idea, but if so, it is an independent loading experiment that is not API-related, and therefore has no normative interplay with Priority Hints. I know Chrome, and I'm sure other browsers, are doing similar experiments to reduce network contention, but yeah, likely not related to the API, as they don't take hints from any exposed API source.

**Comment by yoavweiss** [comment]
@iknik - Friendly ping! I want to add a few words about security and privacy considerations, and would love to have some clarifications on your previous comment.

**Comment by torgo** [comment]
Picking this up again at our February 2019 F2F. This issue has been open for a while. @domfarolino it looks like the draft hasn't moved since October. It looks like the two issues filed based on this review are still open... 

https://github.com/WICG/priority-hints/issues/34
https://github.com/WICG/priority-hints/issues/11

Any update on these? Would any further input from the TAG be useful?

**Comment by yoavweiss** [comment]
Hey TAG folks! :)

> [WICG/priority-hints#34](https://github.com/WICG/priority-hints/issues/34)

This was closed as we added https://wicg.github.io/priority-hints/#negative-ecosystem-side-effects
Please let us know if that language is sufficient from your perspective.

> [WICG/priority-hints#11](https://github.com/WICG/priority-hints/issues/11)

The feedback from @slightlyoff there was that the explainer no longer contains `fetch()` examples, but maybe it should. Looking at the explainer, it seems like all the usage examples have moved from it and into the spec. We should probably duplicate them in the explainer as well.

**Comment by torgo** [comment]
Hi @yoavweiss thanks for the feedback - based on this, I think we are going to close off this issue.
