### ISSUE TITLE
HTML General Review: HTML Drawing

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/design-reviews#260]
Hello TAG！

This issue is part of the TAG's larger effort to review the HTML spec in its entirety--please see the original issue https://github.com/w3ctag/design-reviews/issues/174 for a summary of all the break-out issues.

The "Sections" are all the sections of the WHATWG HTML spec that should be reviewed as part of this issue. Where the spec section has associated Web Platform Tests, the specific WPT path is noted. While the primary focus of the review is the specification text, it can be helpful to review the related tests to help clarify algorithms or see interoperability conformance issues (or find issues with the tests).

The "Features" are just a sample of what you will encounter as part of this spec section, it's not meant to be exhaustive.

Here are some example suggestions for what to look for during the review, but don't limit to only these suggestions!
 * Look for any APIs that could be 'modernized' according to current design practices.
 * Look for things that could require permissions that aren't modelled in the permissions API at the moment.
 * Look for areas of the platform that contain UA 'magic' (aren't possible for JavaScript programs to emulate due to missing primitives in the platform). These are candidates for future Extensible Web archeology.
 * Look for areas of the spec that describe "wishful thinking" (e.g., that describe a feature that is implemented by no one). Such features should at least have implementor commitments, or they might be candidates for removal from the spec.
 * Look for cryptic and hard-to-follow algorithms that could be improved with extra explanatory text or improved prose. E.g., sometimes adding a "developer note" (green box) can add the needed clarity to understand the intent/purpose or outcome of a complex concept. 
 * Look for concepts that are meant to be used together, but where this is not spelled out or explained clearly

|Sections|WPT path|Features|
|-|-|-|
| 4.12.5 | html/semantics/embedded-content/the-canvas-element | `<canvas>` |
| 4.12.5.1 to 4.12.5.2 | 2dcontext | 2d context |
| 4.12.5.3 | offscreen-canvas | `OffscreenCanvas` (see also review #141) |
| 8.8 | (no tests?) | imagebitmap (see also review #141) |

Please provide feedback as (please select one):

  - [ ] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [x] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by travisleithead** [comment]
There is overlap with CSS Houdini's Custom Paint API (which shares large portions of the Canvas context.

**Comment by cynthia** [comment]
Should be reviewed with #288 (notes from F2F)

**Comment by hober** [comment]
Given that we will be fielding annual requests for horizontal review of HTML, I propose that we forward-dupe this to #454 and close.
