### ISSUE TITLE
HTML General Review: IANA Registries

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/design-reviews#274]
Hello TAG！

This issue is part of the TAG's larger effort to review the HTML spec in its entirety--please see the original issue https://github.com/w3ctag/design-reviews/issues/174 for a summary of all the break-out issues.

The "Sections" are all the sections of the WHATWG HTML spec that should be reviewed as part of this issue. Where the spec section has associated Web Platform Tests, the specific WPT path is noted. While the primary focus of the review is the specification text, it can be helpful to review the related tests to help clarify algorithms or see interoperability conformance issues (or find issues with the tests).

The "Features" are just a sample of what you will encounter as part of this spec section, it's not meant to be exhaustive.

Here are some example suggestions for what to look for during the review, but don't limit to only these suggestions!
 * Look for any APIs that could be 'modernized' according to current design practices.
 * Look for things that could require permissions that aren't modelled in the permissions API at the moment.
 * Look for areas of the platform that contain UA 'magic' (aren't possible for JavaScript programs to emulate due to missing primitives in the platform). These are candidates for future Extensible Web archeology.
 * Look for areas of the spec that describe "wishful thinking" (e.g., that describe a feature that is implemented by no one). Such features should at least have implementor commitments, or they might be candidates for removal from the spec.
 * Look for cryptic and hard-to-follow algorithms that could be improved with extra explanatory text or improved prose. E.g., sometimes adding a "developer note" (green box) can add the needed clarity to understand the intent/purpose or outcome of a complex concept. 
 * Look for concepts that are meant to be used together, but where this is not spelled out or explained clearly

|Sections|WPT path|Features|
|-|-|-|
| 16 | html/iana (no tests) | registries meant for IANA |

Please provide feedback as (please select one):

  - [ ] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [x] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by slightlyoff** [comment]
See: https://html.spec.whatwg.org/multipage/iana.html

**Comment by reschke** [comment]
Looking at a random entry:

> 16.10 `Refresh`
> 
> This section describes a header for registration in the Permanent Message Header Field Registry. [RFC3864]
> 
> Header field name:
>     Refresh
> Applicable protocol:
>     http
> Status:
>     standard
> Author/Change controller:
>     WHATWG
> Specification document(s):
>     This document is the relevant specification. 
> Related information:
>     None.

"This document is the relevant specification." - I'd say that pointing to a multi-hundred page spec is relatively unfriendly; how about giving the concrete section number?

**Comment by travisleithead** [comment]
Looks like a PR for the above might be in order :-) (thanks @reschke)

**Comment by hober** [comment]
@travisleithead wrote, a year and a half ago:

> Looks like I could write a PR for the above :-) (good idea @reschke)

Did this happen?

**Comment by hober** [comment]
Given we've only come up with one piece of editorial feedback on this section since this issue was filed, and also given the nature of the section in question, I propose that we close this issue.
