### ISSUE TITLE
Request TAG review of HTML5.3

### ISSUE THREAD

**Issue by LJWatson** [w3ctag/design-reviews#275]
We would welcome your review of [HTML5.3](https://www.w3.org/TR/html53/).

To help make your review easier, we have produced a [changelog](https://www.w3.org/TR/html53/changes.html#changes) that contains all substantive changes made since HTML5.2. Please also note that there are features marked "at risk", documented in the Status.

If there are any issues arising from your review, please file them on the [HTML repo](https://github.com/w3c/html/issues/new/), and apply the "wide review" and "tag" labels to each issue. This will help us track your issues and ensure we respond accordingly.

We would appreciate your feedback no later than Friday 25th May 2018. Thank you.

**Comment by cynthia** [comment]
If there are significant specific differences that we should be looking at, we would be more than happy to review this, I couldn't find anything that would warrant a specific review. If I'm missing something do let me know!

**Comment by LJWatson** [comment]
Thanks @cynthia. I think the most notable difference is probably the inclusion of the Custom Elements specification.

**Comment by LJWatson** [comment]
Ping?

**Comment by cynthia** [comment]
Pong. I’ll bring this up in the next call, which is Tuesday.

**Comment by travisleithead** [comment]
As noted, the TAG is focused on a wide review of the entire HTML specification; however we welcome an opportunity to review anything specific to HTML 5.3 that you'd like to call our attention to and would be happy to keep this issue open to review it. Note, we are tracking Custom Elements as a specific aspect of our wide review (see issue #244).

**Comment by chaals** [comment]
Could you please review two specific things:

1. The `ping` attribute (which is in both specs). There are privacy concerns about this attribute, but there is also a sense that it **could** be used to alleviate such concerns better than alternatives. See https://github.com/w3c/html/issues/1456 for more

2. The way `ruby` allows `<rb>A<rb>B<rb>C<rt>a<rt>b<rt>c` - but currently we only have one implementation plus an intention to implement. See https://github.com/w3c/html/issues/1424

(There is also a specific custom element issue we would like review on - I will note that on #244)

**Comment by travisleithead** [comment]
Thanks! I've copied the `ping` issue into #245 (linking) and the ruby issue into #248 (ruby) so that reviewers of those specific sections will have the context. And I see your note on #244. Given this, I'd like to formally close this issue and thank you for your review request! Please follow-up on the other issues as needed!
