### ISSUE TITLE
Request review of Gamepad API

### ISSUE THREAD

**Issue by LJWatson** [w3ctag/design-reviews#281]
We would welcome your review of the [Gamepad API specification](https://www.w3.org/TR/2018/WD-gamepad-20180508/), as part of our wide review before transitioning to Candidate recommendation (CR).

If there are any issues arising from your review, please file them on the [Gamepad Github repo](https://github.com/w3c/gamepad), and apply the "wide review" label to each issue. This will help us track your comments and respond accordingly.

If there are no issues arising from your review, please let us know by reply to this thread.

We would appreciate your comments no later than Friday 27th June 2018. Thank you.

**Comment by torgo** [comment]
@toji can you help clarify how this fits together with work on gamepad that we've heard whispers of in the WebXR CG?

**Comment by LJWatson** [comment]
In case it helps, the [plan](https://lists.w3.org/Archives/Public/public-webapps/2018JanMar/0019.html) proposed by @SGraham and @cynthia gostonwas to ship an initial version of the spec as it stands/is implemented, with a view to making more substantial changes in V2 - possibly with/within the WebXR space.

**Comment by cynthia** [comment]
We've taken this up in the Seattle F2F, reviewed for any *serious* issues and was unable to find anything substantial that would warrant - say, unshipping the standard.

Some parts would be desirable to improve (e.g. getGamepads() being Promise based and behind a permission), an alternative to a polling model, and many other aspects that have already been reported in the past. We hope those aspects could be improved in the next iteration of the spec - presumably by having us take a look as early as possible.

Thank you for bringing this to our attention.
