### ISSUE TITLE
Page Lifecycle for system initiated Discarding & Freezing

### ISSUE THREAD

**Issue by spanicker** [w3ctag/design-reviews#283]
Hello TAG！

I'm requesting a TAG review of:

  - Name: Page Lifecycle for system initiated Discarding & Freezing
  - Specification URL: https://wicg.github.io/page-lifecycle/spec.html
  - Explainer, Requirements Doc, or Example code: https://github.com/WICG/page-lifecycle/blob/master/README.md
  - Tests: not yet, the plan is here: https://github.com/WICG/page-lifecycle/issues/19
  - Primary contacts: spanicker@

We'd prefer the TAG provide feedback as (please select one):
  - [x] open a single issue in our Github repo for the entire review

**Comment by slightlyoff** [comment]
Hey @plinss & @torgo,

@spanicker let me know that there's a related tab discarding intervention happening in Chromium for 69 (feature freeze at the end of June); marked this for the closest telecon so we can get a look at it before then.

**Comment by spanicker** [comment]
Thanks Alex.
Yes, desktop tab discarding and freezing intervention is targeted for M69.
chrisha@google.com is leading this work.

Also related: https://github.com/w3ctag/design-reviews/issues/205

**Comment by kenchris** [comment]
Looks good to us, thanks for flying TAG!
