### ISSUE TITLE
Carriage of Web Resource in ISOBMFF

### ISSUE THREAD

**Issue by chrisn** [w3ctag/design-reviews#285]
Hello TAG！

I'm requesting a TAG review of:

  - Name: Carriage of Web Resource in ISOBMFF / Advance signaling of MPEG media and containers in web communication environments
  - Specification URL: N/A
  - Explainer, Requirements Doc, or Example code: See email
  - Tests: N/A
  - Primary contacts: @chrisn

Further details (optional):

  - Relevant time constraints or deadlines: June 2018, if possible
  - [ ] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). TBD.
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that these documents were submitted to W3C under liaison from MPEG, for discussion and feedback. The documents themselves are not public, but the authors have confirmed that they are happy for TAG to provide public feedback.

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [x] leave review feedback as a comment in this issue and @-notify @chrisn

**Comment by dbaron** [comment]
The email mentioned is apparently https://lists.w3.org/Archives/Member/tag/2018May/0004.html

**Comment by torgo** [comment]
Discussed on tag call today - question came up of why existing / in progress packaging format cannot be used.

**Comment by chrisn** [comment]
Is either August 28th or September 11th good for a call?

**Comment by cynthia** [comment]
Takeaway from last meeting: https://github.com/w3ctag/meetings/blob/gh-pages/2018/telcons/08-28-minutes.md

Summarized, the use cases seem valid. We have some general concerns around the security model (which has been improved, awaiting access to the updated spec) - particularly on whether or not this context should have access to "powerful features" which are only accessible in secure context, and whether or not this is a secure context, what the origin is, which we would love to have clarified in the updated spec.

Additionally, putting HTTP/packaging equivalent in the scope of a media container as with the current design looks like it could have some future scalability/flexibility issues - we'd love to see if a singular brand that specifies a web package, which can then be run would be an alternate option forward. 

I missed the "Advance signaling of MPEG media and containers in web communication environments" in the review request, will look at that once we have access to the documents. Please let us know when the updated documents have been made available, and we will revisit this review.

**Comment by cynthia** [comment]
I have made attempts to figure out what the advance signaling proposal is trying to do or solve, but a simple explainer could be really helpful here.

**Comment by cynthia** [comment]
As for delivering web content through a MPEG container, we have looked at the proposal and believe that a more adequate approach would be to use web packaging to contain the content, which leaves room for extensibility and doesn't require reinventing a new mechanism. On top of that, using signed exchanges this can prevent tampering with the content, which could be a extremely useful feature given that a DTV transport stream cannot be considered secure against MITM attacks. This is slightly harder when the package is not self-contained, and we believe that this would be more future proof than the proposed approach.

**Comment by dwsinger** [comment]
Hi Cynthia

the point of using a timed container is to get timed actions, which a general package doesn't offer. I'm not sure I understand why an MP4 file is intrinsically insecure -- it's as secure as the channel it's delivered over. Can you explain?

**Comment by cynthia** [comment]
@dwsinger the concern about tampering is because that DTV streams (the kind that goes through a coaxial cable) which aren’t secure.

**Comment by cconcolato** [comment]
The "Advance Signaling" document is not a proposal. It's a survey of the current techniques to do that and of the problems that people are confronted with. The solution may be W3C's Media Capabilities API, but it's not clear at this point.

**Comment by torgo** [comment]
@dwsinger we discussed briefly at f2f and agreed there is something to chat about here. Let's discuss how to be most effective.

**Comment by cynthia** [comment]
Sorry we've dropped the ball on this, @hober and I discussed this during our Tokyo F2F and were curious if any discussion or architectural changes have happened since the last update. (We haven't heard much on this, and since the spec isn't open hard for us to know)

We'd be happy to discuss a path forward on this next week if you folks are available, but the current design seems like it could be iterated on.

**Comment by cynthia** [comment]
(Figured I should explicitly mention @cconcolato and @dwsinger)

**Comment by ylafon** [comment]
@chrisn @cconcolato any news on this, especially if the specification changed since last time we reviewed it.
Thanks,

**Comment by cconcolato** [comment]
The ISO standard has been published late December 2019:
https://www.iso.org/standard/75492.html
I don't know what version you reviewed last, but an important change done just before publication was the removal of the JavaScript tracks.

**Comment by chrisn** [comment]
We haven't discussed this further at W3C, although the team are [exploring running a workshop](https://github.com/w3c/strategy/issues/209) on bundling of interactive media content. We should review the new standard in light of your previous feedback.

**Comment by hober** [comment]
Hi,

@cynthia and I took another look at this during the TAG F2F this week, and we think we can close this review. We encourage all of the interested parties to attend the upcoming related W3C workshop, which we hope will be an excellent opportunity for media people and web people to collaborate in this area.
