### ISSUE TITLE
Request.isReloadNavigation and Request.isHistoryNavigation

### ISSUE THREAD

**Issue by yutakahirano** [w3ctag/design-reviews#289]
Hello TAG！

I'm requesting a TAG review of:

  - Name: Request.isReloadNavigation and Request.isHistoryNavigation
  - Specification URL: https://fetch.spec.whatwg.org/#dom-request-isreloadnavigation and https://fetch.spec.whatwg.org/#dom-request-ishistorynavigation
  - Explainer, Requirements Doc, or Example code: https://github.com/w3c/ServiceWorker/issues/1167
  - Tests: fetch/api/request/ and /service-workers/service-worker/
  - Primary contacts: @yutakahirano, @mattto

Further details (optional):

  - Relevant time constraints or deadlines: We are going to ship the feature very soon.
  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://docs.google.com/document/d/1kxZoY9tUkbRFqTQSZVxNxcdhMsh6dZDC6sJpGXG5gMQ/edit#).
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

[please tell us anything you think is relevant to this review]

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [x] leave review feedback as a comment in this issue and @-notify [github usernames]

--------------------------

_Please preview the issue and check that the links work before submitting_

For background, some decent explainers:

  https://github.com/w3c/ServiceWorker/blob/master/explainer.md
  https://github.com/zkoch/paymentrequest/blob/gh-pages/docs/explainer.md
  https://github.com/WICG/IntersectionObserver/blob/gh-pages/explainer.md (although this one includes IDL, which an explainer should not)

**Comment by mattto** [comment]
Correction: matto should be @mattto

**Comment by yutakahirano** [comment]
Done.

**Comment by travisleithead** [comment]
I took a look at this and think it looks great--addresses developer feedback. And provides an easy to read state that avoids rolling your own system based on cache states.

**Comment by torgo** [comment]
We [had a discussion](https://github.com/w3ctag/meetings/blob/gh-pages/2018/telcons/06-26-minutes.md) on the privacy implications and agreed we were largely happy with this. We noted that @diracdeltas might have further comments regarding the privacy implications? In any case we decided to close. Thank you for flying TAG.
