### ISSUE TITLE
Stale-While-Revalidate handling in browser

### ISSUE THREAD

**Issue by dtapuska** [w3ctag/design-reviews#293]
Hello TAG！

I'm requesting a TAG review of:

  - Name: Stale While Revalidate
  - Specification URL: [Explainer](https://github.com/dtapuska/stale-while-revalidate)
  - Explainer, Requirements Doc, or Example code: [Explainer](https://github.com/dtapuska/stale-while-revalidate)
  - Tests: None
  - Primary contacts: @dtapuska

Further details (optional):

  - Relevant time constraints or deadlines: We wish to conduct an origin trial as soon as possible
  - [X] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://github.com/dtapuska/stale-while-revalidate/blob/master/security_qustionnaire.MD).
  - [X] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

[please tell us anything you think is relevant to this review]

We'd prefer the TAG provide feedback as (please select one):

  - [X] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [dtapuska]

**Comment by ylafon** [comment]
See https://tools.ietf.org/html/rfc5861

**Comment by dbaron** [comment]
It's not clear to me from the explainer if the idea is that, if the revalidation returns something different, the resource is *replaced* (which would make sense for something like images or fonts... but not for something like scripts), or if the only effect is that the cache entry is replaced so the fresh copy is used the next time around.

**Comment by dtapuska** [comment]
No the resource is *not* replaced in a rendered page. It will only be replaced in any caches. Something requesting the resource again (like adding a script or img tag) will get the newly revalidated copy.

**Comment by ylafon** [comment]
We discussed this during our Paris F2F, we have no specific comment on this.
Thanks,
