### ISSUE TITLE
Support codec and container switching with MSE using SourceBuffer.changeType()

### ISSUE THREAD

**Issue by wolenetz** [w3ctag/design-reviews#298]
Bonjour TAG,

I'm requesting a TAG review of:

  - Name: Support codec and container switching with MSE using SourceBuffer.changeType()
  - Specification URL: [WICG Media Source Extensions codec-switching incubation editor's draft, containing changeType() specification and related algorithm updates](https://rawgit.com/wicg/media-source/codec-switching/index.html)
  - [Explainer](https://github.com/wicg/media-source/blob/codec-switching/codec-switching-explainer.md), [Spec issue](https://github.com/w3c/media-source/issues/155), and [Demo, in Chrome 69+, first enable chrome://flags#enable-experimental-web-platform-features](https://rawgit.com/wolenetz/shaka-player/mse-codec-switching-demo-using-shaka-player/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;lang=en-US;logtoscreen;debug;build=uncompiled)
  - Tests: Added to existing MSE suite: media-source/mediasource-changetype.html and media-source/mediasource-changetype-play.html
  - Primary contacts: @wolenetz. (@jyavenard also directly participated in the feature's design and incubation.)

Further details (optional):

  - Relevant time constraints or deadlines: This feature was requested long before MSE REC, and the use case persists. Some MSE users, such as YouTube, have strong interest in using it ASAP.
  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://github.com/wolenetz/media-source/blob/codec-switching/wolenetz-w3ctag-security_and_privacy_questionnaire-codec_switching.md).
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

Firefox 63+ contains an implementation of this new API (SourceBuffer.changeType()) on-by-default.
Chrome 69+ contains an implementation conditioned by chrome://flags#enable-experimental-web-platform-features, and [the intent-to-ship it on-by-default](https://groups.google.com/a/chromium.org/d/topic/blink-dev/K_OFPxA_whE/discussion) is currently pending approvals.

Please go by the editor's draft, not the explainer (the explainer predated the spec, and some small things have changed such as changeType() is a void, not boolean method; it throws if called in bad state or if the change isn't supported.) I'll be updating the explainer this week to make it reflect the spec more precisely.

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [x] leave review feedback as a comment in this issue and @-notify [wolenetz, jyavenard]

Thank you!

**Comment by travisleithead** [comment]
I will note that this has lots of support from various teams inside of Microsoft. :)

**Comment by wolenetz** [comment]
Safari Technical Preview, as of at least a week ago, also contained an experimental implementation of SourceBuffer.changeType(). @jernoble

**Comment by cynthia** [comment]
We're happy to see this addition (bug fix?) to the feature set of MSE. As a much needed addition to the currently shipping MSE API, I don't think we have any notable objections towards the design or functionality of the proposal.

(I do state we, but I haven't actually discussed this with the rest of the group yet. To be brought up in a upcoming call.)

**Comment by travisleithead** [comment]
Likewise, have reviewed this, and have no outstanding concerns. Really appreciate the detailed explainer and concerns and design alternatives considered.

**Comment by cynthia** [comment]
Taken up at Paris F2F, we're happy to see this work move forward - thanks for bringing this to our attention.
