### ISSUE TITLE
FetchEvent.resultingClientId

### ISSUE THREAD

**Issue by mattto** [w3ctag/design-reviews#307]
Bonjour TAG,

I'm requesting a TAG review of:

  - Name: FetchEvent.resultingClientId
  - Specification URL: https://w3c.github.io/ServiceWorker/#fetch-event-resultingclientid
  - Explainer, Requirements Doc, or Example code: There's some discussion at https://github.com/w3c/ServiceWorker/issues/1091 and https://github.com/w3c/ServiceWorker/issues/1245.

  - Tests: service-workers/service-worker/navigation-redirect.https.html
  - Primary contacts: @mattto @jungkees @jakearchibald

Further details (optional):

  - Relevant time constraints or deadlines: I want to implement this in Chrome by next week (Oct 11)
 
You should also know that...

There is a related `replacesClientId` attribute specified, which I am not planning to implement in Chrome for now because there has been no clear developer demand.

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [x] leave review feedback as a comment in this issue and @-notify @mattto @jungkees @jakearchibald

**Comment by cynthia** [comment]
Discussed during today's teleconference. We apologize that this took so long.

We've decided that we dragged on this for way too long, and any feedback at this point would be a bit too late. (already shipping in two implementations) So we are closing this. Thank you so much for the patience.

(If this happens again, please bump the thread and make us aware!)
