### ISSUE TITLE
IndexedDB Transaction Explicit Commit API

### ISSUE THREAD

**Issue by andreas-butler** [w3ctag/design-reviews#316]
こんにちはTAG！

I'm requesting a TAG review of:

  - Name: IndexedDB Explicit Commit API for Transactions
  - Specification URL: https://pr-preview.s3.amazonaws.com/w3c/IndexedDB/pull/242.html#dom-idbtransaction-commit
  - Explainer: https://andreas-butler.github.io/idb-transaction-commit/EXPLAINER
  - Primary contacts: @andreas-butler, @dmurph

Further details (optional):

  - Relevant time constraints or deadlines: Preferably before the end of this quarter.
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [x] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by torgo** [comment]
Discussed on [call 15-jan](https://github.com/w3ctag/meetings/blob/gh-pages/2019/telcons/01-15-agenda.md).

**Comment by kenchris** [comment]
First of all, thanks a lot of the excellent explainer! We noticed that the API can throw so we would like to see some examples of how to do proper error handling.

I understand the worry that people will think they have to manually call `commit()` so what about renaming it to something like `forceCommit()` which feels like something you would only call if you know what you are doing

**Comment by kenchris** [comment]
@andreas-butler, @dmurph please see above

**Comment by andreas-butler** [comment]
Hi Ken,

Thanks for the feedback and the bump. We agree that the commit -> forceCommit rename is a good idea, and we will be adding examples of error handling to the explainer.

Best,
Andreas

**Comment by andreas-butler** [comment]
@inexorabletash raised a point to keep in consideration going forward with the rename: there are plans to, at some point in the future, design and add a feature to indexeddb that allows developers to forego autocommit entirely and commit only when they're ready. If this feature is implemented as another type of 'commit' call it is worth considering if there will be problems naming it if the name 'forceCommit' has already been taken here.

**Comment by cynthia** [comment]
That is a good point, I don’t think any of us are in the position of “this may not ship unless it is renamed to force” so that sounds good to me.

**Comment by kenchris** [comment]
Thanks for flying TAG, this looks fine to us
