### ISSUE TITLE
Querying Encryption Scheme Support Through EME

### ISSUE THREAD

**Issue by joeyparrish** [w3ctag/design-reviews#322]
こんにちはTAG！

I'm requesting a TAG review of:

  - Name: Querying Encryption Scheme Support Through EME
  - Specification URL: No spec text yet beyond the explainer (I'm new at this)
  - Explainer, Requirements Doc, or Example code: https://github.com/WICG/encrypted-media-encryption-scheme/blob/master/explainer.md
  - Tests: None yet
  - Primary contacts: @joeyparrish

We'd prefer the TAG provide feedback as (please select one):

  - [X] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

--------------------------

Thank you!

**Comment by hober** [comment]
Hi @joeyparrish!

The TAG looked at your explainer during our F2F this week, and we're generally happy with the approach here. Closing this issue; please reopen if your design changes enough to warrant additional review.
