### ISSUE TITLE
EME Extension: HDCP Policy Check

### ISSUE THREAD

**Issue by joeyparrish** [w3ctag/design-reviews#323]
こんにちはTAG！

I'm requesting a TAG review of:

  - Name: EME Extension: HDCP Policy Check
  - Specification URL: No spec text yet beyond the explainer (I'm new at this)
  - Explainer, Requirements Doc, or Example code: https://github.com/WICG/hdcp-detection/blob/master/explainer.md
  - Tests: None yet
  - Primary contacts: @joeyparrish

We'd prefer the TAG provide feedback as (please select one):

  - [X] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

--------------------------

Thank you!

**Comment by cynthia** [comment]
Note: Not a full review.

One bit from a API consistency perspective: If there are other cases in the platform that allow scoping of versions, it probably would make sense for this to be consistent. (e.g. One API requiring `{'over': '1.0'}` and another requiring `{'minVersion': '1.0'}` would be suboptimal.)

Curious how this would tie into [1] remote playback devices which are connected to a HDCP display - the current spec design seems like even if one has a HDCP capable playback device/display pair as a remote device one would still get a low-res fallback.

[1] https://w3c.github.io/remote-playback

**Comment by torgo** [comment]
Some question about what the status is here... We have discussed today closing this issue preemptively.

**Comment by hober** [comment]
Looks like this is [shipping in Chrome](https://www.chromestatus.com/feature/5652917147140096).

**Comment by joeyparrish** [comment]
Sorry, everyone, for dropping the ball on responding to the feedback given here.

@cynthia, we have no plans for a maximum HDCP version check, as content security policies only ever go in one direction.

To your point about the remote playback API, we hadn't really considered that.  And I don't see any mention of EME in the remote playback spec, so I'm not sure how remote playback will work with EME generally.  I will reach out to the editors of the remote playback spec about this.

@hober, re:

> The existing way to check for HDCP requires a successful key exchange, which means that only sites trusted by the CDM can query this.

There's no such thing as "sites trusted by the CDM".  The CDM has no knowledge of the context in which it is running, and the license exchange is actually carried out by the web app.  So the reality is that the sites which can do this today are "sites that have access to a license server".  Several open-access license servers exist for the purposes of testing and integration, and their CORS headers allow access from "*".  So this becomes all sites running in a secure context.  Any HTTPS-hosted site can do a license exchange with these open license servers.

**Comment by joeyparrish** [comment]
@hober, moving privacy vs performance discussion to https://github.com/WICG/hdcp-detection/issues/11.  Thanks!

**Comment by joeyparrish** [comment]
@cynthia, moving discussion of remote playback vs EME to https://github.com/w3c/remote-playback/issues/124.  Thanks!

**Comment by hober** [comment]
It looks like it’s [implemented in Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1404230) as well as Blink.

**Comment by hober** [comment]
Hi,

@plinss and I looked at this at our Cupertino F2F. It looks like this is implemented in two browser engines, but there’s a bunch of spec work left to do. Please let us know when the spec is more fleshed out.

We’re going to close this issue, as all of the concerns TAG participants raised earlier have been filed as issues on the spec. Please open a new design review issue if you significantly change the API.
