### ISSUE TITLE
WebRTC DSCP Control API

### ISSUE THREAD

**Issue by alvestrand** [w3ctag/design-reviews#325]
こんにちはTAG！

I'm requesting a TAG review of:

  - Name: WebRTC DSCP Control API
  - Specification URL: https://w3c.github.io/webrtc-dscp-exp/
  - Explainer, Requirements Doc, or Example code: N/A
  - Tests: N/A
  - Primary contacts: hta@google.com, thaloun@google.com

Further details (optional):

  - Relevant time constraints or deadlines: Planning to experiment in Chrome M72
  - [X] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://github.com/w3c/webrtc-dscp-exp/issues/3).
  - [X] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that this is a minor control surface added to the WebRTC spec to split up an existing feature (priority) into two independent components (local prioritization and DSCP codepoint usage) without making changes to already-agreed documents.

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [X] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by alvestrand** [comment]
tagging @thaloun

**Comment by slightlyoff** [comment]
@alvestrand: we quickly discussed today and there's a question about what problem this solves. An explainer would go a long way, as would example code. Without some motivation and context, it's hard to understand what this feature is for, who it helps, and what risks we run.

**Comment by cynthia** [comment]
DSCP isn't disambiguated anywhere in the spec, which I think should be considered a bug. (At least I have not a slight clue what that is.)

**Comment by cynthia** [comment]
We don't quite know what to do with this issue, and it's been dangling for quite a bit. We'll close it for now as - happy to discuss this in person next week during TPAC if still needs our input.
