### ISSUE TITLE
Web Bluetooth Scanning

### ISSUE THREAD

**Issue by dougt** [w3ctag/design-reviews#333]
こんにちはTAG！

I'm requesting a TAG review of:

  - Name: Web Bluetooth Scanning
  - Specification URL: https://webbluetoothcg.github.io/web-bluetooth/scanning.html
  - Explainer: https://docs.google.com/document/d/1N_zWN10qqCsut2-i3JBhTxgV6lgASu7WoslEtm-vyms/edit?usp=sharing
  - Tests: wpt/bluetooth/requestLEScan
  - Primary contacts: dougt
  - Privacy & Security review: in explainer

  - [ X] leave review feedback as a comment in this issue and @-notify dougt

**Comment by cynthia** [comment]
Not a full review, drive-by comment on one detail.

Exposing the underlying technology in the API name (BLE) is not really something that is future-proof, considering that removing APIs from the web platform tend to be harder than adding them. Generally, we recommend a generic interface over polluting the namespace with different underlying technology variants of the same functionality whenever possible.

**Comment by kenchris** [comment]
Also the official standard is called Bluetooth Smart, not Low Energy, to my knowledge.

**Comment by torgo** [comment]
Some questions: What are the user stories? Why is having it  not going to make users sad? Can you articulate some of the possible threats to user privacy that might make users sad? Have the spec been designed such that the threats to user privacy are mitigated?

**Comment by kenchris** [comment]
This allows a website to know about all the devices around it, which is a privacy issue. Would it be possible to restrict this to a specific device UUID? Or would that not cover the use-cases?

**Comment by torgo** [comment]
@dougt can you update the explainer based on the feedback above and we'll cycle back with you?

**Comment by dougt** [comment]
> Also the official standard is called Bluetooth Smart, not Low Energy, to my knowledge.

I believe "Smart" was a marketing term which seems to be no longer used.  I also recall that devices that had that mark may have been compatible with both classic and LE.


> What are the user stories? 

There are a few use cases listed in the explainer as well as the spec:
    https://webbluetoothcg.github.io/web-bluetooth/scanning.html

Per the feedback, I will add more user stories that addresses the value of this API.


> Why is having it not going to make users sad?

I don't understand the question.


> Can you articulate some of the possible threats to user privacy that might make users sad? Have the spec been designed such that the threats to user privacy are mitigated?

There is a privacy considerations section the spec:
   https://webbluetoothcg.github.io/web-bluetooth/scanning.html

From an implementation point of view, we are investigating UX around permission granting and believe that we will have an experience that keeps the user informed of a ble scan as well as protect them against random drive by sites trying to do a BLE scan.


> Would it be possible to restrict this to a specific device UUID? Or would that not cover the use-cases?

A web developer can filter out devices they don't care about, but that is an optimization.


> can you update the explainer based on the feedback above and we'll cycle back with you?

Yes, thank you for the feedback.  In the next few days/weeks I hope to update the explainer. I hope my above answer can help allow you to make a bit of progress on the review.

**Comment by kenchris** [comment]
> I believe "Smart" was a marketing term which seems to be no longer used. I also recall that devices that had that mark may have been compatible with both classic and LE.

No, those are confusingly called "Smart Ready"

**Comment by kenchris** [comment]
> I don't understand the question.

I believe that @torgo is afraid that it compromises privacy, in the case that a site can now figure out what devices are around you, and maybe even finding out who you are with (given they are using the same app and also scanning etc)

**Comment by dougt** [comment]
> I believe that @torgo is afraid that it compromises privacy

Yes, similar to many powerful features that we have brought to the web, without some sort of UX protecting the user, this feature would compromise privacy.  The non-normative section of the spec touches on this, but I can make that more explicit. The explainer has a FAQ which directly answers this concern:

  How are permissions handled?
     The user must grant permission for the site to scan for BLE devices.


> As it would be better to do it upfront so that the web developer never gets access to those other devices in the first place

We have no real way up front to know what devices the UA should share with the user and which it shouldn't.  An implementation can clearly make this call on behalf of the user, but it's probably outside the scope of the specification (maybe we add language that suggests a UA could do this sort of filtering)

As for our implementation, we plan on having some UI that shows the user what devices are currently in the user's space as well as a persistent 'scanning' ui treatment.

**Comment by lknik** [comment]
Hi,

I'm a bit concerned that scanning takes existing bluetooth capacity (along with its [issues](https://blog.lukaszolejnik.com/w3c-web-bluetooth-api-privacy/)) to the next level. Good it is gated with permissions, but I'm wondering if the user will get what the location tracking implications are.

**Comment by cynthia** [comment]
BLE scanning is generally for indoor location tracking through beacons, so I can imagine there are some scary bits to it.

**Comment by torgo** [comment]
@dougt is the explainer available somewhere else at a stable URL that is not a google doc please?

**Comment by torgo** [comment]
We have identified this review as "stalled" from the TAG's perspective. @dougt can you let us know at this point what the state of this spec is and how the TAG's feedback can be most helpful? We remain concerned about the security & privacy aspects of the spec. It still looks like the security & privacy questionnaire hasn't been filled out for this. If it has, can you please point to the results.

**Comment by dougt** [comment]
> @dougt can you let us know at this point what the state of this spec is

It seems implementable. We implemented this API behind a command line flag in Chromium.  Not major issues were found.

> how the TAG's feedback can be most helpful? 

The most important feedback to me would around ensure that the proposed API is consistent with the fundamental  Web architecture and specifically with the existing device APIs that you all have seen.

> We remain concerned about the security & privacy aspects of the spec. 

Specifics are good here.  I have outlined a number of concerns I had and how we addressed them.  What are you concerned about specifically?

> It still looks like the security & privacy questionnaire hasn't been filled out for this. If it has, can you please point to the results.

Is that new?  I don't think we filled one out for the Bluetooth gatt connection API.

**Comment by cynthia** [comment]
Sorry for the extremely delayed reply - this issue fell through the cracks and we did not notice that there was an update. One other bit we are curious about is if there was positive signals from other implementors on this feature.

> The most important feedback to me would around ensure that the proposed API is consistent with the fundamental Web architecture and specifically with the existing device APIs that you all have seen.
> Specifics are good here. I have outlined a number of concerns I had and how we addressed them. What are you concerned about specifically?

We're drafting this right now, will post shortly after this comment.

> Is that new? I don't think we filled one out for the Bluetooth gatt connection API.

Somewhat - I'm not sure when this spec was filed, but it is now a mandate in our new review process. We understand it is a bit of extra work, but a self-review is an extremely useful starting point for us to look into the potential privacy/security implications from the new feature.

**Comment by kenchris** [comment]
I find the requestLEScan a bit weird, first of all, it returns BluetoothLEScan when it resolves which has the same info that you just set as part of calling requestLEScan so maybe not that useful.

Also, it has a `stop` method, but today newer APIs will be using the AbortController instead @francoisbeaufort

**Comment by kenchris** [comment]
I think the scan should be cancelled in certain situations like loosing focus, or maybe a browser defined timeout. In that case you should fire an AbortError. Take a look at the Wake Lock spec to see how it is done there

**Comment by cynthia** [comment]
We took this up during a breakout during the Tokyo F2F. I second the remarks @kenchris made above. Comments and questions follow:

1. This should probably be a feature that only works on the currently focused window.
2. Otherwise, normative reject conditions under race would be extremely helpful for other implementors (e.g. two tabs scanning at the same time - is this possible?)
3. We'd be more happy if this feature was a active tab (Point 1 in this list) only feature, as it can be power consuming for mobile devices and has privacy consideration. A visual indicator (like we do with audio) when scanning could be useful.
4. Following those thoughts, a grace period for blurred tabs (e.g. if user moved focus to a different tab for more than n seconds right after starting a scan, stop scanning) sounds like a potential mitigation for racing (or wasting resources) while adding some safety.

**Comment by g-ortuno** [comment]
I find the use of AbortController a bit confusing in this case. I would expect `abort` to be used when stopping a pending request e.g. a connection request before the connection is made, not when a connection is already established. In this case, since the request to start a scan has already been completed, a `stop()` method makes more sense to me.

**Comment by kenchris** [comment]
in other specs though, (cc @reillyeon) we have been asked to use AbortController for that. That additionally allows to cancel this together with cancelling other things.

**Comment by dougt** [comment]
> We took this up during a breakout during the Tokyo F2F. I second the remarks @kenchris made above. Comments and questions follow:
> 
> 1. This should probably be a feature that only works on the currently focused window.

Yes, that is what we're doing in Chrome.  When the window loses focus, we stop the scan.

> 2. Otherwise, normative reject conditions under race would be extremely helpful for other implementors (e.g. two tabs scanning at the same time - is this possible?)

Yes, you can have two tabs scanning at the same time.  

> 3. We'd be more happy if this feature was a active tab (Point 1 in this list) only feature, as it can be power consuming for mobile devices and has privacy consideration. A visual indicator (like we do with audio) when scanning could be useful.

Agreed about active tab/window only.  The visual indicator is a nice idea, but it's not something that I think we should spec out.

> 4. Following those thoughts, a grace period for blurred tabs (e.g. if user moved focus to a different tab for more than n seconds right after starting a scan, stop scanning) sounds like a potential mitigation for racing (or wasting resources) while adding some safety.

I do not follow this thought.

**Comment by torgo** [comment]
Hi @dougt et al. Has there been any update to the spec / explainer based on the feedback that was shared at TPAC? Also at TPAC I heard about some positive steps being taken to mitigate against privacy issues. Has any of this been documented? Any further info on the progress with this spec's implementation / developer feedback you have had thus-far?

**Comment by dougt** [comment]
Torgo@ see my comment from Sept 21. Can you explain what privacy issues you heard about in TPAC?  Not sure what I should document outside of the privacy considerations in the draft spec.  Thanks!

**Comment by torgo** [comment]
@dougt in the explainer it describes showing the user the devices around you during the permissions request - to emphasize that the user is granting permission for the web page to see this information (rather than just generically asking them for Bluetooth scanning permission). I don't see discussion of this in the privacy & considerations section. Nor do I see a more detailed response to the privacy & security [questionnaire](https://www.w3.org/TR/security-privacy-questionnaire/). The use cases in the use cases document also do not discuss how the user will interact with permissions requests during the operation of this API and this seems intrinsic to the experience since the whole point seems to be to create a seamless user experience of the web page interacting with local BLE devices.

**Comment by torgo** [comment]
Hi @dougt any feedback on the above? We'd like to be able to close this off at our f2f coming up in 2 weeks if possible. Thanks.

**Comment by kenchris** [comment]
@reillyeon @scheib I believe you were both at TPAC and may have been the ones sharing the new info around the permission model showing visible devices around you before accepting.

**Comment by torgo** [comment]
Hi folks - we're not happy with this continuing to be in our queue because form our perspective it doesn't seem to be moving. Rather than continue to spin our wheels, we're going t close this preemptively but when there has been progress and things have moved forward please feel free to ping us here and we can re-open.
