### ISSUE TITLE
Heads up: Verifiable Credentials review request coming shortly

### ISSUE THREAD

**Issue by burnburn** [w3ctag/design-reviews#335]
Hello, TAG!  The Verifiable Claims Working Group has made great progress on its specification, the Verifiable Credentials Data Model 1.0 document.

While we have asked for and received reviews from various other groups at W3C (including PING) and beyond, we have not yet had a TAG review.  Since we are close to publishing our first Candidate Recommendation version of the specification, we need to correct that.  We expect within the next week or two to ask you for your review and were advised to give you a heads up to help with scheduling.

We are finishing up the Explainer for the specification at this time.

Although we are not asking for review yet, here are the links for the spec and explainer if you'd like to take an early look.

Editor's draft (tip of tree): https://w3c.github.io/vc-data-model/
Explainer:  https://github.com/w3c/vc-data-model/blob/gh-pages/VCDMExplainer.md

We will of course use your template when we send the request itself.

**Comment by cynthia** [comment]
Taken up during the Tokyo F2F.

Thank you for letting us know. Please file a new review request when you have a specification ready to review. We will be closing this for now.
