### ISSUE TITLE
Import maps

### ISSUE THREAD

**Issue by domenic** [w3ctag/design-reviews#340]
今日はTAG！

I'm requesting a TAG review of:

  - Name: Import maps
  - Specification URL: no real spec yet; some work in progress at [1](https://github.com/WICG/import-maps/blob/master/spec.md), [2](https://wicg.github.io/import-maps/), [3](https://github.com/WICG/import-maps/tree/master/reference-implementation)
  - Explainer, Requirements Doc, or Example code: https://github.com/WICG/import-maps/blob/master/README.md
  - Tests: Tentative tests in progress at https://chromium-review.googlesource.com/c/chromium/src/+/1449072
  - Primary contacts: @domenic, @hiroshige-g, @nyaxt

Further details (optional):

  - Relevant time constraints or deadlines: we hope to do an origin trial in Chromium within the month.
  - I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://github.com/WICG/import-maps/blob/master/Security%20and%20Privacy.md).
  - I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

Please read the following sections to head off common questions:

- https://github.com/WICG/import-maps/blob/master/README.md#alternatives-considered
- https://github.com/WICG/import-maps/blob/master/README.md#supplying-out-of-band-metadata-for-each-module
- https://github.com/WICG/import-maps/blob/master/README.md#scope
- https://github.com/WICG/import-maps/blob/master/Security%20and%20Privacy.md#a-note-on-threat-models

We'd prefer the TAG provide feedback as (please select one):

  - open issues in our Github repo for each point of feedback

(I hope this is done; in the past I've seen this preference disregarded a lot.)

**Comment by cynthia** [comment]
> (I hope this is done; in the past I've seen this preference disregarded a lot.)

Noted. Apologies for the cases where we didn't acknowledge this preference.

**Comment by cynthia** [comment]
@kenchris and I went through this today. We're happy to see this feature move forward, and apologies that it took so long. We had some minor issues but none that would warrant blocking the feature from moving forward.

I in particular had some questions about the case that involved a long list of imports (and how to mitigate that with dependencies), and whether or not that is a good practice moving forward, which we also brought up in the modulepreload review. That should probably be treated as a separate bug report in some place; we'd appreciate feedback on where that should be filed.

**Comment by domenic** [comment]
> I in particular had some questions about the case that involved a long list of imports (and how to mitigate that with dependencies), and whether or not that is a good practice moving forward, which we also brought up in the modulepreload review. That should probably be treated as a separate bug report in some place; we'd appreciate feedback on where that should be filed.

I'm not sure exactly what you mean, but it sounds like maybe you're concerned in general about applications that import a lot of files? I think that's probably a general concern with the JavaScript module system, and so best filed at https://github.com/tc39/ecma262. But I may be misunderstanding.

**Comment by kenchris** [comment]
Thanks for flying TAG!
