### ISSUE TITLE
Subresource prefetching+loading via Signed HTTP Exchange

### ISSUE THREAD

**Issue by horo-t** [w3ctag/design-reviews#352]
Góðan dag TAG！

I'm requesting a TAG review of:

  - Name: Subresource prefetching+loading via Signed HTTP Exchange
  - Specification URL: https://github.com/WICG/webpackage/issues/347
  - Explainer, Requirements Doc, or Example code: [Explainer](https://docs.google.com/document/d/1tARwhN_yymddnhyGrYmmM8b9RP0RKPKW_6T9yEI5CAg/edit?usp=sharing)
  - Tests: not yet
  - Primary contacts: @horo-t

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [x] leave review feedback as a comment in this issue and @-notify [@kinu @jyasskin @sleevi]

**Comment by annevk** [comment]
Do you have a specification URL that's not a long discussion?

Also, given how prefetching itself [still isn't defined from first principles](https://github.com/w3c/resource-hints/issues/86), I'm rather concerned about adding yet more complexity on top.

**Comment by horo-t** [comment]
Sorry we don't have formal specification yet.
The [Proposal section in the Explainer](https://docs.google.com/document/d/1tARwhN_yymddnhyGrYmmM8b9RP0RKPKW_6T9yEI5CAg/edit#heading=h.jrdo62x5vsb9) may be easier to understand.

**Comment by torgo** [comment]
Discussed at [f2f 22-05-2019](https://github.com/w3ctag/meetings/tree/gh-pages/2019/05-reykjavik).

**Comment by torgo** [comment]
@horo-t we are picking this up now at our f2f (in Google's Tokyo office btw).  It looks like there has been some progress on the WICG web packaging issue that you have referenced above. Can you let us know what the latest status of this is and what type of feedback you would most like to see from the TAG that could help? I see from https://github.com/WICG/webpackage/issues/347#issuecomment-510277033 that there are now 2 explainers? Where would you like the TAG to focus?

**Comment by horo-t** [comment]
During the spec discussion, we focused on how to prevent user tracking.
As described at [Security and Privacy Considerations](https://github.com/horo-t/subresource-signed-exchange/blob/master/signed-exchange-subresource-subtitution-explainer.md#security-and-privacy-considerations), this feature only exposes 1 bit information because UAs can use the cached signed exchange only if the required signed exchanges are all available.


I'd like the TAG to check if following sound reasonable:
 - The overall use-case / considerations we've made for privacy.
 - Iintroducing a new rel=allowed-alt-sxg link header.
   This new "allowed-alt-sxg" link header is only for signed exchange.
 - Extending the usage of the existing rel=alternate link header.
   The alternate link headers are already widely used for several use cases.

Let me also share our current status in Chromium. 
We have implemented in Chromium, and we are planing to start Origin Trial soon.

**Comment by torgo** [comment]
@horo-t we are working through this now. Can you provide any feedback from your origin trial?

**Comment by torgo** [comment]
@lknik can you take a look at their [answers to the security & privacy questionnaire](https://github.com/horo-t/subresource-signed-exchange/blob/master/signed-exchange-subresource-subtitution-explainer.md#self-review-questionnaire-security-and-privacy)?

**Comment by torgo** [comment]
I've put this in "proposed closing" for now as if we are happy with the proposal and with the answers to the security & privacy questionnaire then we might be ready to close this one off.

**Comment by ylafon** [comment]
The extension of rel=alternate seems fine to me, if you consider that it is an alternate format, as it requires specific handling, and not just an alternate URL. (`rel=duplicate` has been used for the latter use case, not sure about its implementation state). Introducing a specific new link header seems also fine (`allowed-alt-xsg`).

**Comment by horo-t** [comment]
I received a feedback that the user agent should send a NEL (Network Error Logging) report when there was a the header-integrity mismatch while handling subresource signed exchanges. (https://crbug.com/1025074)

I will update the explainer.

**Comment by hadleybeeman** [comment]
Since we've had no comments since we proposed closing this issue, and everyone seems happy, we are now closing it. Feel free to open another issue if you'd like to start a new discussion!
