### ISSUE TITLE
Web of Things (WoT) Thing Description

### ISSUE THREAD

**Issue by mmccool** [w3ctag/design-reviews#357]
Góðan dag TAG！

I'm requesting a TAG review of:

  - Name: _Web of Things (WoT) Thing Description_
  - Specification URL: https://w3c.github.io/wot-thing-description
  - Explainer, Requirements Doc, or Example code:  https://github.com/w3c/wot-thing-description/blob/TD-TAG-review/explainer/Explainer.md
  - Tests: https://w3c.github.io/wot-thing-description/testing/report.html
  - Primary contacts: @sebastiankb, @takuki, @mmccool, @vcharpenay

Further details (optional):

  - Relevant time constraints or deadlines: 
     * TAG review feedback need by April 5th
     * CR transition planned for April 9th
        - last possible date to make June 25 deadline for REC
        - end of WG charter is June 30

  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://github.com/w3c/wot-architecture/blob/TAG-review/proposals/security_and_privacy.md); this assessment is shared with all _Web of Things_ documents.
  - [X] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

In the Thing Description specification, text and table entries highlighted with a yellow background indicates a feature associated with an at-risk assertion for which insufficient implementation experience exists. When an entire section is at-risk the words "This section is at risk." will be placed at the start of the section and highlighted with a yellow background.

- The [WoT Security and Privacy Considerations](https://github.com/w3c/wot-security/) document provides extra discussion of security with an IoT focus.
- The related [WoT Architecture](https://github.com/w3c/wot-architecture) document is being submitted for TAG review at the same time.
- The [WoT Binding Templates](https://github.com/w3c/wot-binding-templates) informative WG note describes an optional WoT building block.
- The [WoT Scripting API](https://github.com/w3c/wot-scripting-api) informative WG note describes an optional WoT building block.

During the TAG review period, we plan to update the test results to reduce the number of at-risk assertions as much as possible before CR submission.  The link above refers to the master branch of the repository, not the TAG-review branch.

We'd prefer the TAG provide feedback as (please select one):

  - [x] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by cynthia** [comment]
Both the spec review and explainer 404 to me.

**Comment by sebastiankb** [comment]
The template points to outdated links. Sorry for that.

Please use for the TD spec: https://cdn.staticaly.com/gh/w3c/wot-thing-description/TD-TAG-review/index.html?env=dev

For the explainer: https://github.com/w3c/wot-thing-description/blob/TD-TAG-review/explainer/Explainer.md

@mmccool Please update the links in the template above.

**Comment by mmccool** [comment]
Links fixed.

**Comment by takuki** [comment]
Made a clarification about TD serialization.
This is in order to avoid unintended impression to reviewers that TD has more than one serializations.
TD has only one serialization format that conforms to JSON-LD 1.1.

**Comment by sebastiankb** [comment]
I would just like to mention that we have an updated TD draft that can be found in the master branch:

[Latest TD Specification](https://w3c.github.io/wot-thing-description)

This version has already compiled some I18N aspects, clearer explanations of some features, typo fixes, etc..

**Comment by ashimura** [comment]
@ylafon and @torgo we've been wondering about the final review results from the TAG, because we're planning to publish the update drafts as Proposed Recommendations on June 27th and want (wanted) to send out transition requests for the WoT Thing Description (and the WoT Architecture) today on June 20.

When I talked with @ylafon about the possible review results, he mentioned there would not be many comments in any case. So I'd like to confirm there would not be blocking comments for our Proposed Recommendation transition.

**Comment by dbaron** [comment]
I have some comments that I will try to write up on Monday.

**Comment by ashimura** [comment]
Thanks a lot, @dbaron !

**Comment by dbaron** [comment]
(the discussion has ended up mostly in #355 rather than here)

**Comment by kenchris** [comment]
It is common that explainers have a section listing some of the other solutions that were considered and rejected. This really helps us understand why the chosen solution is better and how you have learned from existing and prior solutions.

**Comment by hadleybeeman** [comment]
Our feedback is primarily in architecture, in [our issue 355](https://github.com/w3ctag/design-reviews/issues/355). We are happy to close this now.
