### ISSUE TITLE
Additional reading methods on Blob and File

### ISSUE THREAD

**Issue by mkruisselbrink** [w3ctag/design-reviews#359]
Góðan dag TAG！

I'm requesting a TAG review of:

  - Name: "Modern" reading API for Blob and File similar to Fetch's Body mixin
  - Specification URL: https://github.com/w3c/FileAPI/pull/117
  - Explainer, Requirements Doc, or Example code: [url]
  - Tests: In progress in https://github.com/web-platform-tests/wpt/pull/15984
  - Primary contacts: @mkruisselbrink

Further details (optional):

  - Relevant time constraints or deadlines: We're currently implementing this in Chrome and hope to ship this soon
  - [ ] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/).
     **N/A, feature doesn't add any new functionality.**
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

[please tell us anything you think is relevant to this review]

We'd prefer the TAG provide feedback as (please select one):

  - [x] open issues in our Github repo for each point of feedback (although until the PR lands, commenting on the PR directly is probably better)
  - [ ] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

--------------------------

_Please preview the issue and check that the links work before submitting_

For background, see our [explanation of how to write a good explainer](https://w3ctag.github.io/explainers).

**Comment by kenchris** [comment]
@domenic should it be called `stream()` or `reader()` here to stay consistent with other specs?

**Comment by domenic** [comment]
There's no exact precedent, but `stream()` is more correct; you get a `reader()` from a stream via `file.stream().getReader()`.

**Comment by kenchris** [comment]
OK, I am good with this change

**Comment by kenchris** [comment]
Thanks for flying TAG! We looked at the additions and have no complains - this looks good!
