### ISSUE TITLE
LazyLoad (loading= attribute)

### ISSUE THREAD

**Issue by scott-little** [w3ctag/design-reviews#361]
Góðan dag TAG！

I'm requesting a TAG review of:

  - Name: LazyLoad
  - Specification URL: Pull request for spec  is https://github.com/whatwg/html/pull/3752
  - Explainer, Requirements Doc, or Example code: Explainer: https://github.com/scott-little/lazyload
  - Tests: In progress
  - Primary contacts: scott-little, bengreenstein

Further details (optional):

  - Relevant time constraints or deadlines: We're aiming for Chrome M75, which would go to Beta around May 2nd - May 9th.
  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://w3ctag.github.io/security-questionnaire/). The [assessment is here](https://github.com/scott-little/lazyload/blob/master/tag_security_privacy.md).
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

We'd prefer the TAG provide feedback as (please select one):

  - [x] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

--------------------------

_Please preview the issue and check that the links work before submitting_

For background, see our [explanation of how to write a good explainer](https://w3ctag.github.io/explainers).

**Comment by hober** [comment]
Hi @scott-little,

What's the current status of the pull request? There was some active discussion around three weeks ago (starting with [this comment from Jake](https://github.com/whatwg/html/pull/3752#issuecomment-483983032)) about how `auto` should work. Has that settled out? Is this stable enough to review?

**Comment by cynthia** [comment]
@hober and I discussed this during the Iceland F2F, and we think this is a really useful feature. We have jotted down a bunch of questions for ourselves to review when you have a slightly more stabilized proposal. Can you please nudge us again when you have an update?

**Comment by domfarolino** [comment]
Hey everyone, I've taken over the current spec PR, and the latest discussion has left its direction in a better state. 

Here are some updates for this thread:
 - Per spec, images and iframes automatically have the "auto" LazyLoad state. This allows UAs to defer these, unless they are in-viewport, or not [connected](https://dom.spec.whatwg.org/#connected) (in the DOM sense). This means that when these elements are created from JavaScript, they will not be deferred, which was the biggest thing folks were concerned about in situations like Jake's comment, for compatibility
 - The latest spec review happens to align the spec very closely to Chrome's implementation, which is just about [ready to ship](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/jxiJvQc-gVg/wurng4zZBQAJ). We've been landing [WPTs](https://github.com/web-platform-tests/wpt/tree/master/loading/lazyload) for this as well.
 - I will be updating the spec soon, to address the latest review

Let me know if I can clarify anything/provide more info

**Comment by hober** [comment]
Hi, sorry for the long delay. We're trying to make a dent in our backlog!

@cynthia and I are looking at this in our Tokyo F2F, and we're pretty happy with where this is, so we're going to close our review. If you decide to take a different direction, please file a new issue because we'd love to take a look at it.
