### ISSUE TITLE
Picture-in-Picture for arbitary content

### ISSUE THREAD

**Issue by beccahughes** [w3ctag/design-reviews#374]
Góðan dag TAG！

I'm requesting a TAG review of:

  - Name: Picture-in-Picture for arbitary content (also referred to as "v2")
  - Specification URL: https://github.com/WICG/picture-in-picture/tree/v2
  - Explainer, Requirements Doc, or Example code: https://github.com/WICG/picture-in-picture/blob/v2/v2_explainer.md
  - Tests: Not yet available
  - Primary contacts: @beccahughes @mounirlamouri @beaufortfrancois

Further details:

Most of the spec is still in [pull requests](https://github.com/WICG/picture-in-picture/pulls?q=is%3Aopen+is%3Apr+label%3Av2) however we are requesting some early feedback on the design.

We'd prefer the TAG provide feedback as (please select one):

  - [X] open issues in our GitHub repo for each point of feedback (with the v2 label)
  - [ ] open a single issue in our GitHub repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by dbaron** [comment]
It would be helpful if the explainer started from the user benefit that is the end goal here.  What are the sites that want this trying to achieve that helps their end users?

**Comment by hober** [comment]
Hi,

Thanks for bringing this review to us. In addition to @dbaron's comment above, we're trying to require all requests for review to have considered the questions in our [security & privacy questionnaire](https://w3ctag.github.io/security-questionnaire/). Please let us know via a comment here when you've run through the security & privacy questionnaire and can share your findings with us.

**Comment by beccahughes** [comment]
I have updated the explainer.

Here is the security & privacy questionnaire: https://github.com/WICG/picture-in-picture/blob/v2/security-privacy-questionnaire.md

**Comment by cynthia** [comment]
Sorry! We just realized that this completely fell through the cracks - we heard that there was some feedback from other implementors (in particular, opposition) on this proposal. Would it be possible to disclose what the reasons were here?

Has that feedback been addressed in the current proposal?

**Comment by mounirlamouri** [comment]
Chrome is still investigating a few different ideas. We shared the history during the Media WG F2F at TPAC and in general, as far as I can tell, the group was fairly supportive of where we are at but expressed concerns that the current idea is complicated but solves the issues. We still need to do a lot of homework on this before pushing it further.

**Comment by hober** [comment]
> We still need to do a lot of homework on this before pushing it further.

In that case, should we close this review & re-open when you've made progress?

**Comment by mounirlamouri** [comment]
Yes, that sounds reasonable. I cannot close the ticket and Becca is OOO these days so if you can, it would be great :)

**Comment by hober** [comment]
Okay, done. LMK when you're ready for another round and we'll reopen. Thanks!
