### ISSUE TITLE
JSON modules

### ISSUE THREAD

**Issue by littledan** [w3ctag/design-reviews#375]
Góðan dag TAG！

I'm requesting a TAG review of:

  - Name: JSON modules
  - Specification URL: https://github.com/whatwg/html/pull/4407
  - Explainer, Requirements Doc, or Example code: https://github.com/whatwg/html/issues/4315#issue-401934423
  - GitHub issues (if you prefer feedback filed there): https://github.com/whatwg/html/issues/4315 https://github.com/w3c/webcomponents/issues/770
  - Tests: https://github.com/web-platform-tests/wpt/pull/16734
  - Primary contacts: @ms2ger @littledan @domenic @annevk @dandclark

Further details (optional):

  - Relevant time constraints or deadlines: None, but note that there is interest in implementing from Google, Mozilla, and Microsoft.
  - [ x ] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). There are no new security/privacy concerns, as this proposal follows JavaScript modules with respect to the usage of fetch
  - [ x ] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

[please tell us anything you think is relevant to this review]

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our GitHub repo for each point of feedback
  - [ ] open a single issue in our GitHub repo for the entire review
  - [ x ] leave review feedback as a comment in this issue and @-notify @littledan

--------------------------

_Please preview the issue and check that the links work before submitting_

For background, see our [explanation of how to write a good explainer](https://w3ctag.github.io/explainers).

**Comment by littledan** [comment]
Note, this is a WHATWG HTML standard, not TC39 (though I do plan to keep TC39 in the loop about it).

**Comment by hober** [comment]
Just a quick triage note for my colleagues on the TAG: I semi-arbitrarily picked an initial set of assignees; please remove yourself if you don't want to be assigned to this review.

**Comment by kenchris** [comment]
We looked at the feature and from the TAG side we are happy with it!

Thanks for flying TAG!
