### ISSUE TITLE
WebAssembly integration with ECMAScript modules

### ISSUE THREAD

**Issue by littledan** [w3ctag/design-reviews#377]
Góðan dag TAG！

I'm requesting a TAG review of:

  - Name: WebAssembly/ESM integration
  - Specification URL: https://webassembly.github.io/esm-integration/js-api/index.html#esm-integration
  - Explainer, Requirements Doc, or Example code: https://github.com/WebAssembly/esm-integration/blob/master/proposals/esm-integration/README.md
  - GitHub issues (if you prefer feedback filed there): https://github.com/WebAssembly/esm-integration/issues
  - Tests: None yet
  - Primary contacts: @littledan @linclark @lukewagner

Further details (optional):

  - Relevant time constraints or deadlines: None
  - [ x ] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). This proposal creates a new loading mechanism (3.6), which was previously possible to achieve with a snippet of JavaScript code. Otherwise, it does not introduce new privacy/security concerns.
  - [ x ] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

[please tell us anything you think is relevant to this review]

We'd prefer the TAG provide feedback as (please select one):

  - [ x ] open issues in our GitHub repo for each point of feedback
  - [ ] open a single issue in our GitHub repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

--------------------------

_Please preview the issue and check that the links work before submitting_

For background, see our [explanation of how to write a good explainer](https://w3ctag.github.io/explainers).

**Comment by littledan** [comment]
Note, this is not a TC39 proposal, but rather being discussed in the WebAssembly CG and WHATWG HTML repository.

**Comment by kenchris** [comment]
@cynthia and I have been looking at this in a breakout.

As far as we understand most of this has landed in most browsers as part of Web Assembly MVP. Is that assumption correct? Or are there parts that have not landed yet and you would like our input on? Where should we concentrate out efforts?

Can you share some of the history and status with us? We saw a bunch of issues related to this which are still open:

* https://github.com/whatwg/html/pull/4372
* https://github.com/WebAssembly/proposals/issues/12

Nit: WebIDL changed and constructors are separate methods now and not annotations.

**Comment by kenchris** [comment]
Related: https://github.com/littledan/proposal-module-attributes/

**Comment by littledan** [comment]
Apologies for my delay here.

> As far as we understand most of this has landed in most browsers as part of Web Assembly MVP. Is that assumption correct?

No, this proposal is not implemented in any browser. There are only experimental implementations in tooling.

This proposal has been waiting on:
- Implementer interest. Browsers have reviewed the proposal or even drove/funded parts of it.
- In the past, top-level await (to handle the asynchronous-ness of Wasm module instantiation). This is now at Stage 3 in TC39, and browser implementations are now coming.
- Now, clarity on whether WebAssembly modules should be specially marked, e.g., with module attributes. @rniwa [indicated](https://github.com/w3c/webcomponents/issues/839#issuecomment-542327813) that he would prefer this, but that it is not a show-stopper the way that this annotation is necessary for JSON modules.

**Comment by kenchris** [comment]
Talking to @cynthia we both believe the module attributes makes sense, because you could serve JavaScript instead that might be able to load any javascript and even load multiple wasm modules, while we believe that you cannot load additional wasm from a wasm module?

**Comment by cynthia** [comment]
Aside from the concerns above, both of us think as an early review the design and problems it is trying to solve are both valid and sound. For this review, we are happy to see this move forward - if you have significant design changes that warrant another round of reviews, please let us know and we'll re-open this issue. Thanks for bringing this proposal to our attention.

**Comment by littledan** [comment]
Thanks for your reviews. Note that, in this proposal, Wasm modules *can* load other Wasm (or JS) modules, sharing the same privilege level in general. However, many people (e.g., @lukewagner) have raised the feature request that Wasm modules be able to operate in a more limited way, so I wonder if this should be revisited.
