### ISSUE TITLE
Content Indexing

### ISSUE THREAD

**Issue by rknoll** [w3ctag/design-reviews#379]
Góðan dag TAG！

I'm requesting a TAG review of:

  - Name: Content Indexing
  - Specification URL: None, yet.
  - Explainer, Requirements Doc, or Example code: https://github.com/rknoll/content-index
  - GitHub issues (if you prefer feedback filed there): https://github.com/rknoll/content-index/issues
  - Tests: None, yet.
  - Primary contacts: @rknoll, @beverloo

https://github.com/rknoll/content-index/blob/master/SECURITY_AND_PRIVACY.md

You should also know that...
There is no spec written yet as this API is still in design phase. We're happy for all feedback!

We'd prefer the TAG provide feedback as (please select one):

  - [x] open issues in our GitHub repo for each point of feedback
  - [ ] open a single issue in our GitHub repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by ylafon** [comment]
It would be good also to expand on the use case (it is currently vague), as well as examples?
Thanks,

**Comment by rknoll** [comment]
Thanks for the initial read! I've added the security & privacy answers to this doc: https://github.com/rknoll/content-index/blob/master/SECURITY_AND_PRIVACY.md
I've also added two use case scenarios here: https://github.com/rknoll/content-index#usage-scenario-1
Let me know if this makes it clear enough or if it needs more elaboration, thanks!!

**Comment by kenchris** [comment]
Just a few quick comments

- why only one icon type/size? (look at web app manifest)
- why not directly available from the main thread without having a SW registered (like the Cache API)?

**Comment by kenchris** [comment]
We would like to see more examples of how this related to other browsers/runtimes, but as an early design this looks good and would like to see more as you move ahead.

**Comment by kenchris** [comment]
Closing for now, please reopen when you have something more for us to review
