### ISSUE TITLE
Ability to customize virtual keyboard via enterkeyhint

### ISSUE THREAD

**Issue by dtapuska** [w3ctag/design-reviews#380]
こんにちはTAG!

I'm requesting a TAG review of:

  - Name: enterkeyhint handling
  - Specification URL: [HTML Spec](https://html.spec.whatwg.org/multipage/interaction.html#attr-enterkeyhint)
  - Explainer (containing user needs and example code)¹: [Explainer](https://dtapuska.github.io/enterkeyhint/)
  - GitHub issues (if you prefer feedback filed there): [HTML Spec issues](https://github.com/whatwg/html/issues/new)
  - Tests: Tested via WPT IDL tester
  - Primary contacts: @dtapuska

Further details:

  - Relevant time constraints or deadlines: [Chrome's I2S](https://groups.google.com/a/chromium.org/d/msg/blink-dev/Hfe5xktjSV8/Re-SMF3wAwAJ)
  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://raw.githubusercontent.com/dtapuska/enterkeyhint/master/SECURITY.md).
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the work on this specification is: whatwg/html
  - Links to major pieces of multi-stakeholder review or discussion of this specification: 
https://github.com/whatwg/html/pull/3538

We'd prefer the TAG provide feedback as (please select one):

  - [x] open issues in our GitHub repo for each point of feedback
  - [ ] open a single issue in our GitHub repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by hober** [comment]
Hi, sorry for the extremely long delay. This request fell through the cracks. We took this up on our telcon today & we're generally happy with the feature. One or two bits of feedback came up that we'll file HTML issues on. Thanks for bringing this to us, and sorry again for the delay.
