### ISSUE TITLE
Contact Picker API

### ISSUE THREAD

**Issue by rayankans** [w3ctag/design-reviews#388]
こんにちはTAG!

I'm requesting a TAG review of:

  - Name: Contact Picker API
  - Specification URL: https://beverloo.github.io/contact-api/spec
  - Explainer (containing user needs and example code)¹: https://github.com/beverloo/contact-api
  - GitHub issues (if you prefer feedback filed there): https://github.com/beverloo/contact-api/issues
  - Tests: N/A
  - Primary contacts (and their relationship to the specification): @rayankans, @beverloo

Further details:

  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://github.com/beverloo/contact-api/blob/master/security-privacy-self-assessment.md).
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

We'd prefer the TAG provide feedback as (please select one):

  - [x] open issues in our GitHub repo for each point of feedback
  - [ ] open a single issue in our GitHub repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by dbaron** [comment]
Is this the same as #337?

**Comment by rayankans** [comment]
@dbaron yeah, but this is with the spec. The initial one was for early API feedback. It wasn't clear to me whether I should create a new issue or update the old one.

**Comment by plinss** [comment]
Closing, will track progress in #337
