### ISSUE TITLE
WebSocketStream

### ISSUE THREAD

**Issue by ricea** [w3ctag/design-reviews#394]
こんにちはTAG!

I'm requesting a TAG review of:

  - Name: WebSocketStream
  - Specification URL: TBD, but API design is at: https://docs.google.com/document/d/1La1ehXw76HP6n1uUeks-WJGFgAnpX2tCjKts7QFJ57Y/edit
  - Explainer (containing user needs and example code)¹: https://github.com/ricea/websocketstream-explainer/blob/master/README.md
  - GitHub issues (if you prefer feedback filed there): https://github.com/ricea/websocketstream-explainer/issues
  - Tests: TBD
  - Primary contacts (and their relationship to the specification): ricea (primary author)

Further details:

  - Relevant time constraints or deadlines: None at this time
  - [X] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://docs.google.com/document/d/1vSFUG0ysqE03soC7tDDnnpioVJarEcCiEYvCPtQDrOg/edit).
  - [X] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the work on this specification is: TBD

We recommend the explainer to be in [Markdown](https://github.github.com/gfm/). On top of the [usual information expected in the explainer](https://w3ctag.github.io/explainers), it is strongly recommended to add:

  - Links to major pieces of multi-stakeholder review or discussion of this specification: 
  - Links to major unresolved issues or opposition with this specification:

You should also know that...

This proposal is still in the early stages. I plan to implement it in Blink to gather feedback, but we won't necessarily ship it. There will be an origin trial to gauge interest from developers.

We'd prefer the TAG provide feedback as (please select one):

  - [X] open issues in our GitHub repo for each point of feedback
  - [ ] open a single issue in our GitHub repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

--------------------------

_Please preview the issue and check that the links work before submitting._ In particular, if anything links to a URL which requires authentication (e.g. Google document), please make sure anyone with the link can access the document.

¹ For background, see our [explanation of how to write a good explainer](https://w3ctag.github.io/explainers).

**Comment by ricea** [comment]
See also the review of the existing WebSocket API at #268.

**Comment by martinthomson** [comment]
@ricea, The underlying protocol supports large messages.  How do you anticipate handling very large messages, such as ones that can't be backed by physical memory (or in the extreme, logical memory)?  It seems like you don't get back pressure in that case.

Would it be better to provide a stream of streams, or use the [fetch mixin](https://fetch.spec.whatwg.org/#body-mixin) for each chunk?

**Comment by ricea** [comment]
@martinthomson My tentative plan is to use a stream of streams. My concern is that this will be hard to understand and use, which is one reason why I'm not trying to tackle it yet.

Using the fetch mixin for each chunk is a really interesting idea. I think it has potential.

The way I see backpressure working with a stream-of-streams is that you have to read the whole of one message before it will give you another one. I think it's possible to explain and justify this with a stream-of-streams, but with a stream-of-bodies people might strongly object that they should be able to just discard the message without reading it. I'm not sure what to do about that.

**Comment by torgo** [comment]
Hi @ricea what is the intended venue for this work?

**Comment by dbaron** [comment]
I'm curious if there is or should be any relationship to the work on Web Transport (#389) -- e.g., if Web Transport is now looking at doing a more stream-based API -- should that be similar to or based on or converge with this?

**Comment by ricea** [comment]
@torgo What I've been discussing is removing the WebSocket parts from the Fetch Standard and HTML Standard and combining them into a new "WebSocket Standard". Then that would be a natural home for WebSocketStream.

I must admit I haven't given much consideration to a plan B.

**Comment by ricea** [comment]
> I'm curious if there is or should be any relationship to the work on Web Transport (#389) -- e.g., if Web Transport is now looking at doing a more stream-based API -- should that be similar to or based on or converge with this?

I expect they will be similar. WebTransport has a lot more variables which may dictate a different API shape. I hope that experience with WebSocketStream will inform the design of WebTransport.

**Comment by martinthomson** [comment]
If it were me, any work in this area might want to be chartered alongside (as in the same group) as what does WebTransport.  Assuming that both are done, that is.  I would want the same API in both cases.

As for stream of streams, we don't want to expose the GC, so we would need to have each body drained.  Most of the accessors aren't a problem, but if you get a stream, then that stream would need to be exhausted before the next message can appear.

**Comment by ricea** [comment]
There are now some tests at https://github.com/web-platform-tests/wpt/tree/master/websockets/stream-tentative. I need to add a lot more.

**Comment by dbaron** [comment]
@kenchris and I are looking at this in a breakout at the TAG [face-to-face meeting in Tokyo](https://github.com/w3ctag/meetings/tree/gh-pages/2019/09-tokyo).

I'm a little unclear on what code using this stream-of-streams model would look like; if you're going down that route, it would be interesting to see an explainer.  It sounds like you might be talking about this for a later version of the API.

That said, we're happy to see this area being worked on -- the stated goals seem worthwhile -- and would again encourage you to make sure this effort fits well with other areas of work like web transport that are happening at the same time.

I feel like to find a bit of time outside of this meeting to look into this in a little bit more detail -- but on the other hand maybe that makes more sense slightly later in the process.  Would you like to get more feedback at this stage, or do you think it would be better to wait a bit before taking a closer look at the spec?

**Comment by dbaron** [comment]
Cycling back to this briefly at a breakout with @ylafon, although we probably don't need to dig in a lot right now...

So the current model (not stream-of-streams model) is that WebSocketStream is a stream of messages?  Or is it a stream of chunks/frames?  Or does the distinction matter given what browsers support today?  (From the specs it looks like WebSockets have a concept of messages split across frames, but the explainer seems to imply that that vision isn't really available today.)

**Comment by ylafon** [comment]
Also the [comment made by @dbaron on WebTransport](https://github.com/w3ctag/design-reviews/issues/389#issuecomment-530694381) is worth exploring, both specifications seem to have similar goals. Would it be possible to have an explainer about the fundamental differences between the two approaches and what would prevent defining only one API there?

**Comment by dbaron** [comment]
For what it's worth -- maybe a more general way to frame my previous comment is that perhaps it would be helpful if the explainer assumed a bit less knowledge about the space already.  It doesn't need to explain the web from first principles, but having a few more paragraphs to explain the basics of what this is building on would likely be helpful.

**Comment by dbaron** [comment]
@kenchris and I are looking at this in a breakout at our Wellington face-to-face.

We're curious what the status of this is.  There was discussion in the past about changing to a stream-of-streams model?  Has that been abandoned, or is that going to move forwards?

It would also be useful to have some explainer updates to explain how this fits with other work and perhaps how it relates to both specification and reality of web sockets (see [earlier comment](https://github.com/w3ctag/design-reviews/issues/394#issuecomment-561357377)).

It sounds like there is implementation work proceeding and this is available behind a flag, and it sounds like there's been some performance work on that implementation.  Is that for the stream-of-messages (or stream-of-chunks) model?

Is it at a stage where TAG feedback would be useful, or would that be more useful at some point in the past or future?

**Comment by ricea** [comment]
> We're curious what the status of this is. There was discussion in the past about changing to a stream-of-streams model? Has that been abandoned, or is that going to move forwards?

We are leaning towards shipping based on developer feedback, but we haven't made a final decision.

It's possible we will support a stream-of-streams model in the future, but I expect to only support stream-of-messages (strings or BufferSources) in the first shipped version. 

> It would also be useful to have some explainer updates to explain how this fits with other work and perhaps how it relates to both specification and reality of web sockets (see earlier comment).

Sorry, I have been remiss in updating the explainer. I will do it but I can't guarantee when.

> It sounds like there is implementation work proceeding and this is available behind a flag, and it sounds like there's been some performance work on that implementation. Is that for the stream-of-messages (or stream-of-chunks) model?

Yes, it is available behind the experimental-web-platform-features flag in Chrome and I have done some performance work in response to early feedback. This is the stream-of-messages model.

> Is it at a stage where TAG feedback would be useful, or would that be more useful at some point in the past or future?

Yes. Initial developer response to the API shape is positive, so more feedback would be useful at this point.

**Comment by dbaron** [comment]
Which of the documents represent the current state of things well, for us to focus on when giving feedback?

**Comment by ricea** [comment]
> Which of the documents represent the current state of things well, for us to focus on when giving feedback?

https://github.com/ricea/websocketstream-explainer/blob/master/README.md is still accurate but I haven't yet updated it it to address the deficiencies noted here. Sorry.

I'm also interested in feedback in the behaviour described in https://github.com/ricea/websocketstream-explainer/issues/6, which I have not yet added to the explainer.

**Comment by tomayac** [comment]
FYI, I [have written](https://web.dev/websocketstream/) about this API some weeks ago. The article sparked quite some [developer interest](https://mobile.twitter.com/search?q=url%3Ahttps%3A%2F%2Fweb.dev%2Fwebsocketstream%2F&src=typed_query&f=live) in the topic.

**Comment by kenchris** [comment]
Hi there, any update on this? What is the cross-browser support story?

**Comment by kenchris** [comment]
Ping @ricea

**Comment by ricea** [comment]
@kenchris Sorry, there hasn't been much progress yet. Expect more activity in the next month. The expected venue is WHATWG.

We will need cross-browser buy-in for standardisation, so it will be solidified soon. Currently there have only been informal discussions.

**Comment by crowlKats** [comment]
What is the state on this?
It would be great to see a proper spec written for WebSocketStream as there is some interest at Deno to implement it.

**Comment by kenchris** [comment]
Is it OK if we close this, and you reopen when/if you get cross-browser buy in? @ricea

**Comment by ricea** [comment]
> Is it OK if we close this, and you reopen when/if you get cross-browser buy in? @ricea

Yes, that's fine.
