### ISSUE TITLE
Default accessibility semantics for custom elements

### ISSUE THREAD

**Issue by rakina** [w3ctag/design-reviews#401]
こんにちはTAG!

I'm requesting a TAG review of:

  - Name: Default accessibility semantics for custom elements
  - Specification URL: https://github.com/whatwg/html/pull/4658, https://github.com/w3c/aria/pull/984
  - Explainer (containing user needs and example code)¹: https://github.com/alice/aom/blob/gh-pages/explainer.md#default-semantics-for-custom-elements-via-the-elementinternals-object
  - Tests: none yet
  - Primary contacts (and their relationship to the specification): @alice @domenic @tkent-google @rakina

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our GitHub repo for each point of feedback
  - [ ] open a single issue in our GitHub repo for the entire review
  - [x] leave review feedback as a comment in this issue and @-notify one of the primary contacts above

--------------------------

_Please preview the issue and check that the links work before submitting._ In particular, if anything links to a URL which requires authentication (e.g. Google document), please make sure anyone with the link can access the document.

¹ For background, see our [explanation of how to write a good explainer](https://w3ctag.github.io/explainers).

**Comment by slightlyoff** [comment]
Just wanted to flag that Blink is likely to ship this, in part, because this review was opened in August but hasn't seen forward movement since then. [Speak now or hold your peace](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/BcWAX13du9w/wlp9E1YGEAAJ)!

**Comment by alice** [comment]
(Also note that this was touched on in the [previous review of AOM](https://github.com/w3ctag/design-reviews/issues/134#issuecomment-434384545).)

**Comment by torgo** [comment]
Discussed briefly on our [call today](https://github.com/w3ctag/meetings/blob/gh-pages/2019/telcons/11-05-agenda.md) and the consensus was to close with positive feedback.
