### ISSUE TITLE
Review request: DOM Standard Review Draft

### ISSUE THREAD

**Issue by LJWatson** [w3ctag/design-reviews#404]
Hello TAG,

As you know, the WHATWG publishes a Review Draft of the DOM Standard every six months. The HTML WG plans to take alternate Review Drafts to W3C Recommendation, starting with the current DOM Review Draft. 

Once this process is established, we expect wide and horizontal review to happen on an ongoing basis as the DOM specification evolves in WHATWG space. For this first attempt we need to do things a little differently though, and so we're officially inviting wide and horizontal review of the [June 2019 DOM Standard Review Draft](https://dom.spec.whatwg.org/review-drafts/2019-06/). 

Issues identified during wide and horizontal review should be filed directly on the WHATWG DOM repository, but please let us have a pointer
to the mechanism or place where you track your issues (assuming this issue isn't it).

We plan to open the CFC to adopt the DOM Standard Review Draft as W3C CR in early November, so would appreciate all you can do to turn around your review by the end of October (sooner if at all possible).
Léonie on behalf of the HTML WG

**Comment by hober** [comment]
Thanks, Léonie. I've added this to the agenda for our next telcon.

**Comment by torgo** [comment]
It would really help us to review this if we had a list of the substantive, significant changes that have happened recently. That would really help us to prioritise the work. @LJWatson is there someone who could put together such a list?

**Comment by annevk** [comment]
@torgo integration of custom elements, shadow trees, aborting ongoing activities, and `StaticRange` objects are the main additions, at a high-level (going from memory). Note that for WHATWG standards we intend to keep the git log in a really good state so browsing through that should be easy and can be done at https://github.com/whatwg/dom/commits. Non-substantive changes are prefixed with "Editorial:" or "Meta". (Rules for that are described at https://github.com/whatwg/meta/blob/master/COMMITTING.md.)

**Comment by cynthia** [comment]
There is a previous review we did earlier: https://github.com/w3ctag/design-reviews/issues/229

**Comment by LJWatson** [comment]
@cynthia does that review stand for this purpose?

**Comment by LJWatson** [comment]
Hearing nothing to the contrary and noting that #229 was closed satisfactorily, we'll assume that review stands.
