### ISSUE TITLE
More restrictive hasEnrolledInstrument() for autofill data

### ISSUE THREAD

**Issue by rsolomakhin** [w3ctag/design-reviews#407]
こんにちはTAG!

I'm requesting a TAG review of:

  - Name: More restrictive hasEnrolledInstrument() for autofill data
  - Explainer: https://gist.github.com/rsolomakhin/d6d242cbb9306864ada5a29de7ab271e
  - Primary contacts: @rsolomakhin - implementer.

Further details:

  - Relevant time constraints or deadlines: Please review before September.
 - [Self-Review Questionnaire on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/) is not applicable, since this is a behavior change to a part of an existing API.
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/), although it does not seem to be applicable here either.
  - The group where the work on this specification is: Web Payments Working Group.

We'd prefer the TAG provide feedback as (please select one):
  - [x] Leave review feedback as a comment in this issue and @-notify @rsolomakhin

**Comment by dbaron** [comment]
The TAG is unsure about whether TAG review is needed for an implementation change that doesn't require spec changes.  If it's an issue that isn't important enough for the spec to specify clearly, then it's not clear why the TAG should be reviewing it.

That said, this does bring up the question of perhaps whether this should be specified in more detail in the spec.  Given the expectations that Chrome is setting, are other implementations of this API going to have to do the same thing in order to be compatible with the expectations of the API's users?  If so, then it might actually need to be in the spec.

**Comment by rsolomakhin** [comment]
Good point, @dbaron. I will bring this up at the next working group meeting to see whether this should be specced.

@ianjacobs: Could you add this topic to the agenda, please?

**Comment by rsolomakhin** [comment]
Sorry, I meant to CC @ianbjacobs.

**Comment by rsolomakhin** [comment]
@dbaron : In [today's WPWG meeting](https://www.w3.org/2019/09/05-wpwg-minutes#item03), the consensus appeared to lean toward adding non-normative notes about behavior of hasEnrolledInstrument() to the three specs:

- Payment Request
- Payment Handler
- Basic Card

But the discussion is ongoing. We hope to come to a conclusion at the 2019 TPAC.

**Comment by hober** [comment]
@rsolomakhin wrote:

> the consensus appeared to lean toward adding non-normative notes about behavior[…] but the discussion is ongoing. We hope to come to a conclusion at the 2019 TPAC.

Did you come to a conclusion? What did you conclude?

**Comment by ianbjacobs** [comment]
@rsolomakhin, should we fold this discussion into other payment handler discussions we are having right now, and in particular:
 https://docs.google.com/document/d/1C_xH-6sJb9UedrvifsvqS_2k_We0IlPSfWFo8Kg54ps/edit

**Comment by rsolomakhin** [comment]
SGTM @ianbjacobs

**Comment by hober** [comment]
@dbaron and I looked at this again in our F2F this week, and since this is still not likely to result in normative changes to the spec, we're inclined to close the issue. We note that we marked it `propose closing` in March. We'll take this up in plenary next week.
