### ISSUE TITLE
Marking tracking vectors

### ISSUE THREAD

**Issue by annevk** [w3ctag/design-reviews#411]
For a long time the HTML Standard has [marked fingerprinting vectors](https://html.spec.whatwg.org/multipage/introduction.html#fingerprint) with [a fingerprint image](https://html.spec.whatwg.org/images/fingerprint.png) (along with appropriate alternative text). The idea is to generalize this in the [Infra Standard](https://infra.spec.whatwg.org/) to encompass all tracking vectors (see https://github.com/whatwg/infra/issues/20 and https://github.com/whatwg/infra/pull/115 in particular). I'd like to push this over the finish line, but thought I'd check in with the TAG to see if there's additional things to take into account here.

cc @zcorpan

**Comment by hober** [comment]
This is a great idea.

**Comment by hober** [comment]
@dbaron and I took a look at this during our Tokyo F2F today.

It looks like there's a lot of useful discussion happening on whatwg/infra#115. In particular, [several recent comments](https://github.com/whatwg/infra/pull/115#pullrequestreview-286520837) from @othermaciej identify a number of other kinds of tracking vectors that should be marked, including client-side storage mechanisms (notably absent from the text being moved here from HTML).

**Comment by dbaron** [comment]
One other thought is that it's possible it's worth distinguishing between active and passive fingerprinting vectors.  Perhaps that shouldn't be prominent, but I think it is a distinction worth thinking about, since I think there's consensus passive fingerprinting vectors are more serious than active ones (although probably not consensus on how much more serious).

**Comment by hober** [comment]
We're really happy to see this move forward, and given that active discussion and improvement is happening in whatwg/infra#115, we're going to close this review for now. Please raise a new review request (& link to this one) if you'd like us to take another look when this firms up.
