### ISSUE TITLE
Wide review request: the HTML Standard Review Draft

### ISSUE THREAD

**Issue by siusin** [w3ctag/design-reviews#412]
こんにちはTAG!

I'm requesting a TAG review of:

  - Name: HTML Standard Review Draft
  - Specification URL: https://html.spec.whatwg.org/review-drafts/2019-07/
  - Changes: all the [changes](https://github.com/whatwg/html/commits) since 2018 except for those prefixed with "Editorial:" or "Meta:"
  - GitHub issues: [the WHATWG HTML repository](https://github.com/whatwg/html/issues/)
  - Tests: [wpt/html](https://github.com/web-platform-tests/wpt/tree/master/html)
  - Primary contacts: @annevk @hober 

Further details:

  - Relevant time constraints or deadlines: the end of October
  - The group where the work on this specification is: the WHATWG

**Comment by alice** [comment]
> all the changes since 2018 except for those prefixed with "Editorial:" or "Meta:"

Does that include or exclude changes made *during* 2018?

**Comment by alice** [comment]
Halfway through bucketing based on https://github.com/whatwg/html/pulls?q=is%3Apr+merged%3A%3C2019-07-16+closed%3A%3E%3D2019-01-01+sort%3Acreated-asc

**Comment by siusin** [comment]
@alice Yes, please include all the changes since the HTML5.2 REC. @sideshowbarker is also working on a report on the implementation status of these changes.

**Comment by hober** [comment]
TAG colleagues: I've assigned @dbaron and @plinss (since you're both effectively working on this already); feel free to unassign yourselves if needed.

**Comment by alice** [comment]
Unassigned everyone since this was split into sub-issues.

**Comment by hober** [comment]
Hi @siusin,

We broke this into a number of sub-issues covering changes in various areas, and over the last few months we've reviewed one sub-issue at a time. Today we finished our last review, so I'm going to close this. Thanks for bringing this to us!
