### ISSUE TITLE
Microtransaction payment handlers

### ISSUE THREAD

**Issue by rsolomakhin** [w3ctag/design-reviews#422]
こんにちはTAG!

I'm requesting a TAG review of:

  - Name: Microtransaction payment handlers.
  - Explainer: https://gist.github.com/rsolomakhin/eba91c185028899883d2c7f37f357d7c
  - Primary contacts: rouslan@chromium.org (editor)

Further details:

  - Relevant time constraints or deadlines:
  - [x] I have read the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/) and it is not applicable.
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the work on this specification is: Web Payment Working Group.

We recommend the explainer to be in [Markdown](https://github.github.com/gfm/). On top of the [usual information expected in the explainer](https://w3ctag.github.io/explainers), it is strongly recommended to add:

  - Links to major pieces of multi-stakeholder review or discussion of this specification: 
  - Links to major unresolved issues or opposition with this specification:

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our GitHub repo for each point of feedback
  - [ ] open a single issue in our GitHub repo for the entire review
  - [x] leave review feedback as a comment in this issue and @-notify @rsolomakhin

--------------------------

_Please preview the issue and check that the links work before submitting._ In particular, if anything links to a URL which requires authentication (e.g. Google document), please make sure anyone with the link can access the document.

¹ For background, see our [explanation of how to write a good explainer](https://w3ctag.github.io/explainers).

**Comment by dbaron** [comment]
This seems reasonable to me based on reading through it.

Two thoughts, although neither is really particularly "from a TAG perspective":

> A single URL-based payment method.

I wonder if this is going to be problematic -- it seems like there might be a desire to support multiple payment methods.  Is the idea that, to get minimal UI, the site has to offer the payment method choice itself in that case?  While it seems like there are some interesting tradeoffs here, it seems like it might be worth keeping an eye on whether this is problematic for the developers and users using this.

> Value below the minimal UI trigger threshold and account balance.

It seems like there might be some cases (e.g., credit cards) where an account balance doesn't make sense (at least not in those terms), so I wonder if *requiring* an account balance is too strong.

**Comment by kenchris** [comment]
I find it reasonable too, but would like some time limit, like doing a few micropayments per day of say a dollar is fine, but you might want to limit it to say 10 dollars per day/hour.

**Comment by dbaron** [comment]
Given that I think we're both fine with this (modulo the minor comments above), we're going to close this issue.  (@plinss and I are going through this at a breakout in [Cupertino](https://w3ctag.github.io/meetings/2019/12-cupertino/).)
