### ISSUE TITLE
WebXR Gamepads Module

### ISSUE THREAD

**Issue by mounirlamouri** [w3ctag/design-reviews#430]
Hello TAG!

I'm requesting a TAG review of:

  - Name: WebXR Gamepads Module
  - Specification URL: https://immersive-web.github.io/webxr-gamepads-module/
  - Explainer (containing user needs and example code)¹: https://github.com/immersive-web/webxr-gamepads-module/blob/master/gamepads-module-explainer.md
  - GitHub issues (if you prefer feedback filed there): https://github.com/immersive-web/webxr-gamepads-module/issues
  - Tests: https://github.com/web-platform-tests/wpt/tree/master/webxr/gamepads-module
  - Primary contacts:
@NellWaliczek, editor
@toji, editor
@cwilso, WG co-chair
@AdaRoseCannon, WG co-chair

Further details: This is an extension of the WebXR API: https://immersive-web.github.io/webxr/

  - Relevant time constraints or deadlines: [please provide]
  - [X] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](url).
  - [X] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the work on this specification is: Immersive Web Working Group

We recommend the explainer to be in [Markdown](https://github.github.com/gfm/). On top of the [usual information expected in the explainer](https://w3ctag.github.io/explainers), it is strongly recommended to add:

  - Links to major pieces of multi-stakeholder review or discussion of this specification: N/A
  - Links to major unresolved issues or opposition with this specification: N/A

We'd prefer the TAG provide feedback as (please select one):

  - [X] open issues in our GitHub repo for each point of feedback
  - [ ] open a single issue in our GitHub repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

--------------------------

_Please preview the issue and check that the links work before submitting._ In particular, if anything links to a URL which requires authentication (e.g. Google document), please make sure anyone with the link can access the document.

¹ For background, see our [explanation of how to write a good explainer](https://w3ctag.github.io/explainers).

**Comment by hober** [comment]
Marking this as `pending external feedback` given the two issues @ylafon raised/linked above.

**Comment by hober** [comment]
Took another look at this in our APAC/USA breakout today. This is still pending resolution of immersive-web/webxr-gamepads-module#6 and immersive-web/webxr-gamepads-module#27

**Comment by torgo** [comment]
We have taken the decision today to close this issue. The only pending item we have is immersive-web/webxr-gamepads-module#27 which we will still keep track off through the external issue tracking mechanism.
