### ISSUE TITLE
Timed Text Markup Language (TTML2) 2nd Edition

### ISSUE THREAD

**Issue by nigelmegitt** [w3ctag/design-reviews#432]
Hello TAG!

I'm requesting a TAG review of:

  - Name: TTML2 Second Edition
  - Specification URL: https://w3c.github.io/ttml2/index.html
  - Explainer (containing user needs and example code)¹: n/a - the [changes](https://w3c.github.io/ttml2/ttml2-changes.html) address specification issues only and introduce no new features; 
  - GitHub issues (if you prefer feedback filed there): https://github.com/w3c/ttml2/issues
  - Tests: https://github.com/w3c/ttml2-tests (not WPT)
  - Primary contacts (and their relationship to the specification): @nigelmegitt (TTWG Chair), @skynavga (Editor), @cconcolato (Editor)

#### Further details:

  - Relevant time constraints or deadlines: please complete review in time for CR publication no later than 2020-01-16 as per the 3 month minimum requirement specified in the new TTWG Charter ([draft charter link](https://w3c.github.io/charter-timed-text/#coordination), since new charter not yet formally in place)
  - [ ] ~I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](url).~
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/): since TTML2 does not present any APIs, it is not applicable.
  - The group where the work on this specification is: TTWG

We recommend the explainer to be in [Markdown](https://github.github.com/gfm/). On top of the [usual information expected in the explainer](https://w3ctag.github.io/explainers), it is strongly recommended to add:

  - Links to major pieces of multi-stakeholder review or discussion of this specification: 
  - Links to major unresolved issues or opposition with this specification:

#### You should also know that...

TTWG is requesting TAG review because it is a process requirement as part of Horizontal Review. We suspect that there is little of interest to TAG in this maintenance update, but welcome feedback all the same.

We completed the [Security and Privacy section in TTML2 1st Edition Rec](https://www.w3.org/TR/ttml2/#security-and-privacy) and we believe that none of the changes modifies the security and privacy considerations.

We'd prefer the TAG provide feedback as (please select one):

  - [x] open issues in our GitHub repo for each point of feedback
  - [ ] open a single issue in our GitHub repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by hadleybeeman** [comment]
Apologies for the delay on this, as 2020 has happened around/to us.

We are happy to close this, and wish you well on the next work in TTML2!
