### ISSUE TITLE
 fetch() upload streaming

### ISSUE THREAD

**Issue by yoichio** [w3ctag/design-reviews#434]
Hello TAG!
 
I'm requesting a TAG review of:
 
  - Name: fetch() upload streaming
  - Specification URL: https://fetch.spec.whatwg.org/#concept-body-stream
    - Commits: https://github.com/whatwg/fetch/commit/0c470b5860fe690b1136b0242951f682405103cc, https://github.com/whatwg/fetch/commit/55141d7644b4f8381814c82898a278796f7fd899
  - User needs: https://github.com/whatwg/fetch/pull/425, https://groups.google.com/a/chromium.org/forum/#!topic/blink-network-dev/bsVgOxNCzFc
  - Tests: http://web-platform-tests.live/fetch/api/basic/request-upload.any.js
  - Primary contacts (and their relationship to the specification): @yoichio
 
Further details:
 
  - Relevant time constraints or deadlines: None
  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://docs.google.com/document/d/1fnPbqwxKDZtqVQpfSJeI2xj61E-RxG1dz8mqvDpMcJ4/).
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the work on this specification is: WHATWG
 
 We'd prefer the TAG provide feedback as (please select one):
  - [ ] open issues in our GitHub repo for each point of feedback
  - [ ] open a single issue in our GitHub repo for the entire review
  - [x] leave review feedback as a comment in this issue and @yoichio, @yutakahirano

**Comment by torgo** [comment]
Hi @yoichio thanks for this - is there an explainer that we can look at?

**Comment by yoichio** [comment]
No explainer for this.

Here is brief description why we want to implement this:
- Web author will be able to upload streaming data - possibly generated by devices, media, and so on.
Some web clients want to talk to a streaming end-point directly without any intermediary translation. 
Traditionally, uploading streaming data was implemented on WebSocket but it has made client/server code messy. Fetch upload streaming makes that simpler.

Code sample:
```javascript
const stream = new ReadableStream({start: controller => {
    controller.enqueue("f");
    controller.enqueue("bar");
    controller.close();
}});

let response = await fetch("http://example.com/", {method:"POST", body: stream});
let text = await response.text();
console.log(`Server responded "${text}"`);
```

**Comment by annevk** [comment]
I wonder if it might be a bit early to ask for review. There's a number of open issues that need to be addressed, right? https://github.com/whatwg/fetch/labels/topic%3A%20streams

https://github.com/whatwg/fetch/issues/538 in particular seems concerning and without a good conclusion, though I haven't reviewed all in detail.

**Comment by yoichio** [comment]
Ping @yutakahirano and @domenic ?

**Comment by yutakahirano** [comment]
Thank you. I think not all of them are blocking, so I created a new label "upload-streaming-blocking", labeled whatwg/fetch#538.

https://github.com/whatwg/fetch/labels/upload-streaming-blocking

**Comment by torgo** [comment]
Ok we are happy to do a review but please confirm back to us that things are ready? Until then I'm going to close.

**Comment by annevk** [comment]
@torgo FWIW, I think we're in a better state now with those issues and https://github.com/whatwg/fetch/issues/966 might be of interest to the TAG at some level.
