### ISSUE TITLE
WebRTC playoutDelayHint

### ISSUE THREAD

**Issue by kuddai** [w3ctag/design-reviews#441]
Hello TAG!

I'm requesting a TAG review of the proposed WebRTC 1.1 extension:

  - Name: PlayoutDelayHint
  - Specification URL: [w3c.github.io/webrtc-extensions/#dom-rtcrtpreceiver-playoutdelayhint](https://w3c.github.io/webrtc-extensions/#dom-rtcrtpreceiver-playoutdelayhint)
  - Explainer, Requirements Doc, or Example code: [discourse.wicg.io/t/hint-attribute-in-webrtc-to-influence-underlying-audio-video-buffering/4038](https://discourse.wicg.io/t/hint-attribute-in-webrtc-to-influence-underlying-audio-video-buffering/4038)
  - Tests: [Blink wpt test](https://cs.chromium.org/chromium/src/third_party/blink/web_tests/external/wpt/webrtc-extensions/RTCRtpReceiver-playoutDelayHint.html?l=3&rcl=45b08193d4fbaeae3d7a40d1bf78f3bc258cadbc).
  - Primary contacts: kuddai@webrtc.org, minyue@webrtc.org, hbos@webrtc.org

Further details:

  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://docs.google.com/document/d/1px_1kCCV_1yqEyNA52fGmzS6bs8O7RVffMCKe1gHg1g/edit?usp=sharing).
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that:
 - To have the context on the current state of WebRTC 1.0 please refer to the [webrtc-pc](https://w3c.github.io/webrtc-pc/) spec.
 - [webrtc-extensions](https://w3c.github.io/webrtc-extensions/) spec describes multiple WebRTC 1.1 extensions. Here, we are requesting review only for the **playoutDelayHint** extension.
 - Chrome implemented it starting from M79.
 - It is designed similarly to the [AudioContextOptions latencyHint option](https://webaudio.github.io/web-audio-api/#dom-audiocontextoptions-latencyhint).

We'd prefer the TAG provide feedback as (please select one):

  - [x] open issues in our GitHub repo for each point of feedback

**Comment by hober** [comment]
The specification URL you've provided is broken.

**Comment by kuddai** [comment]
> The specification URL you've provided is broken.

Thank you! It should work now. We have moved it recently.

**Comment by kuddai** [comment]
Thank you. We recently have moved it. I have updated links now. Please note that most reason discussion is concentrated in this [PR](https://github.com/w3c/webrtc-extensions/pull/22).

**Comment by atanassov** [comment]
It is recommended that time based values are in milliseconds. Is there a reason you're deviating from this principle? 

https://w3ctag.github.io/design-principles/#milliseconds

**Comment by henbos** [comment]
Using double seconds is consistent with WebRTC's getStats() API which returns [jitterBufferDelay](https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-jitterbufferdelay). Setting this API affects the jitterBufferDelay, so it could be confusing if you set one to 1000 and expect the other to be 1.0. This is also consistent with the rest of getStats(), where time is always in seconds.

I don't know the reason why getStats() uses seconds though, but it's been the standard unit of measurement in WebRTC's stats. A wild guess would be that its an [SI unit](https://en.wikipedia.org/wiki/International_System_of_Units).

**Comment by atanassov** [comment]
Reviewing with @hober one more time during our Cork virtual f2f. Keeping the consistency with WebRTC makes sense, thanks for the explanation. At this point we are happy to sign off and close the issue.

@hober and @ylafon we should update the design principles with guidance around favoring milliseconds unless there is preexisting domain expectations, such as WebRTC.
