### ISSUE TITLE
HTTPS and CORS

### ISSUE THREAD

**Issue by plinss** [w3ctag/design-reviews#443]
Hello TAG!

I'm requesting a TAG review of:

  - Name: Issue with HTTPS redirects and CORS raised on mailing list
  - Specification URL: https://www.w3.org/mid/6324B8C3-2039-466A-9489-C1B5D05E1C98@w3.org
  - Explainer (containing user needs and example code)¹: n/a
  - GitHub issues (if you prefer feedback filed there): n/a
  - Tests: n/a
  - Primary contacts (and their relationship to the specification): @timbl 

Further details:

  - Relevant time constraints or deadlines: 
  - [ ] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](url).
  - [ ] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the work on this specification is:

We recommend the explainer to be in [Markdown](https://github.github.com/gfm/). On top of the [usual information expected in the explainer](https://w3ctag.github.io/explainers), it is strongly recommended to add:

  - Links to major pieces of multi-stakeholder review or discussion of this specification: 
  - Links to major unresolved issues or opposition with this specification:

You should also know that...

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our GitHub repo for each point of feedback
  - [ ] open a single issue in our GitHub repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

--------------------------

_Please preview the issue and check that the links work before submitting._ In particular, if anything links to a URL which requires authentication (e.g. Google document), please make sure anyone with the link can access the document.

¹ For background, see our [explanation of how to write a good explainer](https://w3ctag.github.io/explainers).

**Comment by annevk** [comment]
This is just a bug in W3C's CORS preflight setup. A CORS preflight's always needs to be 2xx, it cannot be a redirect. The actual response can be a redirect though.

**Comment by ylafon** [comment]
No, apparently it could be a bug in Chrome, as[ pointed out by Ruben](https://lists.w3.org/Archives/Public/www-tag/2019Dec/0003.html). When doing HTTP requests using curl on W3C website, it works as intended.

**Comment by annevk** [comment]
Hmm, for that snippet I get near-identical results in Chrome Canary and Firefox Nightly. (Either a mixed content error (when not on www.w3.org) or a response (when on www.w3.org).)

**Comment by annevk** [comment]
Okay, so this is about how `upgrade-insecure-requests` works. However, in both Chrome and Firefox I get a response if I run that `fetch()` line from Ruben on www.w3.org in the console. Firefox has redirected set to true though, which is a bug.

**Comment by plinss** [comment]
This appears to be an implementation bug.
