### ISSUE TITLE
[Meta] Issue template should prominently ask for the intended target venue

### ISSUE THREAD

**Issue by hober** [w3ctag/design-reviews#445]
When we get design review requests from an individual's personal GitHub account, it's often unclear which standards body (if any) the individual intends to bring the proposal to. The issue template should explicitly ask filers to state where (e.g. WICG, WHATWG) they intend to make the proposal.

**Comment by dbaron** [comment]
For what it's worth, I made aae000dd307bce69358acaef26a9199648a4d084 in response to the same discussion that led you to file this.
