### ISSUE TITLE
HTML horizontal review: Form controls

### ISSUE THREAD

**Issue by hober** [w3ctag/design-reviews#449]
Subtask of w3ctag/design-reviews#412.

PRs to review:

- [ ] whatwg/html#4143
- [ ] whatwg/html#4447
- [ ] whatwg/html#4573
- [ ] whatwg/html#4597
- [ ] whatwg/html#4621

**Comment by dbaron** [comment]
@kenchris and I looked at these (quite quickly, given the size of them) during our Wellington face-to-face.  We didn't spot any issues that we think require TAG followup discussion, so think it makes sense to close this issue.
