### ISSUE TITLE
HTML horizontal review: Security

### ISSUE THREAD

**Issue by hober** [w3ctag/design-reviews#451]
Subtask of w3ctag/design-reviews#412.

PRs to review:

- [x] whatwg/html#4269
- [x] whatwg/html#4330
- [x] whatwg/html#4331
- [x] whatwg/html#4332

**Comment by torgo** [comment]
Discussed asking for some external feedback on this one.

**Comment by dbaron** [comment]
@atanassov and I looked at this during our face-to-face in Wellington.  All of these changes seem relatively straightforward, and we don't see any issues in them that need further review.
