### ISSUE TITLE
HTML horizontal review: The Event Loop

### ISSUE THREAD

**Issue by hober** [w3ctag/design-reviews#453]
Subtask of w3ctag/design-reviews#412.

PRs to review:

- [ ] whatwg/html#4437
- [ ] whatwg/html#4440

**Comment by dbaron** [comment]
@kenchris and I looked at this during our Wellington face-to-face.  We looked over the two linked PRs; they're pretty technical stuff related to event loops.  We think they're unlikely to raise architectural issues (issues in this area tend to be around interoperability and testing), and don't feel the need to review them in detail.
