### ISSUE TITLE
HTML horizontal review: Canvas

### ISSUE THREAD

**Issue by hober** [w3ctag/design-reviews#454]
Subtask of w3ctag/design-reviews#412.

PRs to review:

- [ ] whatwg/html#4360
- [ ] whatwg/html#4455
- [ ] whatwg/html#4473 (reference existing xforms?)

**Comment by dbaron** [comment]
@kenchris and I just reviewed these three PRs at our Wellington face-to-face, and they all seemed reasonable to us.
