### ISSUE TITLE
HTML horizontal review: Accessibility

### ISSUE THREAD

**Issue by hober** [w3ctag/design-reviews#459]
Subtask of w3ctag/design-reviews#412.

PRs to review:

- [x] whatwg/html#4754

**Comment by hober** [comment]
I've just looked at whatwg/html#4754 and I don't think we need to comment on the change.

**Comment by alice** [comment]
I agree we don't need to comment on that issue, but we should check up on the ongoing efforts (of which this change is a part) to pay down technical debt in the HTML spec around focus.

**Comment by alice** [comment]
Closing in favour of https://github.com/w3ctag/design-reviews/issues/468

**Comment by alice** [comment]
Actually closing per my earlier threat
