### ISSUE TITLE
WebXR Augmented Reality Module

### ISSUE THREAD

**Issue by mounirlamouri** [w3ctag/design-reviews#462]
Hello TAG!

I'm requesting a TAG review of WebXR Augmented Reality Module.

The WebXR Augmented Reality Module extends the WebXR Device API to expose the ability to create a basic augmented reality (AR) session.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/immersive-web/webxr-ar-module/blob/master/ar-module-explainer.md
  - Specification URL: https://immersive-web.github.io/webxr-ar-module/
  - Tests: https://github.com/web-platform-tests/wpt/tree/master/webxr/ar-module
  - Security and Privacy self-review²: https://github.com/immersive-web/webxr-ar-module/blob/master/security-privacy-questionnaire.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/immersive-web/webxr-ar-module
  - Primary contacts (and their relationship to the specification): 
     - Manish Goregaokar, @Manishearth, Mozilla, Editor
     - Nell Waliczek, @NellWaliczek, Amazon, Editor
     - Brandon Jones, @toji, Google, Editor
     - Ada Rose Cannon, @AdaRoseCannon, Samsung, Chair
     - Chris Wilson, @cwilso, Google, Chair
  - Organization(s)/project(s) driving the specification: N/A (Immersive Web WG)
  - Key pieces of existing multi-stakeholder review or discussion of this specification: N/A
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):
    - Chrome Status: https://chromestatus.com/feature/5450241148977152

Further details:

  - [X] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: Chrome will have an Intent to Ship soon for this API.
  - The group where the work on this specification is being done: Immersive Web WG
  - Major unresolved issues with or opposition to this specification: N/A
  - This work is being funded by: N/A

You should also know that...

  - This specification was split from the WebXR specification recently and has been designed as a module/extension.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by atanassov** [comment]
@torgo and myself did a review pass at this proposal during our "Kronos" VF2F. 

We found the answers to the privacy & security considerations section a bit small. This API claims to allow access to the camera image for use in compositing while ensuring the web site doesn't have access to it. This is a very important point to be made explicitly and normatively. The section about why the web site doesn't get access could use such clarity and the requirement ought to be normative (perhaps link to the XR Compositor section).

The terminology section defines types such as opaque, pass through and additive light but it is hard to tie these to real-world scenarios or devices. Which of these defines a phone or computer with camera, headsets etc.? In particular, what is an example of Opaque AR?

Section 2.5 of the spec can benefit greatly from a more complete motivational code example. Also, please clarify the use of the word Content - is this Site Content or Virtual Content?

**Comment by Manishearth** [comment]
Addressed comments in https://github.com/immersive-web/webxr-ar-module/pull/63
