### ISSUE TITLE
HR review of IMSC 1.2 FPWD

### ISSUE THREAD

**Issue by nigelmegitt** [w3ctag/design-reviews#474]
Hello TAG!

I'm requesting a TAG review of IMSC 1.2 FPWD, specifically the [delta relative to IMSC 1.1](https://www.w3.org/TR/ttml-imsc1.2/#substantive-changes-summary), of which the main substantive change is the addition of support for the [`#font`](https://www.w3.org/TR/ttml-imsc1.2/#text-font-source) feature.

This feature allows the content author to specify an external font resource to be used when presenting the document, with attributes similar to the descriptors that can be specified with the CSS `@font-face` rule.

  - Explainer¹ (minimally containing user needs and example code): Closest we have is https://github.com/w3c/tt-reqs/issues/15
  - Requirements: https://w3c.github.io/imsc-vnext-reqs/ in particular the requirement for [font support](https://w3c.github.io/imsc-vnext-reqs/#font-support)
  - Specification URL: [IMSC 1.2 FPWD](https://www.w3.org/TR/2019/WD-ttml-imsc1.2-20191128/)
  - Tests: https://github.com/w3c/imsc-tests/tree/master/imsc1_2
  - Security and Privacy self-review²: This is largely unchanged since IMSC 1.1 however note the privacy review issue raised against TTML2, from which some new features are referenced, at w3c/ttml2#1189 See also w3c/imsc#503
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/imsc/issues/
  - Primary contacts (and their relationship to the specification): 
      - [Pierre-Anthony Lemieux] (@palemieux ), IMSC Editor, representing MovieLabs
      - [Nigel Megitt] (@nigelmegitt), TTWG Chair, BBC
  - Organization(s)/project(s) driving the specification: [organization and/or project name] 
  - Key pieces of existing multi-stakeholder review or discussion of this specification: 
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): None

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/) _but it is not relevant since this is not an API specification_
  - Relevant time constraints or deadlines: we would appreciate an expedited review of this small delta please.
  - The group where the work on this specification is being done: W3C TTWG
  - Major unresolved issues with or opposition to this specification: None
  - This work is being funded by: TTWG group participants

You should also know that...

The FPWD was published on 2019-11-28 and the feature delta is small. 

The main substantive requirement was to allow inline images such as company logos to be inserted into text. By allowing external font resources to be specified, the subtitle or captions document author can have some reassurance that the desired image is present in the selected font. Two image mechanisms are feasible: 1. A fallback image in the font file, e.g. the text "W3C" might be replaced inline with an SVG image of the W3C logo; 2. The Unicode private use area of code points can be used to define bespoke images.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by nigelmegitt** [comment]
Hi @hober, thank you for self-assigning this. And hello to the rest of TAG!

Publication of IMSC 1.2 was discussed during today's [TTWG call](https://www.w3.org/2020/02/20-tt-minutes.html). The group would like to target publication in 4 weeks, i.e. on 2020-03-19, if the reviews do not throw up any blockers. 

Please could you let me know if you would like additional time to review this? Acknowledging TTWG's tardiness in requesting review after FPWD publication, if there's anything more we can do to assist in the review please let me or @palemieux know.

One other thing to note is that as a profile of TTML2, the new feature in IMSC 1.2 is already part of a W3C Recommendation, albeit the variant in IMSC 1.2 is somewhat constrained relative to the TTML2 feature.

**Comment by hober** [comment]
PING's privacy assessment is here: https://lists.w3.org/Archives/Public/public-privacy/2020JanMar/0055.html

**Comment by hober** [comment]
Hi,

Thanks for all your patience as it's taken us many months to get to this review. In the intervening time, you've received and addressed a number of pieces of accessibility and privacy feedback, and you've gone to REC. If you'd still like us to review, we'd appreciate [an explainer](https://github.com/w3ctag/w3ctag.github.io/blob/master/explainers.md) targeted at a general technical audience unfamiliar with TTML and IMSC1.

**Comment by plinss** [comment]
We're going to go ahead and close this issue, if you feel you'd benefit from any TAG feedback on this please ping us to re-open.

**Comment by nigelmegitt** [comment]
Thanks @plinss and @hober. TAG feedback at this juncture would be difficult to integrate into the published Rec, so this seems reasonable.

Given that the closest related feature to that introduced here is the CSS `@font-face` rule, I searched this repo for design reviews of CSS Fonts Level 3, but did not find any issues from when it was introduced. Very likely such review would have predated the repo and I'm looking in the wrong place. However, should there be any future review of the `@font-face` rule as a whole (as opposed to specific additions to it like #557) please could you ping me/TTWG in case there is any action that we should take?
