### ISSUE TITLE
WebXR Anchors Module

### ISSUE THREAD

**Issue by bialpio** [w3ctag/design-reviews#479]
Hello TAG!

I'm requesting a TAG review of WebXR Anchors Module.

An anchor is a concept that allows applications to specify poses (a position and orientation in three dimensional space) that will be tracked by the underlying system. There are systems where pose tracking is based on their understanding of the world. That understanding, and thus the pose of an anchor, varies over time. Anchors allow a developer to specify poses in the world that need to be updated to correctly reflect the evolving understanding of the world, such that the poses remain aligned with the same place in the physical world.

The main idea behind the concept of an anchor is that as the underlying platform's understanding of the world evolves over time, the anchor pose will be updated such that it remains aligned with the same place in the physical world.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/immersive-web/anchors/blob/master/explainer.md
  - Security and Privacy self-review²: https://github.com/immersive-web/anchors/blob/master/security-privacy-questionnaire.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/immersive-web/anchors
  - Primary contacts (and their relationship to the specification):
    - Piotr Bialecki, @bialpio, Google, Editor
    - Trevor F. Smith, @TrevorFSmith, CG Chair
    - Ada Rose Cannon, @AdaRoseCannon, Samsung, WG Chair
    - Chris Wilson, @cwilso, Google, WG Chair
  - Organization/project driving the design: Immersive Web CG
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5129925015109632

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the work on this design is being done (or is intended to be done in the future): Immersive Web CG
  - Existing major pieces of multi-stakeholder review or discussion of this design: https://github.com/immersive-web/anchors/issues
  - Major unresolved issues with or opposition to this design: No major blockers so far, all issues can be found in the repository (link to issues above).
  - This work is being funded by: N/A.

You should also know that...

N/A.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by torgo** [comment]
Hi - we are reviewing this in our [virtual F2F week](https://github.com/w3ctag/meetings/tree/gh-pages/2020/05-distributed). I think the explainer needs a little more info to elaborate what a pose is and what an anchor is. It would be great if you could include some examples (and maybe diagrams) right up front and word it in terms of the user need. 

Also since the term Anchor is already used in web architecture, could you at least have one sentence that emphasises that you are talking about a totally different concept.

**Comment by torgo** [comment]
Thanks for responding to the security & privacy self-check. The responses look good.

**Comment by ylafon** [comment]
Hi, I was wondering if it could make sense to have a way to share anchors, an example would be a specific location in a multiplayer game, or highlight one player?

**Comment by hober** [comment]
Hi @bialpio!

Could you take a look at @torgo and @ylafon's questions & let us know what you think?

**Comment by bialpio** [comment]
Thanks for the ping!

> I think the explainer needs a little more info to elaborate what a pose is and what an anchor is. It would be great if you could include some examples (and maybe diagrams) right up front and word it in terms of the user need.
>
> Also since the term Anchor is already used in web architecture, could you at least have one sentence that emphasises that you are talking about a totally different concept.

Let me add a bit more details to clarify the concepts.

> Hi, I was wondering if it could make sense to have a way to share anchors, an example would be a specific location in a multiplayer game, or highlight one player?

The main challenge that I see with that is making sure that the anchors are able to be shared across various platforms - I don't think we have a way of achieving this now. It definitely is an interesting idea! We are currently working on an image tracking feature that could allow multiple people to orient themselves relative to each other by using a well-known image in the physical world - hopefully this could help with what you're describing.

Can you elaborate on what you mean by "highlighting one player"?

**Comment by torgo** [comment]
Hi @bialpio - we're just checking up on this one in our TAG call today and it doesn't look like any updates have been made to the explainer yet. We're happy to re-review when that's done.

**Comment by ylafon** [comment]
Hi @bialpio, I was making the difference between a static anchor (like a position in space), and a dynamic one (a player, or a moving element, a characteristic), and being able to share those anchors (like in a team, to other players)

**Comment by torgo** [comment]
Hi @bialpio we are trying to close up this issue we're going to bump it to next week's TAG breakouts. Can you feed back on the question @ylafon asked and also let us know if there are any additional updates?

**Comment by bialpio** [comment]
I've started making changes to address your comments, I'll update this thread once they are in.

@ylafon - please take a look at image/marker tracking [explainer](https://github.com/immersive-web/marker-tracking/blob/main/explainer.md) - this may be something that should enable multiplayer experiences. Other than that, I think there is not really a good way to share anchors across devices that is built into WebXR (we have tentatively started discussions around cloud anchors concept, but those still early and not guaranteed to become a reality anytime soon, if at all).

**Comment by alice** [comment]
Thank you so much for the work on the explainer - I just had another read through as part of our virtual face to face, and it answered all of my questions and explained the relevant terminology and user needs really well.

In terms of the proposed API, this is now much clearer - one minor edit I might suggest is to specify the arguments to the two `createAnchor()` options inline, e.g.

`XRFrame.createAnchor(pose, referenceSpace)` and
`XRHitTestResult.createAnchor(pose)` respectively.

That would indicate which arguments are relevant in each case, and then we could read the text below to explain the arguments.

That said, the details of the API seem well thought through and the explainer is now much clearer, so I'm happy to propose closing this.

**Comment by alice** [comment]
Closing this in our roll-up, thank you for all your work on this!
