### ISSUE TITLE
PWA Change logs

### ISSUE THREAD

**Issue by stanleyhon** [w3ctag/design-reviews#484]
Hello TAG!

I'm requesting a TAG review of PWA Change Logs AKA Version History.

When a new version of a piece of native software rolls out users are typically made aware through a notification in their operating system or the app store they use. The web—in contrast—is evergreen, meaning that software built atop it is always up to date. Because of this, there is no formal "moment" in which developers of web-based software can inform their users of what’s changed with their software from release to release (e.g., new features that have been added, which bugs have been fixed). Providing a standardized means of surfacing version history would enable developers to surface this useful—and sometimes crucial—information.

  - Explainer: https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/VersionHistory/explainer.md
  - Security and Privacy self-review²: https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/226
  - GitHub repo (if you prefer feedback filed there): https://github.com/MicrosoftEdge/MSEdgeExplainers
  - Primary contacts:
      - Stanley Hon (@stanleyhon), Microsoft
      - Aaron Gustafson (@aarongustafson), Microsoft
  - Organization/project driving the design: Microsoft
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): https://www.chromestatus.com/feature/6644911535292416

Further details:

  - [X] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future):
  - The group where standardization of this work is intended to be done ("unknown" if not known):
  - Existing major pieces of multi-stakeholder review or discussion of this design: 
  - Major unresolved issues with or opposition to this design:
  - This work is being funded by: Microsoft

You should also know that there is a WICG discourse thread here: https://discourse.wicg.io/t/proposal-pwa-changelogs/4290/8

And also some existing issues have been raised to the explainer github issues: https://github.com/MicrosoftEdge/MSEdgeExplainers/issues?q=is%3Aissue+is%3Aopen+label%3A%22Version+History%22 (filtered to Version History issues)

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @stanleyhon

**Comment by torgo** [comment]
We did discuss this in one of our previous [TAG calls](https://github.com/w3ctag/meetings/blob/gh-pages/2020/telcons/03-23-minutes.md). To summarise our feedback:

If these change logs show up in trusted UI - like somewhere in your system it could open the door abuse and also people will expect it to look very similar in different contexts - and have very low level of formatting.  HTML is very flexible but do you really need all the flexibility - as it might open the door to abuse and create unnecessary complexity in how it's displayed. We suggest starting with something like markdown.

**Comment by stanleyhon** [comment]
We've shelved this project based on feedback and may revisit it at a later date. Closing this review for now. Thanks for the feedback.
