### ISSUE TITLE
Imperative Shadow DOM Distribution API.

### ISSUE THREAD

**Issue by yuzhe-han** [w3ctag/design-reviews#486]
Hello TAG!

I'm requesting a TAG review of Imperative Shadow DOM Distribution API.

This feature will allow web developers to explicitly set the assigned nodes for a slot element. This feature will allow web developers to set the assigned nodes for a slot element explicitly. It enables node assignment based on input properties without needing to change HTML markup.  (see explainer for more details)

  - Explainer¹ (minimally containing user needs and example code): https://github.com/yuzhe-han/webcomponents/blob/gh-pages/proposals/Imperative-Shadow-DOM-Distribution-API.md
  - Security and Privacy self-review²: https://github.com/yuzhe-han/imperative-slot-assignment/blob/master/security-self-review.md
  - Primary contacts (and their relationship to the specification):
      - Yu Han (@yuzhe-han), Google 
      - Mason Freed (@mfreed7), Google 
  - Organization/project driving the design: Imperative Shadow DOM Distribution API. 
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5711021289242624

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): WhatWG
  - The group where standardization of this work is intended to be done ("unknown" if not known): unknown
  - Existing major pieces of multi-stakeholder review or discussion of this design: 
    - https://github.com/whatwg/html/issues/3534
    - blink-dev
  - Major unresolved issues with or opposition to this design: None
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as (please delete all but the desired option):
  💬 leave review feedback as a **comment in this issue** and @-notify @yuzhe-han, @mfreed7

**Comment by hober** [comment]
Overall I think this looks great.

One minor concern I have is with the exclusivity of the slot assignment modes, though I think my concern could easily be addressed by some syntactic sugar.

It's common to have special behavior with one child (or a few children) and some kind of default behavior for the rest. Consider the following markup:

```html
<details>
  <summary>This is the summary.</summary>
  and
  <p>these
  <p>are
  <p>the
  <p>details
</details>
```

The proposed imperative API lets you easily handle `<summary>`. It would be nice if it were easy/straightforward to implement a default slot using the imperative API, so that the rest of `<details>`'s children could be taken care of easily. Maybe something like `shadowRoot.setDefaultSlot(slot)`. You do some manual slotting and then everything not slotted ends up in the default slot.

**Comment by yuzhe-han** [comment]
@hober,

Thanks for reviewing and providing feedback. 

Your concern is a good one and has been discussed in the comments surrounding following comment, https://github.com/whatwg/html/issues/3534#issuecomment-538613515

In there, @fergald provides one way of emulating a default slot in a custom element using manual slot assignment. I think it can be used to address your issue. 
Another way I can think of, but requires addition markup, is to use a custom element to wrap the additional detail's content.

Hopefully these methods above address your concerns. We want to avoid mixing imperative and declarative slot assignment as listed in point 4 of  https://github.com/whatwg/html/issues/3534#issuecomment-537802687.

Thanks.

**Comment by hober** [comment]
@kenchris and I looked at this again during the TAG F2F this week, and we're wrapping up our review. Overall we think this looks great, and while we would have preferred some default slot sugar, we understand why you're reluctant to add it. Thanks! Please open a new design review if your approach significantly changes in the future.
