### ISSUE TITLE
Window Segments API

### ISSUE THREAD

**Issue by dlibby-** [w3ctag/design-reviews#492]
Hello TAG!

I'm requesting a TAG review of the Window Segments API.

Web developers targeting foldable devices want to be able to effectively lay out the content in a window that spans multiple displays. However, the web platform does not yet provide the necessary primitives for building layouts that are optimized for foldable experiences. The Window Segments API will provide a list of logical segments of the viewport that web developers can use to target with different views, as appropriate based on size and configuration of those segments.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/webscreens/window-segments/blob/master/EXPLAINER.md
  - Security and Privacy self-review²: https://github.com/webscreens/window-segments/blob/master/TAG-Security-and-Privacy-Questionnaire.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/webscreens/window-segments
  - Primary contacts (and their relationship to the specification):
      - Daniel Libby, @dlibby-, Microsoft
      - Zouhir Chahoud, @zouhir, Microsoft
  - Organization/project driving the design: Microsoft
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status):

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): Second Screen CG
  - The group where standardization of this work is intended to be done ("unknown" if not known): Unknown
  - Existing major pieces of multi-stakeholder review or discussion of this design: 
  - Major unresolved issues with or opposition to this design: N/A
  - This work is being funded by:  Microsoft

We'd prefer the TAG provide feedback as:

  💬 leave review feedback as a **comment in this issue** and @-notify [github usernames]

**Comment by kenchris** [comment]
The current API exposed the two windows segments, but some devices will have no physical hinge but still have a hinge area that might not be good place to place UI components as the screen might be bending there.

I have heard that from multiple people working at Samsung, that the dual screen APIs would work for non dual screen, actually foldable screen devices, but the hinge area would just be visible.

As that is the case, it might make sense to expose the hinge area as a segment as well, potentially by supplying an option to the method.

**Comment by plinss** [comment]
How does this handle multiple axes? For example, if a user has 4 monitors in a 2x2 grid and the window spans all 4 (fairly common).

Also, is there a defined ordering to the rects or does the user have to infer their spatial relationships based on the coordinates?

Are the returned rects always adjacent? e.g. for hardware with a known gap between devices will that be reflected in the coordinates?

**Comment by plinss** [comment]
Closing this issue, the TAG is satisfied that this is being handled in the CSSWG. Happy to re-review when it reaches later stages.
