### ISSUE TITLE
Content Indexing API

### ISSUE THREAD

**Issue by rayankans** [w3ctag/design-reviews#496]
Hello TAG!

I'm requesting a TAG review of Content Indexing.

The content index allows websites to register their offline enabled content in the browser. This allows the browser to improve their offline capabilities and offer content to users to browse through while offline. This data could also be used to improve on-device search and augment browsing history.

  - Explainer: https://github.com/wicg/content-index
  - Specification URL: https://wicg.github.io/content-index/spec/
  - Tests: https://wpt.fyi/results/content-index
  - Security and Privacy self-review: https://github.com/WICG/content-index/blob/master/SECURITY_AND_PRIVACY.md
  - GitHub repo:  https://github.com/WICG/content-index/
  - Primary contacts:
      - Rayan Kanso (@rayankans), Google, Editor
      - Peter Beverloo (@beverloo), Google, Editor
  - Organization(s)/project(s) driving the specification: Google
  - Key pieces of existing multi-stakeholder review or discussion of this specification: https://discourse.wicg.io/t/proposal-content-indexing-api/4308
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://www.chromestatus.com/feature/5658416729030656

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the work on this specification is currently being done: WICG

You should also know that an early TAG review was done here: https://github.com/w3ctag/design-reviews/issues/379

We'd prefer the TAG provide feedback as:

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by torgo** [comment]
Hi @rayankans @jakearchibald - to clarify, is this intended to go from WICG into the Service Workers working group? If so, what is the time-line intended?

**Comment by kenchris** [comment]
Doesn't this link to the new image resource spec proposal, instead of web app manifest?

**Comment by kenchris** [comment]
We discussed this in the TAG today, as this will be show in important places (Android Slices etc) there is the chance that people will do something similar to SEO to get this to show up in these places, as that can mean big money. This might also lead to aggressive indexing and bandwidth use.

We believe there should be at least a section in the explainer discussing these scenarios.

**Comment by rayankans** [comment]
> is this intended to go from WICG into the Service Workers working group? 

I think the Web Applications Working Group is a better fit for this API.

> Doesn't this link to the new image resource spec proposal, instead of web app manifest?

It does now :) I was waiting for the image resource TAG review to go through.

I also added an Abuse Considerations section in the explainer: https://github.com/wicg/content-index#abuse-considerations

**Comment by kenchris** [comment]
Image resource has passed TAG review and that issue is now closed: https://github.com/w3ctag/design-reviews/issues/490

**Comment by kenchris** [comment]
We find the Abuse Considerations section a bit short, so maybe it could be expanded a bit. Also can you make sure that something like this makes it into the spec itself?

**Comment by rayankans** [comment]
Thanks for the feedback @kenchris.

I expanded the [Abuse Considerations](https://github.com/WICG/content-index#abuse-considerations) section in the explainer to give some more background and include some more ways to handle this scenario.

I also mentioned the scenario in the spec's [Privacy Considerations](https://wicg.github.io/content-index/spec/#privacy-considerations), and added a note within the [display algorithm](https://wicg.github.io/content-index/spec/#content-index-entry-display).

**Comment by kenchris** [comment]
Thanks you! and thanks for consulting with the TAG!
