### ISSUE TITLE
Review request: HTML Standard Jan 2020 Review Draft

### ISSUE THREAD

**Issue by siusin** [w3ctag/design-reviews#499]
Hello TAG!

I'm requesting a TAG review of [Jan 2020 HTML Standard Review Draft](https://html.spec.whatwg.org/review-drafts/2020-01/).

- GitHub repo (if you prefer feedback filed there): https://github.com/whatwg/html/issues/
- Primary contacts (and their relationship to the specification):
      - @hober , HTML WG co-chair
      - @sideshowbarker 
      - WHATWG HTML editors
- Organization(s)/project(s) driving the specification: WHATWG and W3C
- Key pieces of existing multi-stakeholder review or discussion of this specification: 
      - https://github.com/w3ctag/design-reviews/issues/489
      - https://github.com/w3ctag/design-reviews/issues/412

The WHATWG published a new Review Draft of the HTML Standard on 29 January 2020. The HTML WG plans to take the latest Review Draft to W3C Recommendation in June, thus we are inviting another wide and horizontal review of the [commits of the HTML Standard between  16 Jul 2019 (3f7c879) and 29 Jan 2020 (d22075c)](https://github.com/whatwg/html/commits/master?after=d22075cc8e66516c28e73d5efac2d565996d9a9d+99).

We put together [a list of significant changes for each horizontal review group](https://github.com/w3c/htmlwg/issues/8#issue-597865240), please pay attention to these pull requests during your group discussion:
* [Make `<img>.complete` more reliable](https://github.com/whatwg/html/pull/4934)
* [Change default value of `window.open()`'s `url` argument](https://github.com/whatwg/html/pull/4851)
* [Remove `<img>` progress events](https://github.com/whatwg/html/pull/4842)
* [Define `DocumentOrShadowRoot`'s `activeElement`](https://github.com/whatwg/html/pull/4837)
* [Imperatively allocate window agents and agent clusters](https://github.com/whatwg/html/pull/4617)
* [Update all constructors, including `HTMLConstructor`](https://github.com/whatwg/html/pull/4915)
* [Specify which event loop to use for posting messages](https://github.com/whatwg/html/pull/4917)
* [Use width and height as intrinsic aspect ratio for img elements](https://github.com/whatwg/html/pull/4952)
* [Make window.window/frames/self deal with no browsing context](https://github.com/whatwg/html/pull/4410))
* [Ignore document.open/write after the active parser has been aborted](https://github.com/whatwg/html/pull/4907)
* [Change the timing of "flush autofocus candidates”](https://github.com/whatwg/html/pull/5015)
* [Introduce `SubmitEvent` for the form `submit` event](https://github.com/whatwg/html/pull/4984)
* [Revamp the user activation model](https://github.com/whatwg/html/pull/3851)
* [Add "queue an element task” algorithm](https://github.com/whatwg/html/pull/5072)
* [Define `getSVGDocument()` in terms of content document](https://github.com/whatwg/html/pull/5109)
* [Cleanups to "execute a script block” Signpost the debate on some script mismatches](https://github.com/whatwg/html/pull/5154)
* [Move the `DOMParser` class to HTML](https://github.com/whatwg/html/pull/5190)

Further details:
  - Relevant time constraints or deadlines: 22 May 2020
  - The group where the work on this specification is currently being done: WHATWG and W3C HTML WG

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by hober** [comment]
Like last time, I'll organize the above issues into topical buckets & we'll do breakouts on each one.

**Comment by hober** [comment]
Okay, the TAG has reviewed all of the PRs we were tasked with. Closing.
