### ISSUE TITLE
HTML Horizontal Review: User interaction, user activation, focus, tabbing, etc.

### ISSUE THREAD

**Issue by hober** [w3ctag/design-reviews#501]
This is a subtask of #499. Please review these two HTML PRs:

- [x] [Change the timing of "flush autofocus candidates”](https://github.com/whatwg/html/pull/5015)
- [x] [Revamp the user activation model](https://github.com/whatwg/html/pull/3851)

**Comment by dbaron** [comment]
The second one was (as @hober points out) already reviewed by the TAG in #295.

**Comment by atanassov** [comment]
We reviewed whatwg/html#5015 on today's call. We're happy to see the issue being resolved and didn't have major issues that weren't already discussed in the attached issues. @plinss was wondering if running style could change the results of computing the autofocused element. The discussion affirmed this is indeed the desired behavior and at this point we don't have any reasons to keep this open.

As ror issue whatwg/html#3851, as pointed out by @dbaron in the previous comment, it was already reviewed and TAG is fine with closing it.
