### ISSUE TITLE
Does Shortcuts need a design review?

### ISSUE THREAD

**Issue by jungkees** [w3ctag/design-reviews#506]
Hello TAG!

[Shortcuts](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/Shortcuts/explainer.md) has been [merged](https://github.com/w3c/manifest/pull/768) to [Web App Manifest](https://w3c.github.io/manifest/#shortcuts-member) after @aarongustafson and folks discussed this in the TPAC last year and had [a tacit approval](https://github.com/w3c/manifest/issues/782#issuecomment-533363985).

As a TAG design review is recommended for our process, I'd like to ask for your comments whether the discussion the community has gone through - including the discussion with TAG in TPAC - for this feature would be enough? Or would you recommend us rather make a design review request?

/cc @rahulsingh-msft @cmumford @pwnall

**Comment by torgo** [comment]
Hi Jungkee! Yes, we definitely think you should file a design review for this. Please let me know if you have any questions with the template.
