### ISSUE TITLE
shortcuts member of Web App Manifest

### ISSUE THREAD

**Issue by jungkees** [w3ctag/design-reviews#510]
Hello TAG!

I'm requesting a TAG review of shortcuts member of Web App Manifest.

A number of operating systems offer a means by which authors add menu items to the app launcher icon itself. These provide quick access to key tasks for an app. Typically, these are exposed via a right click, long tap, or a similar context menu-triggering action. The list of shortcut actions often contains a mixture of static and dynamic shortcuts. Generally these number around 4–5, depending on the platform—or in the case of Android, the launcher—used. Adding these to the web platform provides an equivalent capability to native apps on many platforms.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/Shortcuts/explainer.md
  - Specification URL: https://w3c.github.io/manifest/#shortcuts-member
  - Security and Privacy self-review²: https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/Shortcuts/security-privacy.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/MicrosoftEdge/MSEdgeExplainers/tree/master/Shortcuts
  - Primary contacts (and their relationship to the specification):
      - Aaron Gustafson (@aarongustafson), Microsoft
      - Kenneth Rohde Christiansen (@kenchris), Intel
      - Matt Giuca (@mgiuca), Google
      - Rahul Singh (@rahulsingh-msft), Microsoft
      - Rayan Kanso (@rayankans), Google
      - Jungkee Song (@jungkees), Microsoft
  - Organization(s)/project(s) driving the specification: Microsoft, Intel, Google
  - Key pieces of existing multi-stakeholder review or discussion of this specification: a discussion during TPAC 2019 including TAG members. See https://github.com/w3c/manifest/issues/782#issuecomment-533363985.
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://www.chromestatus.com/feature/5706099464339456

Further details:

  - [X] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the work on this specification is currently being done: Web Applications Working Group
  - Major unresolved issues with or opposition to this specification: N/A
  - This work is being funded by: Microsoft, Intel, Google

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by kenchris** [comment]
I will let some of my co-TAG members review this as I have been involved - but I will just say that I am happy how it turned out and I think we have been good in incorporating all the different feedback from different stakeholders, and I am happy to see this move forward

**Comment by cynthia** [comment]
Couldn't see anything substantial during the review.

**Comment by torgo** [comment]
We are reviewing in a TAG breakout and we are happy with this. However, is there a standards position on this from Mozilla or any other cross-engine support info you can provide @jungkees ?

**Comment by aarongustafson** [comment]
> However, is there a standards position on this from Mozilla or any other cross-engine support info you can provide?

I am not aware of anything formal, though our informal discussions with @hober and @marcoscaceres at TPAC last year were quite positive. The [PR into the Manifest spec includes references to the bugs we filed for each engine](https://github.com/w3c/manifest/pull/768).

**Comment by kenchris** [comment]
@dbaron will file a standards position issue with Mozilla for completeness sake.

Apart from that, the TAG is happy with this feature!

**Comment by jungkees** [comment]
Thank you TAG for the review!
