### ISSUE TITLE
CSS page-orientation descriptor

### ISSUE THREAD

**Issue by mstensho** [w3ctag/design-reviews#515]
Hello TAG!

I'm requesting a TAG review of the page-orientation descriptor, which is part of the CSS Paged Media Module.

The page-orientation descriptor can be used to set the orientation of a named page, so that it appears rotated in print preview, and also when saving paginated layout to file (e.g. PDF). Page orientation does not affect layout; any rotation is applied after layout.

The Paged Media spec has a ['size'](https://www.w3.org/TR/css-page-3/#page-size-prop) descriptor, which can also be used to set the orientation of a page indirectly, but this also affects layout. The new page-orientation descriptor is different, in that it just rotates all the layout, including any headers and footers. Printed pages may be presented together as a pamphlet or book, which essentially means that every page has the same size, and that the reader is supposed to turn the book or pamphlet 90 degrees when reading rotated pages. External formatting systems, such as word processors, may do page layout on their own and even push the output to a CANVAS, rather than individual DOM nodes. Such web-based word processors can also often support page sizings that are more advanced or specialized than what the user agent is capable of providing.

[1] 

  - Explainer: https://github.com/mstensho/page-orientation
  - Specification URL: https://drafts.csswg.org/css-page-3/#page-orientation-prop
  - Tests: https://chromium.googlesource.com/chromium/src/+/HEAD/third_party/blink/web_tests/printing/page-orientation.html
  - Primary contacts (and their relationship to the specification):
      - Morten Stenshorne (mstensho), Google, for the Chromium implementation
      - CSSWG, for spec issues
  - Organization(s)/project(s) driving the specification: Google
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):
https://bugs.chromium.org/p/chromium/issues/detail?id=1053768
https://chromestatus.com/features/5173237715566592

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the work on this specification is currently being done: Google
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): CSSWG

This feature is actively being worked on in Chromium. Intent to prototype: https://groups.google.com/u/2/a/chromium.org/g/blink-dev/c/ByWuVBk1lFE/m/vAfiloyPBAAJ

We'd prefer the TAG provide feedback as (please delete all but the desired option):

   💬 leave review feedback as a **comment in this issue** and @-notify @chrishtr @mstensho @tabatkins

**Comment by dbaron** [comment]
@cynthia and I talked about this in a breakout.  As I've said in other places (e.g., mozilla/standards-positions#346), this is a small feature, a total hack, but I think it's fine.  (At some point I'd be interested in seeing a clearer processing model for the interaction of `@page` rules with available paper sizes; I think the [current spec section](https://drafts.csswg.org/css-page-3/#renderingpages) could have more detail.)
