### ISSUE TITLE
Allow audio packet rate to adapt in realtime communication.

### ISSUE THREAD

**Issue by minyuel** [w3ctag/design-reviews#517]
Hello TAG!

I'm requesting a TAG review of allowing audio packet rate to adapt in realtime communication.

As the packet rate is a big determining factor to the overall bitrate of an audio stream, an optimal congestion control should be allowed to adapt the packet rate. The audio packet rate is analogous to the video frame rate, which also plays an important role in the video bitrate adaptation.

Although adaptive packet rate may be ubiquitously beneficial, we propose to add a flag for applications to enable or disable it to avoid potential interoperability problems.

  - Explainer: [A new flag in RTCRtpEncodingParameters for adaptive packet rate](https://w3c.github.io/webrtc-extensions/explainer#a-new-flag-in-rtcrtpencodingparameters-for-adaptive-packet-rate)

  - Specification: [adaptivePTime in WebRTC extensions](https://w3c.github.io/webrtc-extensions/#dom-rtcrtpencodingparameters-adaptiveptime)

  - Primary contacts (and their relationship to the specification):
      - Minyue Li (@minyuel), Google
      - Jakob Ivarsson, Google
      - Elad Alon, Google
      - Henrik Boström (@henbos), Google

  - Organization(s)/project(s) driving the specification: Google Hangouts

  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): [Adding adaptivePTime to RTCRtpEncodingParameters](https://www.chromestatus.com/feature/5752004691361792)

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

  - The group where the incubation/design work on this is being done (or is intended to be done in the future): WebRTC W3C WG

  - The group where standardization of this work is intended to be done ("unknown" if not known): WebRTC W3C WG

  - Existing major pieces of multi-stakeholder review or discussion of this design:
     -- interoperability: adapting audio packet rate does not violate existing specifications but may introduce interoperability problems, as some current implementations may take a fixed packet rate as an assumption and thus fail or perform sub-optimally when packet rate changes. We resolved the problem by introducing the adaptivePTime flag as proposed in this review.
 
     -- format: whether to surface an API for a more detailed control of packet rate than just a boolean to allow a browser built-in adaptation scheme. As it will be difficult for Web developers that have no RTC expertise to make adaptation algorithms from scratch.

  - Major unresolved issues with or opposition to this design: none

  - This work is being funded by: Google

**Comment by torgo** [comment]
Just one question – it's possible there are no security & privacy issues, but could you note that in the request if that's the case? Thanks.

**Comment by cynthia** [comment]
We discussed this in our call today, and we are happy to see this move forward. Thanks for bringing this to our attention!

**Comment by ylafon** [comment]
As a followup, we also noted that the parameter is not at the ideal place, it would make more sense to have this parameter at the SDP level, and have ways to dynamically change this at the level, but the rationale provided to have it at the encoding level make sense as a practical way to deploy this.
Thanks again.

**Comment by minyuel** [comment]
> Just one question – it's possible there are no security & privacy issues, but could you note that in the request if that's the case? Thanks.

Yes, added to the request. Thanks for mentioning!

> As a followup, we also noted that the parameter is not at the ideal place, it would make more sense to have this parameter at the SDP level, and have ways to dynamically change this at the level, but the rationale provided to have it at the encoding level make sense as a practical way to deploy this.
> Thanks again.

Thanks for the feedback! We considered SDP parameter as an alternative, but we think "the effort of standardizing a new SDP parameter is large. Another drawback is that the SDP negotiation lacks dynamic nature, as it is difficult to re-configure during a call" (as has been written in the explainer: https://w3c.github.io/webrtc-extensions/explainer#a-new-flag-in-rtcrtpencodingparameters-for-adaptive-packet-rate)
