### ISSUE TITLE
Scroll-linked Animations

### ISSUE THREAD

**Issue by majido** [w3ctag/design-reviews#521]
Hello TAG!

I'm requesting a TAG review of Scroll-linked Animations. [Previous design review request](https://github.com/w3ctag/design-reviews/issues/330) for this stalled for lack of an explainer and the specification was less mature at that point. Since then we have moved the specification to be part of CSSWG and it has undergone major changes to ensure it integrates well with web-animations and improve the API ergonomics.

Scroll-linked animations are a common UX pattern on the web. We are proposing a new API that works in conjunction with existing [Web Animations](https://drafts.csswg.org/web-animations/) and [CSS Animations](https://drafts.csswg.org/css-animations/) APIs to enable declarative scroll-linked animations to improve their smoothness and ergonomics. In  Web Animations, an [AnimationTimeline](https://drafts.csswg.org/web-animations/#timelines) is the source of time progress that drives the animations. ScrollTimeline is a new timeline whose function is to translate “changes in scroll position” of an element into “changes in time”. This allows animations to be driven by scrolling as opposed to by wall clock thus taking advantage of all existing animation machinery on the web.

  - Explainer: https://github.com/w3c/csswg-drafts/blob/master/scroll-animations-1/EXPLAINER.md
  - Specification URL: https://drafts.csswg.org/scroll-animations/
  - Tests: [https://github.com/web-platform-tests/wpt/tree/master/scroll-animations](https://github.com/web-platform-tests/wpt/tree/master/scroll-animations)
  - Security and Privacy self-review²: [https://drafts.csswg.org/scroll-animations/#appendix-a-considerations-for-security-and-privacy](https://drafts.csswg.org/scroll-animations/#appendix-a-considerations-for-security-and-privacy)
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/csswg-drafts/
  - Primary contacts (and their relationship to the specification):
      - Brian Birtles (@birtles), Invited Expert
      - Botond Ballo (@theres-waldo), Mozilla
      - Antoine Quint, (@graouts) Apple
      - Majid Valipour (@majido), Google 
      - Olga Gerchikov (@ogerchikov), Microsoft
  - Organization(s)/project(s) driving the specification: CSSWG 
  - Key pieces of existing multi-stakeholder review or discussion of this specification: 
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): 
      - [Mozilla standard positions](https://github.com/mozilla/standards-positions/issues/347)
      - [Chromium status](https://chromestatus.com/feature/6752840701706240)
      - [WebKit-dev thread](https://lists.webkit.org/pipermail/webkit-dev/2020-June/031228.html)

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: 
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): N/A
  - Major unresolved issues with or opposition to this specification: We are working to remove `timeRange` in the timeline and there is [on-going discussions](https://github.com/w3c/csswg-drafts/issues/4862) on how-to achieve that.
  - This work is being funded by: See affiliation of editors.

You should also know that...

We have been working closely with web-animations specification (Brian Birtles is editor in both specification) to ensure the integration makes sense and works as expected. The specification is modest in terms of the usecases it tries to address but our hope is that it can be expanded in future to allow more usecases.

CSS syntax and Element-based offsets sections have been reworked most recently.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by alice** [comment]
Given that one of the use cases this API is explicitly designed to enable is parallax scroll effects, which is a [known trigger for vestibular disorders](https://webkit.org/blog/7551/responsive-design-for-motion/#multi), it might be worth considering how this feature integrates with `prefers-reduced-motion`. 

For example, should animations expressed using this API be disabled by default if `prefers-reduced-motion` would match? And if so, could we design a way to allow animations to express that they are safe to be shown for users who prefer reduced motion?

I think it might even be worth opening a broader discussion on what the default behaviour for `prefers-reduced-motion` should be for all web APIs which allow animation, but I think the question is especially critical for this API given it's even more likely than average to cause harm to users.

**Comment by majido** [comment]
Thanks @alice  for the feedback.  I have filled an issue this in CSSWG and will bring this up with other editors and will get back to you on that.

**Comment by alice** [comment]
We are looking at this again in our virtual face-to-face meeting.

Has there been any further discussion on the interaction of this feature with user preferences to reduce motion to avoid triggering vestibular disorders and other issues?

**Comment by flackr** [comment]
From https://github.com/w3c/csswg-drafts/issues/5321 it sounded like we are leaning in the direction of adding new media query values for better granularity and possibly to continue to allow for a reduce mode where the author is in control of responsibly reducing their animations without browser intervention.

I'm also not sure whether we were settled on this being exclusive to scroll linked animations vs affecting regular animations.

**Comment by LeaVerou** [comment]
Hi @majido,

@atanassov and I discussed this in our virtual f2f today.

We are happy to see the [CSS WG resolution](https://github.com/w3c/csswg-drafts/issues/5321#issuecomment-910924409) that addresses the accessibility concerns. 

Looking at the proposed API, we thought that while referencing elements by explicit id is easy if the scroll-based animation involves e.g. header elements or the root element, it would be quite painful to use it for a collection of elements (e.g. a list of posts, products, places etc). Not only would that require setting individual ids on each one, but also adding a separate `@scroll-timeline` rule for each one even if the animation is exactly the same. Have you explored ways to reference a source element relative to the animation element? (e.g. keywords for common cases, or relative selectors, or `closest()` are some ideas that come to mind)

**Comment by hober** [comment]
Hi @flackr,

> There is a current proposed rethinking of the declarative syntax which makes some of these changes as well as [...]

Oh, thanks for letting us know! We'll hold off on doing a deeper dive until you've decided which direction to go in with the declarative syntax. Could you let us know when to take another look?

**Comment by atanassov** [comment]
Hi @flackr, looking at this issue again, it appears you're all still working on adopting the new syntax proposed by fantasai/Miriam Suzanne. However, none of the CSSWG resolutions seem to have made their way into the spec or your explainer.

Can you update this issue letting us know when it's ready for us to reengage?

**Comment by atanassov** [comment]
We did another pass at this issue during our breakout session. It appears you folks are running on an alternative approach and syntax, which is great given how interesting and valuable this feature is.

From the TAG perspective we can't add much value at this point, thus we're closing the issue and encourage you to open a new one when ready. 

Thank you for working with us. Looking forward to the next round of reviews.
