### ISSUE TITLE
Multi-screen Window Placement features

### ISSUE THREAD

**Issue by michaelwasserman** [w3ctag/design-reviews#522]
Hello TAG!

I'm requesting a TAG review of proposed multi-screen Window Placement features.

[Window Placement](https://github.com/webscreens/window-placement) concerns the creation and movement of windows throughout the set of displays that comprise the overall visual workspace of a device. A brief summary of the active proposal is to support an optional Screen argument in Element.requestFullscreen() and to support multi-screen coordinates in Window.open() and Window.moveTo(). This builds upon the proposed [Screen Enumeration API](https://github.com/webscreens/screen-enumeration) (TAG design review issue [here](https://github.com/w3ctag/design-reviews/issues/413)).

  - Explainer: https://github.com/webscreens/window-placement/blob/master/EXPLAINER.md
  - Security and Privacy self-review: https://github.com/webscreens/window-placement/blob/master/security_and_privacy.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/webscreens/window-placement
  - Primary contacts (and their relationship to the specification):
      - [Mike Wasserman](https://github.com/michaelwasserman): Google, Chromium implementer, explainer editor
      - [W3C Second Screen Community Group](https://github.com/webscreens): incubator
  - Organization/project driving the design: Chromium & W3C Second Screen CG
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): [Chrome Status](https://www.chromestatus.com/feature/5252960583942144), [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=897300)

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): [Second Screen CG](https://github.com/webscreens)
  - The group where standardization of this work is intended to be done: Maybe [Second Screen WG](https://www.w3.org/groups/wg/secondscreen)
  - Existing major pieces of multi-stakeholder review or discussion of this design: [Explainer](https://github.com/webscreens/window-placement/blob/master/EXPLAINER.md) and [Github Issues](https://github.com/webscreens/window-placement/issues)
  - Major unresolved issues with or opposition to this design: None, possible future goals?
  - This work is being funded by: Google, Intel

You should also know that... There's a lot of room for possible future work in this area...

We'd prefer the TAG provide feedback as: (only a slight preference, all modes are okay)
  🐛 open issues in our GitHub repo for **each point of feedback**

Thank you!
Mike

**Comment by kenchris** [comment]
Assigning same people as on the Screen Enumeration as these are tightly coupled

**Comment by michaelwasserman** [comment]
You may wish to consider some [specific questions](https://github.com/w3ctag/design-reviews/issues/413#issuecomment-644546613), listed in the Screen Enumeration review. Thank you!

**Comment by michaelwasserman** [comment]
I believe this is safe to close, as the proposal has been reviewed in #413 
Feel free to reopen or file issues at https://github.com/webscreens/window-placement/issues
