### ISSUE TITLE
MiniApp Manifest

### ISSUE THREAD

**Issue by zhangyongjing** [w3ctag/design-reviews#524]
Hello TAG!

I'm requesting a TAG review of MiniApp Manifest.

[MiniApp Manifest](https://w3c.github.io/miniapp/specs/manifest/) defines a JSON-based profile file that provides developers with a centralized place to put essential information associated with a MiniApp. Such information include the basic metadata of a MiniApp as well as configurations regarding version control, window style, page resources, permission control etc.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/w3c/miniapp/blob/gh-pages/specs/manifest/docs/explainer.md
  - Security and Privacy self-review²: 
https://w3c.github.io/miniapp/specs/manifest/#security-and-privacy-considerations
  - GitHub repo (if you prefer feedback filed there): 
https://github.com/w3c/miniapp/
  - Primary contacts (and their relationship to the specification):
      - [Yongjing Zhang] (zhangyongjing), Huawei 
      - [Zhiqiang Yu] (zhiqiangyu), Huawei
      - [Shouren Lan] (ShourenLan), Huawei
  - Organization/project driving the design: [W3C MiniApps CG](https://www.w3.org/community/miniapps/)
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): n/a

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): [W3C MiniApps CG](https://www.w3.org/community/miniapps/)
  - The group where standardization of this work is intended to be done ("unknown" if not known): W3C MiniApp WG (under preparation)
  - Existing major pieces of multi-stakeholder review or discussion of this design: [Issues](https://github.com/w3c/miniapp/issues?q=is%3Aissue+is%3Aopen+label%3Amanifest)
  - Major unresolved issues with or opposition to this design: n/a
  - This work is being funded by: Huawei

You should also know that...

The attribute list in the MiniApp Manifest would be further extended so as to provide more feature settings of the MiniApp as the project progresses. Other useful attributes from the [Web App Manifest](https://www.w3.org/TR/appmanifest/) may also be mirrored (see [Explainer](https://github.com/w3c/miniapp/blob/gh-pages/specs/manifest/docs/explainer.md)) when the MiniApp community agrees on the necessity. 

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by cynthia** [comment]
Before we get to a full review, why is this intentionally incompatible with Web App Manifest?

**Comment by zhangyongjing** [comment]
> Before we get to a full review, why is this intentionally incompatible with Web App Manifest?

On the contrary, it's intended to be compatible with Web App Manifest, while focusing more on other aspects that are not covered (e.g. UI configuration, version control). Comparison is given in the [Explainer](https://github.com/w3c/miniapp/blob/gh-pages/specs/manifest/docs/explainer.md).

**Comment by cynthia** [comment]
Additional features aside, the names are not compatible according to the explainer.

**Comment by zhangyongjing** [comment]
> Additional features aside, the names are not compatible according to the explainer.

This is can be fixed easily and is under discussion, but it's also subject to the naming convension that the community needs to agree on (e.g. short_name vs shortName).

**Comment by xfq** [comment]
@cynthia See https://github.com/w3c/miniapp/issues/94

**Comment by siusin** [comment]
Follow-up discussions:
* the TAG's suggested to [extend the WebApp Manifest for MiniApps](https://github.com/w3ctag/design-reviews/blob/f4222f34ba73f442b6cbfd853d6ad6db65b0d699/reviews/miniapps_feedback.md)
* MiniApp Virtual Meeting [2020-07-30](https://www.w3.org/2020/07/30-miniapp-minutes.html), [2020-07-31](https://www.w3.org/2020/07/31-miniapp-minutes.html)
* WebApps Manifest & MiniApp Manifest Editors' Meeting [2020-08-26](https://www.w3.org/2020/08/26-manifest-minutes.html)

**Comment by cynthia** [comment]
We were told that this is being re-worked as an extension of Webapp Manifest - we'd like to revisit this review when that work is done. Please let us know when you have an update!

**Comment by zhangyongjing** [comment]
Sure. We'll post the update here once available.

**Comment by xfq** [comment]
The pull request to re-work MAM as an extension of the WAM has been merged. See https://github.com/w3c/miniapp/pull/136

**Comment by cynthia** [comment]
That's great news! Aside from that detail we are happy to see this work move forward.

**Comment by kenchris** [comment]
It seems that it would be great if the keys would follow the TAG guideline for naming, ie use underscope:

**Comment by xfq** [comment]
> It seems that it would be great if the keys would follow the TAG guideline for naming, ie use underscope:

I filed https://github.com/w3c/miniapp/issues/155 to track this.

**Comment by torgo** [comment]
We're going to close this for now and we look forward to reviewing when you have a manifest extension proposal for us to look at.
