### ISSUE TITLE
WebRTC Insertable Streams

### ISSUE THREAD

**Issue by guidou** [w3ctag/design-reviews#531]
Hello TAG!

I'm requesting a TAG review of WebRTC Insertable Streams.

WebRTC Insertable Streams is a proposed API that allows the insertion of user-defined processing steps in the pipeline that handles media in a WebRTC context. It defines a number of extensions to objects defined in [WEBRTC-PC](https://w3c.github.io/webrtc-pc/), and it draws upon some definitions originally proposed for [WEB-CODECS](https://github.com/WICG/web-codecs).

  - Explainer¹: https://github.com/w3c/webrtc-insertable-streams/blob/master/explainer.md
  - Specification URL: https://htmlpreview.github.io/?https://github.com/w3c/webrtc-insertable-streams/blob/master/index.html
  - Tests: 
    * https://github.com/web-platform-tests/wpt/tree/master/webrtc-insertable-streams
    * https://source.chromium.org/search?q=third_party%2Fblink%2Fweb_tests%2Ffast%2Fpeerconnection%2FRTCPeerConnection-insertable-streams*&sq=

  - Security and Privacy self-review²: https://github.com/w3c/webrtc-insertable-streams/blob/master/tag_sp_questionnaire.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/webrtc-insertable-streams (we don't require the feedback there)
  - Primary contacts (and their relationship to the specification):
      - Guido Urdaneta, (@guidou), Google, Chromium implementer, editor (guidou@chromium.org)
      - Harald Alvestrand, (@alvestrand), Google, Chromium implementer, editor (guidou@chromium.org)
  - Organization(s)/project(s) driving the specification: Chromium & W3C WebRTC WG
  - Key pieces of existing multi-stakeholder review or discussion of this specification:  [WebRTC WG Minutes](https://lists.w3.org/Archives/Public/public-webrtc/2020Jun/0011.html), [Github Issues](https://github.com/w3c/webrtc-insertable-streams/issues) 
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): [Chrome Status](https://www.chromestatus.com/feature/6321945865879552), [Github](https://github.com/w3c/webrtc-insertable-streams/issues)

Further details:

  - [X] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the work on this specification is currently being done: [W3C WebRTC Working Group](https://www.w3.org/groups/wg/webrtc)
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): [W3C WebRTC Working Group](https://www.w3.org/groups/wg/webrtc)
  - Major unresolved issues with or opposition to this specification: None for the API itself, but more work needed for future modules (e.g., end-to-end encryption module, support for raw media frames) to better support use cases.
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as (please delete all but the desired option):
  💬 leave review feedback as a **comment in this issue** and @-notify @guidou and @alvestrand

**Comment by guidou** [comment]
cc @alvestrand @dontcallmedom

**Comment by ylafon** [comment]
Hi,
The TAG reviewed this specification this week and is happy with the way it is progressing.
Thank you for asking the TAG for review.

**Comment by jan-ivar** [comment]
Would the TAG like to re-review this in light of https://github.com/w3ctag/design-principles/pull/404?

There are competing implementations over this.
