### ISSUE TITLE
WebAssembly js-types API

### ISSUE THREAD

**Issue by Ms2ger** [w3ctag/design-reviews#532]
Saluton TAG!

I'm requesting a TAG review of the WebAssembly js-types API.

WebAssembly is typed, and its types carry information that can be useful and important to clients interacting with WebAssembly modules and objects through the JS API. For example, types describe the form of imports and exports, including the size limits of memories and tables or the mutability of globals. This proposal adds respective functionality to the WebAssembly JS API in a systematic manner.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/WebAssembly/js-types/blob/master/proposals/js-types/Overview.md
  - Security and Privacy self-review²: N/A
  - GitHub repo (if you prefer feedback filed there): https://github.com/WebAssembly/js-types/
  - Primary contacts (and their relationship to the specification):
      - @Ms2ger, Igalia, editor
      - Till Schneidereit (@tschneidereit), Mozilla, official champion
      - Clemens Backes (@backes), Google, champion
  - Organization/project driving the design: WebAssembly CG
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): [issue tracker](https://github.com/WebAssembly/js-types/issues/)

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): WebAssembly CG
  - The group where standardization of this work is intended to be done ("unknown" if not known): WebAssembly WG
  - Existing major pieces of multi-stakeholder review or discussion of this design: not aware of any
  - Major unresolved issues with or opposition to this design: [Design of `WebAssembly.Function`](https://github.com/WebAssembly/js-types/issues/16).
  - This work is being funded by: Igalia

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by Ms2ger** [comment]
Fwiw, Igalia is currently implementing in SpiderMonkey and will likely start on implementing in JSC soon. Feedback soon would be very welcome.

**Comment by kenchris** [comment]
```
function print(...args) {
  for (let x of args) console.log(x + "\n")
}

let table = new Table({element: "anyfunc", minimum: 10});

let print_i32 = new WebAssembly.Function({parameters: ["i32"], results: []}, print);
table.set(0, print_i32);
let print_f64 = new WebAssembly.Function({parameters: ["f64"], results: []}, print);
table.set(1, print_f64);
let print_i32_i32 = new WebAssembly.Function({parameters: ["i32", "i32"], results: []}, print);
table.set(2, print_i32_i32);
```

In the above example where  you are exporting a JS function to Wasm, wouldn't it makes sense it I could supply meta data (in the `WebAssembly.Function` call) that would be given to the `print` method when run?

**Comment by hober** [comment]
This [first example](https://github.com/WebAssembly/js-types/blob/master/proposals/js-types/Overview.md#example) seems awfully convoluted. Is there also a higher-level API that does some of this work for you? If we can't improve upon what Emscripten already does for people, why will they bother to switch?

**Comment by kenchris** [comment]
> The WebAssembly.imports() function returns an array containing descriptions of all the declared imports of the given Module.

I found it quite confusing that imports is actually returning a description and not doing any importing.

**Comment by hober** [comment]
@Ms2ger, any thoughts on the observations @kenchris & I made in September?

**Comment by hober** [comment]
Hi @Ms2ger,

We're closing this issue due to the lack of response here & in WebAssembly/js-types#26. If you come back to this project at some point and would like us to revisit, we'd be happy to reopen this, or you could file a new request.

**Comment by Ms2ger** [comment]
@hober apologies for my lack of availability here - I'm hoping to get back to this next year.
