### ISSUE TITLE
Storage Pressure Event

### ISSUE THREAD

**Issue by jarryd999** [w3ctag/design-reviews#533]
Saluton TAG!

I'm requesting a TAG review of the Storage Pressure Event.

This proposal aims to provide an early warning when the storage device backing the user's data is running low on free space. This warning is provided to currently running applications, which can pause or abandon in-progress operations that would otherwise fill up the user's storage device.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/jarryd999/Storage-Pressure-Event
  - Security and Privacy self-review²: https://github.com/jarryd999/Storage-Pressure-Event/blob/master/tag_sp_questionnaire.md
  - GitHub repo (if you prefer feedback filed there):
  - Primary contacts (and their relationship to the specification):
      - [Jarryd Goodman](https://github.com/jarryd999), Google, Chromium implementer
      - [Marijn Kruisselbrink](https://github.com/mkruisselbrink), Google, Chromium implementer
      - [Victor Costan](https://github.com/pwnall), Google, Chromium implementer
  - Organization/project driving the design: Chromium
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status):
     - [Chrome Status](https://chromestatus.com/feature/5666274359115776)
     - [Tracking bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1088004)

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): wicg
  - The group where standardization of this work is intended to be done ("unknown" if not known): whatwg
  - Existing major pieces of multi-stakeholder review or discussion of this design: https://github.com/whatwg/storage/issues/73
  - Major unresolved issues with or opposition to this design: Figure out heuristics for when and how to dispatch these events in a manner that doesn't cause privacy issues.
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as (only slight preference):

  🐛 open issues in our GitHub repo for **each point of feedback**

Thank you,
Jarryd

**Comment by hober** [comment]
@dbaron and I took a look at this during our virtual F2F this week. We'll file issues as we go. There was already an issue for the first thing I noticed, jarryd999/storage-pressure-event#6.

**Comment by dbaron** [comment]
After looking at this issue again today, we're happy closing this issue.  It looks like you've thought a lot about the issues here (and it seems like it's the result of a chain of other issues that have already been dealt with).  It doesn't seem like we're going to have a lot to add; the analysis and discussion that's happening or already happened seems to have been surfacing a bunch of important things things.  So, in other words, keep worrying about the things you're worrying about, and thanks for requesting review from the TAG.
