### ISSUE TITLE
Pointer Events Azimuth Angle and Altitude Angle

### ISSUE THREAD

**Issue by liviutinta** [w3ctag/design-reviews#537]
Saluton TAG!

I'm requesting a TAG review of Pointer Events Azimuth Angle and Altitude Angle.

Currently Pointer Events captures pen inclination by using tiltX (tiltX) and tiltY (tiltY) angles - angles measured from two axes. This proposal is to add altitude and azimuth angles to Pointer Events and to allow user agents to transform from one set of digital pen inclination coordinates to the other automatically thus making both pairs of angles available to developers at the same time.

  - Explainer¹ (minimally containing user needs and example code): https://docs.google.com/document/d/1BkJDlHJvR6jndtJys7IYuqwITgVi6P9iOnfA0z5Cu04/edit#
  - Specification URL: https://w3c.github.io/pointerevents/#dom-pointerevent-altitudeangle
  - Tests: there are web platform tests, not available on [wpt.fyi](https://wpt.fyi/) yet as the code is in the latest stages of code review/approval
  - Security and Privacy self-review²: N/A
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/pointerevents
  - Primary contacts (and their relationship to the specification):
      - Liviu Tinta (@liviutinta), Google
      - Mustaq Ahmed, (@mustaqahmed), Google
      - Navid Zolghadr, (@NavidZ), Google, Pointer Events editor
  - Organization(s)/project(s) driving the specification: Google 
  - Key pieces of existing multi-stakeholder review or discussion of this specification: [PE Issue 321](https://github.com/w3c/pointerevents/issues/321), [PE Issue 320](https://github.com/w3c/pointerevents/issues/320), [PE Issue 274](https://github.com/w3c/pointerevents/issues/274), [PE PR 316](https://github.com/w3c/pointerevents/pull/316), [PE PR 322](https://github.com/w3c/pointerevents/pull/322), [PE PR 323](https://github.com/w3c/pointerevents/pull/323), [PEWG minutes](https://www.w3.org/2020/05/27-pointerevents-minutes.html)  
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://www.chromestatus.com/feature/5731966710185984

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: [please provide]
  - The group where the work on this specification is currently being done: Pointer Events Working Group
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): Pointer Events Working Group
  - Major unresolved issues with or opposition to this specification: N/A 
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as (please delete all but the desired option):
  ☂️ open a single issue in our GitHub repo **for the entire review**

**Comment by hober** [comment]
Hi @liviutinta,

Thank you for your patience while we've had this review open. We've discussed this change and overall we're very happy with it. For many applications, the new values you've added are closer to what the developer needs, so she can do less math, write less code, and (hopefully) cause fewer bugs. And providing both types of values ensures back compat.
