### ISSUE TITLE
MediaStreamTrack Content Hints

### ISSUE THREAD

**Issue by caribouW3** [w3ctag/design-reviews#539]
Saluton TAG!

I'm requesting a TAG review of MediaStreamTrack Content Hint.

This specification extends MediaStreamTrack to provide a media-content hint attribute. This optional hint permits MediaStreamTrack consumers such as PeerConnection (defined in [webrtc]) or MediaRecorder (defined in [mediastream-recording]) to encode or process track media with methods more appropriate to the type of content that is being consumed.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/w3c/mst-content-hint/blob/gh-pages/explainer.md
  - Specification URL:  https://www.w3.org/TR/2020/WD-mst-content-hint-20200728/
  - Tests: [wpt folder(s), if available] https://github.com/web-platform-tests/wpt/tree/master/mst-content-hint
  - Security and Privacy self-review²: https://github.com/w3c/mst-content-hint/blob/gh-pages/security-privacy-questionnaire.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/mst-content-hint/
  - Primary contacts (and their relationship to the specification):
      - @alvestrand, @caribouW3
  - Organization(s)/project(s) driving the specification: W3C WebRTC Working Group
Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: ideally by september, no hard deadline set
  - The group where the work on this specification is currently being done: WebRTC WG
 
  - Major unresolved issues with or opposition to this specification: none
We'd prefer the TAG provide feedback as (please delete all but the desired option):

  ☂️ open a single issue in our GitHub repo **for the entire review**

**Comment by kenchris** [comment]
Our style guide says that string enums should be lowercase and with hyphen, thus "speechRecognition" should be "speech-recognition": https://w3ctag.github.io/design-principles/#casing-rules

**Comment by cynthia** [comment]
Why are arbitrary values (anything aside from well-known values or "", since on the surface it is a DOMString property) disallowed for hints? (Wasn't quite clear from the spec; is it because internally [e.g. during transport] these values are encoded into enums?)

**Comment by kenchris** [comment]
Apart from the filed issues, we are fine with this. Closing.

Thanks for staying at home with the TAG :-)
