### ISSUE TITLE
Screen Wake Lock API

### ISSUE THREAD

**Issue by xfq** [w3ctag/design-reviews#543]
Saluton TAG!

I'm requesting a TAG review of [Screen Wake Lock API](https://w3c.github.io/screen-wake-lock/).

This document specifies an API that allows web applications to request a screen wake lock. Under the right conditions, and if allowed, the screen wake lock prevents the system from turning off a device's screen.

  - Specification URL: https://w3c.github.io/screen-wake-lock/
  - Explainer: https://github.com/w3c/screen-wake-lock/blob/gh-pages/explainer.md
  - Tests: https://github.com/web-platform-tests/wpt/tree/master/screen-wake-lock
  - Security and Privacy self-review: https://w3c.github.io/screen-wake-lock/#security-and-privacy-considerations
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/screen-wake-lock
  - Primary contacts (and their relationship to the specification):
      - Anssi Kostiainen (@anssiko), Intel
      - Fuqiao Xue (@xfq), W3C
      - Reilly Grant (@reillyeon), Google
  - Organization(s)/project(s) driving the specification: Intel, Mozilla
  - Key pieces of existing multi-stakeholder review or discussion of this specification: https://github.com/w3ctag/design-reviews/issues/32

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the work on this specification is currently being done: [W3C DAS WG](https://www.w3.org/das/)
  - Major unresolved issues with or opposition to this specification:
  - This work is being funded by: 

You should also know that...

Changes since the last CR: https://w3c.github.io/screen-wake-lock/#changes-20171214

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  ☂️ open a single issue in our GitHub repo **for the entire review**

**Comment by alice** [comment]
Could you comment as to why there is no explainer for this API?

**Comment by kenchris** [comment]
https://github.com/w3c/screen-wake-lock/issues/284

**Comment by rakuco** [comment]
Hi, everyone. FYI, the PR above was merged earlier today and we now have an [explainer](https://github.com/w3c/screen-wake-lock/blob/gh-pages/explainer.md) in the repository.

**Comment by alice** [comment]
Thank you! I added it to the top comment as well.

**Comment by alice** [comment]
That explainer does what the name implies, thanks so much for your effort there.

@cynthia and I are both happy with this.

My only feedback would be that it would be nice to see a note explaining why you need to pass `"screen"` to `WakeLock.request()` when it's the only possible value - my guess would be that there is an intent to re-use this API for the future System Wake Lock API, but it would be good to be clear on that. Also, a link out to discussion of that API might also be useful context.

**Comment by rakuco** [comment]
> My only feedback would be that it would be nice to see a note explaining why you need to pass `"screen"` to `WakeLock.request()` when it's the only possible value - my guess would be that there is an intent to re-use this API for the future System Wake Lock API, but it would be good to be clear on that. Also, a link out to discussion of that API might also be useful context.

Thanks, I've sent w3c/screen-wake-lock#288 to tackle this one.

**Comment by cynthia** [comment]
We noticed that the issue has been resolved on your end. Thanks! We're happy to see this move forward.
