### ISSUE TITLE
PWAs as URL Handlers

### ISSUE THREAD

**Issue by LuHuangMSFT** [w3ctag/design-reviews#552]
Saluton TAG!

I'm requesting a TAG review of _Progressive Web Apps as URL Handlers_.

"Native applications on many operating systems (Windows, Android, iOS, MacOS) can be associated with http(s) URLs. They can request to be launched as URL handlers when associated URLs are activated. For example, a user could click on a link to a news story from an e-mail. An associated native app for viewing news stories would automatically be launched to handle the activation of the link. Web developers would be able to build more compelling PWA experiences with stronger user engagement if PWAs could request to be URL handlers through their web app manifests."

  - Explainer¹ [https://github.com/WICG/pwa-url-handler/blob/master/explainer.md](https://github.com/WICG/pwa-url-handler/blob/master/explainer.md)
  - Security and Privacy self-review²: [https://github.com/WICG/pwa-url-handler/blob/master/PRIVACY_AND_SECURITY.md](https://github.com/WICG/pwa-url-handler/blob/master/PRIVACY_AND_SECURITY.md)
  - GitHub repo (if you prefer feedback filed there): [https://github.com/WICG/pwa-url-handler](https://github.com/WICG/pwa-url-handler)
  - Primary contacts (and their relationship to the specification):
      - Lu Huang (luhuangMSFT), Microsoft
  - Organization/project driving the design: Microsoft 
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): [https://www.chromestatus.com/feature/5739732661174272](https://www.chromestatus.com/feature/5739732661174272)

Further details:

  - [X] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): WICG
  - The group where standardization of this work is intended to be done ("unknown" if not known): Web Applications Working Group
  - Existing major pieces of multi-stakeholder review or discussion of this design: [Github issues](https://github.com/WICG/pwa-url-handler/issues)
  - Major unresolved issues with or opposition to this design: [compatibility with Declarative Link Capturing proposal](https://github.com/WICG/pwa-url-handler/issues/11)
  - This work is being funded by: Microsoft

You should also know that...

We'd prefer the TAG provide feedback as (please delete all but the desired option):
🐛 open issues in our GitHub repo for each point of feedback

**Comment by kenchris** [comment]
@marcoscaceres @anssiko you probably want to have a look at this

**Comment by kenchris** [comment]
I got a bit confused by

```
            "exclude_paths": [
                "/only/for/partnerapp/*"
            ]
```

Does this mean that the partnerapp (in this case) cannot be developed as a PWA?

**Comment by LuHuangMSFT** [comment]
@kenchris Thanks for asking. That exclude pattern says that the app at https://contoso.com/manifest.json has permission to capture all paths except for paths matching "/only/for/partnerapp/*", i.e. "https://tenant.contoso.com/only/for/partnerapp/*". There is no special significance to that particular path pattern. I just wanted to illustrate that the origin may want to allocate URLs to be handled by different apps.

There's no reason why https://tenant.contoso.com/only/for/partnerapp/ cannot itself be the scope of a PWA (although the origin would then probably not want to allow other apps to handle those URLs). There is also no reason why the PWA at https://partnerapp.com/manifest.json would be hampered.

**Comment by LuHuangMSFT** [comment]
Quick fyi for visibility: I just merged a small PR to the explainer which mainly adjusted the manifest and association file JSON format for this feature. 
https://github.com/WICG/pwa-url-handler/pull/17

**Comment by kenchris** [comment]
I think it makes sense to use the pattern from https://github.com/WICG/urlpattern/blob/master/explainer.md for this @wanderview
Latest commit 23f4f45 on Sep 9, 2020

**Comment by wanderview** [comment]
FWIW I suggested that in https://github.com/WICG/pwa-url-handler/issues/21.

**Comment by kenchris** [comment]
"There is one use case that we wish to address in this explainer: URL activation in native applications."

I think this should also work for installed web applications such as Progressive Web Apps if the URL is out of scope

**Comment by ylafon** [comment]
Also, the goals seems to be matching what the [MiniApp WG](https://www.w3.org/2021/miniapps/) wants to define, I suggest discussing with them as well (ping @xfq)

**Comment by LuHuangMSFT** [comment]
> I think it makes sense to use the pattern from https://github.com/WICG/urlpattern/blob/master/explainer.md for this
I'll open a PR to edit the explainer so we can see what it looks like using URLPattern. 

> I think this should also work for installed web applications such as Progressive Web Apps if the URL is out of scope
I think `url_handlers` and `web-app-origin-association` is able to support this. However, I think this behavior falls under navigation capture and would like to see the in-scope version of it enabled with [Declarative Link Capturing](https://github.com/WICG/sw-launch/blob/master/declarative_link_capturing.md) first.

> Also, the goals seems to be matching what the MiniApp WG wants to define, I suggest discussing with them as well
Thanks for the connect. I'll review the group charter and docs.

**Comment by kenchris** [comment]
Hi there, how does this relate to https://github.com/WICG/manifest-incubations/blob/gh-pages/scope_extensions-explainer.md

**Comment by atanassov** [comment]
We took another look this during our Gethen vf2f plenary. At this point we are closing this review since it has been already overtaken by the new work on scope extensions. Thank you for working with us. We look forward to reviewing the new proposal.
