### ISSUE TITLE
Formal Review Request for css-cascade-3

### ISSUE THREAD

**Issue by fantasai** [w3ctag/design-reviews#555]
Since CSS Cascading and Inheritance Level 3 entered CR more than 2 years ago (in 2015), the Director has asked for a re-review by all HRGs prior to transitioning to PR. Thus, the CSSWG requests formal review of css-cascade-3.

Cascading and Inheritance describes how the UA collates CSS style rules and assigns values to all properties on all elements. See
  https://www.w3.org/TR/css-cascade-3/

The new features added by this specification (since CSS2) are listed in
  https://www.w3.org/TR/css-cascade-3/#changes-2
and consist solely of:
  * the 'all' shorthand
      https://www.w3.org/TR/css-cascade-3/#all-shorthand
  * the 'initial' keyword
      https://www.w3.org/TR/css-cascade-3/#initial
  * the 'unset' keyword
      https://www.w3.org/TR/css-cascade-3/#inherit-initial
  * incorporation of animations and transitions into the cascade
      https://www.w3.org/TR/css-cascade-3/#cascade-sort

The implementation report is here:
  https://drafts.csswg.org/css-cascade-3/implementation-report

The Privacy and Security Considerations section is here:
  https://www.w3.org/TR/css-cascade-3/#priv-sec

Please file any specific issues, separately per point of feedback, in https://github.com/w3c/csswg-drafts/issues and if there are none, please explicitly indicate completion of the review.

Thanks~
~fantasai

**Comment by atanassov** [comment]
@plinss and myself reviewed the request during our Cork virtual f2f and 

The disposition of comment, implementation report and privacy/security template all look great. Please go ahead and publish.
