### ISSUE TITLE
Review for CSS property "aspect-ratio"

### ISSUE THREAD

**Issue by cbiesinger** [w3ctag/design-reviews#559]
Saluton TAG!

I'm requesting a TAG review of the aspect-ratio CSS property.

[One paragraph summary of idea, ideally copy-pasted from Explainer introduction]

  - Explainer¹ (minimally containing user needs and example code): https://docs.google.com/document/d/1VqD0mfkIDyCxQBrrvDw5wEbhXBsmEYIhk6ahiX_fvco/edit#
  - Specification URL: https://drafts.csswg.org/css-sizing-4/#aspect-ratio
  - Tests: https://wpt.fyi/results/css/css-sizing/aspect-ratio?label=experimental&label=master&aligned
  - Security and Privacy self-review²: n/a, this only affects sizing of elements
  - GitHub repo (if you prefer feedback filed there): n/a (or https://github.com/w3c/csswg-drafts/issues)
  - Primary contacts (and their relationship to the specification):
      - Tab Atkins (@tabatkins), Google LLC, Editor
      - Elika Etemad (@fantasai), n/a (Editor)
      - Jen Simmons (@jensimmons), Apple (previously at Mozilla)
      -  Christian Biesinger (@cbiesinger), Google LLC (implementor)
  - Organization(s)/project(s) driving the specification: CSSWG and Google LLC
  - Key pieces of existing multi-stakeholder review or discussion of this specification: The CSSWG has been involved in discussing this spec, including people from Mozilla and Google. Mozilla and Google are currently implementing.
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://www.chromestatus.com/feature/5738050678161408

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: Preferably in the next couple weeks, we'd like to ship soon. Sorry I didn't file this sooner.
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): CSSWG
  - Major unresolved issues with or opposition to this specification: none
  - This work is being funded by: Google

You should also know that...

This form feels overly complex for one fairly straightforward CSS property.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @cbiesinger @chrishtr

**Comment by chrishtr** [comment]
Please also include review of the [interpolation curve for animations of aspect ratios](https://github.com/w3c/csswg-drafts/issues/4953#issuecomment-722054926).

**Comment by hober** [comment]
Hi,

> * Explainer¹ (minimally containing user needs and example code): https://docs.google.com/document/d/1VqD0mfkIDyCxQBrrvDw5wEbhXBsmEYIhk6ahiX_fvco/edit#

We generally recommend that folks make their explainers available in plain text, Markdown or HTML; Google Docs is not globally accessible to web standards contributors.

**Comment by hober** [comment]
@LeaVerou and I looked at this during a breakout of our vF2F today, and we're happy with where the interpolation issue ended up in https://github.com/w3c/csswg-drafts/commit/a898cb0d6110b5c4ac20c1c63228e4c9c936d779 and https://github.com/w3c/csswg-drafts/commit/84a573d49fed1499efe44a065a36763a7acaaee7

**Comment by cbiesinger** [comment]
> Hi,
> 
> > * Explainer¹ (minimally containing user needs and example code): https://docs.google.com/document/d/1VqD0mfkIDyCxQBrrvDw5wEbhXBsmEYIhk6ahiX_fvco/edit#
> 
> We generally recommend that folks make their explainers available in plain text, Markdown or HTML; Google Docs is not globally accessible to web standards contributors.

IMO an explainer for this property is not necessary. Also I don't have a good place to host Markdown/HTML docs.

**Comment by cbiesinger** [comment]
See also related HTML changes:
https://github.com/whatwg/html/pull/6032
https://github.com/whatwg/html/pull/5894

**Comment by LeaVerou** [comment]
As previously stated, we are happy with the current state. In a breakout today, we resolved to close this issue, and will continue to monitor open issues.

There is a meta-issue about explainers which we noticed is present in many CSS WG review requests. Please include an explainer in Markdown, HTML, or plain text with all design review requests. We are going to modify our explainer explainer to clarify this further (per https://github.com/w3ctag/w3ctag.github.io/issues/30 ).
