### ISSUE TITLE
WebRTC Priority Control API

### ISSUE THREAD

**Issue by caribouW3** [w3ctag/design-reviews#560]
Saluton TAG!

I'm requesting a TAG review of the WebRTC Priority Control API.

(Note: discussion had started in https://github.com/w3ctag/design-reviews/issues/465)

This API defines a control surface for manipulating the network control bits (DSCP bits) of outgoing WebRTC packets, and the queueing priority of outgoing WebRTC packets under congestion.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/w3c/webrtc-priority/blob/master/explainer.md
  - Specification URL: https://www.w3.org/TR/2020/WD-webrtc-priority-20200922/
  - Tests: https://github.com/web-platform-tests/wpt/tree/master/webrtc-priority
  - Security and Privacy self-review²: https://github.com/w3c/webrtc-priority/blob/master/security-privacy-questionnaire.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/webrtc-priority
  - Primary contacts (and their relationship to the specification):
      @alvestrand, @caribouW3
  - Organization(s)/project(s) driving the specification: WebRTC WG
  - Key pieces of existing multi-stakeholder review or discussion of this specification: 
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: 
  - The group where the work on this specification is currently being done:
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): WebRTC WG (also in relation to IETF work)
  - Major unresolved issues with or opposition to this specification:
  - This work is being funded by: 

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  ☂️ open a single issue in our GitHub repo **for the entire review**

**Comment by torgo** [comment]
Hi @caribouW3 – can you provide a little more detail in the explainer? In particular, an articulated "user need" e.g. "this will make WebRTC user experience better by xxx" and more of a description of what is therefore proposed?

**Comment by alvestrand** [comment]
hi @torgo and apologies for a slow response - I am reading through the first 4 paragraphs of https://github.com/w3c/webrtc-priority/blob/master/explainer.md and scratching my head about how to do better - those 4 paragraphs lay out:

- Why prioritization is needed (need)
- Why the user wants to prioritize some streams over others (user need)
- Why there needs to be both local prioritization and network prioritization
- That this specification gives a means to control that. (what is proposed)

Looking at your question - could you go into a little more detail about why those 4 paragraphs fail to communicate with you?

**Comment by alvestrand** [comment]
ping @torgo - still don't know how to address this issue.

**Comment by ylafon** [comment]
After reviewing this with @cynthia , it sounds good to us (provided the sound track has proper priority).
Thanks!
