### ISSUE TITLE
APA Pronunciation Explainer

### ISSUE THREAD

**Issue by alice** [w3ctag/design-reviews#561]
HIQaH! QaH! TAG!

I'm requesting a TAG review of APA Pronunciation Explainer on behalf of the Pronunciation Task Force. This issue is just to ensure we schedule time to discuss this, and to track our thoughts on it.

... a standard mechanism to allow content authors to include spoken presentation guidance in HTML content. Also, [...] two identified approaches and enumerates their advantages and disadvantages.

  - Explainer¹ (minimally containing user needs and example code): https://w3c.github.io/pronunciation/explainer/
  - Security and Privacy self-review²: n/a
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/pronunciation
  - Organization/project driving the design: W3C Pronunciation TF

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue**

**Comment by hober** [comment]
We had a joint meeting with APA about this during TPAC. I'm not sure how to find the minutes from that meeting—I'll keep looking—but it was a very productive hour IIRC, and I don't think there's much left to be done on our part. We should consider closing this issue once I've linked the minutes from here.

**Comment by hober** [comment]
[Minutes](https://www.w3.org/2020/10/16-apa-minutes.html)

> Janina: what might our next steps be?
>
> Rossen: One clear action is to engage with the community that works on digital assistants and similar devices and guage their interest in the space. This should provide a lot of additional prior art and/or opinions, and could generate a lot of interest.
>
> Janina: Sounds good
> ... summary: there are challenges but also opportunities; important to bring the wider community along.

**Comment by alice** [comment]
As @hober mentioned above, we gave feedback on this directly at TPAC last year. We are expecting the proposal will likely change shape as a result of that proposal, so we're going to close this review for now and look forward to either re-opening that review or receiving a new review request once that process has completed.

Thank you for working with us!
