### ISSUE TITLE
Byte Streams 

### ISSUE THREAD

**Issue by nidhijaju** [w3ctag/design-reviews#567]
HIQaH! QaH! TAG!

I'm requesting a TAG review of byte streams.

The streams APIs provide ubiquitous, interoperable primitives for creating, composing, and consuming streams of data. For streams representing bytes, readable byte streams are an extended version of readable streams which are provided to handle bytes efficiently, in particular by minimizing copies.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/whatwg/streams/blob/master/byte-streams-explainer.md
  - Specification URL: https://streams.spec.whatwg.org/
    Specific Sections: 
    - https://streams.spec.whatwg.org/#readable-byte-stream
    - https://streams.spec.whatwg.org/#byob-reader-class
    - https://streams.spec.whatwg.org/#rbs-controller-class
    - https://streams.spec.whatwg.org/#rs-byob-request-class
  - Tests: https://github.com/web-platform-tests/wpt/tree/master/streams/readable-byte-streams
  - Security and Privacy self-review²: https://docs.google.com/document/d/15nhR1drg4qEip041RcBFWEFbDjv-5EJc-zsgaON49Zo/view
  - GitHub repo (if you prefer feedback filed there): https://github.com/whatwg/streams
  - Primary contacts (and their relationship to the specification):
    - Nidhi Jaju (nidhijaju), [Google]
    - Adam Rice (ricea), [Google], Spec Editor
    - Yutaka Hirano (yutakahirano), [Google], Spec Contributor
    - Domenic Denicola (domenic), [Google], Spec Editor
  - Organization(s)/project(s) driving the specification: WHATWG
  - Key pieces of existing multi-stakeholder review or discussion of this specification: https://github.com/whatwg/streams/issues/300, https://github.com/whatwg/streams/pull/430
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://chromestatus.com/features/4535319661641728

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: No specific deadlines.
  - The group where the work on this specification is currently being done: WHATWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): WHATWG
  - Major unresolved issues with or opposition to this specification: N/A
  - This work is being funded by: Google

You should also know that...

N/A

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by atanassov** [comment]
@nidhijaju a few of us are looking at your Explainer during our breakout session today. It would be helpful to provide a bit more information so we can engage more efficiently and make progress. In particular - what are your explicit goals and non-goals of the feature? What other options have you considered when choosing the API? What is the exact API that you're proposing? Thanks.

**Comment by nidhijaju** [comment]
Hi @atanassov, I have updated the explainer based on the questions you asked, so hopefully that helps provide some more clarification. Please let me know if there's anything else that you might need. Thank you!

**Comment by hadleybeeman** [comment]
Hi @nidhijaju. We're looking at this in a breakout session. Could you please spell out the user benefit or user needs in your explainer? (This is for the end user, rather than the developer.) For example, if it's all about making things faster, that's worth making explicit — and also specifying what 'things' you have in mind there. Many thanks!

**Comment by nidhijaju** [comment]
Hi @hadleybeeman, the end-user benefit is that it will increase speed and lower memory usage for sites that take advantage of it. Specifically, sites that handle streaming binary data will see improved performance. I've also updated the explainer with this information, so hopefully that helps answer your question. Thank you!

**Comment by kenchris** [comment]
Hi @annevk and @jakearchibald - it would be great with your knowledge, feedback and potential concerns about this proposal.

**Comment by torgo** [comment]
Hi @nidhijaju - and happy new year! We're just picking this up again. You mentioned a couple of WHATWG threads in response to the question on mutli-stakeholder feedback, however I don't see any obvious evidence of multiple implementations there. Is there for example a Mozilla standards position on this?

**Comment by annevk** [comment]
No concerns here. This has been part of the Streams standard for a long time and it was always part of the goals to provide performant I/O streams that integrate well with Typed Arrays. (See https://github.com/mozilla/standards-positions/issues/457 and https://github.com/mozilla/standards-positions/pull/464 for Mozilla's position.)

**Comment by jakearchibald** [comment]
Seconded!

**Comment by ricea** [comment]
@torgo Chrome's is the first browser implementation, however there is an independent TypeScript implementation here: https://github.com/MattiasBuelens/web-streams-polyfill/tree/master/src/lib/readable-stream.

**Comment by ylafon** [comment]
Not a fan of mixing higher level APIs and low-level optimisations, would prefer to have optimisation hints for the VM instead to make it more efficient, but as this API will only be used by people needing it right now...

**Comment by annevk** [comment]
I think it's the ~ same as why we have Array and ArrayBuffer. VMs can do a lot, but for certain performance needs they need help.
