### ISSUE TITLE
Adding AbortSignal option to addEventListener

### ISSUE THREAD

**Issue by josepharhar** [w3ctag/design-reviews#569]
HIQaH! QaH! TAG!

I'm requesting a TAG review of Adding AbortSignal option to addEventListener.

This feature adds a new AbortSignal option, named "signal", to the options parameter of addEventListener.
This new option can be used to remove the event listener with an AbortController by calling abort().
More context: https://github.com/whatwg/dom/issues/911

  - Explainer¹ (minimally containing user needs and example code): none
  - Security and Privacy self-review²: none
  - GitHub repo (if you prefer feedback filed there): none
  - Primary contacts (and their relationship to the specification):
      - Joey Arhar (@josepharhar) Google
      - @benjamingr NodeJS
  - Organization/project driving the design: Google? NodeJS?
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5658622220566528

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): unsure
  - The group where standardization of this work is intended to be done ("unknown" if not known): WHATWG
  - Existing major pieces of multi-stakeholder review or discussion of this design: https://github.com/whatwg/dom/issues/911
  - Major unresolved issues with or opposition to this design: none
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @josepharhar

**Comment by josepharhar** [comment]
This has already been [added to the spec](https://github.com/whatwg/dom/pull/919) and has been implemented in firefox, chrome, and safari

**Comment by kenchris** [comment]
@LeaVerou @cynthia and I looked at this in our TAG Virtual F2F and it looks very sensible and like a nice addition!
