### ISSUE TITLE
DOM Review Draft — Published 15 June 2020

### ISSUE THREAD

**Issue by siusin** [w3ctag/design-reviews#573]
HIQaH! QaH! TAG!

I'm requesting a TAG review of DOM Review Draft — Published 15 June 2020.

The WHATWG published a [new Review Draft of the DOM Standard](https://dom.spec.whatwg.org/review-drafts/2020-06/) on 15 June 2020. The HTML WG plans to take this Review Draft to W3C Recommendation in 2021, thus we are inviting another wide and horizontal review of the commits of the DOM Standard between [19 June 2019 (b5eac4d) and 15 June 2020 (ad06a4c)](https://github.com/whatwg/dom/commits/master?before=ad06a4c686a62a2a0f175125932200930364c170+35).

  - Specification URL: https://dom.spec.whatwg.org/review-drafts/2020-06/
  - Tests: https://github.com/web-platform-tests/wpt/tree/master/dom
  - GitHub repo (if you prefer feedback filed there): https://github.com/whatwg/dom
  - Primary contacts (and their relationship to the specification):
      - @hober , HTML WG co-chair
      - @sideshowbarker 
      - WHATWG HTML editors
  - Organization(s)/project(s) driving the specification: WHATWG and W3C
  - Key pieces of existing multi-stakeholder review or discussion of this specification: 
      - [Declarative Shadow DOM](https://github.com/w3ctag/design-reviews/issues/494)

Further details:

  - Relevant time constraints or deadlines: 29 Dec 2020
  - The group where the work on this specification is currently being done: WHATWG and W3C HTML WG

You should also know that...

We put together a list of significant changes for each horizontal review group. Please note that the classification is only an attempt to help quickly go through the changes, if possible, please look at all of the commits:
   https://github.com/w3c/htmlwg/issues/14#issuecomment-728034670

* [Define ParentNode's replaceChildren()](https://github.com/whatwg/dom/commit/3a11492f09212c944a1b495c47ce3c850136b296)
* [Avoid enqueuing a tree mutation record when there is no mutation](https://github.com/whatwg/dom/commit/d4535b467b793d450c1fb3e61d4956503b6a2515)
* [Use self.origin instead of document.origin](https://github.com/whatwg/dom/commit/55379a77690afcc656728179d4e828373952c870)
* [Replace child text content change steps](https://github.com/whatwg/dom/commit/ce4c6ba5b6e8e26e9c0e6f157243df9942d8b52a)
* [Address infinite loop in TreeWalker's nextNode()](https://github.com/whatwg/dom/commit/868f1734717c791261e75687ba3ce12bfedfae8e)
* [Change add/remove event listener behavior for service workers](https://github.com/whatwg/dom/commit/7a48d64b41c586afc2e57d25eab99e8cfba5de1a)
* [Define the onabort event handler IDL attribute](https://github.com/whatwg/dom/commit/e017c7ad4c24d9870f4029564d820243d90cf4c6)
* [Add the DOM XPath interfaces](https://github.com/whatwg/dom/commit/dea5d92156f144faf57d1a5e54a17227139ca3c5)
* [Add StaticRange constructor](https://github.com/whatwg/dom/commit/a93f9f8be626740f6ac4a459bfb28322e27646d1)

#### WebComponents
* [Catch errors while upgrading customized built-in elements](https://github.com/whatwg/dom/commit/543b7e33487be5e733b0a715eaf71d027e354a50)
* [Avoid enqueuing "disconnectedCallback" on detached custom elements](https://github.com/whatwg/dom/commit/de29633694822f4fd0bab61a2d142de2298dc88b)
* [Add delegatesFocus to attachShadow and flag to ShadowRoot](https://github.com/whatwg/dom/commit/4cf85efcbc22cc25a0917ceb18deac8b8f3e9246)
* [Define the onslotchange event handler IDL attribute](https://github.com/whatwg/dom/commit/a6c6d984e756ad099624350f62c97ab902956cce)
* [Run adopt as part of insert](https://github.com/whatwg/dom/commit/c825ceaf3cb77943f487f85533d8be79bccd2fe3)

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by alice** [comment]
@hober and I just looked at this as part of our virtual face-to-face meeting.

After going through each of the commits, we're happy with these changes.

One minor comment: It would have been slightly more convenient to have links to the pull requests, rather than the commits, since the PRs include generated spec diffs as well as source diffs.

**Comment by siusin** [comment]
Thanks @alice and the TAG.

Will add links to the PRs in future review requests.

**Comment by torgo** [comment]
Based on discussion in the last f2f and on today's call, we're going to close this one.
