### ISSUE TITLE
Web Authentication Level 2

### ISSUE THREAD

**Issue by kreichgauer** [w3ctag/design-reviews#577]
HIQaH! QaH! TAG!

I'm requesting a TAG review of Web Authentication Level 2.

Web Authentication Level 2 is an incremental update over Level 1. New features in Level 2 include the following:
 - A new enum-valued AuthenticatorSelectionCriteria.residentKey property to allow “preferred” creation of a discoverable credential (formerly known as a “resident key”).
 - The Credential Properties Extension (credProps), which reports whether a created credential is discoverable.
 - The Large Blob Storage Extension (largeBlob), which allows associating a credential with opaque data.
 - An additional AttestationConveyancePreference enum value, “enterprise”, to allow requesting attestation statements that may include uniquely identifying information.
 - The Apple Anonymous Attestation Statement Format.
 - Additional convenience methods on AuthenticatorAttestationResponse that extract and convert certain parts of the CBOR-encoded attestationObject.

Requested Links:
  - Explainer¹ (minimally containing user needs and example code): https://docs.google.com/document/d/19tpdFvgV4qaOoudNwGOfsRskDdn989rk8NxtMHA6OEo/view
  - Specification URL: https://www.w3.org/TR/webauthn-2/
  - Tests: https://wpt.fyi/results/webauthn/
  - Security and Privacy self-review²: https://docs.google.com/document/d/1jZNgT_o1BXKJF-dZS81lHzv5hQM61KSv0mfax5xvui4/view
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/webauthn/
  - Primary contacts (and their relationship to the specification):
      - Anthony Nadaline (nadalin), W3C Invited Experts (co-chair and editor)
      - Jeff Hodges (equalsJeffH), Google (editor)
      - Akshay Kumar (akshayku), Microsoft (editor)
      - Daniel Veditz (dveditz), Mozilla
      - Jiewen Tan (alanwaketan), Apple
      - Wendy Seltzer (wseltzer), W3C Team Contact
  - Organization(s)/project(s) driving the specification: W3C Web Authentication WG
  - Key pieces of existing multi-stakeholder review or discussion of this specification: 
    - WG meetings and Github issue/PR discussion threads
    - [PING review](https://lists.w3.org/Archives/Public/public-privacy/2020OctDec/0018.html) (ongoing)
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): 
    - ChromeStatus: [[1](https://chromestatus.com/feature/5701094648840192)][[2](https://chromestatus.com/feature/5102556109864960)]

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: No firm deadlines, but Level 2 is in feature freeze at this point and approaching publication
  - The group where the work on this specification is currently being done: W3C Web Authentication WG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): W3C Web Authentication WG
  - Major unresolved issues with or opposition to this specification: none
  - This work is being funded by: The member organizations of the WG members

You should also know that...

 - WebAuthn Level 1 has already gone through TAG review (see #97), so this review is only meant to cover substantial changes between Levels 1 and 2.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by dbaron** [comment]
I'd note that the discussion in w3c/webauthn#1302 is pretty concerning.  At least in that example I think it shows that this specification containing the material that we expect specifications to contain.  Given that, there seem likely to also be other examples.

**Comment by kreichgauer** [comment]
w3c/webauthn#1302 has been resolved

**Comment by mikewest** [comment]
Hey folks, as obliquely noted in https://groups.google.com/a/chromium.org/g/blink-dev/c/Vfg2o0peyYg/m/Vp0h8i5VBQAJ, this review has been untriaged since November, 2020. If y'all have input for the feature's developers, it would be excellent to provide it. :)

/cc @torgo @plinss

**Comment by torgo** [comment]
Hi @mikewest @agl kreichgauer. Sorry this dropped off of our radar. We are spending some time looking at it today. We're noting a lack of use cases. It looks to me like the use cases in the level 2 spec are the same ones as in the level 1 spec - so this raises the question: what additional use cases (user needs) are being solved with level 2? Our take on explainers is that they should generally start with the user needs. I have no doubt that there are important new user needs that y'all are trying to solve with level 2- but it's not clear from the explainer what those are.  Even if the answer is : "this spec adds some commonly used authentication mechanisms to webauth."

Regarding the security & privacy self-check, the responses look good. I'm concerned about the fingerprinting implications of the apple-specific attestation format. There doesn't seem to be any discussion on mitigation against that. Also, there are no plans to have different behaviour in incognito mode. Is that a good thing, especially considering the additional fingerprinting surface area? Do you have additonal information about why device-vendor-specific mechanisms are required?  It's unusual for device vendor specific technologies in the web platform - see [Web Platform Design Principles](https://w3ctag.github.io/design-principles/#wrapper-apis) and the [Ethical Web Principles](https://w3ctag.github.io/ethical-web-principles/#multi).

One side note: the explainer and response to the security & privacy questionnaire are both in google doc format and we'd really like to encourage these to be in markdown along side of the spec itself...

We're aware we took too long on this review and we're not seeking to block anything, however the we think the quality of the explainer and spec will be greatly improved by addressing the above issues.

**Comment by kreichgauer** [comment]
Hi @torgo,

with regards to use cases, I think the issue is that Level 2 features are all minor tweaks/additions to certain aspects of the spec and need to be looked at individually. I tried pointing out in each individual section under "WebAuthn Level 2 Additional Features" what motivates the addition of that particular feature, in particular:

- ResidentKeyRequirement + credProps: Improve API ergonomics to account for users that may not yet have security keys that support password-less sign-in
- largeBlob: support SSH authentication on the web
- credBlob: support association of WebAuthn credentials with short secret blobs for the purpose of authenticating machines in a non-web context
- Enterprise Attestation: support security keys that can attest a unique serial number when registering a WebAuthn credential enterprise-managed context
- Apple Anonymous Attestation: compatibility with Apple devices
- AuthenticatorAttestationResponse Accessors: API ergonomics

Is there any use case in particular that you would like us to expand on in more depth?

Re fingerprinting implications of Apple-specific attestation, note that the thing being added is just another attestation statement _format_. The general mechanism for requesting authenticator attestation has been there since L1, and its purpose is to provide provenance information about the authenticator that created a WebAuthn credential, which usually includes the authenticator vendor. As far as I'm aware, all browser gate attestation behind a separate permission prompt, regardless of whether the user is in an Incognito browsing context or not.  

Lastly, with regards to why vendor-specific attestation statement formats are necessary, the answer is that different authenticator vendors have different requirements on what is being attested. Physical FIDO2 security keys all generally attest a batched serial number using a vendor-specific certificate (https://w3c.github.io/webauthn/#basic-attestation) under the same format that FIDO prescribes. The platform authenticators provided by operating systems on the other hand each work differently. For example, Windows is sending an attestation generated by a TPM, while Apple's is generated by an online Anonymization CA and Android uses SafetyNet. Even if something like a unified "operating system attestation" format were technically feasible, all these platform authenticator implementations have shipped in their respective OSes, which means we will need to live with them for the foreseeable future, I think.

**Comment by torgo** [comment]
Hi @kreichgauer - just noting that the explainer and the answers to security & privacy questionnaire are still in google doc format – can I ask you to please bring these over to wherever the spec is, in markdown, please?  For one thing, this makes it easier to refer to these documents via a stable URL which can be important during the review process.
