### ISSUE TITLE
Formal Review Request for CSS Text Level 3

### ISSUE THREAD

**Issue by fantasai** [w3ctag/design-reviews#581]
HIQaH! QaH! TAG!

I'm requesting a TAG review of CSS Text Level 3.
This CSS module defines properties for text manipulation and specifies their processing model. It covers line breaking, justification and alignment, white space handling, and text transformation.

  - Explainer¹ (minimally containing user needs and example code): <br> The purpose and example code for each feature is inlined into the spec. (Many normative pieces of this specification would be too hard to understand if this explanatory/example text was extracted into a separate document.) Feel free to complain if anything is insufficiently understandable. Additional information about user requirements is available in the *LREQ family of i18n documents. A user-focused intro to the line-breaking and white-space processing part of this specification is available as a conference talk: https://cssday.nl/2019/speakers#florian If you want a detailed explanation of the considerations going into each design decision over the 20+ years of work that went into this document, please pay a nice graduate student to write a thesis for you. In the meantime, we're happy to answer any questions. :)
  - Specification URL: https://drafts.csswg.org/css-text-3/
  - Tests: http://wpt.live/css/css-text/
  - Security and Privacy self-review²: https://lists.w3.org/Archives/Public/www-style/2020Oct/0003.html
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/csswg-drafts
  - Primary contacts (and their relationship to the specification): co-editors @fantasai (IE), @frivoal (IE), and @kojiishii (Google)
  - Organization(s)/project(s) driving the specification: CSS Working Group and Internationalization Working Group
  - Key pieces of existing multi-stakeholder review or discussion of this specification: See https://drafts.csswg.org/css-text-3/issues-lc-2013 and https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue+label%3Acss-text-3+
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://bugzilla.mozilla.org/show_bug.cgi?id=104960 https://wpt.fyi/results/css/css-text https://bugs.chromium.org/p/chromium/issues/list?q=css-text-3&can=2

Further details:

  - [on my todo list, but I read the CSS part] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: <br> Would be *really nice* to have this transition to CR before the end of year moratorium, given we actually managed to hit zero open issues for the first time since 2002...
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): CSSWG
  - Major unresolved issues with or opposition to this specification: None
  - This work is being funded by: W3C, Microsoft, Mozilla, HP, EAST Japan, Opera Software, Bloomberg, Google, Apple, probably forgot some others.

You should also know that this specification is the product of existing features in CSS2, proprietary features that shipped in IE and WebKit, i18n needs, and an attempt to keep it all as coherent as possible given those constraints.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by fantasai** [comment]
Since we're down to only a few editorial issues, I'm planning to request permission from the CSSWG to transition this specification to CR this week. If the TAG would like to prevent that transition, please let me know. We will of course continue to process issues raised during CR. CC @plinss @torgo

**Comment by plinss** [comment]
The TAG is in recess through the end of the year, but has no objection to CSS Text Level 3 transitioning to CR at this time.

We'll be taking a deeper look in the future, but will file issues as we find them.

**Comment by dbaron** [comment]
@atanassov and I just discussed this in a breakout.  I think we're both fine with closing this; this spec has already gotten a lot of review.

One thing I was thinking about is that one interesting thing in here is that auto hyphenation doesn't work if the page doesn't specify the content language.  I think this is good -- it's probably good that heavily language-dependent features don't depend on UAs using heuristics to guess the content's language.  But this made me wonder two things:  first, whether this is something that should be done for any other language-dependent features, and second, whether it's something that should be a tiny bit more visible in the specification (or maybe elsewhere).  (@atanassov wonders if we have a list of such language-dependent features.)

**Comment by dbaron** [comment]
We discussed this in our mini-plenary during our [virtual face-to-face meeting](https://github.com/w3ctag/meetings/blob/gh-pages/2021/01-Kronos/agenda.md) and agreed to close.  There are a number of folks on the TAG who have already reviewed this spec at other points in its development and we didn't think it needed additional review from the TAG as part of its CR phase.

(See also w3ctag/design-principles#266 which was filed based on the discussion of my previous comment.)
