### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by clelland** [w3ctag/design-reviews#585]
HIQaH! QaH! TAG!

I'm requesting a TAG review of the Reporting API.

The Reporting API is a mechanism for web servers to tell browsers where to send errors and other information about a browsing session.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/w3c/reporting/blob/master/EXPLAINER.md
  - Specification URL: https://w3c.github.io/reporting/
  - Tests: [Generic tests](https://wpt.fyi/results/reporting?label=experimental&label=master&aligned), but also [feature integration tests](https://wpt.fyi/results/permissions-policy/reporting?label=experimental&label=master&aligned)
  - Security and Privacy self-review²: https://github.com/w3c/reporting/blob/master/security-and-privacy-questionnaire.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/reporting/
  - Primary contacts (and their relationship to the specification):
      - Ian Clelland (@clelland), Google (Editor)
      - Douglas Creager (@dcreager), GitHub (Editor)
      - Mike West (@mikewest), Google (Editor)
      - Ilya Grigorik (@igrigorik), Google (Group Chair)
      - Nic Jansma (@nicjansma), Akamai (Group Chair)
      - Yoav Weiss (@yoavweiss), Google (Group Chair)

  - Organization(s)/project(s) driving the specification: Google
  - Key pieces of existing multi-stakeholder review or discussion of this specification: 
The Reporting API has been discussed within WebPerfWG several times; [TPAC 2019 minutes](https://docs.google.com/document/d/1-xMvUHAjqhQdegNqupxlqsLbfPHWq5MJ0iySg9Z1KBs/edit#heading=h.kryll0txlacb), [TPAC 2020 minutes](https://docs.google.com/document/d/1inejuvPONXPOLKTCcUzOBhPh6QOckMcltnR-E3xyZVQ/edit?ts=5fa98a72&pli=1#heading=h.6na6dc1pssqh), as well as issues such as https://github.com/w3c/reporting/issues/158 and https://github.com/w3c/reporting/issues/169, which have resulted in a reduced scope for the specification and changes to the header.
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):
    - [Chrome Platform Status](https://www.chromestatus.com/feature/4672626140119040)
    - [Mozilla Standards Position](https://github.com/mozilla/standards-positions/issues/104)

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: Chrome is preparing to ship changes to the API based on feedback from other browser vendors in https://github.com/w3c/reporting/issues/158, hoping to land those with Chrome 89 soon.
  - The group where the work on this specification is currently being done: WebPerfWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): WebPerfWG
  - Major unresolved issues with or opposition to this specification:
  - This work is being funded by: Google

You should also know that, while the Reporting API has shipped in Chrome for some time, and several features have integrated with it, and ReportingObserver has been reviewed by TAG, the API as a whole was never reviewed. This is relevant now as changes have been made to the scope of the API, as well as the header used and its syntax, which Chrome is looking to ship.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by MattMenke2** [comment]
Sorry, I may make misunderstood the spec (influenced by Chromium's implementation) - is Report-To information now scoped to a document?

**Comment by clelland** [comment]
That is correct, everything covered by the Reporting API should be document-scoped. Reporting endpoint configuration is ephemeral, and reports from separate documents should not be sent together in the same POST request, even if they are coming from the same origin. (There's an open question there — whether it's okay to bundle together reports from different same-origin documents, as long as they are in a single agent cluster, but currently the spec does not allow that.)

NEL is a different case, and isn't covered by the base reporting API. There is an extension to the spec, https://w3c.github.io/reporting/network-reporting.html, which allows for persistent configuration, but that will be a separate TAG review, and will certainly need to take your comments into consideration.

**Comment by MattMenke2** [comment]
That's great - thanks s much for setting me straight!  Then this feature seems totally fine to me, as specced.

**Comment by atanassov** [comment]
@LeaVerou, @plinss and myself looked at our "Kronos" virtual f2f. It would great to have the following issues addressed:

- Can you provide an explicit list of the types of reports we are evaluating for?
- Given this feature could be sending PII through such reports, can you please complete the Privacy & Security questionnaire?
- Some of the report endpoints have to be sent by definition to different servers. That would mean we're exposing information to a 3rd party by design. Are we reading the proposal correctly? 
- What would the list of all types of endpoints be?
- [Would an event be more appropriate?](https://w3ctag.github.io/design-principles/#events-vs-observers)
- Using such reporting mechanism, do you expect to have user-generated events part of the same reports?
- The current design suggests the use of a queue that would require pulling. Could this be a callback instead? That would make it easier to decide between an event and observer.
- Should all reports be visible to script?
- Currently the JSON object includes keys in both underscore case (`user_agent`) and camelCase (`lineNumber`). For consistency, it would be best to use [underscore case](https://w3ctag.github.io/design-principles/#casing-rules) only.

**Comment by clelland** [comment]
Thanks for taking the time to look at this, @atanassov! I'll try to address each of those questions here -- note that some of these points have already been addressed as part of the [TAG review of ReportingObserver](https://github.com/w3ctag/design-reviews/issues/195) mentioned in the 'You should also know that' section.

As a general point, I'm not sure what you mean when you've used the word 'endpoint' -- in the spec, a [reporting endpoint](https://w3c.github.io/reporting/#concept-endpoints) is the location of an HTTP server which can accept POST requests containing reports. I feel like you're using it to mean something different here, so if I've misunderstood your questions, let me know and I'll try to clarify.

> * Can you provide an explicit list of the types of reports we are evaluating for?

Probably not, and this is by design -- the API is a generic framework for other other specs to use to achieve consistent reporting across features. I would prefer to evaluate this API on its own merits, based on what it can and cannot enable, rather than the specific list of current integrations. That said, I can understand that it's difficult to do that completely out of context. The current list of APIs which use this framework for reporting are:
 - [Content Security Policy Level 3](https://w3c.github.io/webappsec-csp/#reporting)
 - [Cross-origin Opener Policy](https://github.com/camillelamy/explainers/blob/master/coop_reporting.md)
 - [Permissions Policy](https://w3c.github.io/webappsec-permissions-policy/#reporting)
 - [Document Policy](https://wicg.github.io/document-policy/#reporting)
 - [Deprecation Reporting](https://wicg.github.io/deprecation-reporting/)
 - [Intervention Reporting](https://wicg.github.io/intervention-reporting/)
 - [Crash Reporting](https://wicg.github.io/crash-reporting/)
 - The related [Network Reporting API](https://w3c.github.io/reporting/network-reporting.html), which enables [Network Error Logging](https://w3c.github.io/network-error-logging/) (there is still work to do there to finish that integration)

(I hope I haven't missed any, but I'll comment if I find new ones)

> * Given this feature could be sending PII through such reports, can you please complete the Privacy & Security questionnaire?

Linked above at https://github.com/w3c/reporting/blob/master/security-and-privacy-questionnaire.md

> * Some of the report endpoints have to be sent by definition to different servers. That would mean we're exposing information to a 3rd party by design. Are we reading the proposal correctly?

The purpose of the reporting framework is to allow reports to be sent over HTTP to remote servers. Cross-origin and third-party servers are included by design, under the belief that:
 - It can be necessary, especially in the case of APIs such as network error logging, to have a report collector which is separate from the site which produces the error.
 - Organizations will probably want to have a central report collector, rather than hosting an endpoint on every origin.
 - Allowing third-party collectors enables an ecosystem of report hosting and analysis services, such as Report-uri.com and uriports.com, among others.
 - In general, the same or similar information could be communicated with third parties through other means (cross-origin subresources, XHR, beacons, etc).

> * What would the list of all types of endpoints be?

I'm not sure what you mean here -- endpoints are the URLs / servers to which reports are sent. They don't have types, unless you're drawing a 1p/3p distinction, or categorizing them by the types of reports which they choose to accept. Can you clarify this question?

> * Would an event be more appropriate?

There was [discussion](https://github.com/w3c/reporting/issues/29) on this when ReportingObserver was designed, although I wasn't part of those discussions at the time (@juliatuttle or @RByers may have additional historical context). I do believe that an observer would be preferable to an event, to support batching (reports are delivered as a list,) post hoc reporting (observers can be registered to retrieve reports from events which happened before they were created, which is useful for early-page-load events,) and to make it easy to write handlers for just some subset of report types. Additionally, the event infrastructure introduces complications such as bubbling, and can require coordination between multiple listeners, neither of which is useful here.

> * Using such reporting mechanism, do you expect to have user-generated events part of the same reports?

Not currently -- there are no free-form user-generated reports. The closest thing that exists is the test-driver-only generateTestReport API. However, it is not impossible for another spec to integrate in that way; nothing in this API prevents that. I suspect that would require a lot more scrutiny, for the possible XSS / injection issues at least. Is the TAG aware of other issues that would mean that we should strongly discourage such things?

> * Should all reports be visible to script?

No, by design there is an allowance for reports which are not visible. This can be just by necessity (crash reports, for instance), or it might be important for privacy, if there are cases where it's not advisable for the page to have immediate, real-time script access to user events.

> * Currently the JSON object includes keys in both underscore case (user_agent) and camelCase (lineNumber). For consistency, it would be best to use underscore case only.

This was discussed in https://github.com/w3c/reporting/issues/72, and I think that the decision was made to follow the TAGs recommendations wherever possible, but that in some cases (CSP reports, for instance,) backwards-compatibility issues meant keeping camelCase identifiers.

**Comment by kenchris** [comment]
This seems related (we did an early review before) https://github.com/w3ctag/design-reviews/issues/419

**Comment by torgo** [comment]
We discussed in today's breakout just now and agreed we need a dedicated breakout to delve into this issue further.

**Comment by plinss** [comment]
@ylafon and I took a look at this during our virtual F2F, thank you for filling the Security and Privacy questionnaire and for your response to our earlier comments.

At this point we don't have any further comment on this, this looks OK to proceed. Thanks!

**Comment by clelland** [comment]
Thanks for the review!
