### ISSUE TITLE
ARIA 1.2

### ISSUE THREAD

**Issue by michael-n-cooper** [w3ctag/design-reviews#586]
HIQaH! QaH! TAG!

I'm requesting a TAG review of ARIA 1.2.

Provides an ontology of roles, states, and properties that define accessible user interface elements and can be used to improve the accessibility and interoperability of web content and applications. These semantics are designed to allow an author to properly convey user interface behaviors and structural information to assistive technologies in document-level markup. 

  - Explainer¹ (minimally containing user needs and example code): https://www.w3.org/TR/2008/WD-wai-aria-roadmap-20080204/
  - Specification URL: https://www.w3.org/TR/2019/WD-wai-aria-1.2-20191218/
  - Tests: https://w3c.github.io/test-results/core-aam-1.2/
  - Security and Privacy self-review²: N/A
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/aria/
  - Primary contacts (and their relationship to the specification):
      - James Nurthen @jnurthen Adobe
      - Joanmarie Diggs @joanmarie Igalia
      - Michael Cooper @michael-n-cooper W3C
  - Organization(s)/project(s) driving the specification: W3C / ARIA 
  - Key pieces of existing multi-stakeholder review or discussion of this specification: N/A
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://github.com/w3c/aria/issues

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: ready for CR as soon as horizontal review complete
  - The group where the work on this specification is currently being done:
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): W3C / ARIA
  - Major unresolved issues with or opposition to this specification: N/A
  - This work is being funded by: N/A

You should also know that...

This project was discussed with the TAG at TPAC 2016. The outcome was that ARIA 1.2 should focus on HTML parity. This version does so (though incomplete, further work in future versions).

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

------------------------------------------------------------------------------------
CAREFULLY READ AND DELETE CONTENT BELOW THIS LINE BEFORE SUBMITTING

Please preview the issue and check that the links work before submitting.

In particular, if anything links to a URL which requires authentication (e.g. Google document), please make sure anyone with the link can access the document. We would prefer fully public documents though, since we work in the open.

¹ We require an explainer to give the relevant context for the spec review, even if the spec has some background information. For background, see our [explanation of how to write a good explainer](https://w3ctag.github.io/explainers). We recommend the explainer to be in [Markdown](https://github.github.com/gfm/).

² A Security and Privacy questionnaire helps us understand potential security and privacy issues and mitigations for your design, and can save us asking redundant questions. See https://www.w3.org/TR/security-privacy-questionnaire/.

**Comment by atanassov** [comment]
@alice and myself reviewed the ARIA 1.2 changes compared to ARIA 1.1 during our "Kronos" VF2F. We are happy with the proposed set of additions and changes, especially with the WebIDL section. We also noticed that this section is currently under development with an [open issue](https://github.com/w3c/aria/issues/1110) about the different types (current WD has all attributes as DomString?). This is going to be of interest to TAG and we suggest opening a different design review in the future, when the WebIDL takes a more final state.
Thank you for working with us.
