### ISSUE TITLE
Declarative Link Capturing

### ISSUE THREAD

**Issue by mgiuca** [w3ctag/design-reviews#589]
HIQaH! QaH! TAG!

I'm requesting a TAG review of Declarative Link Capturing for Progressive Web Apps.

New Web App Manifest members to control what happens when the user navigates to a page within scope of an installed web app.

This feature introduces the "capture_links" member, an enumeration allowing the customization of link capturing behaviour, allowing sites to:

- Automatically open a new PWA window when the user clicks a link to their app.
- Have a "single window mode" like mobile apps.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/WICG/sw-launch/blob/master/declarative_link_capturing.md
  - Security and Privacy self-review²: [Google Doc](https://docs.google.com/document/d/1y0kxaLhbkhRt6vwnN8c9-pf8i7kzaw_gXDqeFo0pPew/edit)
  - GitHub repo (if you prefer feedback filed there): https://github.com/WICG/sw-launch
  - Primary contacts (and their relationship to the specification):
      - Matt Giuca (@mgiuca), Google
  - Organization/project driving the design: Google 
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): https://www.chromestatus.com/feature/5734953453092864

Further details:

  - [X] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): WICG
  - The group where standardization of this work is intended to be done ("unknown" if not known): Web Apps WG
  - Existing major pieces of multi-stakeholder review or discussion of this design: 
  - Major unresolved issues with or opposition to this design:
  - This work is being funded by: Google

This is a sibling spec to [URL Handler](https://github.com/WICG/pwa-url-handler/) which would allow link capturing from different origins and URLs outside of the app scope. We are collaborating with Microsoft (the primary authors of URL Handler) to make sure these two projects fit nicely with one another.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  ☂️ open a single issue in our GitHub repo **for the entire review** (since we are currently sharing the repo with sw-launch)

**Comment by alice** [comment]
Hi Matt,

Thanks for bringing this to us.

We see that this is still in the early stages, but the promising things we note are:

- The list of use cases is helpful to understand the problem(s) being solved, and
- This grew out of an attempt at a more powerful, complex API which has been abandoned/postponed in favour of a simpler, less powerful API
- The list of Issues indicate that this work is still ongoing.

The use cases listed do seem very worth addressing.

It does seem like there are many options to the `capture_links` field - it might be nice to link each one back to a specific use case with a brief example of how it might be used in practice.

Also, it would be helpful to have an explanation of how this would be used in the context of a mobile OS which typically has one window per application. How would that interact with the `new-client` option?

**Comment by mgiuca** [comment]
Thanks for your comments @alice .

I or @alancutter will update the explainer in response. I think we can provide specific use cases for each one.

Also note that we're planning to implement these `capture_links` enums one-by-one, starting with `new_client` and `existing_client_navigate`. So I just put up a big list, but we can implement them (and spec them) as the need arises, rather than speculatively assuming there's a need for all of them.

> Also, it would be helpful to have an explanation of how this would be used in the context of a mobile OS which typically has one window per application. How would that interact with the `new-client` option?

We should think of this entire feature as a hint to the user agent. It doesn't *have* to do what you ask. Browsers are (generally) allowed to close any window / tab whenever it wants, and routinely do. So even if you ask for `new_client`, the mobile browser can just implement it as `existing_client_navigate`, destroying your existing context, which is not very acceptable on desktop but quite normal on mobile. We'll say that in the explainer.

**Comment by rhiaro** [comment]
Hi, the Security & Privacy questionnaire is in a google doc that we can't access. Could you move it to a markdown file in the same repo as the explainer? Thanks!

**Comment by torgo** [comment]
Hi @mgiuca can you give us any visibility of other browser / engine support for this? Is this on its way to the manifest file spec itself? /cc @marcoscaceres

**Comment by mgiuca** [comment]
@rhiaro Moved into the explainer [here](https://github.com/WICG/sw-launch/blob/main/declarative_link_capturing.md#security--privacy-questionnaire). (Hmm, I'm not sure why you couldn't access the doc. It is set to "Anyone on the internet with this link can view". But anyway it's in GitHub now.

@torgo I don't know of any other browsers who have expressed support for this.

**Comment by torgo** [comment]
Hi @mgiuca thanks for that! For the security & privacy questionnaire answers, can we understand that the answers to the other questions is 'no'?  Also just to note: you list WebApps as a destination (presumably because this will become part of webapp manifest) however in order for that to happen there need to be multiple implementations. So I would encourage you to have those discussions with other browsers and try to generate some additional support if you want to take this out of incubation.  We also think this activity needs to be coordinated with the parallel work going in in this area in the MiniApp working group. However in general we're very supportive of this feature and would like to see this move forward.

**Comment by mgiuca** [comment]
I have sent out requests for standards positions from Mozilla and Apple:

- https://github.com/mozilla/standards-positions/issues/520
- https://lists.webkit.org/pipermail/webkit-dev/2021-May/031834.html
