### ISSUE TITLE
Dropper color space

### ISSUE THREAD

**Issue by rkjames** [w3ctag/design-reviews#590]
Are there any color space goals?
Are there any roundtrip goals? (Eg. Setting a div to dropper color should get dropper.color next round)

**Comment by LeaVerou** [comment]
I'm not sure I understand what you're asking. Could you elaborate and provide some more context please?

**Comment by rkjames** [comment]
What color-space will dropper color be reported in? (eg. imagine an image loaded from a different space to the screen)

Can I round trip the color? eg. sample <div background-color:#123>, get the color from the dropper, set the color on the div, will its color change even slightly?

**Comment by LeaVerou** [comment]
I'm not sure which dropper you're referring to. Could you point me to the relevant specification?

In case it helps, hex colors (like your `#123` example) on the Web are in the [sRGB](https://en.wikipedia.org/wiki/SRGB) color space.

**Comment by torgo** [comment]
As discussed in TAG breakout today, we think this is probably redundant with #587 so closing this one for now. Please move conversation there. Thanks!
