### ISSUE TITLE
Early design review of the **updated** Multi-Screen Window Placement API

### ISSUE THREAD

**Issue by michaelwasserman** [w3ctag/design-reviews#602]
HIQaH! QaH! TAG!

I'm requesting a TAG review of the **updated** [Multi-Screen Window Placement API](https://github.com/webscreens/window-placement/blob/master/EXPLAINER.md).

This proposal introduces incremental improvements to existing screen information and window placement APIs, allowing web applications to be intentional about the experiences they offer to users of multi-screen devices. **The API shape [has been updated](https://github.com/webscreens/window-placement/blob/master/CHANGES.md) since [our last TAG review](https://github.com/w3ctag/design-reviews/issues/413)** with feedback from partners and web platform API experts ([example](https://github.com/webscreens/window-placement/issues/30)).

  - Explainer: https://github.com/webscreens/window-placement/blob/master/EXPLAINER.md
  - Changes since [the last TAG review](https://github.com/w3ctag/design-reviews/issues/413): https://github.com/webscreens/window-placement/blob/master/CHANGES.md
  - Security and Privacy self-review: https://github.com/webscreens/window-placement/blob/master/security_and_privacy.md
  - GitHub repo: https://github.com/webscreens/window-placement
  - Primary contacts:
      - @michaelwasserman: Google, Chromium implementer, editor
      - @webscreens: W3C Second Screen Community Group (incubation group)
  - Organization/project driving the design: Google/Chromium & [W3C Second Screen Community Group](https://github.com/webscreens)
  - External status/issue trackers for this feature: [Chrome Status](https://www.chromestatus.com/feature/5252960583942144) and [Chrome Feature Issue](https://bugs.chromium.org/p/chromium/issues/detail?id=897300)

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the incubation/design work on this is being done: [W3C Second Screen Community Group](https://github.com/webscreens)
  - The group where standardization of this work is intended to be done: [W3C Second Screen Work Group](https://www.w3.org/2014/secondscreen/) (maybe?)
  - Existing major pieces of multi-stakeholder review or discussion of this design: [Prior TAG review](https://github.com/w3ctag/design-reviews/issues/413), ([API design discussion](https://github.com/webscreens/window-placement/issues/30)), W3C Second Screen CG's [Form Factors Explained](https://webscreens.github.io/form-factors/) report.
  - Major unresolved issues with or opposition to this design: None
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as (please delete all but the desired option):
  💬 leave review feedback as a **comment in this issue** and @-notify @michaelwasserman

Thank you!

**Comment by tomayac** [comment]
> - Explainer: https://github.com/webscreens/window-placement/blob/master/EXPLAINER.md
> - Changes since the last TAG review: https://github.com/webscreens/window-placement/blob/master/EXPLAINER.md

This looks like a copy & paste glitch. The changes are mentioned in [CHANGES.md](https://github.com/webscreens/window-placement/blob/master/CHANGES.md).

**Comment by michaelwasserman** [comment]
Thanks for catching that, @tomayac! I updated the initial comment above.

**Comment by kenchris** [comment]
I find `Promise<Screens> getScreens();` a bit confusing due to `.screens` property. It can lead devs to write code like

`screens.screens.length` and even the examples use `screensInterface.screens.length` in order to avoid saying `screens` twice. Maybe we should just call it `ScreenInfo` or similar, like `Promise<ScreenInfo> getScreens()` - naming is hard.

I was also thinking about something like "ScreenDevices", but I still hope we can find a better name

**Comment by quisquous** [comment]
> I find `Promise<Screens> getScreens();` a bit confusing due to `.screens` property.

We have that filed on https://github.com/webscreens/window-placement/issues/50 as a place to discuss.  As you say, naming is really hard.  I don't think anybody has come up with a better name yet and so we've been punting on that so far.

> I'm wondering if it would help developer ergonomics to also allow an optional screen argument to the Window.moveTo() method, which if passed, makes the x, y coordinates relative to the passed screen. If added, a similar mechanism should be added to Window.open() (perhaps changing the features argument from a string to an object).

I worry that it might be confusing to have the coordinates change their semantics if an optional third parameter is present.  I wonder if it might be better to pick one of (a) x and y are relative with optional screen or (b) x and y are absolute, no screen parameter.

**Comment by torgo** [comment]
Just reviewing this in the context of our virtual f2f. Appreciate what you've [written here](https://github.com/webscreens/window-placement/blob/main/security_and_privacy.md#22-is-this-specification-exposing-the-minimum-amount-of-information-necessary-to-power-the-feature) about fingerprinting mitigation.

**Comment by michaelwasserman** [comment]
Thanks for the comments and feedback, @kenchris, @plinss, and @torgo. Thanks for the reply, @quisquous.

@kenchris: we're open to naming feedback on webscreens/window-placement#50 and I added a comment there, but we haven't necessarily found a more compelling pattern than our current proposal.

@plinss: I hope we'll continue improving the state of window placement on the web with future proposals, perhaps with something akin to your suggestion, and nothing in this proposal precludes such future work. Perhaps developer ergonomics would be served best by moving away from disparate moveTo(), resizeTo(), etc. functions, and adding a new function that can set a bounds rectangle, and potentially related window placement state (e.g. maximized/zoomed, left-/right-snapped, etc.) in a single request. That could support either global cross-screen coordinates and/or screen-relative coordinates (with an optional screen parameter, or a default assumption of relative placement within the current screen). There's a lot to consider, and this proposal aims to start small, but I have some thoughts in the repo's [additional_explorations.md](https://github.com/webscreens/window-placement/blob/main/additional_explorations.md#alternatives-or-possible-future-supplements-to-the-current-proposal) and aim to continue exploring.

Is there any other feedback from TAG members that we can consider during this early design review? Thanks again!

**Comment by atanassov** [comment]
@kenchris and I did another pass at this review during our Gethen vf2f. Thank you for addressing our earlier feedback about API naming and developer ergonomics. In particular we prefer the `getScreenDetails` name over `getScreens` especially in combination of `getScreenDetails().screens`. Further, the detailed exploration document you linked to goes into great details on how to make the API better and since this is an early design review we hope this will be taken into consideration for the final API shape.

At this point we are happy to close the review as satisfied and look forward to the progress you'll make. Thank you and good luck.

**Comment by michaelwasserman** [comment]
Greetings TAG!

I am requesting an supplemental early design review of a proposed API enhancement.

The proposed enhancement would allow sites with the window-placement permission to initiate a multi-screen experience from a single user activation. A partner [requested this functionality](https://github.com/w3c/window-placement/issues/98), when integrating the Multi-Screen Window Placement API in their web application.

- Explainer: https://github.com/w3c/window-placement/blob/main/EXPLAINER_initiating_multi_screen_experiences.md 
- External status/issue trackers for this feature: [Chrome Status](https://www.chromestatus.com/feature/5173162437246976) and [Chrome Feature Issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1233970)

We'd prefer the TAG provide feedback as:  **comment in this issue** and @-notify @michaelwasserman

Thank you!
Mike Wasserman

**Comment by torgo** [comment]
@michaelwasserman when we closed this issue last year we indicated a concern related to multi-stakeholder. I note that the API is still being developed in the Second Screen Community group and Chrome Status does not list any other engine that has expressed interest. Has this moved in any way towards the Second Screen working group and has there been any interest expressed by other implementers?

**Comment by michaelwasserman** [comment]
Thanks for these inquiries!

@torgo: The API was adopted as a Second Screen Working Group deliverable, see the [latest charter](https://www.w3.org/2022/03/charter-secondscreen-wg.html#:~:text=the%20Working%20Group.-,Multi%2DScreen%20Window%20Placement,-An%20API%20that) and [CfC to publish a FPWD](https://lists.w3.org/Archives/Public/public-secondscreen/2022Jun/0010.html). We are getting [valuable feedback from Mozilla](https://github.com/mozilla/standards-positions/issues/542), which just [continued at a recent SS WG vF2F](https://www.w3.org/2022/06/07-webscreens-minutes.html#:~:text=Public%20Working%20Draft-,Mozilla%27s%20feedback,-Mozilla%20position%3A%20Multi), but have no explicit positive signals from another implementer.

@atanassov: The [proposal](https://github.com/w3c/window-placement/blob/main/EXPLAINER_initiating_multi_screen_experiences.md#proposal) includes mitigations to limit the potential for accidental misuse or abuse. The spec was recently [updated](https://github.com/w3c/window-placement/pull/100) per [Mozilla's enhancement feedback](https://github.com/mozilla/standards-positions/issues/636), to clarify [Security Considerations](https://w3c.github.io/window-placement/#security) around deceptive cross-screen placement. The API's [questionnaire](https://github.com/w3c/window-placement/blob/main/security_and_privacy.md) generally covers this minor enhancement, but the Spec and Explainer more directly address the pertinent considerations of this change.

**Comment by atanassov** [comment]
Hi @michaelwasserman – @torgo and I are just reviewing this at [our f2f](https://github.com/w3ctag/meetings/tree/gh-pages/2022/07-London). It looks like [the issue raised](https://github.com/mozilla/standards-positions/issues/636#issuecomment-1132985573) by @annevk hasn't been adequately addressed. That seems to be a pretty common use case (where a malicious site might seek to take over a display and mimic the user's OS (or similar) in order to steal credentials. Also as we've been reviewing it seems to us like this is more than a small enhancement. This proposal extends several technologies that are not part of multiscreen: `user activation`, `Element.requestFullScreen` and `window.open`. Since the scope is a bit wider than a small enhancement on an existing API. Can we ask that you to fork the topic and file a new design review request for this?

**Comment by torgo** [comment]
Just marking this as `pending editor update` for now - we will close when additional issues have been filed.

**Comment by michaelwasserman** [comment]
Thank you, @atanassov and @torgo! Please see the newly opened [TAG review request](https://github.com/w3ctag/design-reviews/issues/767) and the Explainer's new [Security Considerations](https://github.com/w3c/window-placement/blob/main/EXPLAINER_initiating_multi_screen_experiences.md#security-considerations), which documents and attempts to address the concerns raisied by @annevk; I also replied directly to that [Mozilla standards-position thread](https://github.com/mozilla/standards-positions/issues/636#issuecomment-1132985573). Thank you for your time and patience!

**Comment by torgo** [comment]
We're closing this as the review has moved to #767.
