### ISSUE TITLE
Early Design Review: Speculation Rules

### ISSUE THREAD

**Issue by jeremyroman** [w3ctag/design-reviews#611]
HIQaH! QaH! TAG!

I'm requesting a TAG review of Speculation Rules.

Summary:

Flexible syntax for defining what outgoing links are eligible to be prepared speculatively before navigation (e.g. prefetching, prerendering). Enables access to additional enhancements, such as use of a private prefetch proxy, where applicable.

  - Explainer (minimally containing user needs and example code): https://github.com/jeremyroman/alternate-loading-modes/blob/main/triggers.md
  - Security and Privacy self-review: https://github.com/jeremyroman/alternate-loading-modes/blob/main/speculation-rules-security-privacy-questionnaire.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/jeremyroman/alternate-loading-modes/issues
  - Primary contacts (and their relationship to the specification):
      - Jeremy Roman (@jeremyroman), Google
  - Organization/project driving the design: Google Chrome
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5740655424831488

Further details:

  - ✅ I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): WICG (future)
  - The group where standardization of this work is intended to be done ("unknown" if not known): WHATWG
  - Existing major pieces of multi-stakeholder review or discussion of this design: n/a
  - Major unresolved issues with or opposition to this design: n/a
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as:

  ☂️ open a single issue in our GitHub repo **for the entire review**

**Comment by rhiaro** [comment]
Closing per https://github.com/jeremyroman/alternate-loading-modes/issues/56#issuecomment-908499966

**Comment by torgo** [comment]
Hi @mfalken - one thing to note is that Speculation Rules itself is still in a private repo. 

@jeremyroman is this indeed in WICG? Yes there has been a positive TAG review that was based on an "early review" - if this feature itself is still in incubation then maybe it's premature to start building stuff on top of?   

Regarding speculation rules, Chrome Status still shows "no signals" from other implementers or developers. Is there any multi-implemnter implementation?  Again - a lack of consensus on speculation rules itself could mean that it's premature to base other features on it.

**Comment by torgo** [comment]
We're still concerned because this is sitting in a private repo and not even submitted to WICG. @jeremyroman can you let us know the timeline for getting this into a proper standards track? /cc @chrishtr @yoavweiss

**Comment by jeremyroman** [comment]
Sorry for the slow response on my part, @torgo; we're looking into this now. It was previously submitted to WICG (WICG/proposals#2) but at the time we were told the proposal needed to mature and attract more interest to be accepted to WICG.
