### ISSUE TITLE
ARIA in HTML review

### ISSUE THREAD

**Issue by LJWatson** [w3ctag/design-reviews#614]
We're preparing to transition [ARIA in HTML](https://www.w3.org/TR/2021/WD-html-aria-20210301/
) to CR and we'd welcome your review.

The ARIA in HTML specification documents the authoring rules for using ARIA when HTML is the host language.

You last reviewed ARIA in HTML [in 2018](https://github.com/w3ctag/design-reviews/issues/156). There have been changes to the spec [since then](https://github.com/w3c/html-aria/issues?q=is%3Apull+closed%3A%3E2018-11-01
).

If it's possible for you to complete your review by 2 April, we'd be grateful. The WebApps WG will be rechartering in April/May and we'd very much like to request transition to CR before then if we can.

Please file your comments and issues on the [ARIA in HTML repo](https://github.com/w3c/html-aria/issues
), using the appropriate [horizontal review labels](https://github.com/w3c/html-aria/labels).

If you could reply here to let us know when your review is complete, that would be helpful.

With thanks

**Comment by LJWatson** [comment]
It looks like this is included in this week's milestone. If at all possible, we'd appreciate any comments you have this week. Thanks.

**Comment by torgo** [comment]
Hi @LJWatson thanks for this prompt - we are going to try to get you some feedback by end of this week.

**Comment by atanassov** [comment]
@hober and myself looked through these changes during our May 2021 VF2F (skipping chores and editorial) and are satisfied with all the technical decisions or reasoning behind them. We consider the horizontal review signed off from TAG point of view. Thank you for working with us and for your patience.

**Comment by LJWatson** [comment]
With thanks for helping us get this one a step closer to CR.
