### ISSUE TITLE
TAG Specification review for viewport height client hint

### ISSUE THREAD

**Issue by tarunban** [w3ctag/design-reviews#615]
Ya ya yawm TAG!

I'm requesting a TAG review of Viewport Height Client Hint

Currently, Responsive Image Client Hints provide a way for origins to obtain the viewport’s width. However, no such attribute exists for viewport height. We’ve observed that to optimize the loading of content that appears in viewport, it is essential for the origins to adapt HTML response based on viewport height as well. Current methods of doing that include content-negotiation through the User-Agent string, but that is suboptimal as it’s indirect, and doesn’t cover all platforms.
We’d like to propose adding a new image hint Sec-CH-Viewport-Height (similar to the existing Sec-CH-Viewport-Width). Similar to other client hints, origins would be able to register the opt-in for viewport-height client-hint via Accept-CH header, and receive the attribute value as part of HTTP request headers. This would enable origins to e.g., inline all the content that’s expected to appear in the viewport, or avoid lazy-loading it, optimizing height-constrained images in the absence of the layout height of the image, support server-side automated art direction ensuring that the whole image is always visible above the fold on height-constrained devices.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/WICG/responsive-image-client-hints/blob/main/Viewport-Height-Explainer.md
  - Specification URL: https://wicg.github.io/responsive-image-client-hints/#sec-ch-viewport-height and https://wicg.github.io/client-hints-infrastructure/
  - Tests: [wpt folder(s), if available]: Tests not available yet
  - Security and Privacy self-review²: https://docs.google.com/document/d/1WceBPhmHEaoVbYs_MFYYdMpXx5sypxvReXlXxUK-DlE/edit
  - GitHub repo (if you prefer feedback filed there): n/a
  - Primary contacts (and their relationship to the specification):
     Tarun Bansal (@tarunban), Google.
     Yoav Weiss (@yoavweiss), Google.
     Ryan Sturm (@ryansturm), Google.
  - Organization(s)/project(s) driving the specification: Google
  - Key pieces of existing multi-stakeholder review or discussion of this specification: n/a
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5646861215989760

Further details:

  - [Yes] I have reviewed the TAG's [Web Platform Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: [please provide]
  - The group where the work on this specification is currently being done:
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): 
  - Major unresolved issues with or opposition to this specification: n/a
  - This work is being funded by: Google

You should also know that: n/a

[please tell us anything you think is relevant to this review]: n/a

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify [@tarunban, @yoavweiss, @ryansturm]

**Comment by kenchris** [comment]
Is this affected whether the virtual keyboard is open or not?

**Comment by plinss** [comment]
We took a look and see no issues with this. It would be good if Kenneth's question was clarified in the spec.

**Comment by tarunban** [comment]
/cc @yoavweiss
@kenchris Good question. We were thinking it should not be affected by the virtual keyboard since the virtual keyboards on the screen are generall ephemeral. We would clarify that in the spec.
