### ISSUE TITLE
WebXR Plane Detection Module

### ISSUE THREAD

**Issue by bialpio** [w3ctag/design-reviews#620]
Ya ya yawm TAG!

I'm requesting a TAG review of WebXR Plane Detection Module. 

WebXR Plane Detection API allows WebXR-powered experiences to obtain information about planes (flat surfaces) detected in the users' environment. The information about detected planes' poses (position + orientation) and approximate shapes is being surfaced to the application on every XR frame if the feature was enabled on an XR session. This will allow the applications to provide more immersive experiences, for example by leveraging the returned plane information when computing interactions of virtual objects with users' surroundings.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/immersive-web/real-world-geometry/blob/main/plane-detection-explainer.md
  - Specification URL: https://immersive-web.github.io/real-world-geometry/plane-detection.html
  - Tests: N/A yet.
  - Security and Privacy self-review²: https://github.com/immersive-web/real-world-geometry/blob/main/plane-detection-security-privacy-questionnaire.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/immersive-web/real-world-geometry
  - Primary contacts (and their relationship to the specification):
      - Piotr Bialecki, @bialpio, Google, Editor
  - Organization(s)/project(s) driving the specification: Immersive Web CG
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5732397976911872

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: N/A - the feature is still being worked on, with a planned Origin Trial in Chrome M91-92
  - The group where the work on this specification is currently being done: Immersive Web CG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): Immersive Web WG
  - Major unresolved issues with or opposition to this specification: informing about plane changes / removals - see discussion on [spec draft PR](https://github.com/immersive-web/real-world-geometry/pull/27#discussion_r595730915), and [appendix to the explainer](https://github.com/immersive-web/real-world-geometry/blob/main/planes-notifying-about-removal.md).
  - This work is being funded by: N/A.

You should also know that...

This is an early review request, although we already have a rough specification draft so I decided that "Specification review" may be more appropriate.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by torgo** [comment]
Hi @bialpio! We're just having a look at the ex*plane*r in a TAG breakout session and I'm coming up with a few questions. First of all, I think it could go into a bit more detail on the user need.  Can you give a few examples of where plane detection becomes important in the context of a WebXR application?   The answers to the security & privacy questionnaire look good but do not seem to be fully reflected in the explainer of the spec itself? For example, the quantization of planes is mentioned as a mitigation strategy against privacy attacks in the questionnaire response but this is not mentioned in the spec itself. I think this would be a lot stronger (and less prone to fingerprinting) if the quantization and other mitigation strategies were spelled out in the spec. Finally, you mention synchronous hit-test but it's not clear from the explainer how this fits together with the [hit testing](https://immersive-web.github.io/hit-test/) specification itself? What does this technology provide over and above what WebXR hit testing?  We may also have feedback on the API to share - but I wanted to get this out to you quickly.

**Comment by torgo** [comment]
Hi @bialpio - regarding the use cases, that's great info. Can you please add it to the Explainer as well? We'll try to provide some additional feedback on the API design in the coming week.

**Comment by torgo** [comment]
Hi @bialpio - we're just taking another look at this [this week](https://github.com/w3ctag/meetings/blob/gh-pages/2021/telcons/04-26-agenda.md)... Still missing the connection to *hit testing* and some additional info regarding the privacy & security. Do you want to ping us again when you're ready for us to re-review?

**Comment by bialpio** [comment]
I've just merged the PR that should address the initial feedback, please let me know if you think the changes are not sufficient.

**Comment by atanassov** [comment]
@torgo, @rhiaro and myself did another pass through this issue during our May 2021 vf2f. Thank you for the quick turnaround addressing of all the issues we raised and even making the PRs to both explainer and spec. This is a really great example of effective TAG review and we are happy if you feel the same.
We are also happy to see this work proceed forward, thus, resolving as satisfied. Thank you for working with us!
