### ISSUE TITLE
Back/Forward Cache

### ISSUE THREAD

**Issue by rakina** [w3ctag/design-reviews#628]
Hi TAG!

I'm requesting a TAG review of Back/Forward Cache (BFCache).

We’ve recently looked into how BFCache is specified in the HTML spec and other standards, and noticed some problems with the current state. We’ve identified possible solutions for some of them, but we’re interested in getting TAG’s opinion on how we should approach these problems, especially the ones we don’t really have answers to.

The explainer can be found [here](https://github.com/rakina/bfcache-explainer/blob/main/README.md). TL;DR:

- How various APIs/existing concepts interact with BFCache is quite underspecified
- How BFCache is specified is quite subtle, so it’s hard for API spec authors to specify things correctly
- User agent implementation varies quite a lot
- We have concrete proposal to update various docs ([Web Platform Design Principles](https://w3ctag.github.io/design-principles/) and [Security and Privacy Questionnaire](https://www.w3.org/TR/security-privacy-questionnaire/)) and improve the foundational HTML spec, but there are open questions on more high-level stuff such as “How should we retrofit current APIs” and “Which behavior should be specified and which should be left to user agents’ discretion?”

This is probably different from the usual TAG review request, as we’re not really asking for a review of specific APIs, but instead want to answer more meta questions around the design process and how we should approach specifying things (as mentioned above). Our goal is to improve currently-existing specifications and also ensure new APIs are designed with BFCache support in mind by integrating it into the existing design guidelines (and hopefully TAG reviews can help enforce this).

  - Explainer¹ (minimally containing user needs and example code): https://github.com/rakina/bfcache-explainer/blob/main/README.md
  - Primary contacts (and their relationship to the specification):
      - Rakina Zata Amni (@rakina), Google
      - Fergal Daly (@fergald), Google
      - Domenic Denicola (@domenic), Google
  - Organization(s)/project(s) driving the specification: Google
  - Key pieces of existing multi-stakeholder review or discussion of this specification: https://github.com/whatwg/html/issues/5880 
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://www.chromestatus.com/feature/5815270035685376

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: We're hoping to update TAG docs etc sometime in the next 1-2 months
  - The group where the work on this specification is currently being done: WHATWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): WHATWG
  - Major unresolved issues with or opposition to this specification: (see [explainer](https://github.com/rakina/bfcache-explainer/blob/main/README.md))
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @rakina

**Comment by rakina** [comment]
Thanks @hober! We’ve sent PRs to update the documents ([1](https://github.com/w3ctag/design-principles/pull/317), [2](https://github.com/w3ctag/security-questionnaire/pull/128)) and will open more spec issues for BFCache, tracked in the [BFCache meta-bug](https://github.com/whatwg/html/issues/5880).

We will also continue working with owners of current APIs (and start contacting ones we haven’t reached out to yet) to figure out how BFCache fits into their API. We’re grateful that TAG supports our goal, and we hope TAG can help by checking for the "bfcache consideration" bit for future APIs in TAG reviews!

Thanks again!

**Comment by cynthia** [comment]
Closing! (this should have been closed with the last comment, but something happened.)

**Comment by rakina** [comment]
Hello! During last month's F2F, Chrome's BFCache team met with TAG and discussed how we can improve BFCache-support checking during TAG reviews, as we have noticed some APIs had gone through TAG review but don't support BFCache.

One thing we decided to do is to rewrite the [Design Principles guide](https://w3ctag.github.io/design-principles/#support-non-fully-active) and [Security & Privacy Questionnaire question](https://www.w3.org/TR/security-privacy-questionnaire/#non-fully-active) to be simpler and more explicit, and move the full BFCache guide into a separate document, like the [Promise Guide](https://www.w3.org/2001/tag/doc/promises-guide). I've finished rewriting the guide (with lots of input from @domenic, @fergald, and @cynthia) and can be found here:
* Security & Privacy Questionnaire: [HTML version](https://rakina.github.io/security-questionnaire/), [Google Docs version](https://docs.google.com/document/d/1jE7qIBrctm778nUyzHAlrs-v8TK90vJnXSxgw0rx8Dw/edit#heading=h.y3vaaqr2n1hj), [Draft PR](https://github.com/w3ctag/security-questionnaire/pull/144)
* Design Principles: [HTML version](https://rakina.github.io/design-principles/), [Google Docs version](https://docs.google.com/document/d/1jE7qIBrctm778nUyzHAlrs-v8TK90vJnXSxgw0rx8Dw/edit#heading=h.u8nqs4k0yd5i), [Draft PR](https://github.com/w3ctag/design-principles/pull/392)
* New "Supporting BFCached Documents" doc: [HTML version](https://rakina.github.io/bfcache-guide/),  [Google Docs version](https://docs.google.com/document/d/1jE7qIBrctm778nUyzHAlrs-v8TK90vJnXSxgw0rx8Dw/edit#heading=h.6grduywchojv). Not really sure how to make a PR for this since it's a brand new doc. Any suggestions?

We're hoping the TAG will reopen this issue to review the rewritten docs (cc @hober and @torgo). We also realized that the docs didn't get reviewed by other browser vendors last time, so tagging @smaug---- and @cdumez (or other BFCache folks from Mozilla/Apple) to review the new documents.

Other ideas that came up during the TAG F2F was:
* Adding an explicit "BFCache considerations" section to specs, which @domenic is trying out with some new specs we're working on, we'll see if we can get that be a required section for new specs.
* Improvements to the TAG design review process to be more consistent and follow the latest guidelines. I don't really have much visibility into this, but looking forward to seeing the improvements!

**Comment by rakina** [comment]
Friendly ping for reviews :) (should this issue be re-opened?) cc ) @cynthia @hober @torgo
