### ISSUE TITLE
Partitioning Storage, Service Workers, and Communication APIs

### ISSUE THREAD

**Issue by wanderview** [w3ctag/design-reviews#629]
Ya ya yawm TAG!

I'm requesting a TAG review of Partitioning Storage, Service Workers, and Communication APIs.

This effort proposes that a number of web platforms APIs used for storage and communication should be partitioned in 3rd party contexts. In this context "partitioned" means that in addition to being isolated by the same-origin policy, the affected APIs in 3rd party contexts would also be separated by the site of the top-level context.

  - Explainer: https://github.com/wanderview/quota-storage-partitioning/blob/main/explainer.md
  - Security and Privacy self-review²: https://github.com/wanderview/quota-storage-partitioning/blob/main/tag-security-privacy.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/wanderview/quota-storage-partitioning
  - Primary contacts (and their relationship to the specification):
      - Ben Kelly (@wanderview), Marijn Kruisselbrink (@mkruisselbrink)
  - Organization/project driving the design: Chromium
  - External status/issue trackers for this feature: https://chromestatus.com/feature/5723617717387264

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): WICG
  - The group where standardization of this work is intended to be done ("unknown" if not known): The individual working groups that own each API (service workers wg, web apps wg, whatwg, etc)
  - Existing major pieces of multi-stakeholder review or discussion of this design:
  - Major unresolved issues with or opposition to this design:
  - This work is being funded by:

You should also know that...

[please tell us anything you think is relevant to this review]

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by plinss** [comment]
@ylafon and I looked at this today during a breakout session, we're satisfied with the current approach but want to get further input from other TAG members.

**Comment by hober** [comment]
Thanks for bringing this to us for review. We're happy to see that engineers who work on all three engines are involved or are being consulted, and that there's a real effort to converge on one, interoperable partitioning model. Please do request another review in the future if your approach substantively changes!
