### ISSUE TITLE
Pre CR review request of CSS Multi-column layout Level 1

### ISSUE THREAD

**Issue by rachelandrew** [w3ctag/design-reviews#634]
Ya ya yawm TAG!

I'm requesting a TAG review of the CSS Multi-column layout module. I would like to be able to take this spec back to CR, and have review requests in to all of the horizontal review groups.

CSS Multi-column Layout is a module of CSS that adds support for multi-column layouts. Support is included for establishing the number of columns in a layout, as well as how content should flow from column to column, gap sizes between columns, and column dividing lines (known as column rules) along with their appearance.

  - Explainer¹ (minimally containing user needs and example code): https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns (as multicol is essentially a mature spec, see notes below, I have linked to the user facing documentation I have written for MDN)
  - Specification URL: https://www.w3.org/TR/css-multicol-1/
  - Tests: https://wpt.fyi/results/css/css-multicol
  - Security and Privacy self-review²: no issues found
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/csswg-drafts/issues
  - Primary contacts (and their relationship to the specification):
      - Rachel Andrew, @rachelandrew, Florian Rivoal, @frivoal
  - Organization(s)/project(s) driving the specification: CSSWG
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: 
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): CSSWG
  - Major unresolved issues with or opposition to this specification: none
  - This work is being funded by: no one

You should also know that...

CSS Multicol is a fairly old spec and was in CR when I started working on it, As there had been no updates for several years so the CSSWG resolved to take it back to WD status. It has almost complete implementation in browsers, and is also heavily used by print User Agents. Most of the reported interop issues with multicol at this point are actually fragmentation issues.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by torgo** [comment]
Hi @rachelandrew we are just taking a look at this in our TAG breakout this morning. We're trying to figure out how we can best add value. It doesn't look like there's much for us to do. You mentioned interop issues - can you be more specific?  Is there something you would specifically like the TAG's opinion on here? Otherwise we think this is proabbly good to go and we'll close this issue.

**Comment by rachelandrew** [comment]
Hi @torgo I don't think there is much for you here. 

Interop/lack of support issues tend to relate to Fragmentation and the `break-before`, `break-after` and `break-inside` properties. For example, right now Can I Use flags partial implementation, due to fragmentation issues (I have raised an issue about that https://github.com/Fyrd/caniuse/issues/5903).

**Comment by LeaVerou** [comment]
Hi @rachelandrew,

We looked at this again in a breakout today. Given that multicol is a mature specification that has been shipped in browsers for almost a decade, we don't think there is much to do here.
If the CSS WG would like more eyes on the CSS Fragmentation module, that should be a separate review.

Thank you for flying TAG!

**Comment by rachelandrew** [comment]
thank you!
