### ISSUE TITLE
HTTP 103 Early Hints

### ISSUE THREAD

**Issue by bashi** [w3ctag/design-reviews#638]
Hi TAG!

I'm requesting a TAG review of HTTP 103 Early Hints.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/bashi/early-hints-explainer/blob/main/explainer.md
  - Specification URL (IETF): https://datatracker.ietf.org/doc/html/rfc8297
  - Tests: Plan to add WPTs once https://github.com/whatwg/fetch/issues/1225 is resolved.
  - Security and Privacy self-review²: https://docs.google.com/document/d/1gCh_CnfrJq_VL7aGoq6skc7sn4yn5pKsM0gkHe5B9go/edit#heading=h.fhq04xt0tah6
  - Primary contacts (and their relationship to the specification): @bashi @yutakahirano
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://www.chromestatus.com/feature/4854144902889472

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: sometime around Aug/Sep would be helpful.
  - The group where the work on this specification is: IETF.

You should also know that...

  - Fastly's blog post that describes the motivation: https://www.fastly.com/blog/beyond-server-push-experimenting-with-the-103-early-hints-status-code

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @bashi

**Comment by torgo** [comment]
Hi! Quick request - can you please move the explainer over to a markdown file somewhere at a stable URL (e.g. somewhere on GitHub)?

**Comment by torgo** [comment]
We discussed today and agreed that as this is about implementation of an already reviewed IETF spec that we are happy with this. Thanks!
