### ISSUE TITLE
Resource Timing

### ISSUE THREAD

**Issue by caribouW3** [w3ctag/design-reviews#641]
Ya ya yawm TAG!

I'm requesting a TAG review of Resource Timing.

This is actually a request to confirm or amend previous review, as requested in the CR transition
https://github.com/w3c/transitions/issues/337#issuecomment-850633515

This specification was originally developed in levels, Level 1 has been a CR for a long time,
Level 2 has had a wide review draft in 2017. 

  - Explainer¹ (minimally containing user needs and example code): giving the history of this spec, its scope is hopefully well-understood at this point. From the Director's comment in the CR transition request, it seems that only recent additions would eventually need a review.
  - Specification URL: https://w3c.github.io/resource-timing/
  - Tests: [wpt folder(s), if available] https://wpt.fyi/results/resource-timing
  - Security and Privacy self-review²: https://w3c.github.io/perf-security-privacy/#privacy-and-security-considerations
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/resource-timing/issues
  - Primary contacts (and their relationship to the specification): @yoavweiss, @caribouW3
  - Organization(s)/project(s) driving the specification:  WebPerf WG

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

  💬 leave review feedback as a **comment in this issue** and @-notify [github usernames] 

Thank you!

**Comment by torgo** [comment]
Hi @caribouW3 can you please give us a bit more context on this review - specifically you mention that there have been "recent additions" that would require a re-review but can you please be specific about what those additions are and what kind of feedback you're seeking from the TAG on these?

**Comment by caribouW3** [comment]
Hi,
Apart from some editorial work and minor tweaks, I suppose the most interesting part for this TAG review would be in section 4.5 Cross-Origin Resources.

**Comment by cynthia** [comment]
@kenchris and I discussed this today in our VF2F and we are happy with the changes. (Given that it is only 4.5 that changed) Thank you for bringing this to our attention.
