### ISSUE TITLE
Performance Timeline

### ISSUE THREAD

**Issue by caribouW3** [w3ctag/design-reviews#644]
Ya ya yawm TAG!

I'm requesting a TAG review of Performance Timeline.

This is actually a request to confirm or amend previous review, as requested in the CR transition
https://github.com/w3c/transitions/issues/339#issuecomment-850639142

This specification was originally developed in levels, Level 1 in REC in 2013,
Level 2 has had a wide review in 2016 before entering CR 
https://www.w3.org/TR/2016/CR-performance-timeline-2-20161208/
There is no fundamental change to the goals of the spec. The processing model is more detailed and
data structure updated.
We plan to drop levels and use a living standard development model (from process2020).

  - Explainer¹ (minimally containing user needs and example code): giving the history of this spec, its scope is hopefully well-understood at this point. From the Director's comment in the CR transition request, it seems that only recent changes would eventually need a review.
  - Specification URL: https://w3c.github.io/performance-timeline/
  - Tests: [wpt folder(s), if available] https://wpt.fyi/results/performance-timeline/
  - Security and Privacy self-review²: https://w3c.github.io/perf-security-privacy/#privacy-and-security-considerations
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/performance-timeline/issues
  - Primary contacts (and their relationship to the specification): @yoavweiss, @caribouW3
  - Organization(s)/project(s) driving the specification:  WebPerf WG

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

  💬 leave review feedback as a **comment in this issue** and @-notify [github usernames] 

Thank you!

**Comment by cynthia** [comment]
Thanks for bringing this to our attention (and sorry for the delay!) - we were curious if we could get a delta of the parts that we are supposed to review, so we don't nitpick at stuff that has already been shipped as CR. Thanks!

**Comment by kenchris** [comment]
As this is a Level 2, pointing out what changes were actually made would really help us. We might have comments to the existing parts of Level 1 but as those are shipping looking at those parts is not the best use of our time.

**Comment by torgo** [comment]
Hi @caribouW3 sorry but I think we really need to see an explainer here. The spec may be understood to the group working on it. However one of the points of "wide review" is that people who are unfamiliar with the spec review it (or at least review the delta) with fresh eyes. Can you please provide a little more info for us here? Otherwise we are going to close this as not satisfactory.

**Comment by npm1** [comment]
Explainer: https://github.com/w3c/performance-timeline/blob/gh-pages/explainer.md
Let me know if you have any questions or want me to expand on some part of it. Thanks.

**Comment by kenchris** [comment]
@cynthia and I looked though the changes and we don't have any concerns.

Thank you for the explainer!
