### ISSUE TITLE
MediaStream Image Capture (wide review)

### ISSUE THREAD

**Issue by caribouW3** [w3ctag/design-reviews#651]
Ya ya yawm TAG!

I'm requesting a TAG review of MediaStream Image Capture.

[One paragraph summary of idea, ideally copy-pasted from Explainer introduction]

Cameras on client platforms like mobile devices, tablets and laptops are increasingly adding advanced features. In many cases, users do use external cameras when the inbuilt cameras are not delivering the required experience, say on a video call. This specification exposes some of the advanced photography primitives in a standards compliant manner using media track constraints in MediaDevices.getUserMedia(). For manipulating video related capabilities, current settings and constraints are done via MediaStreamTrack.applyConstraints(). Photo-specific capabilities and current settings can be retrieved via getPhotoCapabilities()/getPhotoSettings() and configured via takePhoto()'s PhotoSettings argument. The produced image can be in the form of a Blob or as a ImageBitmap.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/w3c/mediacapture-image/blob/main/explainer.md
  - Specification URL: https://w3c.github.io/mediacapture-image/
  - Tests: [wpt folder(s), if available] https://wpt.fyi/results/mediacapture-image
  - Security and Privacy self-review²: https://github.com/w3c/mediacapture-image/blob/main/security-privacy-questionnaire.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/mediacapture-image
  - Primary contacts (and their relationship to the specification):
      - @caribouW3, Rijubrata Bhaumik @riju (Intel), Miguel Casas-Sanchez (Google)
  - Organization(s)/project(s) driving the specification: [organization and/or project name] W3C WebRTC WG
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://github.com/w3c/mediacapture-image/blob/main/implementation-status.md

We'd prefer the TAG provide feedback as (please delete all but the desired option): GH issues

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by plinss** [comment]
I'm wondering why the PhotoSettings passed to takePhoto only allow control over resolution and flash modes. Couldn't some of the other settings potentially be selected only for the photo without changing the underlying stream? e.g. exposure controls, white balance, etc

**Comment by atanassov** [comment]
@plinss and I looked at this review again during our Gethen vf2f. We like use cases addressed by this proposed capability and the overall shape of the API. Apart from the [one feedback that we cross-posted ](https://github.com/w3c/mediacapture-image/issues/288) to your repo we are happy to close the review.

Thank you for working with TAG. We look forward to seeing further progress made with the WebRTC folks.
