### ISSUE TITLE
MSE-in-Workers

### ISSUE THREAD

**Issue by wolenetz** [w3ctag/design-reviews#656]
Ya ya yawm TAG!

I'm requesting a TAG review of MSE-in-Workers.

Enable Media Source Extensions (MSE) API usage from DedicatedWorker contexts to enable improved performance of buffering media for playback by an HTMLMediaElement on the main Window context. By creating a MediaSource object on a DedicatedWorker context, an application may then create an ObjectURL for it and postMessage that URL to the main thread for use in attaching to an HTMLMediaElement. The context that created the MediaSource object may then use it to buffer media.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/wicg/media-source/blob/mse-in-workers-using-handle/mse-in-workers-using-handle-explainer.md
  - Specification URL: (as a PR to the main MSE specification): https://github.com/w3c/media-source/pull/282
  - Tests: WPT: media-source/dedicated-worker/*
  - Security and Privacy self-review²: https://github.com/w3c/media-source/blob/main/wolenetz-w3ctag-security_and_privacy_questionnaire-mse-in-workers.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/media-source
  - Primary contacts (and their relationship to the specification):
      - Matthew Wolenetz (@wolenetz, Google Inc.) - editor
      - Mark Watson (@mwatson2, Netflix Inc.) - editor
      - Chris Needham (@chrisn, BBC) - Media WG chair
      - Jer Noble (@jernoble, Apple) - Media WG chair
  - Organization(s)/project(s) driving the specification: W3C Media WG: https://www.w3.org/media-wg/
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
      - Much discussion on the main MSE issue tracking this feature: https://github.com/w3c/media-source/issues/175 
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):
      - https://chromestatus.com/feature/5177263249162240
      - https://github.com/w3c/media-source/issues/175

Further details:

  - [ x ] I have reviewed the TAG's [Web Platform Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: This feature is expected to be part of the MSE v2 specification, whose editor's draft will be entering FPWD soon.
  - The group where the work on this specification is currently being done: https://www.w3.org/media-wg/
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): https://www.w3.org/media-wg/
  - Major unresolved issues with or opposition to this specification: None.
  - This work is being funded by: N/A

We'd prefer the TAG provide feedback as:

  🐛 open issues in our GitHub repo for **each point of feedback**, with issue title prefix "MSE-in-Workers:".

**Comment by atanassov** [comment]
@hober and I looked at this proposal during our Gethen virtual f2f. The explainer and security & privacy questionnaire are really easy to follow. We especially appreciated the open questions discussion and the overall clarity of the explainer.

We are happy to close the review as satisfied. Good luck in further experimentations in shipping the feature alongside the Media WG. Thank you for working with us.
