### ISSUE TITLE
Pre-CR review: HTML Review Draft — Published 18 January 2021

### ISSUE THREAD

**Issue by siusin** [w3ctag/design-reviews#657]
Ya ya yawm TAG!

I'm requesting a TAG review of [HTML Review Draft — Published 18 January 2021](https://html.spec.whatwg.org/review-drafts/2021-01/).

The WHATWG published a new Review Draft of the HTML Standard on 18 January 2021. The HTML WG plans to take the latest Review Draft to W3C Recommendation in September, thus we are inviting another wide and horizontal review of the commits of the HTML Standard between [Jan 2020](https://github.com/whatwg/html/commit/d22075cc8e66516c28e73d5efac2d565996d9a9d) and [Jan 2021](https://github.com/whatwg/html/commit/773de98aea71fa6813237a1813db4dff3102692c).

  - Specification URL: https://html.spec.whatwg.org/review-drafts/2021-01/
  - Tests: [wpt /html](https://wpt.fyi/results/html?label=experimental&label=master&aligned)
  - GitHub repo (if you prefer feedback filed there): https://github.com/whatwg/html/issues
  - Primary contacts (and their relationship to the specification):
      - @hober , HTML WG co-chair
      - @sideshowbarker
      - WHATWG HTML editors
  - Organization(s)/project(s) driving the specification: WHATWG & W3C
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
     [HTML Review Draft — Published 18 January 2021: review tracker](https://github.com/w3c/htmlwg/issues/17)

Further details:

  - Relevant time constraints or deadlines: 2021-08-24
  - The group where the work on this specification is currently being done: WHATWG and W3C HTML WG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): WHATWG and W3C HTML WG
  - This work is being funded by: WHATWG and W3C

We put together [a list of significant changes](https://github.com/w3c/htmlwg/issues/17), please pay attention to these pull requests during your group discussion:

- https://github.com/whatwg/html/commit/a5113415d28ece380dfc3c1c3c8063ceee610745
Add more checks when matching SharedWorkerGlobalScopes

- https://github.com/whatwg/html/commit/0283e9e5f349b107c745dbeb73034445a6b55796
Add <img loading=lazy> "lazy loading images”

- https://github.com/whatwg/html/commit/344798be98d699dc165e4731c1385781a49a94c8
Fix the entry settings object for promise callbacks

- https://github.com/whatwg/html/commit/f425515bb642ea1f622ab8cf85af07ed5c789bbc
Navigation: avoid processing a response twice

- https://github.com/whatwg/html/commit/9b8f6368747519b69a8cfd9cd1234c772d48a0f1
<img alt> is to be rendered as a replaced element

- https://github.com/whatwg/html/commit/7fe9953cf4e01c950654c9ca1e9412e4db669795
Stop mapping <iframe hspace/vspace> to style

- https://github.com/whatwg/html/commit/760a14428f052d1e893fa4130fbc545b132d87cf
BroadcastChannel: move destination close flag

- https://github.com/whatwg/html/commit/9d7a82ce548a0c029d20d8e288c6b011db5b2042
Add connected check to input/change events for checkboxes/radios

- https://github.com/whatwg/html/commit/916a923a70450cb549cd0613f3227282e0697f11
- Define the top-level origin of an environment settings object

- https://github.com/whatwg/html/commit/7eef5372ce7b165cce23b6b43a3e893151f1896c
Remove one "mark paint timing call" in update the rendering

- https://github.com/whatwg/html/commit/c747ce0c403d6d3172432a8ee089263db4d74578
Fire an error event for parse errors when constructing SharedWorker

- https://github.com/whatwg/html/commit/203842ab70fbb158726a303feba6cafb3499452e
Layering: Implement HostEnqueuePromiseJob

- https://github.com/whatwg/html/commit/2053069ca8dc2b46742ced2a9362d608cbcc8c88
Note how orientation metadata affects naturalWidth/Height

- https://github.com/whatwg/html/commit/80e087c48b6fb15540cbe3e0805f36cb0c1996e9
Do not throw when cloning %ObjectPrototype%

- https://github.com/whatwg/html/commit/c76e86cee30e834562ecf4c4b5cf9edbf3a1356b
Convert  "queue a task" to "queue an element task"

- https://github.com/whatwg/html/commit/cd59059ceeab9266cf0dd81db869b50697078f3d
Clean up the event loop and agent correspondence

- https://github.com/whatwg/html/commit/12a2a56a41b9f141e04b705fba2c9bbc949b349b
Make all agent allocation imperative

- https://github.com/whatwg/html/commit/b954ac0190adfeafe85afeefb1a9b115c03d5345
Change "scripting is disabled" to be per-global

- https://github.com/whatwg/html/commit/5e7d60696452760d6531debdd0c14d474dcee7f3
Disentangle images loading on-demand from scripting

- https://github.com/whatwg/html/commit/af228b2a3018c5ae0f280550ff995905248cc0e5
Remove the title argument from registerProtocolHandler()

- https://github.com/whatwg/html/commit/6144c0ce7606d500cf7563f8789ede23c80e932c
Prevent execution of (some) scripts moving between documents

- https://github.com/whatwg/html/commit/caebee38fb9dc9d02033b6f2283f302af31285f6
Stop dispatching invalid on <form>

- https://github.com/whatwg/html/commit/49962baf46f2cb2616880d5b3bf836651fd14aa1
Define height attribute for thead, tbody, and tfoot elements

- https://github.com/whatwg/html/commit/72a6f175d1cd17b2202b1c9eda864d1769b0fd40
registerProtocolHandler(): only "https" schemes for the handler

- https://github.com/whatwg/html/commit/9deddcd6d4c4a9a76b7c3d324c762830d16eb7eb
registerProtocolHandler() cleanup

- https://github.com/whatwg/html/commit/351d56a84a37dbb15e52b3152eae06c0f75e0ae0
Specify image lazy loading in terms of IntersectionObserver

- https://github.com/whatwg/html/commit/9e7788790dc2f9e3c6ea255f44385b37689b0aad
Add `<link disabled>`

- https://github.com/whatwg/html/commit/bb0bcac25b289b46c3f39681fb83bc8ee5d97eca
Fix sandboxing flags handling in browsing context creation

- https://github.com/whatwg/html/commit/f913be0c444198c6e675dc8df3bce4a4640b0ee3
Expose Worker and SharedWorker less

- https://github.com/whatwg/html/commit/db2ce7e9686b08234c7b0e8e3cb9a89a8491c788
Change request destinations of nested navigations

- https://github.com/whatwg/html/commit/31b264a56253e7b047d1cc6a02a4c6337dd6cff5
Redo top-level origin and add top-level creation URL

- https://github.com/whatwg/html/commit/c9fddd7082cd2b926f7081cd276c842b09304392
Add cross-origin opener policy

- https://github.com/whatwg/html/commit/70b8bb4e8bbd529229a3c2f2c12a41b1db5b69db
Add cross-origin embedder policy

- https://github.com/whatwg/html/commit/bb864bda06da398db6709b7f6400559ed8437254
Define "secure context”

- https://github.com/whatwg/html/commit/c9d8983a8b78d226d5959dd58711790f4049959a
Add the cross-origin isolated primitive

- https://github.com/whatwg/html/commit/231538d6e38024ee5bdf0d7d62964148dee59d9c
Add <iframe> lazyloading

- https://github.com/whatwg/html/commit/a2294a9c4205104d70440ab3aa8077cf309d2a9b
Change MessagePort owner from incumbent to current

- https://github.com/whatwg/html/commit/81d7284d82395816786b96218864c8f3460ada38
Add the manifest link relation

- https://github.com/whatwg/html/commit/63a0e646cdce30524b1bf0b4f064fea2b2f728d8
Fire a load event for network errors in <embed>

- https://github.com/whatwg/html/commit/898a25e4af2c59fe05c405df6f4d9d27a1308fc9
Introduce the navigation params struct

- https://github.com/whatwg/html/commit/82a07842d62eeb01895b09cf4a229c3f3855f7b2
Do not delay the load event for aborted media loads

- https://github.com/whatwg/html/commit/ac285c08eabeb4ab131dfc23b8dea21a3cbfc01e
Sanitize classic script's base URL when muted errors flag is set

- https://github.com/whatwg/html/commit/230af41003ee12fa086f4258689d33da58303ba5
Adjust registerProtocolHandler() handling

- https://github.com/whatwg/html/commit/c7c6b1726e06da15cfb0117c4d125197b6bcf70a
Remove HTTPS state

- https://github.com/whatwg/html/commit/2333203fe0b4900d3f2d8bd654c4af954f35869a
Add preservesPitch to HTMLMediaElement

- https://github.com/whatwg/html/commit/a1ad979f4ada802801a1549d2c89d10d92556c17
Extend "window open steps" to observe COOP

- https://github.com/whatwg/html/commit/4191e0c5bddf85658264a2439c422d2a962a2394
Define the foundations of find-in-page

- https://github.com/whatwg/html/commit/e991e2f42cdcaef8b7ad2a51066672c3b3b4b58b
Remove user override of window.open() in a sandbox

- https://github.com/whatwg/html/commit/f781a90bd611e15ac849e8c7f80f0c3ec8b3ec41
Introduce the "cross-origin-isolated” permission

- https://github.com/whatwg/html/commit/97c73c3d73057b9186181acb503c7607c37015fe
Add MIME type checking for HTTP(S) worker scripts

- https://github.com/whatwg/html/commit/40e3868b09f17fc12860596b990bb56bc5cc2a3f
Remove the dragexit event

- https://github.com/whatwg/html/commit/3c52fe139d9c637eb901932a77d743d6d5ecaa56
Allow mutating <input disabled type=checkbox/radio>

- https://github.com/whatwg/html/commit/539f4e816bfed0098222db2eee5ab8416128e7cb
Fix contradictory missing value default for formmethod=“"

- https://github.com/whatwg/html/commit/b417e8892e93af99d83028e105bf1005fd165697
Fire "input" events as composed

- https://github.com/whatwg/html/commit/bd32618232114578187fb4384fed6ad932fc72bb
Define X-Frame-Options processing

- https://github.com/whatwg/html/commit/8c90eb64dd562517c3924e35f0a3fb370b7a090a
Augment COEP violation report

- https://github.com/whatwg/html/commit/d37f992de1523f4942cca7f3d1d93cfb509d13f8
Add the Origin-Isolation header

- https://github.com/whatwg/html/commit/ea6b0caa3c7602c65d8a87ad3ded4dd359461f44
Specify sequence of navigation failure checks

- https://github.com/whatwg/html/commit/c8d5ad32c2edc8e05ac0e5d5fc3e5099f9846213
Set "destination" of requests from <link rel=icon>

- https://github.com/whatwg/html/commit/ed61fda996cf422f5097a7bd4c2d152ca601fcce
Resolve whenDefined()'s promise with the element's constructor

- https://github.com/whatwg/html/commit/7d852a34877f3ff90d0e41e96c6a3e9bdedae121
COOP: modify redirect handling

- https://github.com/whatwg/html/commit/804da31a611d2940208bfd00832f9486ba3e74b6
Remove width attribute fallback from sizes calculation

- https://github.com/whatwg/html/commit/140dd67172e5c6c3a0043ac0e40a013662c0e600
Remove allowpaymentrequest attribute

- https://github.com/whatwg/html/commit/16667c370e29d9be8d4e24886c27a10f0189bb11
Prevent attachInternals() use before custom element constructor

- https://github.com/whatwg/html/commit/564dfd55844ae3b59083ee76e6991818aa3881f7
Add shadowRoot to ElementInternals

- https://github.com/whatwg/html/commit/1076db6d23116e0d18c7bc9a0bc596cb733382cd
Rendering: further details/summary cleanup

- https://github.com/whatwg/html/commit/b3b7add4cfb9d731764c240a76541b0362c81c30
Change beforeunload, unload, and bfcache interaction

- https://github.com/whatwg/html/commit/25c78e4b71d9afaa6ff9d731afa53fbd9f345318
Move worklets into the HTML Standard
https://github.com/whatwg/html/commit/f703a2c1d55ebe44eaf94ac018eb7cc109ff7bdf
Allow implementations to kill worklets whenever, by default
https://github.com/whatwg/html/commit/de47fa3d65b3b8f57ef53d85f3f84f00c7a3f919
Disallow import() in worklets

- https://github.com/whatwg/html/commit/440fde89f6d0643ecddd67c97e55b08b968b3fd5
Suggest a rootMargin strategy for lazy-loaded elements

- https://github.com/whatwg/html/commit/979af1532b8045f84ec4a430124657064806e095
Change modal <dialog>s to be positioned via CSS

- https://github.com/whatwg/html/commit/a2d27c62bd2b183de3a5f2ba26707cfa75063a05
Stop passing CSP algorithms unused parameters

- https://github.com/whatwg/html/commit/d324d9b76b515efca80d386452c99c3119203a4a
Make the default "process the linked resource" algorithm a noop

- https://github.com/whatwg/html/commit/0666f4eb58c8396bab5e6d529800c5effb8158a8
Add cross-origin opener policy reporting

- https://github.com/whatwg/html/commit/2ae50c688689a5f3ab4e0834140663a6e6ea02f7
Fix regression in iframe/frame loading

- https://github.com/whatwg/html/commit/e4330d510a1d05e1f5f84707c9d6dcec97db94b8
Remove AppCache

- https://github.com/whatwg/html/commit/65b2af51897b10130f7a6cb2b403cc096b924265
Gate beforeunload dialogs behind sticky activation

- https://github.com/whatwg/html/commit/fee73fa967233a450ea0f604e9802a0b1cd34991
Top-level await integration

- https://github.com/whatwg/html/commit/07a5b3e4d5edf4c2867a3bc8a42832ce101f4080
Introduce the system focus concept

- https://github.com/whatwg/html/commit/cbcf6ac32e1b4ef85a78a6d93350303bbe598294
Make COOP+COEP not imply cross-origin isolated

- https://github.com/whatwg/html/commit/4b6e5ba1ef64a6fd09f7852f152d8664edc05ca2
Reset window.name also when opener is set to null

You should also know that...

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by LeaVerou** [comment]
Hi @siusin, apologies for the late reply. We understand this is widely implemented by now, and we have confidence in the WHATWG that all of the features have been adequately vetted so we are going to close this.

Furthermore, after discussing this in a breakout today (present: @cynthia @rhiaro and me) we do not think it's productive to do such large reviews, at such a late stage. They demand a lot of resources, but it's too late for the effort to make a meaningful difference. Please instead ask for reviews of individual features earlier, before they are so widely implemented.
