### ISSUE TITLE
Pre-CR review: DOM Review Draft — Published 21 June 2021

### ISSUE THREAD

**Issue by siusin** [w3ctag/design-reviews#658]
Ya ya yawm TAG!

I'm requesting a TAG review of [DOM Review Draft — Published 21 June 2021](https://dom.spec.whatwg.org/review-drafts/2021-06/).

The WHATWG published a new Review Draft of the DOM Standard on 21 June 2021. The HTML WG plans to take the latest Review Draft to W3C Recommendation in September, thus we are inviting another wide and horizontal review of the commits of the DOM Standard between Jun 2020 and Jun 2021.

  - Specification URL: https://dom.spec.whatwg.org/review-drafts/2021-06/
  - Tests: [wpt/dom](https://wpt.fyi/results/dom?label=experimental&label=master&aligned)
  - GitHub repo (if you prefer feedback filed there): https://github.com/whatwg/dom/issues
  - Primary contacts (and their relationship to the specification):
      - @hober , HTML WG co-chair
      - @sideshowbarker
      - WHATWG DOM editors
  - Organization(s)/project(s) driving the specification: WHATWG & W3C
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
     [Wide Review for the DOM Review Draft — Published 21 June 2021](https://github.com/w3c/htmlwg/issues/19)

Further details:

  - Relevant time constraints or deadlines: 2021-08-31
  - The group where the work on this specification is currently being done: WHATWG and W3C HTML WG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): WHATWG and W3C HTML WG
  - This work is being funded by: WHATWG and W3C

We put together [a list of significant changes](https://github.com/w3c/htmlwg/issues/19), please pay attention to these pull requests during your group discussion:
  - https://github.com/whatwg/dom/commit/12beda246fe9efa4d6dcb0545be81ba6a9529d87
  DOM Events introduction: clarify how listeners are invoked
  
  - https://github.com/whatwg/dom/commit/f837ce19d0540bfba76e038070e006a33d419ba1
  Add "precustomized" custom element state
  
  - https://github.com/whatwg/dom/commit/8c0049e8163693fe31d186f1d37937da091a6ffc
  Add "is available to element internals"
  
  - https://github.com/whatwg/dom/commit/52f7a52fe9d2acefee4203c6b53564e246c501be
  Need to catch exceptions to report them
  
  - https://github.com/whatwg/dom/commit/83037a112f3f78f071e9c3ad7d979e85dc7e7283
  Add signal support to addEventListener()
  
  - https://github.com/whatwg/dom/commit/aa384af67fbf8862c5ee2ed09dc7afb6696a48ae
  Add AbortSignal.abort() static method
  
  - https://github.com/whatwg/dom/commit/c80cbf52b351609b3a107bb2d047d6377ffafbf9
  Use a single exception for name validation (follow-up)
  
  - https://github.com/whatwg/dom/commit/acfe96ba18ae62a46c4509de7ab1dc26e122223d
  Add imperative slot assignment API
  
  - https://github.com/whatwg/dom/commit/d2c84ec3462fe01383d0274aab9e65d54e33eacd
  Add the IDL of XSLTProcessor
  
  - https://github.com/whatwg/dom/commit/f346858acfdb5ce30dfbad4c1383db2245b7f5ff
  Add ShadowRoot.prototype.delegatesFocus attribute

**Comment by LeaVerou** [comment]
Hi @siusin,

@plinss and looked at this today during our virtual f2f.

We had some questions:

- We see references to a new "precustomized" state for custom elements, but we did not find a definition of what this state means, and how do you get there. It seems to be completely undefined.
- There is an "is available to element internals" flag, but no definition of what it means
- If `shadowRoot` is available to internals, is there a difference between `this.shadowRoot` and `this.internals.shadowRoot` or do they point to the same thing?
- We see a new `delegatesFocus` property has been added on `ShadowRoot`, but there is no description of what it's supposed to do. By looking around we found [this](https://html.spec.whatwg.org/multipage/interaction.html#data-model), but it's still unclear what use cases it solves and what exactly it does.

The rest of the changes seem fine.

**Comment by annevk** [comment]
Could you please file these as issues against whatwg/dom? Seems most of these should be easy to clarify with a couple of notes. Thanks!

**Comment by LeaVerou** [comment]
We posted them as questions here first in case they are explained somewhere in the spec and we just missed it. If not, we can definitely make new issues.

**Comment by annevk** [comment]
I think for "precustomized" there is a note that explains its purpose. It's essentially an implementation detail.

The others could do with some notes I think.

FWIW, `this.internals.shadowRoot` can point to a closed shadow tree. In which case `this.shadowRoot` would return null. In retrospect perhaps shadow roots should only have been exposed on custom elements, but not everyone is of that opinion.

**Comment by LeaVerou** [comment]
Hi @siusin, apologies for the late reply. We have provided some feedback above, but overall this looks good to us. We also understand this is widely implemented by now, which reduces the impact any review could have. Spec diffs are not an explainer, and do not contain [the information we need to review](https://tag.w3.org/explainers/).

Furthermore, after discussing this in a breakout today (present: @cynthia @rhiaro and me) we do not think it's productive to do such large reviews, at such a late stage. They demand a lot of resources, but it's too late for the effort to make a meaningful difference. Please instead ask for reviews of individual features earlier, before they are so widely implemented.

**Comment by annevk** [comment]
Will you still file issues for the desired clarifications?

**Comment by rhiaro** [comment]
I've copied Lea's questions over to the WHATWG DOM repo issues.

**Comment by annevk** [comment]
🙏🏻
