### ISSUE TITLE
Gamepad API input events

### ISSUE THREAD

**Issue by nondebug** [w3ctag/design-reviews#662]
Ya ya yawm TAG!

I'm requesting a TAG review of **Gamepad API input events.**

The [Gamepad API](https://www.w3.org/TR/gamepad/) requires applications to poll to detect new inputs. Many applications follow the spec's [recommendation](https://www.w3.org/TR/gamepad/#practice-timing) to coordinate polling with `requestAnimationFrame`. However, polling in this manner is likely to lose inputs since gamepads typically update more quickly than the animation frame rate. Polling will also increase average input latency by half the polling interval. This proposal addresses both the missed inputs and latency by adding input events that fire when the gamepad state has changed.

  - Explainer: [Gamepad API Button and Axis Events Explainer](https://github.com/w3c/gamepad/blob/button-axis-events-explainer/button-axis-events-explainer.md)
  - Specification URL: [Pull request](https://github.com/w3c/gamepad/pull/152) | [Preview](https://pr-preview.s3.amazonaws.com/w3c/gamepad/pull/152.html) | [Diff](https://pr-preview.s3.amazonaws.com/w3c/gamepad/152/bde81c8...bf1e7b2.html)
  - Tests: None yet, web platform tests will be added with the prototype implementation
  - Security and Privacy self-review: No security or privacy risks are expected since the events only expose data that is already available through the polling interface.
  - Primary contacts:
      - Matt Reynolds (@nondebug), Google, Spec editor, Implementer
      - James Hollyer (@jameshollyergoogle), Google, Spec editor, Implementer
  - Organization(s)/project(s) driving the specification: [Web Apps WG](https://www.w3.org/2019/webapps/)
  - Chrome Status: https://chromestatus.com/features/5989275208253440

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: none
  - The group where the work on this specification is currently being done: Gamepad API is part of the [Web Apps WG](https://www.w3.org/2019/webapps/)
  - Major unresolved issues with or opposition to this specification: Event spamminess, see below
  - This work is being funded by: Google

You should also know that...

Gamepads can potentially produce a lot of input events and we are interested in feedback on how to mitigate the spamminess of these events. Consider a DualShock 4 that has two 2-axis thumbsticks and updates at 1000 Hz. When both thumbsticks are moving it will generate 4 axis change events per input frame, or 4000 events per second. If the application allows events to queue then it will be handling stale inputs, adding input latency.

This is mostly an issue for analog axis inputs but also affects pressure-sensitive buttons and analog triggers.

We have some ideas for mitigating this: 

* Combine all the button and axis changes that occur within an input frame into a single event so that at most one event is fired per input frame. This is analogous to how the [PointerEvents API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events) combines the X and Y axes of a pointing device into a single event object. The downside is that applications only interested in one type of input (for instance, button presses) will still be notified for every other input.
* Don't allow events to queue. Always deliver the most recent data, but provide a method for retrieving events that were not delivered. This is analogous to [getCoalescedEvents](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/getCoalescedEvents) in the PointerEvents API.

See [here](https://docs.google.com/document/d/1rnQ1gU0iwPXbO7OvKS6KO9gyfpSdSQvKhK9_OkzUuKE) for more discussion on this proposal, the above mitigations, and comparison with the earlier Firefox implementation of these events.

We'd prefer the TAG provide feedback as:

  💬 leave review feedback as a **comment in this issue** and @-notify @nondebug and @jameshollyergoogle

**Comment by torgo** [comment]
Hi - we're just having a look at this today and on first pass it looks good. 👍 One question: what is the current status of any additional implementer support? Right now the ChromeStatus page says "unknown" for Safari and Firefox.

**Comment by kenchris** [comment]
Adaptive triggers is more than just controlling haptic feedback such as vibration. It is also about having non-binary values for buttons. Like a machine gun (in a game) might start shooting faster and faster the longer down you press the button.

Adaptive triggers can also allow developers to configure the tension the user will experience as they press the button:

https://www.theverge.com/2020/11/3/21547303/sony-ps5-dualsense-adaptive-triggers-haptics-teardown-features

**Comment by kenchris** [comment]
Other comments: 

* `ongamepadchange` sounds like the gamepad itself is being changed. I think `"onchange"` or `"oninputchange"` would be better names.
* If you have `oninputchange`, I don't think we should add `onbuttondown` and `onbuttonup` - It is better to teach developers to actually just use the other event. I don't think `onbutton*` adds any convenience - but they might add confusion

**Comment by kenchris** [comment]
> rawgamepadchange is dispatched if any button or axis state has changed. When multiple changes occur at the same time, one event is dispatched that encapsulates all the changes.

> A fourth gamepadchange event is proposed that is created whenever a rawgamepadchange event would be dispatched and placed into an internal queue. The event may be dispatched immediately or delayed for performance reasons. Queued events must be dispatched before animation callbacks are run and before a buttondown or buttonup event is dispatched for that gamepad.

That is very complex and I would *never* have guess that was the behavior from the event names.

Also, events cannot have side-effects so you would have to have the implementation be prepared to dispatch both events at all times. Listeners to one event type cannot change how events are being dispatched internally.

Are there strong cases to be able to configure how events are being dispatched? If not, please just choose one. If you really need it, then couldn't this be configured with a method instead, with a sane default.

**Comment by nondebug** [comment]
Thanks for the comments, @kenchris

> Are there strong cases to be able to configure how events are being dispatched? If not, please just choose one.

There's a strong case to dispatch input events immediately to support streaming game clients. For cloud gaming, inputs need to be uploaded with minimal latency. The `rawgamepadchange` event is intended to satisfy that use case and any other case where low latency is needed. Currently, the only "good" way to do this is to poll `getGamepads()` as quickly as possible, which still adds a small amount of latency. Events tied to the animation frame loop aren't useful for this use case because they add latency, on average half the interval between animation frames which will always be worse than rapid polling.

The case for having a coalesced `gamepadchange` event is that there can potentially be a huge number of `rawgamepadchange` events. The input rate is determined by the gamepad hardware, not the user agent. If script can't keep up with the events then they'll queue and add latency. By flushing all events any time one event is fired, script is always processing fresh input data but still has access to all the historical input data since the last event. Synchronizing on the animation frame callback is convenient because that's where most applications currently process gamepad inputs.

> If you really need it, then couldn't this be configured with a method instead, with a sane default.

I think configuring the dispatch behavior with a method on the Gamepad object could work. Probably `gamepadchange`'s coalescing behavior should be default so the user agent can control the event rate if needed. Changing from a coalescing mode to a non-coalescing mode should flush pending events to ensure no inputs are lost.

Is there any precedent for configuring the event dispatch behavior after an event listener is registered?

> Also, events cannot have side-effects so you would have to have the implementation be prepared to dispatch both events at all times. Listeners to one event type cannot change how events are being dispatched internally.

I may have worded this confusingly, I want to specify the same behavior as in Pointer Events where "The user agent MUST fire a pointer event named [pointermove](https://www.w3.org/TR/pointerevents3/#the-pointermove-event) when a pointer changes button state." The intent is to flush the `gamepadchange` queue whenever a button's `pressed` attribute changes regardless of whether any event listeners are registered.

> If you have oninputchange, I don't think we should add onbuttondown and onbuttonup - It is better to teach developers to actually just use the other event. I don't think onbutton* adds any convenience - but they might add confusion

I agree, if the `gamepadchange` overhead is tolerable then `buttondown` and `buttonup` don't add much. I think it's reasonable to drop them.

> Adaptive triggers is more than just controlling haptic feedback such as vibration. It is also about having non-binary values for buttons. Like a machine gun (in a game) might start shooting faster and faster the longer down you press the button.

I may have misunderstood your original suggestion. Non-binary button values have always been supported by Gamepad API and in this proposal we'd fire a change event whenever a trigger value changes. I've only heard the term "adaptive triggers" used in the context of DualSense's adjustable tension.

I think you're suggesting `buttondown` and `buttonup` could be generalized in a way that better supports non-binary buttons. Instead of firing a single `buttondown` when the trigger value crosses the button press threshold, we would fire multiple `buttonpress` events as the value increases.

If we're dropping `buttondown` and `buttonup` then this is moot.

**Comment by kenchris** [comment]
> Is there any precedent for configuring the event dispatch behavior after an event listener is registered?

@domenic do you know of such a case, or do you have any other comments regarding this?

**Comment by torgo** [comment]
@nondebug one process issue - can you please move the explainer over to w3 space (webapps wg repo) along with the spec?

**Comment by kenchris** [comment]
Maybe we could do something like `addEventListener("gamepadchange", callback, { coalesce: false })`

Event listeners already have options like `once: true`

**Comment by kenchris** [comment]
I am not a fan of having two different event handlers when you are only supposed to use one of them and choose. Also, as they deliver data differently you can argue that they are not side effect free (as they configure this change) and that is thus against the web design principles (as Anne pointed out).

The Generic Sensor API works around this by having `start()` and `stop()` methods and `start()` can take arguments, so you could do something like `start( { coalesce: false })`

**Comment by torgo** [comment]
Hi @nondebug any feedback on the above?

**Comment by nondebug** [comment]
> Maybe we could do something like addEventListener("gamepadchange", callback, { coalesce: false })

I like this.

> The Generic Sensor API works around this by having start() and stop() methods

With Generic Sensor you can create a new sensor object for each consumer but for Gamepad all consumers always see the same Gamepad object. We'd need to add a Gamepad.getGamepadSensor() method to return something that can be unique for each consumer so we can call its start() and stop() without interfering with other consumers. This could work but it seems overly complex to me.

**Comment by cynthia** [comment]
> We'd need to add a Gamepad.getGamepadSensor() method to return something that can be unique for each consumer so we can call its start() and stop() without interfering with other consumers. This could work but it seems overly complex to me.

Understood. Thanks for clarifying - I think this is something that we may want to revisit if there are user needs in the future. For now, based on our last breakout discussion we think it's fine to move forward with this proposal as is.

Thank you for bringing this to our attention!
