### ISSUE TITLE
Review of AccessHandles for the Origin Private File System 

### ISSUE THREAD

**Issue by fivedots** [w3ctag/design-reviews#664]
Ya ya yawm TAG!

I'm requesting a TAG review of AccessHandles for the Origin Private File System.

We propose augmenting the Origin Private File System (OPFS) with a new surface that brings very performant access to data. This new surface differs from existing ones by offering in-place and exclusive write access to a file’s content. This change, along with the ability to consistently read unflushed modifications and the availability of a synchronous variant on dedicated workers, significantly improves performance and unblocks new use cases for the File System Access API.

  - Explainer: https://github.com/WICG/file-system-access/blob/main/AccessHandle.md
  - Security and Privacy self-review: https://github.com/WICG/file-system-access/blob/main/security-privacy-questionnaire.md (no update was necessary to the existing File System Access API questionnaire)
  - Primary contacts:
      - Emanuel Krivoy (@fivedots), Google Inc., specifier / implementer
      - Richard Stotz (@rstz), Google Inc., specifier / implementer
  - Organization/project driving the design: Chromium
  - External status/issue trackers for this feature: https://www.chromestatus.com/feature/5702777582911488

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the incubation/design work on this is being done: WICG
  - The group where standardization of this work is intended to be done: unknown
  - Existing major pieces of multi-stakeholder review or discussion of this design:
      - Document with context and alternatives considered: https://docs.google.com/document/d/121OZpRk7bKSF7qU3kQLqAEUVSNxqREnE98malHYwWec
      - Document with first draft of the proposal: https://docs.google.com/document/d/1g7ZCqZ5NdiU7oqyCpsc2iZ7rRAY1ZXO-9VoG4LfP7fM
  - Major unresolved issues with or opposition to this design: none
  - This work is being funded by: Google Inc.

You should also know that...

A previous iteration of an API to cover these use cases has already gone through an early TAG review: #566. This new proposal is a response to feedback that NativeIO seemed to duplicate existing functionality and should be integrated into the File System Access API.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @fivedots and @rstz

**Comment by cynthia** [comment]
@kenchris and I looked at it during our breakout today, the proposal and problem statement looks good to us. We'll discuss this further in the plenary and see if we can close this. Thanks!

**Comment by cynthia** [comment]
We have one every week, but I missed the last one. There is one this week so I'll try to put it into the agenda.

**Comment by cynthia** [comment]
We discussed this during our VF2F, and group consensus was that this is good to go. Apologies for the delay, and thank you for bringing this to our attention!
