### ISSUE TITLE
review request, CSS Masking and Clipping

### ISSUE THREAD

**Issue by svgeesus** [w3ctag/design-reviews#665]
Unseasonably warm greetings, TAG!

I'm requesting a TAG review of [CSS Masking Module Level 1](https://drafts.fxtf.org/css-masking-1/).

Masking describes how to use another graphical element or image as a luminance or alpha mask. Typically, rendering an element via CSS or SVG can conceptually be described as if the element, including its children, are drawn into a buffer and then that buffer is composited into the element’s parent. Luminance and alpha masks influence the transparency of this buffer before the compositing stage. Clipping describes the visible region of visual elements. The region can be described by using certain SVG graphics elements or basic shapes. Anything outside of this region is not rendered.

  - Explainer¹ (minimally containing user needs and example code): [Intro has pretty pictures!](https://drafts.fxtf.org/css-masking-1/#intro)
  - Specification URL: [spec url](https://drafts.fxtf.org/css-masking-1/)
  - Tests: [wpt / css / css-masking](https://github.com/svgeesus/wpt/tree/master/css/css-masking) and [test results](https://test.csswg.org/harness/results/css-masking-1_dev/grouped/)
  - Security and Privacy self-review²: [here](https://github.com/w3c/fxtf-drafts/issues/432#issuecomment-893442363)
  - GitHub repo (if you prefer feedback filed there): [fxtf](https://github.com/w3c/fxtf-drafts/issues)
  - Primary contacts (and their relationship to the specification):
      - [Dirk Schulze] ([@dirkschulze]), [Adobe] Co-Editor
      - [Brian Birtles] ([@birtles]), [Mozilla Japan]  Co-Editor
      - [Tab Atkins] ([@tabatkins ]), [Google]  Co-Editor
      - [Chris Lilley] ([@svgeesus]), [W3C] Staff contact
      - [Alan Stearns] ([@astearns]), [Adobe] Co-chair
  - Organization(s)/project(s) driving the specification: [CSSWG, fx task force]
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): CanIUse [css mask](https://caniuse.com/css-masks) |  [css clip](https://caniuse.com/css-clip-path)

Further details:

  - [ x] I have reviewed the TAG's [Web Platform Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: [no rush, 3 months is fine, let us know]
  - The group where the work on this specification is currently being done: CSSWG
  - Major unresolved issues with or opposition to this specification: [issues list](https://github.com/w3c/fxtf-drafts/issues)
  - This work is being funded by: CSSWG member organizations

You should also know that...

- We will write an explainer if you really, really don't like the spec intro, but please tell us what is missing
- This functionality was in SVG for ages, but is now being extended and generalized to HTML/CSS as well

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by LeaVerou** [comment]
Hi @svgeesus,

We looked at this in our Gethen virtual f2f today. 

This looks good to us. While this is a mature specification and there is already a lot of content on the Web that discusses these features, we would ask that future design reviews include an explainer, especially if they are about earlier stage specs.

Thank you for flying TAG!
