### ISSUE TITLE
EME MediaKeySessionClosedReason

### ISSUE THREAD

**Issue by xhwang-chromium** [w3ctag/design-reviews#671]
Ya ya yawm TAG!

I'm requesting a TAG review of EME `MediaKeySessionClosedReason`.

The current EME spec says:
> "the CDM may close a session at any point, such as when the session is no longer needed or when system resources are lost." 

However, there's no way to specify the exact reason for session closure. In some cases, this is part of normal user flow, e.g. user close laptop lid to put the device into sleep mode, where the player should resume playback. In some other cases, this is due to some unrecoverable fatal error.

This proposal updates the `closed` attribute on `MediaKeySession` to provide a `MediaKeySessionClosedReason` so that the JavaScript player can handle session closure differently based on the reasons.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/w3c/encrypted-media/issues/473
  - Specification URL: https://w3c.github.io/encrypted-media/#dom-mediakeysessionclosedreason
  - Tests: media/encrypted-media/encrypted-media-session-closed-event.html
  - Security and Privacy self-review²: https://github.com/w3c/encrypted-media/issues/473#issuecomment-907509842
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/encrypted-media
  - Primary contacts (and their relationship to the specification):
      - Xiaohan Wang (@xhwang-chromium, Google Inc.)
      - Joey Parrish (@joeyparrish, Google Inc.) - editor
      - Greg Freedman (@gregwfreedman, Netflix Inc.) - editor
  - Organization(s)/project(s) driving the specification: W3C Media WG: https://www.w3.org/media-wg/
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
      - Spec discussion: https://github.com/w3c/encrypted-media/issues/473
      - W3C Media Working Group meeting discussion: https://lists.w3.org/Archives/Public/public-media-wg/2020Sep/0004.html
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):
      - https://github.com/w3c/encrypted-media/issues/473
      - https://www.chromestatus.com/feature/5632124143009792

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: I'd like to ship this feature by default in Chromium M96.
  - The group where the work on this specification is currently being done: https://www.w3.org/media-wg/
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): https://www.w3.org/media-wg/
  - Major unresolved issues with or opposition to this specification: None
  - This work is being funded by: N/A

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @xhwang-chromium

**Comment by cynthia** [comment]
(Setting aside all debate about whether or not EME should exist in the first place, since the cat is out of the box. For that bit, please refer to our [feedback from 2017](https://github.com/w3c/encrypted-media/issues/389).)

Given that this is a small incremental change to an existing spec that improves developer ergonomics, we are happy to see this move forward. Thanks for bringing this to our attention.

Noticed that the EME spec doesn't have a S&P section - think it would be worth adding something there (not just for this feature, but for EME as a whole) if possible.
