### ISSUE TITLE
WritableStream controller's AbortSignal

### ISSUE THREAD

**Issue by nidhijaju** [w3ctag/design-reviews#672]
Ya ya yawm TAG!

I'm requesting a TAG review of WritableStream controller's AbortSignal.

The streams APIs provide ubiquitous, interoperable primitives for creating, composing, and consuming streams of data. This change permits an underlying sink to rapidly abort an ongoing write or close when requested by the writer. Previously, when writer.abort() was called, a long-running write would still have to continue to completion before the stream could be aborted. With this change, the write can be aborted immediately. An underlying sink which doesn't observe the controller.signal will continue to have the existing behavior. In addition to being exposed to streams authored in JavaScript, this facility will also be used by platform-provided streams such as WebTransport.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/whatwg/streams/blob/main/writable-stream-abort-signal-explainer.md
  - Specification URL: https://streams.spec.whatwg.org/
     Specific Sections:
       - https://streams.spec.whatwg.org/#writablestreamdefaultcontroller-signal
       - https://streams.spec.whatwg.org/#writablestreamdefaultcontroller-abortreason
  - Tests: https://github.com/web-platform-tests/wpt/blob/master/streams/writable-streams/aborting.any.js
  - Security and Privacy self-review²: https://docs.google.com/document/d/1dOLMBME1_7Ht7EVAaLLEhC4VMdeuWoiY09sFYzGqARY/edit?usp=sharing
  - GitHub repo (if you prefer feedback filed there): https://github.com/whatwg/streams
  - Primary contacts (and their relationship to the specification):
      - Nidhi Jaju (@nidhijaju), Google, Spec Contributor
      - Adam Rice (@ricea), Google, Spec Editor
      - Yutaka Hirano (@yutakahirano), Google, Spec Contributor
  - Organization(s)/project(s) driving the specification: WHATWG
  - Key pieces of existing multi-stakeholder review or discussion of this specification: https://github.com/whatwg/streams/pull/1132, https://github.com/whatwg/streams/issues/1015
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5698931422920704

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: We are hoping to launch WebTransport in M96, which will use this API in [SendStream's write and close](https://w3c.github.io/webtransport/#sendstream).
  - The group where the work on this specification is currently being done: WHATWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): WHATWG
  - Major unresolved issues with or opposition to this specification: N/A
  - This work is being funded by: Google

You should also know that...

N/A

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by plinss** [comment]
@atanassov and I looked at this during our Gethen VF2F, overall this looks good. We're only wondering if the `abortReason` would be better served as an extension to `AbortController` and `AbortSignal` rather than being carried an a separate property.

**Comment by torgo** [comment]
Closing as we are satisfied that our feedback has been taken on board.
