### ISSUE TITLE
CSS Display Level 3

### ISSUE THREAD

**Issue by fantasai** [w3ctag/design-reviews#673]
Ya ya yawm TAG!

I'm requesting a TAG review of CSS Display Level 3.

  - Explainer¹ (minimally containing user needs and example code): N/A
  - Specification URL: https://www.w3.org/TR/css-display-3/
  - Tests: https://wpt.fyi/results/css/css-display?label=master&label=experimental&aligned
  - Security and Privacy self-review²: https://lists.w3.org/Archives/Public/www-archive/2021Sep/0002.html
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/csswg-drafts/issues
  - Primary contacts (and their relationship to the specification): @tabatkins and @fantasai
  - Organization(s)/project(s) driving the specification: CSSWG
  - Key pieces of existing multi-stakeholder review or discussion of this specification: https://drafts.csswg.org/css-display-3/issues-cr-2020
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):

Further details:

  - [you're still using a GitHub URL for this and it is Not Cool] I have reviewed the TAG's [Web Platform Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: none
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): CSSWG
  - Major unresolved issues with or opposition to this specification: None
  - This work is being funded by: Google

You should also know that...

https://www.w3.org/TR/css-display-3/#changes

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by plinss** [comment]
@hober and I looked at this in our VF2F and it all looks good. Thanks for all your hard work and a very clear changes section.
