### ISSUE TITLE
renderPriority element attribute

### ISSUE THREAD

**Issue by vmpstr** [w3ctag/design-reviews#676]
Hello TAG!

I'm requesting a TAG review of renderPriority element attribute.

The renderPriority attribute is an HTML attribute that informs the User Agent to keep the element's rendering state updated with a specified priority. This is used on elements whose rendering state would not otherwise be kept up-to-date.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/WICG/display-locking/blob/main/explainers/update-rendering.md
  - Security and Privacy self-review²: Not yet available; the feature does not impact security or privacy on the web.
  - GitHub repo (if you prefer feedback filed there): https://github.com/WICG/display-locking/
  - Primary contacts (and their relationship to the specification):
      - Vladimir Levin (@vmpstr), Google Chrome
      - Chris Harrelson (@chrishtr), Google Chrome
  - Organization/project driving the design: Google Chrome
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status):
      - https://chromestatus.com/feature/5764311403200512

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): WICG
  - The group where standardization of this work is intended to be done ("unknown" if not known): WHATWG or CSSWG

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @vmpstr

**Comment by andruud** [comment]
The arguments for preferring a HTML attribute for this seem pretty weak so far, https://github.com/WICG/display-locking/issues/200#issuecomment-926450085. (Perhaps there are other unspoken arguments)?

**Comment by vmpstr** [comment]
> The arguments for preferring a HTML attribute for this seem pretty weak so far, [WICG/display-locking#200 (comment)](https://github.com/WICG/display-locking/issues/200#issuecomment-926450085). (Perhaps there are other unspoken arguments)?

I left some more thoughts on that issue, but I would definitely appreciate TAG's view on it

**Comment by LeaVerou** [comment]
Thank you for the explanation. Saving milliseconds to several seconds certainly sounds worthwhile to me.

> I agree that upgrading the renderpriority to something higher in the subtree is problematic, since it would violate the ancestor render priority setting and cause more work than necessary (as you mention with the ads injecting high priority content). I believe there is no such issues if we keep the priority at the minimum of ancestor and nested element (i.e. if one of them is background, then the content in the inner element is updated with background priority). We are also considering not updating nested renderpriority things at all (ie treat them as renderpriority=never), which would simplify reasoning about this and allow us to have improvements in the future.

Given that the default renderpriority is `user-visible`, wouldn't that effectively render `user-blocking` impossible to use, unless you're willing to set it on the root, defeating its purpose?

**Comment by torgo** [comment]
Hi @vmpstr - we're just reviewing progress on this today and it looks like so far the explainer hasn't been updated. Do you you have any additional status you can share?

**Comment by vmpstr** [comment]
Hey, I apologize for the delay. I've just updated the explainer as a result of the discussions that we had on this issue. 

Thank you!

**Comment by LeaVerou** [comment]
Hi @vmpstr,

@cynthia and I discussed this again today in a breakout today.
On attribute vs CSS property we definitely think this is more suitable as a CSS property. This way it is easier to use it for creating defaults, including in Web components, and also given that it interacts with other CSS properties.

We are still not sure about certain details of the proposed algorithm, including my question from above about nesting higher priority elements inside lower priority elements.

We would like to see some examples of actually using the feature to target the user needs you are targeting. Are all these values necessary to address these use cases?

**Comment by vmpstr** [comment]
Thank you for your feedback and questions!

> On attribute vs CSS property we definitely think this is more suitable as a CSS property. This way it is easier to use it for creating defaults, including in Web components, and also given that it interacts with other CSS properties.

That makes sense, thanks.

> We are still not sure about certain details of the proposed algorithm, including my question from above about nesting higher priority elements inside lower priority elements.

The intent is to have this property be treated as a maximum rendering priority for itself and its descendants. This would mean that higher priority descendants would still be limited by the lower priority ancestors. In other words, a parent with a baackground priority will cause all of its children to update with at most a background priority, even if one of its children is a user-blocking priority. 

> We would like to see some examples of actually using the feature to target the user needs you are targeting. Are all these values necessary to address these use cases?

* user-blocking - this is currently the behavior for most (all?) visible content: updates always happen synchronously even if that blocks other work
* user-visible - this priority isn't really required (the priorities were largely inspired by the [task scheduling api](https://wicg.github.io/scheduling-apis/#enumdef-taskpriority))
* background - this is the most interesting priority to us, since that would allow developers to update `content-visibility: hidden` subtrees without blocking other important work.
* never - this is currently the behavior for `content-visibility: hidden` subtrees, since the rendering in those subtrees is not updated.
* auto - this seems like a nice default for the UA to select another priority. For example, UA can select "user-blocking" for visible content and "never" for content with `content-visibility: hidden` subtrees.

I don't have any working examples since we don't have a working prototype of this feature, but I can work to construct hypothetical examples where this would be useful.

Thanks again!

**Comment by torgo** [comment]
closing for now based on @chrishtr - can be re-opened when appropriate
