### ISSUE TITLE
Conditional Focus (When Display-Capture Starts)

### ISSUE THREAD

**Issue by eladalon1983** [w3ctag/design-reviews#679]
Braw mornin' TAG!

I'm requesting a TAG review of [Conditional Focus](https://eladalon1983.github.io/conditional-focus/).

When an application starts capturing a display-surface, the user agent faces a decision - should the captured display-surface be brought to the forefront, or should the capturing application retain focus.

The user agent is mostly agnostic of the nature of the capturing and captured applications, and is therefore ill-positioned to make an informed decision.

In contrast, the capturing application is familiar with its own properties, and is therefore better suited to make this decision. Moreover, by reading [displaySurface](https://www.w3.org/TR/screen-capture/#dom-mediatrackconstraintset-displaysurface) and/or using [Capture Handle](https://wicg.github.io/capture-handle/), the capturing application can learn about the captured display-surface, driving an even more informed decision.

  - Explainer: https://github.com/WICG/conditional-focus/blob/main/README.md
  - Specification URL: https://wicg.github.io/conditional-focus/
  - Tests: N/A
  - Security and Privacy self-review: TBD
  - Primary contacts:
      - Elad Alon (@eladalon1983), Google
  - Organization(s)/project(s) driving the specification: Google
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
      - https://github.com/w3c/mediacapture-screen-share/issues/190
      - https://github.com/WICG/proposals/issues/37
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://www.chromestatus.com/feature/5646614535340032

Further details:

  - [X] I have reviewed the TAG's [Web Platform Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: N/A
  - The group where the work on this specification is currently being done: WebRTC WG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): WebRTC WG and/or WICG
  - Major unresolved issues with or opposition to this specification: N/A
  - This work is being funded by: Google

You should also know that...

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @eladalon1983

**Comment by torgo** [comment]
Hi @eladalon1983 - Looking at the [thread in WebRTC](https://github.com/w3c/mediacapture-screen-share/issues/190), it looks like this is still under active discussion. If so, it seems like it might be premature for the TAG to be reviewing this?  Is the plan to incubate this in WICG and then bring it to WebRTC for a future WebRTC rechartering?

**Comment by rhiaro** [comment]
Hello, @torgo and I looking at this in our virtual face-to-face today. We noticed the problem statement in the explainer is from the perspective of the user agent, rather than the end user. Would you mind adding some examples/use cases/scenarios of how the end user of an application benefits or is affected by this feature? We appreciate that you have noted one security concern in the explainer; do you have an idea of when you will be able to complete the [privacy and security questionnaire](https://www.w3.org/TR/security-privacy-questionnaire/)? Are you expecting to take this work to the WebRTC WG?

**Comment by eladalon1983** [comment]
> Hi @eladalon1983 - Looking at the [thread in WebRTC](https://github.com/w3c/mediacapture-screen-share/issues/190), it looks like this is still under active discussion. If so, it seems like it might be premature for the TAG to be reviewing this? Is the plan to incubate this in WICG and then bring it to WebRTC for a future WebRTC rechartering?

It's being [incubated](https://wicg.github.io/conditional-focus/) in the WICG at the same time as it's [presented](https://github.com/w3c/mediacapture-screen-share/issues/190) to the WebRTC WG. (It's also in origin trial in Chrome starting m96.) We've had some fruitful discussions in the WebRTC WG and I am hoping we'll reach a mutually agreed-upon API shape in January or possibly earlier.

> Hello, @torgo and I are looking at this in our virtual face-to-face today. We noticed the problem statement in the explainer is from the perspective of the user agent, rather than the end user. Would you mind adding some examples/use cases/scenarios of how the end user of an application benefits or is affected by this feature? 

I can rephrase this with the next revision, no problem. Could you share more of your thoughts about the phrasing? For example, I took a look at the [Web Cryptography API](https://www.w3.org/TR/WebCryptoAPI/#use-cases) and it looked to me to also be centered around the user agent and the applications, not the user. The way I see it, in both cases, the benefit to users is applications can serve them better. In the case of **Conditional Focus**, this better service is through less distractions thrown the user's way, and less clicks required of the user, when they are engaged in something as mentally-challenging as presenting to a live audience. 

> We appreciate that you have noted one security concern in the explainer; do you have an idea of when you will be able to complete the [privacy and security questionnaire](https://www.w3.org/TR/security-privacy-questionnaire/)? Are you expecting to take this work to the WebRTC WG?

Presently, I expect to do that after the final shape is agreed upon in WebRTC WG discussions.

**Comment by rhiaro** [comment]
> this better service is through less distractions thrown the user's way, and less clicks required of the user, when they are engaged in something as mentally-challenging as presenting to a live audience

Thanks, that's exactly the kind of language we like to see in an explainer. It can also be helpful to walk us through how someone interacts with the feature from first principles, assuming little prior familiarity with the details of the work. (If you haven't already seen it, there are some links to good explainers in the [explainer explainer](https://github.com/w3ctag/tag.w3.org/blob/main/explainers/index.md).)

**Comment by torgo** [comment]
Hi @eladalon1983 - can you let us know status on the API shape (and security & privacy questionnaire response)?

**Comment by eladalon1983** [comment]
(Apologies for still not responding, but I am prioritizing other work. Please leave this open. I intend to get back to this in the next few weeks.)

**Comment by torgo** [comment]
Hi @eladalon1983 just pinging on this. Has there been any update we should be aware of?

**Comment by eladalon1983** [comment]
Sorry, still in the pipeline.

**Comment by torgo** [comment]
Hi @eladalon1983 we're going to close this for now just to keep our agendas in order. Can you ping us when you're ready for us to re-open and review?

**Comment by eladalon1983** [comment]
Will do.

**Comment by eladalon1983** [comment]
> Can you ping us when you're ready for us to re-open and review?

Following discussions in the WebRTC WG, the API was reshaped. The new shape is visible in these PRs:
* https://github.com/w3c/mediacapture-screen-share/pull/235
* https://github.com/w3c/mediacapture-screen-share/pull/240

I'll be updating the explainer soon.
Please take a look.
