### ISSUE TITLE
Preserve-parent-color value of forced-color-adjust CSS property

### ISSUE THREAD

**Issue by sartang** [w3ctag/design-reviews#681]
Braw mornin' TAG!
 
I'm requesting a TAG review for the addition of the `preserve-parent-color` value to the [`forced-color-adjust` CSS property](https://www.w3.org/TR/css-color-adjust-1/#propdef-forced-color-adjust).
 
The `preserve-parent-color` value provides similar behavior to `none`, except it also allows an element to inherit its parent's used `color` value. In other words, `preserve-parent-color` provides the ability for an element to inherit its parent's Forced Colors Mode adjusted `color` value. 
 
  - Explainer¹ (minimally containing user needs and example code): [https://github.com/sartang/MSEdgeExplainers/blob/PreserveParentColor/Accessibility/PreserveParentColor/explainer.md](https://github.com/sartang/MSEdgeExplainers/blob/PreserveParentColor/Accessibility/PreserveParentColor/explainer.md)
  - Specification URL: [here](https://www.w3.org/TR/css-color-adjust-1/#propdef-forced-color-adjust)
  - Tests:
    - [https://wpt.fyi/results/css/css-forced-color-adjust](https://wpt.fyi/results/css/css-forced-color-adjust)
    - [https://wpt.fyi/results/forced-colors-mode/forced-colors-mode-03.html](https://wpt.fyi/results/forced-colors-mode/forced-colors-mode-03.html)
    - [https://wpt.fyi/results/forced-colors-mode/backplate/forced-colors-mode-backplate-01.html](https://wpt.fyi/results/forced-colors-mode/backplate/forced-colors-mode-backplate-01.html)
  - User research: [https://github.com/w3c/csswg-drafts/issues/6310](https://github.com/w3c/csswg-drafts/issues/6310)
  - Security and Privacy self-review²: This feature does not have security or privacy concerns
  - GitHub repo (if you prefer feedback filed there): [https://github.com/w3c/csswg-drafts/issues](https://github.com/w3c/csswg-drafts/issues)
  - Primary contacts (and their relationship to the specification):
      - @sartang
      - @alisonmaher
  - Organization(s)/project(s) driving the specification: Microsoft, Google
  - Key pieces of existing multi-stakeholder review or discussion of this specification: [https://github.com/w3c/csswg-drafts/issues/6310](https://github.com/w3c/csswg-drafts/issues/6310) 
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): [https://www.chromestatus.com/feature/4887620095049728](https://www.chromestatus.com/feature/4887620095049728)
 
Further details:
 
  - [X] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: N/A
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): CSSWG
  - Major unresolved issues with or opposition to this specification:
  - This work is being funded by: Microsoft, Google, Apple, Mozilla
 
We'd prefer the TAG provide feedback as (please delete all but the desired option):
 
  💬 leave review feedback as a **comment in this issue** and @-notify @sartang, @alisonmaher

**Comment by atanassov** [comment]
Thank you for opening the issue, the explainer, use cases and API looks good. Being a small delta that fits and conforms into an existing design the TAG has signed off we are happy to close the issue as satisfied.
