### ISSUE TITLE
EPUB 3.3

### ISSUE THREAD

**Issue by dauwhe** [w3ctag/design-reviews#684]
Greetings and salutations, Technical Architecture Group of the World Wide Web Consortium!

I’m requesting a TAG review of EPUB 3.3.

EPUB 3.3 is a packaging mechanism for web content, designed for electronic books. In a nutshell, an EPUB is a zip package, containing an XML manifest file and XHTML5 content documents. 

EPUB’s roots go back to 1999, with the OEB 1.0 specification from the Open Ebook Forum (which evolved into the IDPF) In 2007, a packaging format was introduced and OEB became EPUB 2.0. In 2011, EPUB 3.0 added support for XHTML5. Changes since then have been minor. The IDPF was absorbed into W3C in 2017, and responsibility for the maintenance of EPUB fell to the EPUB 3 Community Group, which released EPUB 3.2 in 2019 as a community group note. EPUB is twenty-one years old, but has never gone through the W3C Recommendation track, until now.

  - Explainer (minimally containing user needs and example code): https://github.com/w3c/epub-specs/blob/main/epub33/explainers/EPUB33-explainer.md
  
EPUB 3.3 consists of five specifications, three of which are normative and on the W3C Recommendation Track:
  
  - Spec URL: [EPUB 3.3 Overview](https://w3c.github.io/epub-specs/epub33/overview/), a non-normative overview of EPUB 3.3
  - Spec URL: [EPUB 3.3 Core](https://w3c.github.io/epub-specs/epub33/core/), the specification of the file format
  - Spec URL: [EPUB 3.3 Reading Systems](https://w3c.github.io/epub-specs/epub33/rs/), the specification for user agents, known as EPUB Reading Systems. 
  - Spec URL: [EPUB Accessibility 1.1](https://w3c.github.io/epub-specs/epub33/a11y/), the accessibility specification that builds on WCAG. 
  - Spec URL: [EPUB Accessibility Techniques 1.1](https://w3c.github.io/epub-specs/epub33/a11y-tech/), a non-normative techniques document.
  
  
  - Tests: https://github.com/w3c/epub-tests
  - User research: none
  - Security and Privacy self-review: https://github.com/w3c/epub-specs/blob/main/epub33/explainers/EPUB-33-security-privacy.md. Note the Working Group met with PING on October 26, 2021, and work with them is ongoing.
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/epub-specs
  - Primary contacts (and their relationship to the specification):
      - [Dave Cramer](https://github.com/dauwhe), Invited Expert, Working Group co-chair
      - [Wendy Reid](https://github.com/wareid), Rakuten Kobo, Working Group co-chair
      - [Ivan Herman](https://github.com/iherman), W3C Staff Contact
      - [Matt Garrish](https://github.com/mattgarrish), DAISY Consortium, primary editor
      - [Shinya Takami](https://github.com/shiestyle), Kadokawa, Working Group co-chair
      
      
  - Organization(s)/project(s) driving the specification: none
  - Key pieces of existing multi-stakeholder review or discussion of this specification: none
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): none

Further details:

  - [x] I have reviewed the TAG’s [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: We hope to move to CR at the end of 2021
  - The group where the work on this specification is currently being done: EPUB 3 Working Group
  - Major unresolved issues with or opposition to this specification: you tell us :) 
  - This work is being funded by: Our long-suffering employers, but the DAISY Consortium is generously allowing Matt Garrish to edit the specs. 

You should also know that...

We’d prefer the TAG provide feedback as:

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by torgo** [comment]
Hi @dauwhe just fyi we've started our review at our [virtual f2f](https://github.com/w3ctag/meetings/tree/gh-pages/2021/12-Madripoor) this week and we'll be starting to surface some of that feedback here soon and asking questions.... Thanks for bearing with us.

**Comment by dauwhe** [comment]
> * Relevant time constraints or deadlines: We hope to move to CR at the end of 2021

We now plan for CR in Q1 of 2022.

**Comment by rhiaro** [comment]
Hello, I have opened a couple of issues (#1957, #1958, #1959) primarily around privacy considerations, as part of this review.

The main point here is that more expansive privacy considerations sections in both the EPUB and EPUB Reading Systems specs would be great.

I also want to note some other ongoing threads I'm particularly interested in the outcomes of:

* [Information Exposure and Fingerprintability](https://github.com/w3c/epub-specs/issues/1872)
* [EPUB and the Browseable Web](https://github.com/w3c/epub-specs/issues/1871)
* [Interactivity](https://github.com/w3c/epub-specs/issues/1875)

**Comment by hadleybeeman** [comment]
Looking at this in our W3CTAG breakout session.

Just noting that in two of the issues that @rhiaro opened, the working group minutes (mentioned in @iherman's reply) indicate that they are planning to address them and will get back to us.

And it doesn't look like there is any comment yet on the third: [[TAG] Reading systems and permissions prompts #1958](https://github.com/w3c/epub-specs/issues/1958).

**Comment by iherman** [comment]
> Looking at this in our W3CTAG breakout session.
> 
> Just noting that in two of the issues that @rhiaro opened, the working group minutes (mentioned in @iherman's reply) indicate that they are planning to address them and will get back to us.
> 

There has been extensive changes recently on the security and privacy section of the specs (as a result of the relevant horizontal reviews), see 

- https://www.w3.org/TR/epub-33/#sec-security-privacy
- https://www.w3.org/TR/epub-rs-33/#sec-security-privacy

we feel that these answer most of the TAG issues, too. Apologies not to ping you here earlier.

> And it doesn't look like there is any comment yet on the third: [[TAG] Reading systems and permissions prompts #1958](https://github.com/w3c/epub-specs/issues/1958).

cc @dauwhe @wareid

**Comment by cynthia** [comment]
Casual drive-by question - is there any path forward for a non-ZIP container here? ZIP isn't great for streaming.

**Comment by iherman** [comment]
@cynthia there were lots of discussions in the past few years (although not as part of the EPUB Working Group) about using the [Web packaging specs](https://github.com/WICG/webpackage#specifications). Future versions of EPUB may very well adopt that specification in some way or other, but it is certainly too early to do that in the present version of EPUB.

**Comment by rhiaro** [comment]
Thanks for the great work on the Privacy and Security sections. The threat models and mitigations now look very comprehensive, and we appreciate the effort that went into these.

I had [one question remaining around permission prompts](https://github.com/w3c/epub-specs/issues/1958), which is not blocking, but I hope to see the conversation continue.

Having completed our review, we are happy to see this move forward. Thanks!

**Comment by iherman** [comment]
Thank you, Amy.
