### ISSUE TITLE
Review Request for adding video- prefixed media features

### ISSUE THREAD

**Issue by willcassella** [w3ctag/design-reviews#697]
Braw mornin' TAG!

I'm requesting a TAG review of adding `video-` prefixed media features.

`video-` prefixed media features give webpages the ability to disambiguate media queries for devices which have different display characteristics for video and non-video web content.

  - Explainer¹ (minimally containing user needs and example code): [Explainer for `video-` prefixed media features](https://github.com/willcassella/blink-hdr/blob/main/explainers/video-%20prefixed%20media%20features.md)
  - Specification URL: https://www.w3.org/TR/mediaqueries-5/#video-prefixed-features
  - Tests: https://wpt.fyi/results/css/mediaqueries/dynamic-range.html
  - Security and Privacy self-review²: https://github.com/w3c/security-request/issues/19
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/csswg-drafts/issues
  - Primary contacts (and their relationship to the specification):
      - Dean Jackson - Apple, spec editor
      - Florian Rivoal - Spec editor
      - Tab Atkins Jr - Google, spec editor
      - Chris Cunningham (chcunningham) - Google, spec 
      - Will Cassella (willcassella) - Google, implementor in Chromium
  - Organization(s)/project(s) driving the specification: Google, Microsoft, Apple, Netflix, HBBTV
  - Key pieces of existing multi-stakeholder review or discussion of this specification: 
    - https://github.com/w3c/csswg-drafts/issues/4471
    - https://github.com/w3c/media-capabilities/issues/135
    - https://github.com/w3c/csswg-drafts/issues/6793
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): Not yet created

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: None
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): CSSWG
  - Major unresolved issues with or opposition to this specification: None (yet?)
  - This work is being funded by: Implementation by Google

We'd prefer the TAG provide feedback as:
  💬 leave review feedback as a **comment in this issue** and @-notify willcassella

**Comment by torgo** [comment]
Hi folks - we are having a look at this at our face-to-face this week. One thing that became clear is that the explainer jumps right into a discussion of the technology without articulating the end-user need or the developer need. Can you please add some intro to the explainer that expands on these points a bit? We did see the motivation section - but we're talking about documenting what authors actually want to accomplish and in service of what improvement to the end-user experience? That would not only help us with our review but also help to explain this technology going forward when documented for developers. Thanks! ✨
