### ISSUE TITLE
HIDDevice forget()

### ISSUE THREAD

**Issue by beaufortfrancois** [w3ctag/design-reviews#703]
Braw mornin' TAG!

I'm requesting a TAG review of the `forget()` method for `HIDDevice`.

The `forget()` method allows web developers to voluntarily revoke a permission to a `HIDDevice` that was granted by a user.

Some sites may not be interested in retaining long-term permissions to access a HID device. For example, for an educational web application used on a shared computer with many devices, a large number of accumulated user-generated permissions creates a poor user experience. In addition to user agent mitigations to avoid this problem, such as defaulting to a session scoped permission on the first request or expiring infrequently used permissions, it should be possible for the site itself to clean up user-generated permissions it is no longer interested in retaining.

```js
// Request any HID device.
const [device] = await navigator.hid.requestDevice({ filters: [] });

// Then later... revoke permission to the HID device.
await device.forget();
```

⚠️ We expect similar functionality in Web Bluetooth, WebUSB, and the Serial API to be added.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/WICG/webhid/pull/84
  - User research: None
  - Security and Privacy self-review²: None yet for this specific feature - https://github.com/WICG/webhid/blob/gh-pages/security-and-privacy-questionnaire.md is the one for WebHID
  - GitHub repo (if you prefer feedback filed there): [url]
  - Primary contacts (and their relationship to the specification):
      - François Beaufort (@beaufortfrancois, Google)
      - Matt Reynolds (@nondebug, Google)
  - Organization/project driving the design: WICG
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5723581527883776

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): WICG
  - The group where standardization of this work is intended to be done ("unknown" if not known):
  - Existing major pieces of multi-stakeholder review or discussion of this design:
  - Major unresolved issues with or opposition to this design:
  - This work is being funded by: Google

You should also know that we're eager to hear the TAG's opinion on a method like this given that `navigator.permissions.revoke()` is non-standard.

We'd prefer the TAG provide feedback as:

  💬 leave review feedback as a **comment in this issue** and @-notify @beaufortfrancois

**Comment by beaufortfrancois** [comment]
FYI We've just sent an intent to ship on blink-dev at https://groups.google.com/a/chromium.org/g/blink-dev/c/Fk-IJF63UWc

**Comment by torgo** [comment]
Hi @beaufortfrancois one question - does this assume that there will be a future "privacy budget" type mechanism that would encourage web apps to revoke no-longer-needed permissions in order to acquire other permissions?  Just curious to understand more about the use case - and especially the user need. Also there is no explainer. Although it's clear this is a small addition to an existing spec I think it could benefit from at least a small explainer to put this in context of the **user need**.

**Comment by beaufortfrancois** [comment]
> Hi @beaufortfrancois one question - does this assume that there will be a future "privacy budget" type mechanism that would encourage web apps to revoke no-longer-needed permissions in order to acquire other permissions?

It doesn't assume this type of mechanism.

> Just curious to understand more about the use case - and especially the user need. Also there is no explainer. Although it's clear this is a small addition to an existing spec I think it could benefit from at least a small explainer to put this in context of the user need.

Websites used by multiple users (e.g. students) on a machine/browser will want to provide a way to for their users to clean their devices as it would clutter the list of devices already granted to them. Screenshot below shows you what it looks like in Chrome browser. Websites will want to provide the same functionalities with a potential "reset all" button for instance.

![image](https://user-images.githubusercontent.com/634478/152957355-f9dc1c24-cc30-4129-9666-0bb5fa243702.png)


 > Also if there are privacy & security requirements behind this feature then could you amend the security & privacy questionnaire responses accordingly?
 
 I didn't find one. `requestDevice()` grants you access to HID devices. `forget()` simply lets you forget manually. Users could already perform that action from the browser.

**Comment by maxpassion** [comment]
One clarification question: What is the expected user interaction when HIDDevice forget() is invoked? Will it notify the user?

**Comment by beaufortfrancois** [comment]
The browser won't notify the user. It is expected that the website provides a UI to revoke access to a HID device. You can try it in Chrome Canary at https://hiddevice-forget.glitch.me with the "Experimental Web Platform Features" flag.

**Comment by beaufortfrancois** [comment]
FYI We're shipping this in Chrome 100. See https://twitter.com/quicksave2k/status/1491709997138464768

**Comment by beaufortfrancois** [comment]
Developer documentation can be found at https://web.dev/hid/#revoke-access

**Comment by cynthia** [comment]
Thanks for the clarification, happy that this work is moving forward. We will also take note to revisit parts of the platform where such patterns (returning permissions) might be necessary.

**Comment by beaufortfrancois** [comment]
FYI We've just sent another intent to ship for USBDevice forget() at https://groups.google.com/a/chromium.org/g/blink-dev/c/pSM2W0TtKEI
