### ISSUE TITLE
[mediaqueries-4] Range contexts

### ISSUE THREAD

**Issue by andruud** [w3ctag/design-reviews#707]
Braw mornin' TAG!

I'm requesting a TAG review of the new media query syntax in Media Queries Level 4, which allows expressing media queries in a more readable (to some) way. 

  - Explainer: https://www.bram.us/2021/10/26/media-queries-level-4-media-query-range-contexts/
  - Specification URL: https://drafts.csswg.org/mediaqueries-4/#mq-syntax
  - Tests: Mostly wpt/css/mediaqueries/test_media_queries.html
  - User research:
  - Security and Privacy self-review: Can't see how this exposes new information at all.
  - GitHub repo: https://github.com/w3c/csswg-drafts
  - Primary contacts:
      - @andruud, Google, implementing the feature in Chromium.
  - Organization(s)/project(s) driving the specification: CSSWG
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines:
  - The group where the work on this specification is currently being done: CSSWG
  - Major unresolved issues with or opposition to this specification:
  - This work is being funded by:

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by torgo** [comment]
Hi @andruud can you please write an explainer for this and link to it rather than linking to a blog post?

**Comment by atanassov** [comment]
Hi again @andruud,

We took a look at this in our hybrid meeting today. Since an explainer is still missing, we're gonna go ahead and close this for now. Please feel free to reopen once there's an explainer, as I suspect the rest of the review will be rather straightforward.

Cheers, @LeaVerou, @atanassov and @plinss
