### ISSUE TITLE
Review request before CR:  CSS `selector()`

### ISSUE THREAD

**Issue by svgeesus** [w3ctag/design-reviews#709]
Braw mornin' TAG!

I'm requesting a TAG review of CSS `selector()`.

CSS `@supports` enables conditional application of style based on support for **properties** and **property values**; this specification adds the missing piece, checking for support of **selectors**.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/dbaron/css-supports-functions/blob/main/explainer.md
  - Specification URL:  https://www.w3.org/TR/css-conditional-4/
  - Tests: [wpt folder(s), if available]
     - https://wpt.fyi/results/css/css-conditional?label=experimental&label=master&aligned
     - https://github.com/web-platform-tests/wpt/tree/master/css/css-conditional
     - [inline in specification](https://drafts.csswg.org/css-conditional-4/#at-supports-ext)
  - User research: From explainer "Having feature queries based on selectors is probably the highest priority addition".
  - Security and Privacy self-review²: https://www.w3.org/TR/css-conditional-4/#privacy https://www.w3.org/TR/css-conditional-4/#security
  - GitHub repo (if you prefer feedback filed there): [CSSWG repo](https://github.com/w3c/csswg-drafts/issues)
  - Primary contacts (and their relationship to the specification):
      - L. David Baron ( @dbaron ), Invited Expert: editor
      - Elika J. Etemad / fantasai ( @fantasai ), Invited Expert: editor
      - Chris Lilley ( @svgeesus ), W3C: editor
  - Organization(s)/project(s) driving the specification: _all browsers_
  - Key pieces of existing multi-stakeholder review or discussion of this specification: [Closed CSS issue #3207](https://github.com/w3c/csswg-drafts/issues/3207)
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): already implemented, so no open bug trackers

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: We are hoping to move this small specification to CR very soon
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): CSSWG
  - Major unresolved issues with or opposition to this specification:  [None](https://github.com/w3c/csswg-drafts/labels/css-conditional-4)
  - This work is being funded by: n/a

You should also know that...

- `selector()` is the only new feature in CSS Conditional 4, compared to CSS Conditional 3
- [MDN article on checking for supported selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports#testing_for_the_support_of_a_selector)
- [CanIUse shows support in all browsers](https://caniuse.com/mdn-css_at-rules_supports_selector)
- [wide review for the previous level, CSS Conditional 3, which is now implemented everywhere](https://github.com/w3c/csswg-drafts/issues/5569)
- [Wide review meta-issue for CSS Conditional 4](https://github.com/w3c/csswg-drafts/issues/6954)

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by LeaVerou** [comment]
We looked at this during a breakout today. We don't see any issues with this feature and are happy for it to move forward.

**Comment by kirav** [comment]
not sure if anyone will look here, but
```
@supports not (selector(::-webkit-scrollbar)) {
    scrollbar-color: var(--primary) #fff;
    scrollbar-width: thin;
  }
```
this code does not compile properly
@supports not (selector(::-webkit-scrollbar))
TERM IS EXPECTED
:(
