### ISSUE TITLE
FYI - MediaCapabilities API for WebRTC

### ISSUE THREAD

**Issue by drkron** [w3ctag/design-reviews#720]
Braw mornin' TAG!

I'm requesting a TAG review of extending the MediaCapabilities API to WebRTC.

Per the Chromium Intent to Ship, [it was requested that I file a TAG review as a FYI](https://groups.google.com/a/chromium.org/g/blink-dev/c/loWlekYWswQ/m/yCs53Yq1DQAJ) - hence this request.

The MediaCapabilities API helps web sites to make informed decisions on what codec, resolution, etc. to use for video playback by providing information about whether a configuration is supported and also whether the playback is expected to be smooth. This feature extends the MediaCapabilities API to also include WebRTC streams.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/drkron/media-capabilities/blob/webrtc_examples/explainer.md#webrtc
  - Specification URL: https://w3c.github.io/media-capabilities/
  - Tests: 
    - https://wpt.fyi/results/media-capabilities/decodingInfo.webrtc.html,
    - https://wpt.fyi/results/media-capabilities/encodingInfo.webrtc.html
  - Primary contacts (and their relationship to the specification):
      - Johannes Kron (@drkron), Google, implementor in Chromium
      - Chris Cunningham (@chcunningham), Google, Spec editor
  - Organization(s)/project(s) driving the specification: Google, Microsoft, Apple
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/6242376685191168

Further details:

  - [X] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the work on this specification is currently being done: WebRTC WG

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @drkron.

**Comment by cynthia** [comment]
This looks good to us. It would be useful to get the review in a bit earlier than I2S in the future though. Thanks for bringing this to our attention.
