### ISSUE TITLE
Early design review: Subresource loading with Web Bundles (request for resuming #616)

### ISSUE THREAD

**Issue by hayatoito** [w3ctag/design-reviews#722]
Braw mornin' TAG!

We'd like to resume TAG review of #616, which we had closed.

I've added a [comment](https://github.com/w3ctag/design-reviews/issues/616#issuecomment-1067615089) to ask for resuming #616, as explained in https://github.com/w3ctag/design-reviews/issues/616#issuecomment-804263438,  however, it seems I can't re-open the issue, so I'm filing a new issue here to get an attention.

I'm not sure which is a preferred way, re-opening #616 or filing a new issue, so please feel free to close this new issue and re-open the #616 if the former is better than the latter.

Thanks!

**Comment by ShivanKaul** [comment]
We had left feedback on V1 of the Subresource Loading plan here: https://github.com/WICG/webpackage/issues/648#issuecomment-965744330. I understand only V1 is being put up for TAG review as per https://github.com/w3ctag/design-reviews/issues/616#issuecomment-1067615089.

**Comment by hayatoito** [comment]
Thanks!
I've added a comment on https://github.com/WICG/webpackage/issues/648#issuecomment-1074924985.

**Comment by hober** [comment]
Reopening #616 as requested; please continue discussion over there!
