### ISSUE TITLE
Web of Things (WoT) Discovery

### ISSUE THREAD

**Issue by mmccool** [w3ctag/design-reviews#733]
Ready for review, however WD update still pending.  In the meantime the following branch should be used for review: [review-pre-cr-wd](https://github.com/w3c/wot-discovery/tree/review-pre-cr-wd).

Braw mornin' TAG!

I'm requesting a TAG review of Web of Things (WoT) Discovery

WIP: [One paragraph summary of idea, ideally copy-pasted from Explainer introduction]

  - Explainer¹ (minimally containing user needs and example code): https://github.com/w3c/wot-discovery/blob/main/explainer/Explainer.md
  - Specification URL: 
      - Editor's draft: https://w3c.github.io/wot-discovery/
      - Working draft: https://www.w3.org/TR/wot-discovery/
      - Review draft: https://github.com/w3c/wot-discovery/tree/review-pre-cr-wd
  - Tests: [Draft Implementation Report](https://github.com/w3c/wot-discovery/blob/main/testing/report.html) 
  - User research: [WoT Use Cases and Requirements](https://github.com/w3c/wot-usecases)
  - Security and Privacy self-review²: https://github.com/w3c/wot-architecture/blob/main/publication/ver11/security_and_privacy.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/wot-discovery
  - Primary contacts (and their relationship to the specification):
      - Andrea Cimmino (AndreaCimminoArriaga), Universidad Politécnica de Madrid, editor
      - Michael McCool (mmccool), Intel, editor/co-chair
      - Farshid Tavakolizadeh, (farshidtz), Canonical, editor 
      - Kunihiko Toumura, (k-toumura), Hitachi, editor
      - Sebastian Kaebisch (sebastiankb), Intel, co-chair
  - Organization(s)/project(s) driving the specification: WoT WG
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: CR transition planned for 30 August 2022
  - The group where the work on this specification is currently being done: WoT WG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue):
  - Major unresolved issues with or opposition to this specification: 
  - This work is being funded by:

You should also know that...

* Security and Privacy Questionnaire was done for WoT as a whole, but answers call out individual deliverables as appropriate.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

------------------------------------------------------------------------------------
CAREFULLY READ AND DELETE CONTENT BELOW THIS LINE BEFORE SUBMITTING

Please preview the issue and check that the links work before submitting.

In particular, if anything links to a URL which requires authentication (e.g. Google document), please make sure anyone with the link can access the document. We would prefer fully public documents though, since we work in the open.

¹ We require an explainer to give the relevant context for the spec review, even if the spec has some background information. For background, see our [explanation of how to write a good explainer](https://tag.w3.org/explainers/). We recommend the explainer to be in [Markdown](https://github.github.com/gfm/).

² A Security and Privacy questionnaire helps us understand potential security and privacy issues and mitigations for your design, and can save us asking redundant questions. See https://www.w3.org/TR/security-privacy-questionnaire/.

**Comment by rhiaro** [comment]
Overall, the direction of this looks good. The two-stage discovery process seems sensible to us. What use cases can be met after only carrying out the first step?

We note that you have deferred work on geolocation queries. This is something we will be very interested to review in the future from a privacy and security, and general social impact, perspective. We would welcome early review requests on this as your draft progresses.

The [related work](https://github.com/w3c/wot-discovery/blob/main/explainer/Explainer.md#related-work) section in your explainer contains references to other work but without any links. Could you add some?

Please also see the [review for the Architecture specification](https://github.com/w3ctag/design-reviews/issues/736#issuecomment-1162135635) as this contains feedback that concerns all of the related specs.

**Comment by rhiaro** [comment]
@mmccool We are closing this review request, but when you have chance to respond to my [earlier question](https://github.com/w3ctag/design-reviews/issues/733#issuecomment-1162141086) or make the improvements to the explainer, please ping me here. Thanks!

**Comment by mmccool** [comment]
Response from WoT Discovery TF (call Aug 1; sorry, last week we had no meeting):
1. Use cases for first phase.  There are not any; some "exploration mechanism" must be used to access metadata.  Introductions are intentionally designed to reveal as little information as possible since in general they are unauthenticated.  Although I suppose someone could infer that *something* in the area supports WoT Discovery, so there might be some "unintentional" use cases.
2. Agree about geolocation, we are in extensive discussion with SDW and OGC on this. 
3. Regarding links to related work in the explainer: there are already a lot of links in the document itself.    For now we have just updated the explainer to note that there are many links in the document itself, but we will look for a survey article or two to add, such as the following (although then we may want to add these to the main document as well).
   - https://www.sciencedirect.com/science/article/abs/pii/S2542660520301256?via%3Dihub
   - https://dl.acm.org/doi/10.1145/2991561.2991570
