### ISSUE TITLE
Web of Things (WoT) Architecture 1.1

### ISSUE THREAD

**Issue by mmccool** [w3ctag/design-reviews#736]
Ready for review.  The WD will be updated shortly based on branch [architecture-1.1-pre-cr-wd](https://github.com/w3c/wot-architecture/tree/architecture-1.1-pre-cr-wd)

Braw mornin' TAG!

I'm requesting a TAG review of Web of Things (WoT) Architecture 1.1

The W3C WoT formally describes the interfaces of IoT devices and platforms to ease integration across IoT ecosystems and application domains. Rich metadata based on URIs, hypermedia controls, and collaborative schema definitions allows clients to adapt to the peculiarities of a given IoT platform by configuring its protocol stack.

The WoT Architecture document serves as an umbrella for all WoT specifications, and sets the general goals of the W3C Web of Things. It defines the abstract architecture and the design space for current and future WoT building blocks, which are specified in separate documents.

  - Explainer¹ (minimally containing user needs and example code): [WoT Architecture Explainer11.md](https://github.com/w3c/wot-architecture/blob/main/explainer/explainer11.md)
  - Specification URL: 
      * [Editor's Draft](https://w3c.github.io/wot-architecture/)
      * [Last Published Version](https://w3c.github.io/wot-architecture/)
      * [Branch for review (WD update pending)](https://github.com/w3c/wot-architecture/tree/architecture-1.1-pre-cr-wd)
  - Tests: [Draft Implementation Report](https://github.com/w3c/wot-architecture/blob/main/testing/report11.html)  
  - User research: [WoT Use Cases and Requirements](https://github.com/w3c/wot-usecases)
  - Security and Privacy self-review²: https://github.com/w3c/wot-architecture/blob/main/publication/ver11/security_and_privacy.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/wot-architecture
  - Primary contacts (and their relationship to the specification):
      - Michael Lagally (mlagally), Oracle, editor
      - Ryuichi Matsukura (mryuichi), Fujitsu, editor
      - Kunihiko Toumura (k-toumura), Hitachi, editor
      - Michael McCool (mmccool), Intel, co-chair
      - Sebastian Kaebisch (sebastiankb), Siemens, co-chair
  - Organization(s)/project(s) driving the specification: WoT WG
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: CR Transition planned for 30 August 2022
  - The group where the work on this specification is currently being done: WoT WG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue):
  - Major unresolved issues with or opposition to this specification:
  - This work is being funded by:

You should also know that...

* Security and Privacy Questionnaire was done for WoT as a whole, but answers call out individual deliverables as appropriate.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

------------------------------------------------------------------------------------
CAREFULLY READ AND DELETE CONTENT BELOW THIS LINE BEFORE SUBMITTING

Please preview the issue and check that the links work before submitting.

In particular, if anything links to a URL which requires authentication (e.g. Google document), please make sure anyone with the link can access the document. We would prefer fully public documents though, since we work in the open.

¹ We require an explainer to give the relevant context for the spec review, even if the spec has some background information. For background, see our [explanation of how to write a good explainer](https://tag.w3.org/explainers/). We recommend the explainer to be in [Markdown](https://github.github.com/gfm/).

² A Security and Privacy questionnaire helps us understand potential security and privacy issues and mitigations for your design, and can save us asking redundant questions. See https://www.w3.org/TR/security-privacy-questionnaire/.

**Comment by mmccool** [comment]
Response from WoT Security TF:
1. The "Security Best Practices" document was meant to contain a set of non-normative statements about security such as the best version of TLS to use, when to use it, etc. but these have been superseded by the normative statements about these in the current version of the deliverables (TD, Architecture, Discovery, and Profiles).   We were going to update the "Security Best Practices" document but as it seems redundant at this point will remove reference to this document by the CR transition.  **ACTION: Remove references to "Security Best Practices" in normative documents.**
2. The "Security and Privacy Guidelines" document was unfortunately not defined as a normative deliverable in our last charter.  We might want to consider making it normative in our next charter and consolidating normative assertions about security and privacy in it, but can't do so according to our current charter.  It's true this document has not been updated in a while but it currently makes general statements which are still correct.  Being informative, we were also planning to update it after the current normative deliverables are in CR but prior to PR.  **ACTION: Review and update prior to PR transition of other deliverables.**
3. References to "Security and Privacy Guidelines" should note that it is an informative document.  **ACTION: Update references to ensure that all references to "Security and Privacy Guidelines" are informative.**
4. The "Security and Privacy Guidelines" document however also was also used as a place to put testing recommendations for security.  In general we will be reviewing assertions prior to CR transition and making sure they are testable statements about implementations and not statements about policy.  For example, a statement about "Identifiers SHOULD be rotated" should probably be "Implementations SHOULD provide a means to rotate identifiers."  We would like to somehow make statements about recommended policies but these are hard to test in an implementation as they depend on usage of systems not available at release time (unfortunately).  But at least we can make sure the suggested policy is *possible*.  **ACTION: Review and update security and privacy assertions so they are testable statements about implementations.**

**Comment by mlagally** [comment]
Dear TAG members,

thanks again for your extensive review.

@rhiaro We will work through the soceital impact questionnaire:
https://github.com/w3c/wot-architecture/issues/807
Is there a Markdown version of the questionnaire?

We will address your review comments in individual issues, these are tracked with a dedicated label:
https://github.com/w3c/wot-architecture/labels/address%20TAG%20feedback

**Comment by rhiaro** [comment]
Hi @mlagally - the Societal Impacts Questionnaire is at the moment on the outside an html doc, but on the inside markdown, so you can take the text from [this page](https://github.com/w3ctag/societal-impact-questionnaire/blob/main/index.html) for markdown versions of the headings and descriptions for each question.

**Comment by rhiaro** [comment]
@mmccool Thank you for your comprehensive responses about the Security and Privacy documents, I really appreciate you taking the time to explain that and highlight actions. That all sounds like a positive direction.

**Comment by rhiaro** [comment]
Based on the responses to feedback, and assuming adequate discussion of and resolution to the open issues (linked by github above) that will track the various points, I'm going to close this review request. If you do any major restructuring and think it would be helpful for us to re-review at some point, please do open another review request. I will continue to follow the progress you make on the open issues with interest, and hope that your work progresses smoothly.
