### ISSUE TITLE
Design review: AbortSignal.any()

### ISSUE THREAD

**Issue by shaseley** [w3ctag/design-reviews#737]
Braw mornin' TAG!

I'm requesting a TAG review of `AbortSignal.any(signals)`.

`AbortSignal.any(signals)` returns a signal that is aborted when any of the source signals are aborted. Developers can use this to combine independent abort sources, e.g. timeouts specified with `AbortSignal.timeout()` and signals associated with user input, and pass them to async APIs like `fetch()`.

  - Explainer: https://github.com/shaseley/abort-signal-any/blob/main/README.md
  - User research: N/A
  - Security and Privacy self-review: https://github.com/shaseley/abort-signal-any/blob/main/tag-questionnaire.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/shaseley/abort-signal-any/
  - Primary contacts (and their relationship to the specification):
      - Scott Haseley (@shaseley), Google, designing/specifying/implementing in Chrome
  - Organization/project driving the design: This is in response to an [open WHATWG DOM issue](https://github.com/whatwg/dom/issues/920)
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5202879349522432

Further details:

  - [X] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): The explainer will likely stay in a personal repo, with conversation moving to a WHATWG (DOM) PR.
  - The group where standardization of this work is intended to be done ("unknown" if not known): WHATWG
  - Existing major pieces of multi-stakeholder review or discussion of this design: https://github.com/whatwg/dom/issues/920#issuecomment-1105756079
  - Major unresolved issues with or opposition to this design: None we're aware of
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by LeaVerou** [comment]
Hi there,

We looked at this during a breakout today and we think this is ok — the addition does not introduce any new issues to the AbortSignal API.

Thank you for working with us!

**Comment by shaseley** [comment]
Thanks all!

**Comment by shaseley** [comment]
FYI: this feature has been merged into the [dom spec](https://dom.spec.whatwg.org/#dom-abortsignal-any) (with no changes to the API since TAG review).
