### ISSUE TITLE
Early design review: Back/forward cache NotRestoredReasons API

### ISSUE THREAD

**Issue by rubberyuzu** [w3ctag/design-reviews#739]
Braw mornin' TAG!

I'm requesting a TAG review of Back/forward cache NotRestoredReasons API.

  - Explainer¹ (minimally containing user needs and example code): [Explainer](https://github.com/rubberyuzu/bfcache-not-retored-reason/blob/main/NotRestoredReason.md)
  - User research: N/A
  - Security and Privacy self-review²: [Questionnaire](https://github.com/rubberyuzu/bfcache-not-retored-reason/blob/main/NotRestoredReason.md#self-review-questionnaire-security-and-privacy)
  - GitHub repo (if you prefer feedback filed there): [GitHub Repo(https://github.com/rubberyuzu/bfcache-not-retored-reason)]
  - Primary contacts (and their relationship to the specification):
      - Yuzu Saijo @rubberyuzu Google Chrome 
  - Organization/project driving the design:  Google (BFCache team)
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): [Chrome status](https://chromestatus.com/feature/5684908759449600)

Further details:

  - [✓] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): The explainer will stay in personal repo.
  - The group where standardization of this work is intended to be done ("unknown" if not known): WHATWG
  - Existing major pieces of multi-stakeholder review or discussion of this design:[Navigation Timing API GitHub issue](https://github.com/w3c/navigation-timing/issues/171#issuecomment-1062672989)
  - Major unresolved issues with or opposition to this design: [Avoid browser specific reasons](https://github.com/rubberyuzu/bfcache-not-retored-reason/issues/2#issuecomment-1084015788)
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as :
🐛 open issues in our GitHub repo for each point of feedback

**Comment by rubberyuzu** [comment]
Thanks for the review! I added a more detailed explanation on security and privacy here: [explainer](https://github.com/rubberyuzu/bfcache-not-retored-reason/blob/main/NotRestoredReason.md#security-and-privacy)

**Comment by cynthia** [comment]
Discussed in this week's breakouts. We've reviewed the updated explainer, and are happy to see this move forward. Thanks for bringing this to our attention.

Please don't forget about the potential risks of extension leakage in the actual implementation, as we believe that is an actual risk.
