### ISSUE TITLE
CSS property object-view-box review

### ISSUE THREAD

**Issue by khushalsagar** [w3ctag/design-reviews#740]
Braw mornin' TAG!

I'm requesting a TAG review of a new CSS property : `object-view-box`.

object-view-box allows the author to specify a subset within an image that should draw within the content box of the target replaced element. This enables an author to create an image with a custom glow or shadow applied, with proper ink-overflow behavior like a CSS shadow would have.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/w3c/csswg-drafts/issues/7058
  - Specification URL: https://drafts.csswg.org/css-images-4/#the-object-view-box
  - Tests: [wpt folder(s), if available] : [WPT](https://wpt.fyi/results/css/css-images?label=master&label=experimental&aligned&q=object-view-box).
  - User research: [url to public summary/results of research]: N/A
  - Security and Privacy self-review²: [review](https://github.com/WICG/shared-element-transitions/blob/main/object-view-box-security-privacy-review.md)
  - GitHub repo (if you prefer feedback filed there): N/A
  - Primary contacts (and their relationship to the specification):
      - @khushalsagar Chromium, Implementor
      - @tabatkins Chromium, Spec author
      - @vmpstr Chromium
  - Organization(s)/project(s) driving the specification: Google
  - Key pieces of existing multi-stakeholder review or discussion of this specification: [CSSWG issue](https://github.com/w3c/csswg-drafts/issues/7058)
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): [Chrome status](https://chromestatus.com/feature/5213032857731072)

Further details:

  - [X] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: None
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): CSSWG
  - Major unresolved issues with or opposition to this specification: None
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify khushalsagar.

**Comment by LeaVerou** [comment]
Hi there,

We took a look during a breakout today and this looks good to us.

Thanks for flying TAG!
