### ISSUE TITLE
Collection of Screensharing-related UX Hints

### ISSUE THREAD

**Issue by eladalon1983** [w3ctag/design-reviews#744]
Ma ha'matzav TAG?!

I'm requesting a TAG review of a collection of UX hints related to screensharing. They are too far apart to be described together, but close enough that they can be reviewed as a group - as suggested by @chrishtr on [this thread](https://groups.google.com/a/chromium.org/g/blink-dev/c/bIGZVdkZ4OE/m/G1C2aXcIAAAJ?utm_medium=email&utm_source=footer).

  - Explainers:
    - DisplayMediaStreamConstraints.selfBrowserSurface explainer: [[.md]](https://github.com/eladalon1983/screen-share-explainers/blob/main/selfBrowserSurface_Explainer.md) / [[Google Doc]](https://docs.google.com/document/d/1M63lyDHV-v6LPFzHjfsjBDMfyn075pySa3xfIRSB9zU/edit?usp=sharing)
    - DisplayMediaStreamConstraints.surfaceSwitching explainer: [[.md]](https://github.com/eladalon1983/screen-share-explainers/blob/main/surfaceSwitching_Explainer.md) / [[Google Doc]](https://docs.google.com/document/d/1kqdLoUcwWe8znVCMXyz2FHk9WMylHbIo7gUjhyHmY_w/edit?usp=sharing)
    - DisplayMediaStreamConstraints.systemAudio explainer: [[.md]](https://github.com/eladalon1983/screen-share-explainers/blob/main/systemAudio_Explainer.md) / [[Google Doc]](https://docs.google.com/document/d/1q3oGy7hLJmdQA4ZK7QG7DnwgtcpL6oB2pqLQJ6MP1tY/edit?usp=sharing)
    - MediaTrackSupportedConstraints.suppressLocalAudioPlayback explainer: [[.md]](https://github.com/eladalon1983/screen-share-explainers/blob/main/suppressLocalAudioPlayback_Explainer.md) / [[Google Doc]](https://docs.google.com/document/d/1OmuV1W4f2UvToeNxUVGHv8NcFuL63r94gWwz9i_-VBc/edit?usp=sharing)
    - displaySurface Constraint explainer: [[.md]](https://github.com/eladalon1983/screen-share-explainers/blob/main/displaySurface_Constraint_Explainer.md) / [[Google Doc]](https://docs.google.com/document/d/1uI51R4YfFQtfiDTw1KfnLqzIu45OgxhYoUT7khlhmwQ/edit?usp=sharing)
  - Specification URL: All of these new hints are part of [w3c/mediacapture-screen-share](https://w3c.github.io/mediacapture-screen-share/). Their respective PRs are:
    - [PR for DisplayMediaStreamConstraints.selfBrowserSurface](https://github.com/w3c/mediacapture-screen-share/pull/216/files)
    - [PR for DisplayMediaStreamConstraints.surfaceSwitching](https://github.com/w3c/mediacapture-screen-share/pull/225/files)
    - [PR for DisplayMediaStreamConstraints.systemAudio](https://github.com/w3c/mediacapture-screen-share/pull/222/files)
    - [PR for MediaTrackSupportedConstraints.suppressLocalAudioPlayback](https://github.com/w3c/mediacapture-screen-share/pull/164/files)
    - [PR for displaySurface Constraint](https://github.com/w3c/mediacapture-screen-share/pull/186/files)
  - Tests: N/A
  - User research: N/A
  - Security and Privacy self-review: Covered by the [existing questionnaire](https://github.com/w3c/mediacapture-screen-share/blob/gh-pages/questionnaire.md).
  - Primary contacts (and their relationship to the specification):
      - Elad Alon (@eladalon1983), Google
  - Organization(s)/project(s) driving the specification: Google
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):
    - [DisplayMediaStreamConstraints.selfBrowserSurface ChromeStatus entry](https://chromestatus.com/feature/5118675366445056)
    - [DisplayMediaStreamConstraints.surfaceSwitching ChromeStatus entry](https://chromestatus.com/feature/5067650299330560)
    - [DisplayMediaStreamConstraints.systemAudio ChromeStatus entry](https://chromestatus.com/feature/4649448880734208)
    - [MediaTrackSupportedConstraints.suppressLocalAudioPlayback ChromeStatus entry](https://chromestatus.com/feature/5201258309746688)
    - [displaySurface Constraint ChromeStatus entry](https://chromestatus.com/feature/5186392840732672)

Further details:

  - [X] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: N/A
  - The group where the work on this specification is currently being done: W3C WebRTC Working Group
  - Major unresolved issues with or opposition to this specification: N/A
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as:
  💬 leave review feedback as a **comment in this issue** and @-notify @eladalon1983

**Comment by eladalon1983** [comment]
2022-06-16: Added `DisplayMediaStreamConstraints.surfaceSwitching` to the list of changes this TAG review is for.

**Comment by maxpassion** [comment]
Hello Elad @eladalon1983, 

We have a discussion in our TAG breakout B meeting, we currently have the following comments:
1. Could you please elaborate more on the multi-stakeholders support of those proposed features?
2. Please do not use google docs for the explainers. You can refer to [https://tag.w3.org/explainers/](url) for explainer writing.

**Comment by maxpassion** [comment]
Since there is no response for the comments for a while, close this for now. Please re-open it when necessary.

**Comment by eladalon1983** [comment]
Apologies for not responding earlier. I am on extended PTO at the moment and so I try to limit work to keeping-the-lights-on.

> Could you please elaborate more on the multi-stakeholders support of those proposed features?

1. Yes.
   * Each of these mini-features links a PR that was merged with the approval of one Mozilla rep and one Apple rep.
   * The linked ChromeStatus entries each reference a request for an official position from Mozilla and Apple. As of the time of this writing, not all of these have received an official response.

> 2. Please do not use google docs for the explainers. You can refer to [https://tag.w3.org/explainers/](https://github.com/w3ctag/design-reviews/issues/url) for explainer writing.

2. I will migrate the explainers and @mention you (@maxpassion) with a request to reopen this thread. This will likely happen in about a month.

**Comment by eladalon1983** [comment]
Hi @maxpassion. The explainers are now also available in `.md` form here:
* [DisplayMediaStreamConstraints.selfBrowserSurface explainer](https://github.com/eladalon1983/screen-share-explainers/blob/main/selfBrowserSurface_Explainer.md)
* [DisplayMediaStreamConstraints.surfaceSwitching explainer](https://github.com/eladalon1983/screen-share-explainers/blob/main/surfaceSwitching_Explainer.md)
* [DisplayMediaStreamConstraints.systemAudio explainer](https://github.com/eladalon1983/screen-share-explainers/blob/main/systemAudio_Explainer.md)
* [MediaTrackSupportedConstraints.suppressLocalAudioPlayback explainer](https://github.com/eladalon1983/screen-share-explainers/blob/main/suppressLocalAudioPlayback_Explainer.md)
* [displaySurface Constraint explainer](https://github.com/eladalon1983/screen-share-explainers/blob/main/displaySurface_Constraint_Explainer.md)
Could you please re-open this issue and review?

**Comment by atanassov** [comment]
Hi @eladalon1983 thank you for providing the `.md` versions of the documents. As we attempt another review today, we found it difficult to understand what is the overall ask for this design review. 

In [this linked thread](https://groups.google.com/a/chromium.org/g/blink-dev/c/bIGZVdkZ4OE/m/G1C2aXcIAAAJ) it was already suggested that you combine the review and outline what are the goals and non-goals, what was considered as alternative approaches, and what should the TAG focus on reviewing - PRs, parts of the PRs etc. If nothing else, at least you can capture these in the issue here.

**Comment by eladalon1983** [comment]
The request is for a review of the five new API surfaces introduced by the five PRs referenced in the original post in this thread. Each PR is associated with its own explainer, linked in the original post on this thread; now also on .md form as per TAG's request. Each of these five surfaces is completely distinct and can be reviewed independently. However, they are presented together here so as to help form a cohesive general picture.

With respect to alternatives considered - each surface had its associated discussion in the WebRTC WG. Some discussions were captured in the relevant GitHub thread.

When triaging this request and attempting to set a priority for it, it might help you to know that, in the intervening time since this thread was started in 2022-06-02, Chrome has already shipped all of these surfaces.

**Comment by cynthia** [comment]
Thank you for taking the time to revisit this, and we apologize for the delay on our end. We've discussed this at length in our virtual F2F, and not only do we think these are useful features for the platform, but we have seen how it was useful in the wild (especially given the pandemic) and we're happy to see features like this make the platform more capable to the users.

Thank you for bringing this to our attention!
