### ISSUE TITLE
Site-initiated mirroring

### ISSUE THREAD

**Issue by takumif** [w3ctag/design-reviews#745]
Wotcher TAG!

I'm requesting a TAG review of site-initiated mirroring.

We're proposing an API to allow Web pages to request mirroring themselves to a
secondary display. They will be allowed to request customization of the
mirroring implementation in certain respects.

- Explainer¹ (minimally containing user needs and example code):
  https://github.com/webscreens/site-initiated-mirroring/blob/main/explainer.md
- User research: N/A
- Security and Privacy self-review²:
  https://github.com/webscreens/site-initiated-mirroring/pull/3
- GitHub repo (if you prefer feedback filed there):
  https://github.com/webscreens/site-initiated-mirroring
- Primary contacts (and their relationship to the specification):
  - Takumi Fujimoto (@takumif), Google (spec proposer)
  - Mark Foltz (@mfoltzgoogle), Google (spec proposer, Presentation API spec
    editor)
  - Anssi Kostiainen (@anssiko), Intel (Second Screen WG chair)
  - Louay Bassbouss (@louaybassbouss), Fraunhofer Gesellschaft (Second Screen WG
    chair)
- Organization/project driving the design: Google Chrome
- External status/issue trackers for this feature (publicly visible, e.g. Chrome
  Status): https://chromestatus.com/feature/5648093276012544

Further details:

- [x] I have reviewed the TAG's
      [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
- The group where the incubation/design work on this is being done (or is
  intended to be done in the future): Second Screen WG/CG
- The group where standardization of this work is intended to be done ("unknown"
  if not known): Second Screen WG
- Existing major pieces of multi-stakeholder review or discussion of this
  design: https://www.w3.org/2021/10/26-webscreens-minutes.html#t03
- Major unresolved issues with or opposition to this design: N/A
- This work is being funded by: The explainer was written by and the Chromium
  implementation is being worked on by Google employees.

We'd prefer the TAG provide feedback as (please delete all but the desired
option):

🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by maxpassion** [comment]
Hello Takumi,

I have one comment:  When there is a network problem or the user close the tab accidentally, is there a mechanism to make sure that the ongoing mirroring session be terminated safely? Otherwise there would be a security/privacy problem.

**Comment by takumif** [comment]
Hi Dapeng,

In those cases, the receiver might keep on showing the last frame it received before it got disconnected -- is that the security/privacy issue you're concerned about?

For network problems, I imagine we'd want to wait some time before we time out and disconnect, just in case the connection is restored quickly and we can resume the mirroring session. Once we time out then the UA can terminate the session and notify the web page via the [`onterminate` event](https://w3c.github.io/presentation-api/#interface-presentationconnection). At that point the UA cannot communicate with the receiver so what the receiver does is up to its implementation, but I expect it to typically also end the session after a timeout.

If the tab is closed, then the UA can terminate the session immediately, and if the web page persists in a non-fully-active state then we can notify it via `onterminate`.

**Comment by ylafon** [comment]
Hi,
I wonder if there is a need to differentiate between local network usage and wan usage here, it might give different prompts based on leakage possibilities. Perhaps addressing this in the security & privacy questionnaire would be good.
Otherwise it looks ok to progress in the Second Screen WG.
Thanks

**Comment by takumif** [comment]
Hi Yves,

Mirroring to a display in the LAN is in scope of the spec but WAN is not. This is also true for the existing Presentation and Remote Playback APIs. [I'll add a paragraph](https://github.com/webscreens/site-initiated-mirroring/pull/4) to the explainer to clarify this.

Thanks for the reviews Dapeng and Yves :)

**Comment by maxpassion** [comment]
Hi @takumif ,  we had a TAG review today and this looks good for us. Thanks for flying TAG.
