### ISSUE TITLE
MiniApp Manifest

### ISSUE THREAD

**Issue by xfq** [w3ctag/design-reviews#752]
Wotcher TAG!

I'm requesting a TAG review of MiniApp Manifest.

MiniApp Manifest defines a JSON-based profile file that provides developers with a centralized place to set up essential information associated with a MiniApp ([What is MiniApp?](https://w3c.github.io/miniapp-white-paper/#what-is-miniapp)).

  - Explainer¹ (minimally containing user needs and example code): https://github.com/w3c/miniapp-manifest/blob/main/docs/explainer.md
  - Specification URL: https://www.w3.org/TR/miniapp-manifest/
  - Tests: [WIP](https://github.com/w3c/miniapp/issues/182)
  - Security and Privacy self-review²: https://github.com/w3c/miniapp-manifest/blob/main/docs/security-privacy-questionnaire.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/miniapp-manifest
  - Primary contacts (and their relationship to the specification):
      - Martin Alvarez-Espinar (@espinr, Huawei, editor)
  - Organization(s)/project(s) driving the specification: Huawei
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: CR in October 2022
  - The group where the work on this specification is currently being done: W3C MiniApps WG
  - Major unresolved issues with or opposition to this specification:

You should also know that...

Previous TAG review: https://github.com/w3ctag/design-reviews/issues/524

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by torgo** [comment]
Hi - just picking this up today at our f2f - @xfq we're largely happy to see this work proceed. Before closing, can you confirm back that you've discussed the additional manifest fields - especially the mini-app specific ones - with the web apps working group to make sure there isn't a collision with any work happening in web app manifest itself? 

/cc @marcoscaceres

**Comment by torgo** [comment]
Agreed today to close and focus the miniapp activity in TAG to #762 and #523.

**Comment by espinr** [comment]
> Hi - just picking this up today at our f2f - @xfq we're largely happy to see this work proceed. Before closing, can you confirm back that you've discussed the additional manifest fields - especially the mini-app specific ones - with the web apps working group to make sure there isn't a collision with any work happening in web app manifest itself?
> 
> /cc @marcoscaceres


Thanks, Dan. The MiniApp WG intends to reuse web app manifest as much as possible. 

Basically, we have identified the overlap of the [`id`](https://www.w3.org/TR/appmanifest/#id-member) and [`app_id`](https://www.w3.org/TR/miniapp-manifest/#app_id-member) members in the specs. We included the MiniApp `app_id` time ago and are now discussing the alignment in w3c/miniapp-manifest#43 and w3c/manifest#1048.
