### ISSUE TITLE
TAG review of Data Catalog Vocabulary (DCAT) - Version 3

### ISSUE THREAD

**Issue by riccardoAlbertoni** [w3ctag/design-reviews#758]
Wotcher TAG!

I'm requesting a TAG review of Data Catalog Vocabulary (DCAT) - Version 3.

DCAT is an RDF vocabulary designed to facilitate interoperability between data catalogs published on the Web.

DCAT enables a publisher to describe datasets and data services in a catalog using a standard model and vocabulary that facilitates the consumption and aggregation of metadata from multiple catalogs. This can increase the discoverability of datasets and data services. It also makes it possible to have a decentralized approach to publishing data catalogs and makes federated search for datasets across catalogs in multiple sites possible using the same query mechanism and structure. Aggregated DCAT metadata can serve as a manifest file as part of the digital preservation process.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/w3c/dxwg/blob/gh-pages/docs/explainer.md
  - Specification URL: https://www.w3.org/TR/2022/WD-vocab-dcat-3-20220510/
  - Security and Privacy self-review²: https://github.com/w3c/dxwg/issues/1507
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/dxwg/
  - Primary contacts (and their relationship to the specification):
      - Peter Winstanley (@pwin), Invited expert: WG Chair & Specification Editor
      - Caroline Burle (@cburle), Invited expert: WG Chair
      - Riccardo Albertoni (@riccardoAlbertoni), Invited expert: Specification Editor
      - David Browning (@davebrowning), Invited expert: Specification Editor
      - Simon Cox (@dr-shorthair), Invited expert: Specification Editor
      - Alejandra Gonzalez Beltran (@agbeltran), Invited expert: Specification Editor
      - Andrea Perego (@andrea-perego), Invited expert: Specification Editor
  - Key pieces of existing multi-stakeholder review or discussion of this specification: https://github.com/w3c/dxwg/issues
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://github.com/w3c/dxwg/issues

Further details:

  - [X] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: End of September, Early October as we plan to move to CR in Autumn.
  - The group where the work on this specification is currently being done: [Dataset Exchange Working Group](https://www.w3.org/groups/wg/dx)
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): [Dataset Exchange Working Group](https://www.w3.org/groups/wg/dx)
  - Major unresolved issues with or opposition to this specification: The DXWG received considerable feedback, requests for additional features and specific use cases. The group has considered the feedback and included suggestions and revisions received, closing more than 160 GitHub issues and discussing an even greater number. However, the total number of issues exceeded the group capacity in terms of effort and available resources. As a result, DXWG was forced to prioritize the efforts to some of the most urgent extensions, dealing with versioning and dataset series. The remaining pending issues are left open in the Github repository for consideration in future DCAT versions.

We'd prefer the TAG to provide feedback as:

  ☂️ open a single issue in our GitHub repo **for the entire review**

**Comment by hadleybeeman** [comment]
Hello! Thanks for your review request, and it's nice to see the progress on DCAT. 

It would be really helpful for us if the explainer could go into a bit of detail about the "more pressing use cases and requests among those left unaddressed in the previous standardization round" that version 3 is addressing. It would help us to understand if/how you've accomplished what you set out to do with DCAT 3.0.

We also try to join up work across working groups and W3C specs. We see that you've created new terms (such as dcat:first, dcat:prev and dcat:last) which could instead be covered by something like [RDF lists](https://www.w3.org/TR/rdf-schema/#ch_collectionvocab) — could you tell us why you made that choice? Are there any other opportunities to reuse existing work in DCAT 3.0?

**Comment by riccardoAlbertoni** [comment]
DXWG replies are tracked by  https://github.com/w3c/dxwg/issues/1530

**Comment by riccardoAlbertoni** [comment]
> DXWG replies are tracked by [w3c/dxwg#1530](https://github.com/w3c/dxwg/issues/1530)

Hi @rhiaro, @danbri and @hadleybeeman,
Can you live with the explanations in  supplied [w3c/dxwg#1530](https://github.com/w3c/dxwg/issues/1530)?

If there is nothing else to clarify, please let us know when we can consider the review from TAG concluded.

Thanks a lot.

**Comment by rhiaro** [comment]
Hi @riccardoAlbertoni, sorry for the delay in following up. We are satisfied with your responses, and are happy to conclude this review. Thanks!
