### ISSUE TITLE
Output Device Selection in Web Audio API: AudioContext.setSinkId()

### ISSUE THREAD

**Issue by hoch** [w3ctag/design-reviews#766]
Hello,

I'm requesting a TAG review of AudioContext.setSinkId().

AudioContext.setSinkId sets the ID of the audio device to use for output. This allows the AudioElement to route audio to a connected output device of user's choosing.

  - Explainer, User research, Security and Privacy self-review: [Public Design Doc](https://docs.google.com/document/d/15_Hi3FGSqcIoUfWy4h33VvqE9IOgHNQGI6NDQlsDJN8/edit#)
  - Primary contacts (and their relationship to the specification):
      - Hongchan Choi (@hoch), Google
      - Paul Adenot (@padenot), Mozilla
  - Organization/project driving the design: W3C Audio WG
  - External status/issue trackers for this feature: https://chromestatus.com/feature/5190163462881280

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): Audio WG
  - The group where standardization of this work is intended to be done: Audio WG
  - Existing major pieces of multi-stakeholder review or discussion of this design: 
      - https://github.com/WebAudio/web-audio-api/issues/2400 (discussion)
      - https://github.com/WebAudio/web-audio-api/pull/2498 (spec change PR)
  - Major unresolved issues with or opposition to this design: None

We'd prefer the TAG provide feedback as (please delete all but the desired option):
  ☂️ open a single issue in our GitHub repo **for the entire review**

**Comment by hoch** [comment]
Adding @svgeesus for visibility: we initially discussed this feature is too small for TAG review, but I am requesting it here per Chrome's launch process.

**Comment by svgeesus** [comment]
TAG review of small, focused features is perfectly fine.

**Comment by svgeesus** [comment]
> some useful abilities will also be included: a) an ability to specify an output device in the AudioContext’s constructor and b) an ability to specify a “silent output device” to minimize the power consumption.

A sentence motivating the user need for each of those two improvements would be a helpful addition to the explainer. Why does WebAudio API need them? Why does HTML not have them, and should it?

**Comment by hoch** [comment]
Thanks for the feedback, @svgeesus! I've added the "Motivation" section on the explainer. (i.e. public design doc above)

**Comment by maxpassion** [comment]
> Thanks for the feedback, @svgeesus! I've added the "Motivation" section on the explainer. (i.e. public design doc above)
> 
> > Why does HTML not have them, and should it?
> 
> For this question, I am not sure if I can answer it with confidence. For what it's worth, there's a method [selectAudioOutput()](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/selectAudioOutput) under MediaDevices, but I don't think that is suitable for Web Audio API.

Hi @hoch, you mentioned that [selectAudioOutput()] is not suitable for Web Audio API, could you update the explainer document to explain the reason behind the design choices?

**Comment by hoch** [comment]
@maxpassion Here's my response to the question ([link](https://docs.google.com/document/d/15_Hi3FGSqcIoUfWy4h33VvqE9IOgHNQGI6NDQlsDJN8/edit#bookmark=id.jt7ulmx5yyqq
)):

Using [selectAudioOutput()](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/selectAudioOutput) under MediaDevices:

Although the [Audio Output Device API](https://w3c.github.io/mediacapture-output/#dom-mediadevices-selectaudiooutput) spec mentions briefly about AudioContext, it lacks the detail of how Web Audio API is controlled by this method. (As of writing, no browser has implemented this feature) Additionally, the method is designed to change the audio output device for all instances of MediaElement and AudioContext in a document. Even with the implementation of selectAudioOutput(), AudioContext doesn't have the ability to set the output device separately whereas AudioElement does.

**Comment by torgo** [comment]
Thanks for this review request. We're happy to see this move forward and we're especially glad to see it do so with multiple stakeholder support and the attention to privacy considerations. We are slightly concerned that some of the functionality is duplicated elsewhere in the platform, however we understand the different context.  Can you please move the explainer into a markdown file in the appropriate repo? 🎶

**Comment by hoch** [comment]
@torgo Thanks for your review! I'll move the explainer to https://github.com/WebAudio/web-audio-api.
