### ISSUE TITLE
Multi-Screen Window Placement on the Web - Initiating Multi-Screen Experiences

### ISSUE THREAD

**Issue by michaelwasserman** [w3ctag/design-reviews#767]
Wotcher TAG!

I'm requesting a TAG review of Multi-Screen Window Placement on the Web - Initiating Multi-Screen Experiences.

This proposal introduces a Multi-Screen Window Placement API enhancement that would allow web applications to initiate a multi-screen experience from a single user activation.

  - Explainer¹ (minimally containing user needs and example code): [Explainer](https://github.com/w3c/window-placement/blob/main/EXPLAINER_initiating_multi_screen_experiences.md)
  - User research: [Feature Request](https://github.com/w3c/window-placement/issues/98)
  - Security and Privacy self-review²: [Questionnaire](https://github.com/w3c/window-placement/blob/main/security_and_privacy_initiating_multi_screen_experiences.md)
  - GitHub repo (if you prefer feedback filed there): [Repo](https://github.com/w3c/window-placement)
  - Primary contacts (and their relationship to the specification):
      - Mike Wasserman (@michaelwasserman), [Google] (Spec editor)
      - Joshua Bell (@inexorabletash), [Google] (Spec editor)
      -  Anssi Kostiainen (@anssiko), [Intel] ([Second Screen WG](https://www.w3.org/2014/secondscreen/) co-chair)
      - Louay Bassbouss (@louaybassbouss), [Fraunhofer FOKUS] ([Second Screen WG](https://www.w3.org/2014/secondscreen/) co-chair)
  - Organization/project driving the design: Google
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5173162437246976

Further details:
  - [✓] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): [Second Screen WG](https://www.w3.org/2014/secondscreen/)
  - The group where standardization of this work is intended to be done ("unknown" if not known): [Second Screen WG](https://www.w3.org/2014/secondscreen/)
  - Existing major pieces of multi-stakeholder review or discussion of this design: [Mozilla standards position issue](https://github.com/mozilla/standards-positions/issues/636) and [Prior TAG review request](https://github.com/w3ctag/design-reviews/issues/602#issuecomment-1121694034)
  - Major unresolved issues with or opposition to this design: Mozilla security considerations (see above), TAG request for a new design review (see above)
  - This work is being funded by: Google

You should also know that...

I appreciate your time reviewing this proposal; thank you!

We'd prefer the TAG provide feedback as (please delete all but the desired option):
  💬 leave review feedback as a **comment in this issue** and @-notify @michaelwasserman

**Comment by michaelwasserman** [comment]
If it is helpful, the high-level Explainer changes since my [earlier review request](https://github.com/w3ctag/design-reviews/issues/602#issuecomment-1121694034) are:
- A new [Security Considerations](https://github.com/w3c/window-placement/blob/main/EXPLAINER_initiating_multi_screen_experiences.md#security-considerations) section (and a terse Security and Privacy [self-review](https://github.com/w3c/window-placement/blob/main/security_and_privacy_initiating_multi_screen_experiences.md))
  - These document and attempt to address points raised by [earlier TAG review](https://github.com/w3ctag/design-reviews/issues/602#issuecomment-1195596347) and [Mozilla](https://github.com/mozilla/standards-positions/issues/636#issuecomment-1132985573)
- More detailed [Spec Changes](https://github.com/w3c/window-placement/blob/main/EXPLAINER_initiating_multi_screen_experiences.md#spec-changes), with Multi-Screen Window Placement Working Draft Spec links.
- A new [Example Code](https://github.com/w3c/window-placement/blob/main/EXPLAINER_initiating_multi_screen_experiences.md#example-code) section

**Comment by michaelwasserman** [comment]
This is available in Chrome without a flag since 104. A partner requested this functionality when integrating the Multi-Screen Window Placement API in their web application. We have not yet received explicit signals from any other engines. Should I have requested a "Specification review" rather than an "Early design review"?

I would still greatly appreciate TAG feedback, and especially guidance for generalizing the design to support initiating a broader set of multi-display web application experiences. Web application developers have continued to express strong interest in this space via w3c/window-placement#98, w3c/window-placement#92, w3c/window-placement#74, and w3c/window-placement#7.

**Comment by torgo** [comment]
Hi @michaelwasserman yes probably it would have been better to request a spec review for something this far along in the process. We're concerned about the lack of multi-stakeholder support or signals thereof. We note extensive discussion on the security considerations in mozilla/standards-positions [#636](https://github.com/mozilla/standards-positions/issues/636) and [#542](https://github.com/mozilla/standards-positions/issues/542) which don't seem to have come to resolution yet. Any update on this or info on other implementers supporting / working on this?  Lack of feature detection is also concerning and goes against our [design principle](https://w3ctag.github.io/design-principles/#feature-detect) on detectability.

**Comment by torgo** [comment]
Hi @michaelwasserman has there been any update you can share? Thanks!

**Comment by michaelwasserman** [comment]
Hi @torgo, thanks for your consideration and persistence, I apologize for my delayed reply.

1) Regarding Mozilla standards positions ([#636](https://github.com/mozilla/standards-positions/issues/636) and [#542](https://github.com/mozilla/standards-positions/issues/542)): We held promising discussions in webscreens [2022 Q2](https://www.w3.org/2022/06/07-webscreens-minutes.html#:~:text=Public%20Working%20Draft-,Mozilla%27s%20feedback,-Mozilla%20position%3A%20Multi) and [TPAC 2022](https://www.w3.org/2022/09/16-webscreens-minutes.html#t06:~:text=Mozilla%20standard%20position) meetings. I also merged [#100](https://github.com/w3c/window-placement/pull/100/files) and replied with security consideration clarifications and new mitigation ideas. We are still awaiting a response.

2) Regarding WebKit's standards positions: We are awaiting responses on [#117](https://github.com/WebKit/standards-positions/issues/117) and older webkit-dev requests ([original api](https://lists.webkit.org/pipermail/webkit-dev/2021-June/031903.html) and [this enhancement](https://lists.webkit.org/pipermail/webkit-dev/2022-May/032223.html)), and other forms of outreach have not yet been fruitful.

3) There is a [spec issue for feature-detection](https://github.com/w3c/window-placement/issues/9), which deserves exploration and discussion.

Here are some AIs I can take upon myself, WDYT?
- Open a new TAG spec review request (for the entire spec) as part of our [wide review](https://github.com/w3c/window-placement/issues/110) effort.
- Ping and update standards-positions issues and invite discussion before/during [Second Screen WG/CG - 2023 Q1 virtual meeting #7](https://github.com/w3c/secondscreen-wg/issues/7)
- Continue refining the spec’s security considerations section and feature-detection issue

**Comment by torgo** [comment]
Hi @michaelwasserman   Based on your comments it looks like the issues TAG has raised are being considered.  On this basis we’re happy to close this review as “satisfied”.
 
Regarding opening up a new review request for the entire spec, I think we already had some signifigant discussion in [issue 602](https://github.com/w3ctag/design-reviews/issues/602).  I think it may be appropriate to open up a new issue as part of wide review when the spec goes to CR.
