### ISSUE TITLE
Delta review (to CR) of WebXR Augmented Reality Module

### ISSUE THREAD

**Issue by himorin** [w3ctag/design-reviews#769]
Wotcher TAG!

I'm requesting a TAG review of WebXR Augmented Reality Module.

The WebXR Augmented Reality Module extends the WebXR Device API to expose the ability to create a basic augmented reality (AR) session.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/immersive-web/webxr-ar-module/blob/master/ar-module-explainer.md
  - Specification URL: https://www.w3.org/TR/webxr-ar-module-1/
  - Tests: https://github.com/web-platform-tests/wpt/tree/master/webxr/ar-module
  - User research: N/A
  - Security and Privacy self-review²: https://github.com/immersive-web/webxr-ar-module/issues/85 ([initial phase](https://github.com/immersive-web/webxr-ar-module/blob/master/security-privacy-questionnaire.md))
  - GitHub repo (if you prefer feedback filed there): https://github.com/immersive-web/webxr-ar-module
  - Primary contacts (and their relationship to the specification):
      - Manish Goregaokar, @Manishearth, Google, Editor
      - Brandon Jones, @toji, Google, Editor
      - Rik Cabanier, @cabanier, Meta
      - Ada Rose Cannon, @AdaRoseCannon, Apple, Chair
      - Chris Wilson, @cwilso, Google, Chair
      - Ayşegül Yönet, @Yonet , Microsoft
  - Organization(s)/project(s) driving the specification: [Immersive Web WG](https://www.w3.org/immersive-web/)
  - Key pieces of existing multi-stakeholder review or discussion of this specification: N/A
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):
    - Chrome Status: https://chromestatus.com/feature/5450241148977152

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: delta review request for CR transition (no solid date)
  - The group where the work on this specification is currently being done: [Immersive Web WG](https://www.w3.org/immersive-web/)
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue):
  - Major unresolved issues with or opposition to this specification: N/A
  - This work is being funded by: N/A

You should also know that...

- Last TAG review was #462 (2020/Jan), right after FPWD
- Please see [changes from FPWD](https://www.w3.org/TR/webxr-ar-module-1/#changes-from-20191010)

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by torgo** [comment]
Hi @himorin - We reviewed this week and we don't think [any of the chanegs](https://www.w3.org/TR/webxr-ar-module-1/#changes-from-20191010) represent any architectural changes from the previous positive review.  Privacy considerations looks great.  Thanks!
