### ISSUE TITLE
Delta review (to CR) of WebXR Gamepads Module

### ISSUE THREAD

**Issue by himorin** [w3ctag/design-reviews#770]
Wotcher TAG!

I'm requesting a TAG review of WebXR Gamepads Module.

This specification module describes support for accessing button, trigger, thumbstick, and touchpad data associated with virtual reality (VR) and augmented reality (AR) devices on the Web.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/immersive-web/webxr-gamepads-module/blob/master/gamepads-module-explainer.md
  - Specification URL: https://www.w3.org/TR/webxr-gamepads-module-1/
  - Tests: https://github.com/web-platform-tests/wpt/tree/master/webxr/gamepads-module
  - User research: N/A
  - Security and Privacy self-review²: https://github.com/immersive-web/webxr-gamepads-module/issues/56
  - GitHub repo (if you prefer feedback filed there): https://github.com/immersive-web/webxr-gamepads-module/
  - Primary contacts (and their relationship to the specification):
      - Manish Goregaokar, @Manishearth, Google, Editor
      - Brandon Jones, @toji, Google, Editor
      - Rik Cabanier, @cabanier, Meta
      - Ada Rose Cannon, @AdaRoseCannon, Apple, Chair
      - Chris Wilson, @cwilso, Google, Chair
      - Ayşegül Yönet, @Yonet , Microsoft
  - Organization(s)/project(s) driving the specification: [Immersive Web WG](https://www.w3.org/immersive-web/)
  - Key pieces of existing multi-stakeholder review or discussion of this specification: N/A
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):
    - Chrome status: https://chromestatus.com/feature/5659025263820800

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: delta review request for CR transition (no solid date)
  - The group where the work on this specification is currently being done: [Immersive Web WG](https://www.w3.org/immersive-web/)
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue):
  - Major unresolved issues with or opposition to this specification: N/A
  - This work is being funded by: N/A

You should also know that...

- Last TAG review was #430 (2019/Oct), right after FPWD
  - one unresolved issue from last review, https://github.com/immersive-web/webxr-gamepads-module/issues/27, handed to Gamepad API https://github.com/w3c/gamepad/pull/158
- Please see [changes from FPWD](https://www.w3.org/TR/webxr-gamepads-module-1/#changes-from-20191010) 

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by torgo** [comment]
One question that came up in our discussions today on this – Are there any updates that need to be made to the explainer based on the listed changes to the spec?

**Comment by torgo** [comment]
Also … it seems from https://github.com/immersive-web/webxr-gamepads-module/pull/49 that you're talking about exposing the gamepad outside of the XR environment?  If so, then doesn't this "compete" with the plain [gamepad API](https://w3c.github.io/gamepad/)?

**Comment by cabanier** [comment]
I think that should be a note.
The intent is to clarify that a gamepad can be exposed through the regular gamepad api and WebXR at the same time.

**Comment by torgo** [comment]
Hi @cabanier thanks for sending us this review. We're happy to see this go forward. Thanks for flying TAG and see you in the New Year.
