### ISSUE TITLE
Requesting TAG review for Trace Context Level 2 changes

### ISSUE THREAD

**Issue by kalyanaj** [w3ctag/design-reviews#777]
Hello TAG!

I'm requesting a TAG review of Trace Context Level 2 which is in FPWD.

**What:** The main difference from Trace Context Level 1 (which is already in recommendation status) is the ability to express whether at least a part of the traceID has been randomly (or pseudo-randomly) generated. 
**Why:** This enables downstream systems to use the trace ID for sampling purposes or for sharding purposes. 
**How:** This is achieved by the introduction of a new flag called "Random Trace ID flag".  If the newly introduced random-trace-id flag is set, at least the right-most 7 bytes of the trace-id MUST be randomly (or pseudo-randomly) generated. 

  - Explainer¹ (minimally containing user needs and example code): [[url]](https://github.com/w3c/distributed-tracing-wg/blob/main/EXPLAINER.md)
  - Specification URL:  https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Ftrace-context-1%2F&doc2=https%3A%2F%2Fwww.w3.org%2FTR%2F2022%2FWD-trace-context-2-20220929%2F
  - Tests: https://github.com/w3c/trace-context/tree/main/test, WIP for random-id flag.
  - User research: 
  - Security and Privacy self-review²: https://github.com/w3c/trace-context/issues/496
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/trace-context/
  - Primary contacts (and their relationship to the specification):
      - [Sergey Kanzhelev](https://github.com/SergeyKanzhelev), [Google], co-chair/editor]
      - [Daniel Dyla](https://github.com/dyladan), [Dynatrace], Editor]
      - [J. Kalyana Sundaram](https://github.com/kalyanaj), [Microsoft], co-chair]
  - Organization(s)/project(s) driving the specification:  Multiple companies
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://github.com/w3c/trace-context/issues

Further details:

  - [X] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: We want to get to CR before end of year
  - The group where the work on this specification is currently being done: [Distributed Tracing Working Group](https://www.w3.org/groups/wg/distributed-tracing)
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): [Distributed Tracing Working Group](https://www.w3.org/groups/wg/distributed-tracing)
  - Major unresolved issues with or opposition to this specification:  None
  - This work is being funded by:  Multiple companies

You should also know that...

[please tell us anything you think is relevant to this review]

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by maxpassion** [comment]
Hi @kalyanaj , we had a discussion at our TAG meeting today and are generally happy with this proposal.
