### ISSUE TITLE
CSS Values and Units Level 4

### ISSUE THREAD

**Issue by fantasai** [w3ctag/design-reviews#781]
Wotcher TAG!

I'm requesting a TAG review of  CSS Values and Units Level 4.

[One paragraph summary of idea, ideally copy-pasted from Explainer introduction]

  - Explainer¹ (minimally containing user needs and example code): None
  - Specification URL: https://www.w3.org/TR/css-values-4/
  - Tests: https://wpt.fyi/results/css/css-values
  - User research: None
  - Security and Privacy self-review²: https://lists.w3.org/Archives/Public/www-style/2022Oct/0008.html
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/csswg-drafts/issues
  - Primary contacts (and their relationship to the specification):
      - Elika J. Etemad (@fantasai), editor
      - Tab Atkins-Bittner (@tabatkins), Google, editor
  - Organization(s)/project(s) driving the specification: Google
  - Key pieces of existing multi-stakeholder review or discussion of this specification: https://www.w3.org/Search/Mail/Public/search?type-index=www-style&index-type=t&keywords=css-values-4&search=Search
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue+is%3Aopen+label%3Acss-values-4

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: Hoping to transition to CR sometime in the next 3-6 months.
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): CSSWG
  - Major unresolved issues with or opposition to this specification:
      - Some [open issues around clarifying URL handling](https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+label%3Acss-values-4+label%3A%22topic%3A+urls%22)
      - Some [open issues around viewport units](https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue+is%3Aopen+label%3Acss-values-4+viewport)
  - This work is being funded by: Spec editing by Google, implementation across all the browser core teams.

You should also know that...

This spec is now feature-frozen; additional features will be added in Level 5.

Please let us know if you would like us to follow up with the TAG once the URL and viewport unit issues are resolved or if you don't feel the need to have a re-review requested.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by LeaVerou** [comment]
This is a fairly mature specification, so we're fine to close this. Thank you for flying TAG!
