### ISSUE TITLE
Content-type in Resource Timing

### ISSUE THREAD

**Issue by abinpaul1** [w3ctag/design-reviews#785]
Wotcher TAG!

I'm requesting a TAG review of Content-type in Resource Timing.

Proposal to add a new field `contentType` to PerformanceResourceTiming which holds a string corresponding to the content type of the fetched resource

  - Explainer: https://github.com/abinpaul1/resource-timing/blob/explainer-content-type/Explainers/Content-Type.md
  - Specification URL: https://github.com/w3c/resource-timing/pull/341
  - Tests: https://github.com/web-platform-tests/wpt/pull/36059
  - User research: None
  - Security and Privacy self-review: https://github.com/abinpaul1/resource-timing/blob/explainer-content-type/Explainers/Content-Type.md#self-review-questionnaire-security-and-privacy
  - Primary contacts (and their relationship to the specification):
      - Abin K Paul (@abinpaul1), spec author
      - Yoav Weiss (@yoavweiss), Google, spec mentor
  - Organization(s)/project(s) driving the specification: Google
  - Key pieces of existing multi-stakeholder review or discussion of this specification: 
  - External status/issue trackers for this specification: https://chromestatus.com/feature/5156068351541248

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: 
  - The group where the work on this specification is currently being done: W3C Web Performance WG
  - Major unresolved issues with or opposition to this specification: None
  - This work is being funded by: Google

You should also know that...

We'd prefer the TAG provide feedback as :

  💬 leave review feedback as a **comment in this issue** and @-notify @abinpaul1 @yoavweiss

**Comment by maxpassion** [comment]
Hi @abinpaul1, We had a discussion last week and this proposal looks good to us.
