### ISSUE TITLE
UI Events Keyboard Events Key Values review request

### ISSUE THREAD

**Issue by LJWatson** [w3ctag/design-reviews#789]
Wotcher TAG!

I'm requesting a TAG review of [UI Events Keyboard Events Key Values](https://w3c.github.io/uievents-key/)

>This document specifies the set of valid key attribute values  that MUST be used in the KeyboardEvent's key  attribute to encode the key’s meaning.

  - Specification URL: https://w3c.github.io/uievents-key/
  - Security and Privacy self-review²: https://github.com/w3c/uievents-key/issues/57#issuecomment-1301234131
  - Primary contacts (and their relationship to the specification):
LJWatson - WebApps Chair
@marcoscaceres  WebApps Chair
@garykac UI Events Editor

  - Relevant time constraints or deadlines: We'd appreciate this review being completed before 2022-01-31
  -   - The group where the work on this specification is currently being done: WebApps

**Comment by LeaVerou** [comment]
Hi @LJWatson et al,

Thank you for submitting a review request. Could you please add an [explainer](https://tag.w3.org/explainers/)? 
Thank you!

**Comment by LJWatson** [comment]
Thanks @LeaVerou. We don't have an explainer for this spec, partly because of its simple nature and partly because the [Introduction](https://w3c.github.io/uievents-key/) explains what it is and we don't think a detailed explainer would add anything useful.

**Comment by marcoscaceres** [comment]
If it helps as an explainer, there is a good MDN page covering UI Events:
https://developer.mozilla.org/en-US/docs/Web/API/UI_Events

(our spec just covers a small part of that)

**Comment by LeaVerou** [comment]
This looks good to us. Thank you for flying TAG!

**Comment by LJWatson** [comment]
With thanks to the TAG, your review is appreciated as always.
