### ISSUE TITLE
Gamepad Extensions API touch input

### ISSUE THREAD

**Issue by bradleyneedham** [w3ctag/design-reviews#799]
Wotcher TAG!

I'm requesting a TAG review of Gamepad Extensions API touch input.

Many modern gamepads support touch functionality. This proposal addresses the missed inputs by adding the events to the gamepad.

* Explainer: [Gamepad Touch Extension](https://github.com/bradleyneedham/gamepad/blob/multitouch-explainer/multitouch_explainer.md)
* Specification URL: [Pull request](https://github.com/w3c/gamepad/pull/168)
* Tests: None yet, web platform tests will be added with the prototype implementation
* Security and Privacy self-review:
* Primary contacts:
  * Matt Reynolds (@nondebug), Google, Spec editor, Implementer
  * Bradley Needham (@bradleyneedham), Sony, Spec contributor, Implementer
* Organization(s)/project(s) driving the specification: Web Apps WG
* Chrome Status: https://chromestatus.com/feature/4782975812108288

**Comment by MattMenke2** [comment]
The linked pull request completely replaces the contents of a file ("extensions.html").  Is this review for the delta between the old version of the file and a new version, or is it for the new version of the file?  Also, I'm not seeing a privacy section?

**Comment by bradleyneedham** [comment]
The deltas.
Looks like my run of tidy might have made too many white space changes so it looks like the entire file is replaced.
Some wording changes to section 7 and many updates to section 8 with the addition of 8.1 and 8.2 are what I made.
Not sure about the privacy section @nondebug may have a response to that.

**Comment by MattMenke2** [comment]
I'm still not sure if this tag review is for the delta, or the entire file.  The file is entitled "Gamepad Touch Extension", this request is entitled "Gamepad Extensions API touch input", which sounds like the entire API, as opposed to just the parts of it being changed in the linked PR.

**Comment by MattMenke2** [comment]
Oops - missed the first line of your response.  Sorry.

**Comment by RByers** [comment]
FWIW we had some [discussions](https://github.com/w3c/pointerevents/issues/206) years ago in the PointerEvents WG about event models for non-screen-relative touchpads. Mostly we decided they were too different from PointerEvents (and not urgent enough) so never made progress on it. But the fact that these sorts of touchpads do not have pixel coordinates is (or any other sort of connection to the rendering surface), IMHO, a reasonable reason for the API to be completely separate from our input event APIs.

**Comment by torgo** [comment]
We are late getting to this so apologies. We're largely happy with this proposal given the constraints proposed and in particular the integration into Gamepad API itself and the documented non-goals. I would like to suggest that you amend the explainer with some explicit (example) user needs - "the user wants to do xxx..." rather than starting right away with "Enable applications to consume inputs ...". However we're happy to close this.
