### ISSUE TITLE
WebAssembly JavaScript Promise Integration API

### ISSUE THREAD

**Issue by fgmccabe** [w3ctag/design-reviews#809]
Wotcher TAG!

I'm requesting a TAG review of JSPI.

The WebAssembly JavaScript Promise Integration (JSPI) API is a standard-track effort of the WebAssembly WG (via its CG) to allow WebAssembly applications to access asynchronous APIs, under the constraint that the only changes are to the JS API and not to core WebAssembly (or to JavaScript)

  - [Explainer](https://github.com/WebAssembly/js-promise-integration/blob/main/proposals/js-promise-integration/Overview.md)
  - Specification URL: [spec url](https://github.com/WebAssembly/js-promise-integration/blob/main/proposals/js-promise-integration/Overview.md)
  - Tests: [wpt](https://github.com/WebAssembly/js-promise-integration/tree/main/test/js-api/js-promise-integration)
  - User research: [url to public summary/results of research]
  - Security and Privacy self-review²: [url](https://github.com/WebAssembly/js-promise-integration/discussions/19)
  - GitHub repo (if you prefer feedback filed there): [url](https://github.com/WebAssembly/js-promise-integration)
  - Primary contacts (and their relationship to the specification):
      - Co-champions: [Francis McCabe](fgmccabe),  [Ross Tate](ross.tate@gmail.com)
      - CG Chairs: [Deepti Gandluri](gdeepti@chromium.org), [Derek Schuff](dschuff@chromium.org), [Conrad Watt](conrad.watt@cl.cam.ac.uk)
  - Organization(s)/project(s) driving the specification: WebAssembly CG
  - Key pieces of existing multi-stakeholder review or discussion of this specification: see [explainer](https://github.com/WebAssembly/js-promise-integration)
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): see [chrome status](https://chromestatus.com/feature/5674874568704000)

Further details:

  - [ x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: There is no specific deadline; however, a second browser implementation is anticipated in 2023H1.
  - The group where the work on this specification is currently being done: WebAssembly Community Group
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): WebAssembly Working Group
  - Major unresolved issues with or opposition to this specification: none
  - This work is being funded by:

You should also know that...

1. The purpose of this API is to allow WebAssembly applications originally written against synchronous APIs to work with APIs that are mostly asynchronous in nature (i.e., Web APIs). WebAssembly code is typically compiled from languages like C++ that do not have a rich history of asynchronous functionality.
2. We have been careful in the design to not require any changes to either the JavaScript language or the WebAssembly instruction set.
3. We have been careful to constrain the design in such a way that JavaScript applications cannot use JSPI to implement alternate suspension mechanisms to those already part of the Web ecosystem. (I.e., JS programs cannot use JSPI to suspend themselves.)
4. This is part of a larger effort to bring coroutining capabilities to WebAssembly. However, this is not dependent on those efforts and also has benefits that do not rely on 'core' stack switching.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  ☂️ open a single issue in our GitHub repo **for the entire review**. Note, if appropriate, it is also possible to initiate discussion topics on the [repo](https://github.com/WebAssembly/js-promise-integration/discussions)

**Comment by fgmccabe** [comment]
I was wondering if there was any movement from the TAG on this issue.
We are hoping to ship this API in 24H1.

**Comment by fgmccabe** [comment]
Chrome (M123) is just about to enter origin trial for this feature.

**Comment by jyasskin** [comment]
Thank you @fgmccabe for bringing this to us, and we apologize for taking so long to respond to it. We appreciate the work to integrate Promises into Web Assembly. We think the Web Assembly CG is/has been the right place to review it, so we're going to decline the review here.
