### ISSUE TITLE
CR Snapshot Review for EPUB 3.3

### ISSUE THREAD

**Issue by wareid** [w3ctag/design-reviews#816]
こんにちは TAG-さん!

I'm requesting a TAG review of EPUB 3.3, EPUB Reading Systems 3.3, and EPUB Accessibility 1.1.

A review of these specifications was completed mid-way through 2022, but as we approach PR we have been asked to get another review and sign off for our latest CR snapshot. You can review the change logs for each document (linked below), but the majority of the changes made since last review have been editorial clarifications of existing features, additions based on review (specifically our addition of the Security and Privacy sections for each document), and clarifications based on [test results](https://w3c.github.io/epub-tests/results). 

  - Explainer¹: [Overview](https://www.w3.org/TR/epub-overview-33/)
  - Specification URL: [EPUB 3.3](https://w3.org/TR/epub-33), [EPUB Reading Systems 3.3](https://w3.org/TR/epub-rs-33), [EPUB Accessibility 1.1](https://w3.org/TR/epub-a11y-11)
  - Change log URLs: [EPUB 3.3 change log](https://www.w3.org/TR/epub-33/#change-log), [EPUB Reading Systems 3.3 change log](https://www.w3.org/TR/epub-rs-33/#change-log), [EPUB Accessibility 1.1 change log](https://www.w3.org/TR/epub-a11y-11/#change-log)
  - Tests: [EPUB Tests](https://w3c.github.io/epub-tests/)
  - Security and Privacy self-review²: [Our self-review](https://github.com/w3c/epub-specs/blob/main/epub33/explainers/EPUB-33-security-privacy.md)
  - GitHub repo (if you prefer feedback filed there): [EPUB WG](https://github.com/w3c/epub-specs/)
  - Primary contacts (and their relationship to the specification):
      - [Dave Cramer] ([dauwhe]), [Hachette]
      - [Shinya Takami] ([shiestyle]), [KADOKAWA]
      - [Wendy Reid] ([wareid]), [Rakuten Kobo]
      - [Matt Garrish] ([mgarrish]), [DAISY]
      - [Ivan Herman] ([iherman]), [W3C]
  - Key pieces of existing multi-stakeholder review or discussion of this specification: [Previous TAG Review](https://github.com/w3ctag/design-reviews/issues/684)

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: We plan to publish our CR Snapshot on February 21st, then go to PR on April 11 barring any issues.
  - The group where the work on this specification is currently being done: EPUB 3 Working Group
  - Major unresolved issues with or opposition to this specification: None 

You should also know that...

We appreciate your feedback!

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by wareid** [comment]
Changes we think will be of interest to the TAG: 
EPUB 3.3 
* 11-Jan-2023: Marked the dir attribute under-implemented due to lack of support in reading systems. See [pull request 2515](https://github.com/w3c/epub-specs/pull/2515).
* 18-July-2022: The viewport meta element for specifying the initial containing boundary in fixed-layout documents is now formally defined. See [issue 2292](https://github.com/w3c/epub-specs/issues/2292). 
* 07-June-2022: The usage of File URLs has been disallowed. See [issue 2324](https://github.com/w3c/epub-specs/issues/2324).
* 07-June-2022: Updated privacy and security recommendations to use normative language. See [pull request 2297](https://github.com/w3c/epub-specs/pull/2297).
* 27-May-2022: Added recommendation to only reference remote resources via https. See [issue 2263](https://github.com/w3c/epub-specs/issues/2263).

EPUB Reading Systems 3.3 
* 06-Jan-2023: Reduced the requirement to support prefixed CSS properties to a recommendation. See [pull request 2514](https://github.com/w3c/epub-specs/pull/2514).
* 22-July-2022: The name and version properties of the epubReadingSystem object have been deprecated. See [issue 1872](https://github.com/w3c/epub-specs/issues/1872).
* 07-June-2022: The usage of File URLs has been disallowed. See [issue 2324](https://github.com/w3c/epub-specs/issues/2324).
* 07-June-2022: Noted that unsigned EPUB publications represent a security risk and added recommendation to treat sideloaded unsigned publications as untrusted. See [issue 2265](https://github.com/w3c/epub-specs/issues/2265).
* 07-June-2022: Updated privacy and security recommendations to use normative language.
* 27-May-2022: Added reading system conformance section. See [issue 2271](https://github.com/w3c/epub-specs/issues/2271).
* 27-May-2022: Added recommendation to only load remote resources referenced via https. See [issue 2263](https://github.com/w3c/epub-specs/issues/2263).

EPUB Accessibility 1.1 
* 07-June-2022: Updated privacy and security recommendations to use normative language.

**Comment by rhiaro** [comment]
Thanks for the summary list of changes for us to review. 

We appreciate the strengthening of the security and privacy sections.

We're finding it difficult to review the other changes based on links to PRs and issue discussions however. We'd like to be able to provide meaningful feedback that is useful to the WG. Could you put together a small explainer for the important changes, including what user needs have been addressed by them and why you ended up with the solutions you did? And if you have any specific questions or sections of the spec(s) it would be useful for us to focus on, could you let us know that as well?

**Comment by wareid** [comment]
@rhiaro Apologies for the massive delay on this, I was trying to come up with an explanation for the other items. 

To be honest, none of the changes we have made have been particularly significant, many involve reacting to test results. Since the overall work on EPUB 3.3 has been refining the specs as opposed to introducing new features, our changes have been incremental.

**Comment by hadleybeeman** [comment]
Hi @wareid et al! Given that you've told us that 3.3 contains only incremental changes, we surmise that there are no new architectural issues — so we we won't do a TAG review. 

Best of luck with this work, and do come back to us if there is anything we can help with.

**Comment by wareid** [comment]
@hadleybeeman Thanks so much! Much appreciated.
