### ISSUE TITLE
Review of DPUB-ARIA 1.1 and DPUB-AAM 1.1

### ISSUE THREAD

**Issue by mattgarrish** [w3ctag/design-reviews#821]
こんにちは TAG-さん!

I'm requesting a TAG review of Digital Publishing WAI-ARIA Module 1.1 and Digital Publishing Accessibility API Mappings 1.1.

WAI-ARIA is a technical specification that defines a common host language semantic accessibility API and framework that enables web browsers to map the accessibility semantics in web content to platform-specific accessibility APIs. This enables web content to be interoperable with platform assistive technologies similar to native platform applications without platform dependencies. DPUB-ARIA is a modular extension of WAI-ARIA designed for the digital publishing industry, with mappings to the platform accessibility APIs defined in DPUB-AAM.

  - Explainer¹ (minimally containing user needs and example code): https://www.w3.org/TR/2023/WD-dpub-aria-1.1-20230222/#introduction (see also the [ARIA roadmap](https://www.w3.org/TR/2008/WD-wai-aria-roadmap-20080204/) for an overview of WAI-ARIA)
  - Specification URL:
    - https://www.w3.org/TR/2023/WD-dpub-aria-1.1-20230222/
    - https://www.w3.org/TR/2023/WD-dpub-aam-1.1-20230223/
  - Tests: Testing of roles will be done during CR
  - User research: N/A
  - Security and Privacy self-review²: Security and privacy considerations are adapted from ARIA as the DPUB module only extends the list of roles, it does not add new features. See https://www.w3.org/TR/2023/WD-dpub-aria-1.1-20230222/#privacy-and-security-considerations
  - GitHub repo (if you prefer feedback filed there):
    - https://github.com/w3c/dpub-aria
    - https://github.com/w3c/dpub-aam
  - Primary contacts (and their relationship to the specification):
      - Matt Garrish, @mattgarrish, DAISY Consortium, Editor
      - Tzviya Siegman, @TzviyaSiegman, Wiley, Editor
      - James Nurthen, @jnurthen, Adobe, Chair ARIA WG
      - Valerie Young, @spectranaut, Bocoup, Chair ARIA WG
  - Organization(s)/project(s) driving the specification: W3C / Publishing@W3C / ARIA
  - Key pieces of existing multi-stakeholder review or discussion of this specification: N/A
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):
    - https://github.com/w3c/dpub-aria/issues
    - https://github.com/w3c/dpub-aam/issues

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: No hard deadlines to move to CR
  - The group where the work on this specification is currently being done: Work is done by the DPUB-ARIA task force of the ARIA WG. Work on the specifications is largely carried out through github, not by meetings.
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): N/A
  - Major unresolved issues with or opposition to this specification: None
  - This work is being funded by: N/A

You should also know that...

DPUB-ARIA and DPUB-AAM are extensions of ARIA/Core-AAM. As such, they don't represent new technologies; they only introduce new roles for publishing using the existing ARIA framework.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by daniel-montalvo** [comment]
@rhiaro  @torgo  @plinss 

The group is planning on moving this to CR soon. Have you reviewed these specs or you still plan on submitting a review in the near future?

Best.

**Comment by daniel-montalvo** [comment]
@rhiaro @torgo @plinss
Hearing no objections to the above comment, @mattgarrish and I are planning on moving this forward imminently.

**Comment by rhiaro** [comment]
Sincere apologies for the delay in getting back to you on this @daniel-montalvo. Considering this is an extension to existing features, we don’t see any architectural issues and so we’re happy to see this move forward.

A note for future review requests - including an explainer which covers the user needs met by the feature, any tradeoffs weighed and other alternatives considered is really helpful for us in carrying out effective reviews, even for small changes.

Thanks!

**Comment by mattgarrish** [comment]
Thanks @rhiaro !
