### ISSUE TITLE
text-wrap: balance

### ISSUE THREAD

**Issue by kojiishi** [w3ctag/design-reviews#822]
Hello TAG!

I'm requesting a TAG review of the `text-wrap: balance` CSS property.

This feature adjusts line breaking to balance the length of each line box in a block, for better readability and to prevent typographic widows. This feature is often used in headlines.

There are several JavaScript libraries to achieve this effect, such as [NYTimes text balancer], [React Wrap Balancer], or [Adobe Balance Text].

[Jen's tweet](https://twitter.com/jensimmons/status/1542264788029423616) has a sample image, and it got a lot of positive responses from web developers.

[NYTimes text balancer]: https://github.com/nytimes/text-balancer
[React Wrap Balancer]: https://github.com/shuding/react-wrap-balancer
[Adobe Balance Text]: https://github.com/adobe/balance-text

  - Explainer¹ (minimally containing user needs and example code): [url](https://docs.google.com/document/d/16-T9gqCagJxcST6hcnneSb7qGunxXa37_UHYqMqhPL0/edit#)
  - Specification URL: [spec url](https://w3c.github.io/csswg-drafts/css-text-4/#valdef-text-wrap-balance)
  - Tests: [wpt folder(s), if available](https://wpt.fyi/results/css/css-text/white-space?label=master&label=experimental&aligned&view=subtest&q=text-wrap)
  - User research: [url to public summary/results of research]
  - Security and Privacy self-review²: [url]
  - GitHub repo (if you prefer feedback filed there): [url]
  - Primary contacts (and their relationship to the specification):
      - @kojiishi (Implementer), @bfgeek (Implementer), @fantasai (Spec Editor)
  - Organization(s)/project(s) driving the specification: Google
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5196960707903488

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: Implementation complete.
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): CSSWG
  - Major unresolved issues with or opposition to this specification:
  - This work is being funded by: Blink implementation is being done by Google.

  💬 leave review feedback as a **comment in this issue** and @-notify [github usernames]

**Comment by torgo** [comment]
Hi - just a quick request hopefully - we noticed that the explainer is a google doc, not in a markdown next to the spec.  There doesn't appear to be an answer to the security & privacy questionnaire. The chrome status also doesn't reflect the reality as shown by the web platform tests info. We recognise that this is already in the spec and there's significant developer support but can you please update the request info so we can progress?

**Comment by kojiishi** [comment]
Hi @torgo, thanks for the feedback. This is the first time I submit requests here, appreciate your support.

Can you tell me where the "security & privacy questionnaire"? This is a layout feature that doesn't do anytying with external servers, so I don't think it has any impacts to security & privacy, but when I wrote this based on #801 `baseline-source`, I didn't find any. The [CSS Text Level 4 spec Privacy and Security Considerations](https://w3c.github.io/csswg-drafts/css-text-4/#priv-sec) has some description:
> This specification introduces no new security considerations.
>
> This specification leaks the user’s installed hyphenation and line-breaking dictionaries.

This feature supports blocks with hyphenations and line-breaking dictionaries at the same level as this feature is off; i.e., no new leaks due to this feature. Does this answer your question?

> The chrome status also doesn't reflect the reality as shown by the web platform tests info.

Could you explain a bit more which part of "the chrome status" doesn't look reflecting the reality to you? Happy to fix errors if any.

The [wpt.fyi](https://wpt.fyi/results/css/css-text/white-space?label=experimental&label=master&aligned&view=subtest&q=text-wrap) has one failure, it's because the Chrome build on wpt.fyi hasn't incorporated the fix (it looks like the tests come to wpt before the fix) so it should be green sometime soon. Is this what you're talking about?

**Comment by LeaVerou** [comment]
Hi there, we looked at this again today and agreed this looks good to us.
