### ISSUE TITLE
Background Blur API

### ISSUE THREAD

**Issue by riju** [w3ctag/design-reviews#826]
こんにちは TAG-さん!

I'm requesting a TAG review of [Background Blur API](https://w3c.github.io/mediacapture-extensions/#exposing-mediastreamtrack-source-background-blur-support).

On the Web, due to a lack of a standardized JS API for Background Blur and widespread demand (specially on Video conferencing/ Streaming use cases), developers have no options but to use ML frameworks like Tensorflow.js and other WASM libraries to satisfy their customers. This Background Blur API gives developers a choice to use the native platform's API. 

  - Explainer : [explainer](https://github.com/riju/backgroundBlur/blob/main/explainer.md)
  - Specification URL: [spec url](https://w3c.github.io/mediacapture-extensions/#exposing-mediastreamtrack-source-background-blur-support)
  - Tests: [wpt](https://github.com/web-platform-tests/wpt/blob/master/mediacapture-extensions/GUM-backgroundBlur.https.html)
  - User research: 
  - Security and Privacy self-review: [url](https://github.com/riju/backgroundBlur/blob/main/security-privacy-self-assessment.md)
  - GitHub repo: [repo](https://github.com/riju/backgroundBlur/)
  - Primary contacts 
      - Rijubrata Bhaumik [riju](https://github.com/riju), Intel
      - François Beaufort [beaufortfrancois](https://github.com/beaufortfrancois), Google
      - Youenn Fablet [youennf](https://github.com/youennf) Apple
  - Organization(s)/project(s) driving the specification: Intel, Google, Apple. WebRTC.
  - Key pieces of existing multi-stakeholder review or discussion of this specification: [reviews](https://github.com/w3c/mediacapture-extensions/pull/61) + [WebRTC meetings minutes](https://www.w3.org/2022/05/17-webrtc-minutes.html#t07).
  - External status/issue trackers for this specification [Chrome Status](https://chromestatus.com/feature/5077577782263808)

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: planning Origin Trial (chrome) end of march.
  - The group where the work on this specification is currently being done: WebRTC
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): WebRTC
  - Major unresolved issues with or opposition to this specification: None
  
You should also know that...

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify [riju](https://github.com/riju)

**Comment by torgo** [comment]
Hi @riju we're just reviewing in today's TAG breakout. This looks very good to us, particularly the use of transformstreams and multi-stakeholder participation in this work. You've noted that there's no security & privacy section in the spec yet - it would be good to see one, even if it's minimal.

**Comment by torgo** [comment]
Hi @riju one thing that came up in today's TAG call is the use of boolean instead of something more expressive such as percentage?  Just taking a look at Whereby which we are running our TAG call in they already offer 2 blur modes - light and strong - so in this case it seems this API wouldn't be sufficient. We see in the explainer you're already considering something more extensible. We're worried about introducing an API that you'd have to change very soon. Is the group considering something more sophisticated than boolean? Thanks! ✨

**Comment by riju** [comment]
@torgo : Absolutely. This is one of the [goals of Origin Trial ](https://groups.google.com/a/chromium.org/g/blink-dev/c/Jr9vE8mSS-8/m/_Pv0vcDhBwAJ) 
_We can learn if the API in its present form satisfies the needs of the users, or do we need something more to wow the users. One concrete example would be boolean vs enumeration. Right now, BG Blur only uses a bool which is an ON/OFF switch, but ChromeOS (5 blur levels) and Windows 11 (2 blur levels) offer more. We wanted to start off with something simple, get feedback and iterate on building something which the majority wants._

**Comment by torgo** [comment]
Hi @riju - Ok understood. As documented above, we already see examples in the market where a boolean would not be sufficient. Please note: the Whereby.com service I mentioned above is the one we're currently using for TAG calls. So just to be clear: our feedback is that the API looks good except for this issue. We strongly recommend you move to something more expressive than Boolean. Thanks!

**Comment by riju** [comment]
> Awesome API! But I have some doubts. I've tried it with various cameras (both new and old) and it only seems to work if the camera has a background blur feature?
> 
> I've been testing with this example: https://googlechrome.github.io/samples/image-capture/background-blur.html
> 
> We currently have many companies using virtual/blur backgrounds on the web, but the performance is pretty subpar, it even creates bottlenecks in the main thread, breaking other things, so having a native implementation would be fantastic!

Hi @matiaslopezd , good to hear that. Yes, on Windows it works only with support for Windows Studio effects. On Mac, any M series will work and on ChromeOS, there's a list of relatively newer client devices, but the list is increasing.

Please join the [Origin Trial ](https://developer.chrome.com/origintrials/#/view_trial/2228155915641552897) and give us feedback.
