### ISSUE TITLE
Web Bluetooth exclusionFilters option in requestDevice()

### ISSUE THREAD

**Issue by beaufortfrancois** [w3ctag/design-reviews#830]
こんにちは TAG-さん!

I'm requesting a TAG review of Web Bluetooth exclusionFilters option in requestDevice()

The "exclusionFilters" option in navigator.bluetooth.requestDevice() allows web developers to exclude some devices from the browser picker. It can be used to exclude devices that match a broader filter but are unsupported.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/WebBluetoothCG/web-bluetooth/issues/599#issue-1638254435
  - Specification URL: https://webbluetoothcg.github.io/web-bluetooth/#ref-for-dom-requestdeviceoptions-exclusionfilters
  - Tests: N/A
  - User research: N/A
  - Security and Privacy self-review²: N/A
  - Primary contacts (and their relationship to the specification):
      - Francois Beaufort (@beaufortfrancois), Google.
      - Reilly Grant (@reillyeon), Google.
  - Organization(s)/project(s) driving the specification: [organization and/or project name]
  - Key pieces of existing multi-stakeholder review or discussion of this specification: N/A
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):
    - https://groups.google.com/a/chromium.org/g/blink-dev/c/MukeIcVHBas
    - https://chromestatus.com/feature/6208474255458304
    
Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: None
  - The group where the work on this specification is currently being done: Web Bluetooth Community Group
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): N/A
  - Major unresolved issues with or opposition to this specification: N/A
  - This work is being funded by: Google

You should also know that this issue is an FYI as we value TAG folks's time.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @beaufortfrancois

**Comment by plinss** [comment]
@maxpassion and I looked at this during our Tokyo F2F and don't see any issues. We're closing this as satisfied. Thanks for flying TAG.

For future reviews please prepare a proper [explainer](https://tag.w3.org/explainers/), digging through issues and PRs isn't the best way to review things.
