### ISSUE TITLE
[FYI] Report Critical-CH caused restart in NavigationTiming

### ISSUE THREAD

**Issue by arichiv** [w3ctag/design-reviews#833]
こんにちは TAG-さん!

I wanted to give TAG a heads up about "Report Critical-CH caused restart in NavigationTiming".

Websites can indicate that a particular [Client Hint](https://wicg.github.io/client-hints-infrastructure/) is critical to the page by including it in a Critical-CH HTTP response header. Doing so will trigger a connection restart if the hint listed in the Critical-CH HTTP response header could be (but wasn’t) included in the HTTP request initially sent. We should indicate this has happened in [Navigation Timing](https://github.com/w3c/navigation-timing) so that developers can know if a restart occurred and impacted timing.

  - Explainer: [[url]](https://groups.google.com/a/chromium.org/g/blink-dev/c/f28WWMD8HVE)
  - GitHub repo (if you prefer feedback filed there): [[url]](https://github.com/w3c/navigation-timing/pull/188)
  - Primary contacts (and their relationship to the specification):
      - [Ari Chivukula](@arichiv), Google
  - Organization/project driving the design: Chromium
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): https://crbug.com/1425910

**Comment by slightlyoff** [comment]
An FYI for the TAG that this feature has an I2S out and was filed late. Any quick feedback would be helpful.

**Comment by cynthia** [comment]
Discussed in breakout today, LGTM (meaning the folks in the call today).
