### ISSUE TITLE
Detect UA Transitions on Same-Document Navigations

### ISSUE THREAD

**Issue by khushalsagar** [w3ctag/design-reviews#834]
I'm requesting a TAG review for an API to detect UA defined visual transitions on same-document navigations.

Smooth visual transitions as users navigate on the web can lower cognitive load by helping users stay in context. It can also provide a [visual cue](https://www.wired.com/2014/04/swipe-safari-ios-7/) about the destination before initiating the navigation. Both site authors and user-agents (UAs) add visual transitions to their navigations for these use-cases.

However, the user experience is bad if [both the site author and the UA](https://stackoverflow.com/questions/19662434/in-ios-7-safari-how-do-you-differentiate-popstate-events-via-edge-swipe-vs-the) add these transitions: the transitions may conflict and cause confusion for the user. The goal of this proposal is to avoid such cases to ensure only one visual transition is executed at a time.

  - Explainer¹ (minimally containing user needs and example code): [Explainer](https://github.com/WICG/view-transitions/blob/main/default-ua-transitions.md). This review is for the API specified [here](https://github.com/WICG/view-transitions/blob/main/default-ua-transitions.md#detecting-ua-transition).
  
  - User research: [url to public summary/results of research]
  - Security and Privacy self-review²: None. The API is limited to same-document navigations.
  - GitHub repo (if you prefer feedback filed there): None. I'd appreciate feedback in comments on this review.
  - Primary contacts (and their relationship to the specification):
      - [Khushal](https://github.com/khushalsagar), Google
      - [William](https://github.com/liuwilliam-gh), Google
  - Organization/project driving the design: Google
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5204831477694464

Further details:

  - [X] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): WICG
  - The group where standardization of this work is intended to be done ("unknown" if not known): HTML
  - Existing major pieces of multi-stakeholder review or discussion of this design:
  - Major unresolved issues with or opposition to this design:
  - This work is being funded by:

The html issue for discussing this proposal is [here](https://github.com/whatwg/html/issues/8782).

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify [khushalsagar](https://github.com/khushalsagar).

**Comment by hober** [comment]
This seems pretty reasonable to me. I don't think there's any fingerprinting concern here, given that you don't learn anything that you don't already know via the User-Agent string.
