### ISSUE TITLE
VC JSON Schema

### ISSUE THREAD

**Issue by decentralgabe** [w3ctag/design-reviews#859]
As an editor of the specification, I'm requesting a TAG review of VC JSON Schema:

Verifiable Credentials (VCs) provide a JSON-LD data model that enables the issuance, sharing, and verification of digital credentials in a secure and interoperable manner. These credentials provide a way for individuals, organizations, and other entities to digitally represent and share their qualifications, attributes, and/or other relevant information. Verifiable Credentials are designed to enhance trust, privacy, and control in digital interactions by allowing the owner of the credentials to control how their information is shared and verified. By adding data schemas to VCs we enable a consistent data shape for credential data, promoting reusability and allowing for static validation of credential data.

  - Explainer: [vc-json-schema-explainer](https://github.com/w3c/vc-json-schema/blob/main/EXPLAINER.md)
  - Specification URL: [VC JSON Schema - Latest Draft](https://w3c.github.io/vc-json-schema)
  - Tests: tests are under development
  - User research: n/a
  - Security and Privacy self-review: [Security/Privacy](https://github.com/w3c/vc-json-schema/issues/167)
  - GitHub repo (if you prefer feedback filed there): [VC JSON Schema Repo](https://github.com/w3c/vc-json-schema)
  - Primary contacts (and their relationship to the specification):
      - Brent Zundel (@brentzundel), VCWG Chair, Gen
      - Kristina Yasuda (@Sakurann), VCWG Chair, Microsoft
      - Gabe Cohen (@decentralgabe), Editor, Block/TBD
      - Orie Steele (@OR13), Editor, Transmute
      - Andres Uribe (@andresuribe87), Editor, Block/TBD
  - Organization(s)/project(s) driving the specification: [W3C Verifiable Credentials Working Group](https://www.w3.org/2017/vc/WG/)
  - Key pieces of existing multi-stakeholder review or discussion of this specification: n/a
  - External status/issue trackers for this specification: [Issue Tracker](https://github.com/w3c/vc-json-schema/issues)

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: The VCWG is planning to take this specification to Candidate Recommendation in September 2023 (at W3C TPAC), reviews before that time frame (ideally, by the end of July 2023) would be ideal.
  - The group where the work on this specification is currently being done: [W3C Verifiable Credentials Working Group](https://www.w3.org/2017/vc/WG/)
  - Major unresolved issues with or opposition to this specification: 
    -  There is some consideration over whether JSON Schema can be normatively referenced since it has been independently developed via [json-schema.org](https://json-schema.org/) and now resides within the [OpenJS Foundation](https://openjsf.org/)
  - This work is being funded by: The members of the W3C VCWG that are actively participating in the development of these specifications including funding from the US Federal Government, the European Commission, and the Canadian Federal Government.

You should also know that...
* This work intersects heavily with the [Verifiable Credentials v2.0](https://www.w3.org/TR/vc-data-model-2.0/) work, which is also something that the TAG will be actively reviewing around the same time.

**Comment by rhiaro** [comment]
Sorry for the delay on getting back to you on this. We have no architectural concerns with the JSON Schema.

**Comment by jyasskin** [comment]
I want to double-check on how the lack of architectural concerns here matches up with @hober's architectural concerrns about polyglot formats in https://github.com/w3ctag/design-principles/issues/239 and https://tess.oconnor.cx/2023/09/polyglots-and-interoperability. This use of JSON Schema to validate JSON-LD (RDF) data seems like it endorses a polyglot format.

**Comment by rhiaro** [comment]
@jyasskin we expect to address that more broadly as part of the VC data model 2.0 review, asap.
