### ISSUE TITLE
TAG spec review of Bounce Tracking Mitigations

### ISSUE THREAD

**Issue by amaliev** [w3ctag/design-reviews#862]
こんにちは TAG-さん!

I'm requesting a TAG review of Bounce Tracking Mitigations.

With browser vendors now actively working to remove third-party cookies from the web, some platform trackers are moving to bounce tracking. This technique involves navigating to a tracker domain at the top level of a browser tab, setting or reading a first-party cookie, and then quickly redirecting away using a request that encodes the value of that first-party cookie. Sometimes the redirect is back to the original page and sometimes to a new site. In either case, bounce tracking semantically functions like setting a third-party cookie. This explainer outlines a proposal for mitigating the privacy impact of bounce trackers.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/privacycg/nav-tracking-mitigations/blob/main/bounce-tracking-explainer.md
  - Specification URL: https://privacycg.github.io/nav-tracking-mitigations/
  - Tests: None. (Our algorithm runs on a long timer, and there is no support for moving the clock forward in WPT tests.)
  - User research: N/A (some additional background in Google-internal [doc](https://docs.google.com/document/d/16Il2-9Ou_WInXu__CiWNzTBkKreCQwEFw9-k3seeGGI/edit?usp=sharing))
  - Security and Privacy self-review²: https://github.com/privacycg/nav-tracking-mitigations/blob/main/tag-privacy-security.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/privacycg/nav-tracking-mitigations
  - Primary contacts (and their relationship to the specification):
      - [Jeffrey Yasskin] (jyasskin, Google): Primary spec author and reviewer
      - [Ben Kelly] (wanderview, Google): Primary spec author
      - [Anton Maliev] (amaliev, Google): Spec contributor
  - Organization(s)/project(s) driving the specification: Google, Privacy Sandbox
  - Key pieces of existing multi-stakeholder review or discussion of this specification: N/A
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): N/A

Further details:

  - [X] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: Q3 2023
  - The group where the work on this specification is currently being done: PrivacyCG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): N/A
  - Major unresolved issues with or opposition to this specification: N/A
  - This work is being funded by: Google

You should also know that...

N/A

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by rhiaro** [comment]
Hi @wanderview @amaliev @jyasskin. We (@torgo @hadleybeeman @maxpassion and I) reviewed this in our virtual face-to-face this week. We're really happy to see this being worked on! The design looks good and well aligned with the [privacy principles](https://www.w3.org/TR/privacy-principles/). 

What feedback have you had from other browsers in the PrivacyCG? It's great to see that you feel the proposal is aligned with what other implementers have done, and we would be even happier to see other implementers collaborating with you on documenting this behaviour – which would give clear guidance to web developers. ✨

We're looking forward to hearing more about your progress going forward. What are your thoughts about your next steps?

**Comment by wanderview** [comment]
Thank you!

We agree that browser interop on this feature would be great and we intend to keep working on alignment with other vendors.  Next steps for us:

1. Launch our MVP and get experience in production.  We hope this will provide evidence it's safe for other browsers to move beyond list-based approaches.
2. Run additional experiments to close the gap between chrome's coverage and the coverage achieved by other browsers.  (For example, triggering on [http cache state](https://github.com/privacycg/nav-tracking-mitigations/issues/41))

The coming TPAC will be a good opportunity to discuss with other browser vendors.

**Comment by wanderview** [comment]
> What feedback have you had from other browsers in the PrivacyCG?

Sorry, missed answering this.

We have official requests for feedback from other browser vendors here:

https://github.com/mozilla/standards-positions/issues/835
https://github.com/WebKit/standards-positions/issues/214

I don't want to speak for them, but I will say personally I think our interactions in privacycg on this feature have been positive.

**Comment by hadleybeeman** [comment]
Hi @wanderview @amaliev @jyasskin. We are looking at this again in our W3C TAG breakout session.

We are going to close this. We like the direction and design of this feature, but we note how early it is and are glad you're collaborating with other stakeholders — though we would like to see full consensus (which we understand comes later than positive interactions).

We hope you continue to work on getting that consensus. Please do open a new review when the design (and consensus) is a bit more mature.
