### ISSUE TITLE
ServiceWorker static routing API

### ISSUE THREAD

**Issue by yoshisatoyanagisawa** [w3ctag/design-reviews#863]
こんにちは TAG-さん!

I'm requesting a TAG review of ServiceWorker static routing API.

This API allows developers to configure the routing, and allows them to offload simple things ServiceWorkers do. If the condition matches, the navigation happens without starting ServiceWorkers or executing JavaScript, which allows web pages to avoid performance penalties due to ServiceWorker interceptions.

  - Explainer¹ (minimally containing user needs and example code): [url](https://github.com/yoshisatoyanagisawa/service-worker-static-routing-api)
  - User research: it is a well-studied phenomenon that faster sites are better for users, but we have not conducted any user studies specifically on this feature.
  - Security and Privacy self-review²: [url](https://github.com/yoshisatoyanagisawa/service-worker-static-routing-api/blob/main/security-privacy-questionnaire.md)
  - GitHub repo (if you prefer feedback filed there): [url](https://github.com/yoshisatoyanagisawa/service-worker-static-routing-api) ([proposed](https://github.com/WICG/proposals/issues/102) to move to WICG)
  - Primary contacts (and their relationship to the specification):
      - Yoshisato Yanagisawa (@yoshisatoyanagisawa), Google
      - Shunya Shishido (@sisidovski), Google
  - Organization/project driving the design: Google Chrome
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status):
      - [ChromeStatus](https://chromestatus.com/feature/5185352976826368)
      - [Mozilla standards position](https://github.com/mozilla/standards-positions/issues/828)
      - [WebKit standards position](https://github.com/WebKit/standards-positions/issues/206)

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): W3C Service Workers Working Group
  - The group where standardization of this work is intended to be done ("unknown" if not known): W3C Service Workers Working Group
  - Existing major pieces of multi-stakeholder review or discussion of this design: https://github.com/w3c/ServiceWorker/issues/1373
  - Major unresolved issues with or opposition to this design: Maybe no as far as I took a glance at https://github.com/w3c/ServiceWorker/issues/1373
  - This work is being funded by: Google

You should also know that...

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by maxpassion** [comment]
Hi @yoshisatoyanagisawa, We had a discussion in our breakout C meeting this week. One concern is that this proposal uses URLPattern but URLPattern has not been standardized. Is there any update on this?

**Comment by yoshisatoyanagisawa** [comment]
Thank you for reviewing our proposal.
@domenic @wanderview Do you know the current URLPattern status?

**Comment by domenic** [comment]
URLPattern is fully specified. It's true that it hasn't moved to a standards organization, but that's due to other browsers choosing not to implement, which isn't something we can speak to; you'd have to ask representatives of other browsers about their plans in that area.

**Comment by torgo** [comment]
Hi @domenic - thanks for that clarification.  As with a number of other current reviews, in that case, I'd like to express concerns that we are building new capabilities on top of shaky ground – that is, existing specifications that do not have consensus and do not have multiple implementations across multiple browsers.
  
Further to that, we have another open review, [Compression Dictionary Transport
](https://github.com/w3ctag/design-reviews/issues/877) which also makes use of "URL Patterns" but [does not appear](https://github.com/WICG/compression-dictionary-transport/blob/main/README.md#dictionary-options-header) to reference the URLPattern spec.
  
Could there be an option here to work together to specify static routing without relying on URLPattern, or to specify a fall-back?

Alternatively, [is there a way forward](https://github.com/WebKit/standards-positions/issues/61#issuecomment-1527486428) to bring URLPattern forward for standardization that could unblock multiple implementations?

**Comment by domenic** [comment]
> Could there be an option here to work together to specify static routing without relying on URLPattern, or to specify a fall-back?

I don't think it's a good idea to invent a second URL pattern syntax for routing on the web platform, and you need some sort of syntax for specifying URL patterns if you're to statically give a pattern for which URLs are statically routed...

> Alternatively, [is there a way forward](https://github.com/WebKit/standards-positions/issues/61#issuecomment-1527486428) to bring URLPattern forward for standardization that could unblock multiple implementations?

Again, I think there's nothing blocking this besides the other implementations' interest. Chrome has done everything we can by laying out a full specification, web platform tests suite, and so on. The "way forward" is for another implementation to support standardization, and that's not something the Chrome team has control over. I'd really encourage the TAG to bring these concerns up with the other engines directly, instead of the current approach (which I see across multiple reviews) of asking Chrome team members for information on the future plans of other companies.

**Comment by torgo** [comment]
> I'd really encourage the TAG to bring these concerns up with the other engines directly, instead of the current approach (which I see across multiple reviews) of asking Chrome team members for information on the future plans of other companies.

@domenic I think you know it's not the TAG's job to sell Google's vision of the web to other browser makers. Having said that, we are trying to drive cross-platform consensus around topics such as Powerful APIs and Web Privacy - I suggest you attend those sessions at this week's TPAC plenary to learn more.

**Comment by torgo** [comment]
We're going to go ahead and close this with "satisfied with concerns" - we're happy with the overall design but we remain concerned about URLPattern's status on the standards track.  Considering there seems to be a [way forward for standardization](https://github.com/WebKit/standards-positions/issues/61#issuecomment-1527486428), we'd encourage you to pursue that path.

**Comment by chrishtr** [comment]
> Considering there seems to be a [way forward for standardization](https://github.com/WebKit/standards-positions/issues/61#issuecomment-1527486428), we'd encourage you to pursue that path.

FYI the URL Pattern spec is [now at the WHATWG](https://urlpattern.spec.whatwg.org/) and [Webkit is positive on this proposal](https://github.com/WebKit/standards-positions/issues/61#issuecomment-1767882081).
