### ISSUE TITLE
navigateEvent.sourceElement

### ISSUE THREAD

**Issue by natechapin** [w3ctag/design-reviews#867]
こんにちは TAG-さん!

I'm requesting a TAG review of navigateEvent.sourceElement.

This is a small extension of the [navigation API](https://github.com/WICG/navigation-api), which was previously reviewed in https://github.com/w3ctag/design-reviews/issues/605 and https://github.com/w3ctag/design-reviews/issues/717. The navigateEvent exposes many details about a navigation that has just begun, and we wish to add a `sourceElement` attribute: the `Element` that initiated the navigation (if any).

  - Explainer¹ (minimally containing user needs and example code): https://github.com/WICG/navigation-api/pull/264
  - User research: Requested and discussed on our issue tracker: https://github.com/WICG/navigation-api/issues/225
  - Security and Privacy self-review²: None - this shouldn't expose anything that isn't already available
  - GitHub repo (if you prefer feedback filed there): https://github.com/WICG/navigation-api/
  - Primary contacts (and their relationship to the specification):
      -  Nate Chapin (@natechapin), Google
      -  Domenic Denicola (@domenic), Google
  - Organization/project driving the design: Google
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): None yet.

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): WICG
  - The group where standardization of this work is intended to be done ("unknown" if not known): WHATWG
  - Existing major pieces of multi-stakeholder review or discussion of this design: https://github.com/WICG/navigation-api/issues/225
  - Major unresolved issues with or opposition to this design: None yet. The main point of debate has been the name. I am happy to consider alternatives to `sourceElement`.
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify [@natechapin, @domenic]

**Comment by letitz** [comment]
Hi there @natechapin, @domenic, a quick request for clarification:

> * Security and Privacy self-review²: None - this shouldn't expose anything that isn't already available

This is because the navigation events are always from same-origin sources, so the website could have tracked the source element itself if it so desired?

**Comment by natechapin** [comment]
> Hi there @natechapin, @domenic, a quick request for clarification:
> 
> > * Security and Privacy self-review²: None - this shouldn't expose anything that isn't already available
> 
> This is because the navigation events are always from same-origin sources, so the website could have tracked the source element itself if it so desired?

Correct!

**Comment by domenic** [comment]
What is wrong with the explainer linked in the OP? (Notice this is a single added property in a larger spec, so it's being done as an update to that spec's explainer.)

**Comment by LeaVerou** [comment]
> What is wrong with the explainer linked in the OP? (Notice this is a single added property in a larger spec, so it's being done as an update to that spec's explainer.)

You mean [this](https://github.com/WICG/navigation-api/pull/264/files)? It’s missing nearly all the sections an explainer needs, described [here](https://tag.w3.org/explainers/). If it's too small a feature to need an explainer, it may be too small to need TAG review.

**Comment by domenic** [comment]
That explainer (full version at https://github.com/WICG/navigation-api/blob/b0286752a0a5a1babd782e4bc8e68e696538fd10/README.md) does have all the sections. It's true this addition is a small part of the overall navigation API. Perhaps it is too small to need TAG review; if that's the TAG's judgment, then please feel free to close :).

**Comment by torgo** [comment]
As agreed on today's call. We agree it's too small to require a TAG review so we're going to close.
