### ISSUE TITLE
The `FileSystemObserver` interface

### ISSUE THREAD

**Issue by a-sully** [w3ctag/design-reviews#868]
こんにちは TAG-さん!

I'm requesting a TAG review of the `FileSystemObserver` interface for the [File System specification](https://fs.spec.whatwg.org/).

This proposal introduces a `FileSystemObserver` interface which will much more easily allow a website to be notified of changes to the file system.

The file system is a shared resource that can be modified from several contexts. A [Bucket File System](https://fs.spec.whatwg.org/#sandboxed-filesystem) (a.k.a. an [Origin Private File System](https://github.com/whatwg/fs/commit/69c51d387cc94e86c8a26acbc0051d7c2a560cfd), or OPFS) spans numerous [agents](https://tc39.es/ecma262/#sec-agents) - tabs, workers, etc - within the same [storage key](https://storage.spec.whatwg.org/#storage-keys). The local file system also spans across origins and other applications on the host operating system.

Currently, for a given agent to know about modifications to the file system - made either by itself or from some external context - it must poll the file system to detect changes. This is inefficient and does not scale well.

  - Explainer: https://github.com/whatwg/fs/blob/main/proposals/FileSystemObserver.md 
  - Security and Privacy self-review: No changes to [the existing review](https://github.com/WICG/file-system-access/blob/main/security-privacy-questionnaire.md), though that review [needs to be updated](https://github.com/WICG/file-system-access/issues/421) to consider interaction with pages which are not [fully active](https://html.spec.whatwg.org/multipage/document-sequences.html#fully-active). In the meantime, this feature’s interaction with non-fully-active pages is discussed [here](https://github.com/whatwg/fs/blob/main/proposals/FileSystemObserver.md#handling-changes-made-outside-the-lifetime-of-a-filesystemobserver). See also the [Permissions Considerations](https://github.com/whatwg/fs/blob/main/proposals/FileSystemObserver.md#permission-considerations) and [Fingerprinting Risk](https://github.com/whatwg/fs/blob/main/proposals/FileSystemObserver.md#fingerprinting-risk) sections of the explainer
  - GitHub repo: [whatwg/fs](https://github.com/whatwg/fs/)
  - Primary contacts (and their relationship to the specification):
      - Austin Sullivan (@a-sully), Google Chrome
  - Organization/project driving the design: Google/Chromium
  - External status/issue trackers for this feature: https://chromestatus.com/feature/4622243656630272

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the incubation/design work on this is being done: [whatwg/fs](https://github.com/whatwg/fs/) and [WICG/file-system-access](https://github.com/WICG/file-system-access)
  - The group where standardization of this work is intended to be done: [whatwg/fs](https://github.com/whatwg/fs/)
  - Existing major pieces of multi-stakeholder review or discussion of this design: Developers have enumerated several use cases, discussed various designs, and provided example code for how file paths can be watched with the existing APIs in https://github.com/WICG/file-system-access/issues/72. No discussion with other stakeholders yet
  - Major unresolved issues with or opposition to this design:
  - This work is being funded by: Google

You should also know that...

The proposed interface can be used to observe both files on the user's local device (as specified in [WICG/file-system-access](https://github.com/wicg/file-system-access/)) and files in the Bucket File System (as specified in [whatwg/fs](https://github.com/whatwg/fs/)).

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by torgo** [comment]
Hi @a-sully this unfortunately seems to have dropped off our radar and we did not get to it in a timely fashion. My apologies. Can you update us on the latest status of this proposal? Also it would be good to understand the multi-stakeholder situation - especially any support from other browsers. That will help us get you an answer quickly.

**Comment by a-sully** [comment]
> Hi @a-sully this unfortunately seems to have dropped off our radar and we did not get to it in a timely fashion. My apologies. Can you update us on the latest status of this proposal? 

Sure thing! This feature is currently being prototyped in Chromium. It's a very highly requested feature from developers that we're hoping to get into their hands sometime early next year

> Also it would be good to understand the multi-stakeholder situation - especially any support from other browsers. That will help us get you an answer quickly.

___My___ apologies for forgetting to file the standards position issues months ago. I have discussed this idea in the abstract with some folks from other browsers in the past, though I believe that was before a concrete proposal was made. I've now filed https://github.com/mozilla/standards-positions/issues/942 and https://github.com/WebKit/standards-positions/issues/291 to solicit their input :)

**Comment by cynthia** [comment]
We reviewed this during our F2F, and the feature looks great! Thanks for bringing this to our attention.

If there are any negative signals from other implementors that may require a significant change, please let us know and we can reopen for further discussion.

**Comment by dslee414** [comment]
Hi, I would like to note that the spec PR is in progress: https://github.com/whatwg/fs/pull/165

It does not differ much from the original design proposed here, with some minor changes such as `FileSystemChangeType` names.
