### ISSUE TITLE
Portable Network Graphics (PNG), Third Edition.

### ISSUE THREAD

**Issue by svgeesus** [w3ctag/design-reviews#873]
こんにちは TAG-さん!

I'm requesting a TAG review of  **Portable Network Graphics (PNG), Third Edition.**

The Third Edition adds widely-requested features and folds in errata reported since the Second Edition.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/w3c/PNG-spec/blob/main/Third_Edition_Explainer.md
  - Specification URL: https://www.w3.org/TR/2023/WD-png-3-20230720/
  - Tests: [wpt folder(s), if available] https://wpt.fyi/results/png in progress
  - User research: [url to public summary/results of research] see explainer
  - Security and Privacy self-review²:  https://github.com/w3c/PNG-spec/issues/228#issuecomment-1279390248
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/PNG-spec
  - Primary contacts (and their relationship to the specification):
      - Chris Lilley, @svgeesus W3C, Staff contact, Editor
      - Chris Blume, @programmax W3C Invited Experts, Chair, Editor
  - Organization(s)/project(s) driving the specification: W3C
  - Key pieces of existing multi-stakeholder review or discussion of this specification: 
    - https://github.com/w3c/PNG-spec/blob/main/Third_Edition_Explainer.md#stakeholder-feedback--opposition
    - https://www.w3.org/Graphics/Color/Workshop/report.html#imgformats
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):
    - https://groups.google.com/a/chromium.org/g/chromium-reviews/c/Un4cX9rD9TI

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: _none_
  - The group where the work on this specification is currently being done: PNG WG
  - Major unresolved issues with or opposition to this specification: https://github.com/w3c/PNG-spec/issues
  - This work is being funded by: W3C

You should also know that...

 We have a hard constraint with web-compat and are unable (by charter) to make changes such as better compression which would invalidate existing content or existing viewers.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by atanassov** [comment]
We really like the proposed changes and overall direction of the spec. The details are somewhat out of our technical depth but we trust you and the WG to have captured the current state of implementations. Having spec text for APNG is particularly great to see. Thanks for you working with us and we're excited to see how the spec matures. Thanks for flying TAG!
