### ISSUE TITLE
content-visibility: auto forces contain-intrinsic-size: auto

### ISSUE THREAD

**Issue by vmpstr** [w3ctag/design-reviews#876]
こんにちは TAG-さん!

I'm requesting a TAG review of "content-visibility: auto forces contain-intrinsic-size: auto".

This is a resolution recorded in CSSWG: https://github.com/w3c/csswg-drafts/issues/8407#issuecomment-1440466558. The summary is that because it's possible to produce unstable layouts, it is better to have content-visibility: auto force contain-intrinsic-size to gain the auto keyword. This means that after the content-visibility: auto has been "relevant to the user", it remembers its rendered size as the last remembered size and uses it in place of the specified size when content-visibility: auto element is no longer "relevant to the user"

  - Explainer¹ (minimally containing user needs and example code): The github issue prompting the resolution is a good example of the problem this seeks to address https://github.com/w3c/csswg-drafts/issues/8407
  - Specification URL: [css-contain-2](https://drafts.csswg.org/css-contain-2/) and [css-sizing-4](https://drafts.csswg.org/css-sizing-4)
  - Tests: [[wpt folder(s), if available]](https://wpt.fyi/results/css/css-contain/content-visibility)
  - User research: N/A
  - Security and Privacy self-review²: N/A -- this feature is limited to CSS and interaction between two properties, it doesn't introduce any extra security or privacy considerations.
  - GitHub repo (if you prefer feedback filed there): [[url]](https://github.com/w3c/csswg-drafts/issues)
  - Primary contacts (and their relationship to the specification):
      - @vmpstr (Google, Inc)
  - Organization(s)/project(s) driving the specification: CSSWG
  - Key pieces of existing multi-stakeholder review or discussion of this specification: N/A
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5111301323358208

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: N/A
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): CSSWG
  - Major unresolved issues with or opposition to this specification: None
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by torgo** [comment]
Thanks for this. Just noting that this needs to go through full process in the CSS working group. Please make sure the CSS working group is OK with shipping this. We don't see any architectural issues. ✨
