### ISSUE TITLE
`inverted-colors` CSS Media Query

### ISSUE THREAD

**Issue by lukewarlow** [w3ctag/design-reviews#883]
こんにちは TAG-さん!

I'm requesting a TAG review of `inverted-colors`.

The `inverted-colors` media feature indicates whether the content is displayed normally, or whether colors have been inverted.

  - Explainer¹ (minimally containing user needs and example code): https://developer.mozilla.org/en-US/docs/Web/CSS/@media/inverted-colors
  - Specification URL: https://drafts.csswg.org/mediaqueries-5/#inverted
  - Tests: https://github.com/web-platform-tests/wpt/blob/master/css/mediaqueries/inverted-colors.html
  - User research: [url to public summary/results of research]
  - Security and Privacy self-review²: https://gist.github.com/lukewarlow/ef98913a5272124e3850f2c36245178d
  - GitHub repo (if you prefer feedback filed there): n/A
  - Primary contacts (and their relationship to the specification):
      - Dean Jackson, Apple
      - [Florian Rivoal](https://github.com/frivoal), Invited Expert
      - [Tab Atkins Jr](https://github.com/tabatkins), Google
      - Daniel Libby, Microsoft
  - Organization(s)/project(s) driving the specification: [organization and/or project name]
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
    - [CSSWG GitHub Issue](https://github.com/w3c/csswg-drafts/issues/732) - this also shows Safari has supported this media query for a while
    - [Intent to prototype Firefox](https://groups.google.com/a/mozilla.org/g/dev-platform/c/knC9tMRu_cw/m/lTUKB69TBwAJ)
    - [Intent to prototype Chromium](https://groups.google.com/a/chromium.org/g/blink-dev/c/0ugmlt_SLIw/m/aCm6qYPbAAAJ)
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):
    - https://chromestatus.com/feature/5940010603773952

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: n/a
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): CSSWG
  - Major unresolved issues with or opposition to this specification: adds a fingerprinting vector
  - This work is being funded by:
  
We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @lukewarlow

**Comment by atanassov** [comment]
We're happy to see this moving forward, thus we are closing it. One small feedback for future reviews is to please try and use the explainer template as it helps us get a much broader perspective. Thank you for flying TAG!
