### ISSUE TITLE
CSS State Container Queries

### ISSUE THREAD

**Issue by lilles** [w3ctag/design-reviews#885]
こんにちは TAG-さん!

I'm requesting a TAG review of CSS State Container Queries.

Level 3 of CSS Containment introduces Container Queries for querying size and style of containers to style their descendants depending on layout and computed styles respectively. There are requests to allow to query other states associated with a container, in particular various scroll based states.

  - Explainer¹ (minimally containing user needs and example code): [url](https://lilles.github.io/explainers/state_container_queries.html)
  - Primary contacts (and their relationship to the specification):
      - @lilles (Google, Implementer)
      - @tabatkins (Google, Editor)
      - @frivoal (On behalf of Bloomberg, Editor)
      - @mirisuzanne (Invited Expert, Editor)
  - Organization/project driving the design: Google
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status):
      - [CSS Sticky State Container Queries](https://chromestatus.com/feature/5072263730167808)

Further details:

  - [X] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): CSSWG
  - The group where standardization of this work is intended to be done ("unknown" if not known): CSSWG
  - Major unresolved issues with or opposition to this design:
    - Should containment be enforced for the new container-types, and if so which (size, layout, paint, style)?
    - Are container queries a better choice than pseudo classes?
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @lilles

**Comment by LeaVerou** [comment]
We looked at this during a breakout today. Great explainer, thank you!
We think the feature covers a lot of very prominent author use cases, and the container query design circumvents a lot of the issues with past proposals.
What is the status of multi-stakeholder support? Going forwards, it may help to request standards positions from Gecko and WebKit to see if they’re also on board.

**Comment by lilles** [comment]
>  What is the status of multi-stakeholder support? Going forwards, it may help to request standards positions from Gecko and WebKit to see if they’re also on board.

The standards positions were previously filed, but no response yet:

https://github.com/mozilla/standards-positions/issues/896
https://github.com/WebKit/standards-positions/issues/261

I have Agenda+'ed the [CSSWG issue](https://github.com/w3c/csswg-drafts/issues/6402#issuecomment-1788747734) to get a resolution to start working on the spec.
