### ISSUE TITLE
`field-sizing` CSS property

### ISSUE THREAD

**Issue by tkent-google** [w3ctag/design-reviews#890]
こんにちは TAG-さん!

I'm requesting a TAG review of `field-sizing` CSS property.

`field-sizing` CSS property allows web authors to disable a historical special sizing behavior of HTML form controls. Web authors will be able to make form control sizes automatically-growable depending on their contents.

  - Explainer¹ (minimally containing user needs and example code): [form-sizing.md](https://github.com/tkent-google/explainers/blob/main/form-sizing.md)
  - Specification URL: https://github.com/w3c/csswg-drafts/pull/9251 
  - Tests: https://wpt.fyi/results/css/css-ui/parsing https://wpt.fyi/results/html/rendering/widgets
  - User research: N/A
  - Security and Privacy self-review²: https://drafts.csswg.org/css-ui-4/#security-privacy-considerations
  - GitHub repo (if you prefer feedback filed there): N/A
  - Primary contacts (and their relationship to the specification):
      - [Kent Tamura](@tkent-google), Google
      - [Ian Kilpatrick](@bfgeek), Google
      - [Florian Rivoal](@frivoal), Bloomberg, the specification editor
  - Organization(s)/project(s) driving the specification: Google
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
      - See https://github.com/w3c/csswg-drafts/issues/7542 . This was discussed in CSSWG meetings multiple times.
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5176596826161152

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: N/A
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): CSSWG
  - Major unresolved issues with or opposition to this specification: Value keywords are not fixed yet.
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as:
  💬 leave review feedback as a **comment in this issue** and @-notify [@tkent-google]

**Comment by torgo** [comment]
@tkent-google we're going to have a look at this - but do you consider this an early review? It looks to us like this is still being discussed and worked on by the working group so it wouldn't be appropriate as a later stage review. Hoping you can clarify.

**Comment by tkent-google** [comment]
> do you consider this an early review?

I intended this was a specification review, not an early review.
When I submitted this review request, we already had a CSSWG resolution, and the discussion was not active.
The discussion got active after the request, then it got calm again after two CSSWG resolutions.

**Comment by rhiaro** [comment]
We're really happy to see this important use case being addressed. 

We have concerns about the design, and the additional complexity this brings to the mental model for sizing in CSS, but we understand that alternatives have been explored extensively by the WG. Can you please add alternatives considered, and reasons why those designs weren't chosen, to the explainer, so we have this on record for the future?
  
Thanks!

**Comment by tkent-google** [comment]
Thank you for the suggestion.

> Can you please add alternatives considered, and reasons why those designs weren't chosen

I added a section: https://github.com/tkent-google/explainers/blob/main/form-sizing.md#considered-alternatives

**Comment by rhiaro** [comment]
Thanks for the extra information, that was very helpful, we're happy to conclude this review.
