### ISSUE TITLE
The CSS `word-break: auto-phrase` property

### ISSUE THREAD

**Issue by kojiishi** [w3ctag/design-reviews#891]
Hello TAG!

I'm requesting a TAG review of the CSS `word-break: auto-phrase` property..

This feature enables keeping natural phrases (of multiple words) together when line breaking.

  - Explainer¹ (minimally containing user needs and example code): [url](https://docs.google.com/document/d/1QyPza8XS4aaYD-yA1MHYx56Hy7DZuEm9cAH-A6lTu8c/edit?usp=sharing)
  - Specification URL: [url](https://drafts.csswg.org/css-text-4/#valdef-word-break-auto-phrase)
  - Tests: [wpt folder(s)](https://wpt.fyi/results/css/css-text/word-break/auto-phrase?label=master&label=experimental&aligned)
  - User research: [url to public summary/results of research](https://twitter.com/kojiishi/status/1687688315896733696)
  - Security and Privacy self-review²: [url](https://drafts.csswg.org/css-text-4/#sec)
  - GitHub repo (if you prefer feedback filed there): [url](https://github.com/w3c/csswg-drafts/issues)
  - Primary contacts (and their relationship to the specification):
      - @kojiishi (implementer), @bfgeek (implementer), @fantasai (spec editor), @frivoal (spec editor), @astearns (csswg char), @atanassov (csswg char)
  - Organization(s)/project(s) driving the specification: @fantasai, @frivoal
  - Key pieces of existing multi-stakeholder review or discussion of this specification: https://github.com/w3c/csswg-drafts/issues/7193
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5133892532568064

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: Implementation complete.
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): CSSWG
  - Major unresolved issues with or opposition to this specification: None
  - This work is being funded by: Blink implementation is being done by Google.

We'd prefer the TAG provide feedback as (please delete all but the desired option):
  💬 leave review feedback as a **comment in this issue** and @-notify [@kojiishi (implementer), @bfgeek (implementer), @fantasai (spec editor), @frivoal (spec editor)]

**Comment by rhiaro** [comment]
Hi @kojiishi please could you update your request with the rest of the template filled in?

**Comment by kojiishi** [comment]
Hi @rhiaro, sorry I missed some fields to fill in. Done.

**Comment by torgo** [comment]
Hi @kojiishi we really need an explainer in order to do a review. Also can you please clarify at what stage this is in in the CSS working group? Is this still under discussion or has this reached consensus?

**Comment by kojiishi** [comment]
@torgo I'm an implementer, the design doc linked above is all what I have. The spec was driven at CSSWG so maybe you can ask there?

**Comment by frivoal** [comment]
> Can you please clarify at what stage this is in in the CSS working group?

Quite settled. We might have to address follow up issues if raised, but the core of the discussion has settled, and the spec is where we expect it to be for this feature.

> Explainer

In addition to the document shared by Koji, [appendix H in the spec](https://drafts.csswg.org/css-text-4/#word-phrase-detection), as well as [example 22](https://drafts.csswg.org/css-text-4/#jp-title-break) do give some examples and some high level description of what this is.
