### ISSUE TITLE
DisplayMediaStreamOptions monitorTypeSurfaces

### ISSUE THREAD

**Issue by beaufortfrancois** [w3ctag/design-reviews#892]
こんにちは TAG-さん!

I'm requesting a TAG review of DisplayMediaStreamOptions monitorTypeSurfaces.

When `getDisplayMedia()` is called, the browser offers the user a choice of display surfaces: tabs, windows, or monitors. Using the `monitorTypeSurfaces` option, the web application may now hint to the browser if it prefers to include display surfaces whose type is monitor among the choices offered to the user. The browser may still ignore this hint. Web applications are therefore encouraged to still check the displaySurface setting of the tracks they receive.

  - Explainer: https://github.com/eladalon1983/screen-share-explainers/blob/main/monitorTypeSurfaces_Explainer.md
  - Specification URL: https://w3c.github.io/mediacapture-screen-share/#dom-displaymediastreamoptions-monitortypesurfaces
  - Tests: https://wpt.fyi/results/screen-capture/getdisplaymedia.https.html
  - User research: N/A
  - Security and Privacy self-review: Covered by the [existing questionnaire](https://github.com/w3c/mediacapture-screen-share/blob/gh-pages/questionnaire.md).
  - Primary contacts (and their relationship to the specification):
      - Elad Alon (@eladalon1983), Google
  - Organization(s)/project(s) driving the specification: Google
  - Key pieces of existing multi-stakeholder review or discussion of this specification: https://github.com/w3c/mediacapture-screen-share/issues/261
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5558622137876480

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: N/A
  - The group where the work on this specification is currently being done: W3C WebRTC Working Group
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): W3C WebRTC Working Group
  - Major unresolved issues with or opposition to this specification: N/A
  - This work is being funded by: Google

You should also know that this feature is a simple addition of a single flag to an existing dictionary, following an established pattern that’s also used by a few other keys of the same dictionary (selfBrowserSurface, systemAudio, surfaceSwitching). well-known patterns. We already filed a TAG review for similar options at https://github.com/w3ctag/design-reviews/issues/744 which was marked as satisfied.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @beaufortfrancois @eladalon1983

**Comment by cynthia** [comment]
Discussed this (w/ @martinthomson @rhiaro and @ylafon)  during F2F. We discussed the potential security/privacy implications of this, in particular whether there are ways to steer users in a direction that allows extraction of information and there is low (to zero) risk. We're happy to see this move forward.
