### ISSUE TITLE
Tag review request for the "Dubbing and Audio description Profiles of TTML2"

### ISSUE THREAD

**Issue by cconcolato** [w3ctag/design-reviews#897]
こんにちは TAG-さん!

I'm requesting a TAG review of DAPT (Dubbing and Audio description Profiles of TTML2).

DAPT (Dubbing and Audio description Profiles of TTML2) defines a profile of the Timed Text Markup Language version 2.0 [[TTML2](https://www.w3.org/TR/ttml2/)] intended to support [dubbing](https://w3c.github.io/dapt/#dfn-dubbing) and [audio description](https://w3c.github.io/dapt/#dfn-audio-description) workflows worldwide and to permit usage of visual presentation features from other TTML2 profiles such as [[IMSC](https://www.w3.org/TR/ttml-imsc1.2/)].

  - Explainer¹ (minimally containing user needs and example code): https://github.com/w3c/dapt/wiki/DAPT-Explained
  - Specification URL: https://w3c.github.io/dapt/
  - Tests: Given the spec is a profile of TTML2, most of the features are already tested in TTML test repo, but we will create incremental tests for the extension features defined in DAPT, they will be available at https://github.com/w3c/dapt-tests
  - User research: Not applicable
  - Security and Privacy self-review²: https://github.com/w3c/dapt/wiki/Considerations-for-the-Privacy-and-Security-Reviews
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/dapt
  - Primary contacts (and their relationship to the specification):
      - Nigel Megitt (@nigelmegitt, BBC), chair of TTWG and co-editor
      - Cyril Concolato (@cconcolato, Netflix), co-editor
  - Organization(s)/project(s) driving the specification: TTWG, Netflix, BBC
  - Key pieces of existing multi-stakeholder review or discussion of this specification: Audio Description Community Group, Media Accessibility User Requirements, GitHub issues created by external parties (ITV, Yella Umbrella, ...), Wide Review results.
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): Not applicable

Further details:

  - [X] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: We'd like to have a review by October 31, 2023
  - The group where the work on this specification is currently being done: TTWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): TTWG
  - Major unresolved issues with or opposition to this specification: None
  - This work is being funded by: the companies participating in the editing and TTWG

You should also know that the specification is:
* for an exchange document format used both in workflows and in client delivery
* not defining any Web API
* should help content creators meet the MAUR as there is a gap in the standards space

We'd prefer the TAG provide feedback as:

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by ruoxiran** [comment]
a11y tracked at: https://github.com/w3c/a11y-request/issues/66

**Comment by nigelmegitt** [comment]
Hey TAG, is this floating towards the top of the pile any time soon?

**Comment by rhiaro** [comment]
Sorry for the delay. We have no architectural concerns and are happy to see this work move forward.

**Comment by nigelmegitt** [comment]
Thank you!
