### ISSUE TITLE
CSS `text-spacing` property and its longhands

### ISSUE THREAD

**Issue by kojiishi** [w3ctag/design-reviews#907]
Hello TAG!

I'm requesting a TAG review of CSS `text-spacing` property and their longhands.

This property is a shorthand for setting [text-spacing-trim](https://drafts.csswg.org/css-text-4/#propdef-text-spacing-trim) and [text-autospace](https://drafts.csswg.org/css-text-4/#propdef-text-autospace) in a single declaration. They control the typographic behavior for Han-derived scripts, specifically Chinese and Japanese. Traditional Han-based Korean is also included but Hangul is usually not included.

  - Explainer¹ (minimally containing user needs and example code): [url 1](https://docs.google.com/document/d/10G1uasooKpKjNeyr1wtLV85wFMlc_TK4-vb9LG_3Fzw/edit#heading=h.gvpvufxddzuy), [2](https://docs.google.com/document/d/146Bupkg3nrNALL3bm8UElRd0vsLVH5807xubsnrthDw/edit#heading=h.gvpvufxddzuy)
  - Specification URL: [spec url](https://drafts.csswg.org/css-text-4/#text-spacing-property)
  - Tests: [wpt folder(s) 1](https://wpt.fyi/results/css/css-text?label=master&label=experimental&aligned&q=text-autospace), [2](https://wpt.fyi/results/css/css-text?label=master&label=experimental&aligned&q=text-spacing)
  - Security and Privacy self-review²: [url](https://drafts.csswg.org/css-text-4/#sec)
  - GitHub repo (if you prefer feedback filed there): [url](https://github.com/w3c/csswg-drafts/issues)
  - Primary contacts (and their relationship to the specification):
      - @kojiishi (implementer), @clqsin45 (implementer), @bfgeek (implementer), @fantasai (spec editor), @frivoal (spec editor), @astearns (csswg char), @atanassov (csswg char)
  - Organization(s)/project(s) driving the specification: @fantasai, @frivoal
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):
      - https://chromestatus.com/feature/5202578236768256
      - https://chromestatus.com/guide/edit/5170044014690304

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: Chormium planning to start shipping incrementally, from M120
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): CSSWG
  - Major unresolved issues with or opposition to this specification: None
  - This work is being funded by: Blink implementation is being done by Google.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify [@kojiishi (implementer), @clqsin45 (implementer), @bfgeek (implementer), @fantasai (spec editor), @frivoal (spec editor)]

**Comment by torgo** [comment]
Hi @kojiishi we really need an explainer in order to execute a review. Thanks!

**Comment by kojiishi** [comment]
@torgo I'm an implementer of an existing spec, so the design doc is all what I have. Maybe you can ask at the CSSWG?

**Comment by kojiishi** [comment]
> Can you also let us know more about the status of this work in the CSS working group

@frivoal @fantasai ?

> and multi-browser support. Are there webkit and Mozilla standards positions on this?

WebKit said "[text-spacing is something we’d like to start implementing soon](https://github.com/w3c/csswg-drafts/issues/4246#issuecomment-1397831533)", and Safari Technology Preview has a runtime flag. @nt1m might be able to provide more.

[Mozilla standards-position #903](https://github.com/mozilla/standards-positions/issues/903) has a comment "yes" but I'm not sure if this is from a Mozilla's engineer. @jfkthame @masayukinakano ?

> Can you also let us know about any W3C internationalization review if this has happened?

@r12a was involved in most of discussions for this property at CSSWG, and [W3C Japanese Requirement Task Force](https://github.com/w3c/jlreq) (@kidayasuo chairs this TF) as well.

**Comment by frivoal** [comment]
>> Can you also let us know more about the status of this work in the CSS working group
> @frivoal @fantasai ?

The spec as a whole has yet to reach CR, which would indicate that the CSS-WG thinks it's done with it (unless further external feedback comes), so it is premature to claim stability on the whole feature set, and things are quite interconnected overall.

That said, for this particular part, I think we're getting close. I would expect some further tweaking of the details as we continue to iterate (see https://github.com/w3c/csswg-drafts/pull/9503, or https://github.com/w3c/csswg-drafts/issues/9423, or https://github.com/w3c/csswg-drafts/issues/8511 for instance), but I think the way the feature works overall, and its syntax in particular, are unlikely to change much going forward.

**Comment by ylafon** [comment]
We looked at this during our latest breakout, discussing the "generic" name of `text-spacing-trim` while it applies only to CJK, in contrast, `text-autospace` applies to more than the CJK context.
Considering also the assessment of stability above, we are happy to close this issue.
