### ISSUE TITLE
View Transitions: list of types

### ISSUE THREAD

**Issue by vmpstr** [w3ctag/design-reviews#908]
こんにちは TAG-さん!

I'm requesting a TAG review of View Transitions: list of types.

The [View Transitions](https://drafts.csswg.org/css-view-transitions-1/) feature allows developers to create transitions between DOM states. A significant portion of the transition is a declarative set up, followed by a script trigger. This works well for a single type of transition. However, developers have [expressed interest](https://github.com/w3c/csswg-drafts/issues/8960) to be able to declare multiple transitions in their CSS, and then trigger only one of them from script. The list of types proposal attempts to address this use case.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/vmpstr/web-proposals/blob/main/explainers/view-transition-types.md
  - Specification URL:
    - https://drafts.csswg.org/css-view-transitions-2/#the-active-view-transition-pseudo
    - https://drafts.csswg.org/css-view-transitions-2/#additions-to-document-api 
  - Tests: None yet
  - User research: N/A
  - Security and Privacy self-review²: N/A as there are no additional security implications over View Transitions API. Let me know if you disagree, and I will put together the self-review.
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/csswg-drafts/issues (css-view-transitions-2 label)
  - Primary contacts (and their relationship to the specification):
      - Vladimir Levin (@vmpstr, Google, implementor)
      - Noam Rosenthal (@noamr, Google, spec author)
  - Organization(s)/project(s) driving the specification: Google
  - Key pieces of existing multi-stakeholder review or discussion of this specification: This has been discussed at CSSWG via https://github.com/w3c/csswg-drafts/issues/8960
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5089552511533056

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: None
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): CSSWG
  - Major unresolved issues with or opposition to this specification: We have not head of opposition, but some bikeshedding on the names remains to be done.
  - This work is being funded by: Google

  💬 leave review feedback as a **comment in this issue** and @-notify @vmpstr @noamr

**Comment by LeaVerou** [comment]
Hi @vmpstr,

We just took this up on our breakout A today, but we couldn't find a list of use cases in the explainer. There was [this issue](https://github.com/w3c/csswg-drafts/issues/8960) which is linked, but it was not clear to us whether that is the *only* use case, or whether there are more. It would also be useful to include any alternatives considered. Please take a look [here](https://tag.w3.org/explainers/) for more advice on writing effective explainers.

**Comment by vmpstr** [comment]
Hi @LeaVerou,

Thank you for the feedback. The use-case described in https://github.com/w3c/csswg-drafts/issues/8960 is the same use-case [described in the explainer](https://github.com/vmpstr/web-proposals/blob/main/explainers/view-transition-types.md#:~:text=This%20works%20well,this%20use%20case.), and is the main use-case for this API addition to the View Transitions feature.

We are also discussing using types for a similar use-case in the cross-document navigation case, where the polyfill is potentially harder to implement. We are early in the discussion of how types can be used in that case though.

I've added [alternatives considered](https://github.com/vmpstr/web-proposals/blob/main/explainers/view-transition-types.md#alternatives-considered) section that mentions this as well.
