### ISSUE TITLE
CSS Spelling and Grammar Customization

### ISSUE THREAD

**Issue by schenney-chromium** [w3ctag/design-reviews#913]
こんにちは TAG-さん!

I'm requesting a TAG review of CSS ::spelling and ::grammar pseudo classes, and the text-decoration-line: spelling/grammar-error property values.

CSS highlight pseudo-elements allow developers to style text that the UA has flagged as misspelled or grammatically incorrect, and line decorations exposing the UA’s default decorations for spelling and grammar errors. These features allow authors to choose more legible colors for the default spelling and grammar errors, highlight misspelled words with background colors or other decorations, and implement custom spell checking with native appearance.
For example, authors may customize the appearance of spelling/grammar mistakes when the UA’s default color for a mistake has inadequate contrast with the background color.

  - Explainer¹: [[url]](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/highlight/explainer.md)
  - Specification URL: [[spec url]](https://drafts.csswg.org/css-pseudo-4/#highlight-selectors)
  - Specification URL: [[spec url]](https://www.w3.org/TR/css-text-decor-4/#text-decoration-line-property)
  - Tests: https://wpt.fyi/results/css/css-pseudo?label=master&view=subtest, WPT does not yet allow for setting spelling or grammar errors so most testing is browser vendor internal
  - User research: The feature has already been available experimentally for a long time. For example https://medium.com/@stheodorejohn/marker-spelling-error-grammar-error-css-selectors-to-enhance-web-content-quality-db045f4115e0, 
  - Security and Privacy self-review²: [[url]](https://docs.google.com/document/d/1ppxR9_CnE9wzsfdqWusEcCEAmH4HlLUpF-rDz2N-t9I/edit?usp=sharing)
  - GitHub repo (if you prefer feedback filed there): [url]
  - Primary contacts (and their relationship to the specification):
      - [Stephen Chenney]([schenney-chromium]), [Igalia] Implementor
      - [Elika J. Etemad]([fantasai]), [Apple] Spec editor
  - Organization(s)/project(s) driving the specification: [chromium, Apple]
   - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/4811776539492352

Further details:

  - [Yes] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: WebKit are currently implementing, chromium wants to ship it.
  - The group where the work on this specification is currently being done: CSS
  - Major unresolved issues with or opposition to this specification: None
  - This work is being funded by: Bloomberg

You should also know that...

These features have been enabled under experimental web platform features in chromium since August 2022, and I'm only requesting review now because there's an Intent to Ship and it was discovered that no TAG review was ever done.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify [schenney-chromium]

**Comment by schenney-chromium** [comment]
I see that https://github.com/w3ctag/design-reviews/issues/584 covered some aspects of this, the ::spelling and ::grammar pseudo classes, but not the text-decoration-line: spelling-error and grammar-error.

**Comment by torgo** [comment]
Hi @schenney-chromium - thanks for the opportunity to review this.  We're happy to see this proceed. ✨✨
