### ISSUE TITLE
Animating font-palette

### ISSUE THREAD

**Issue by tursunova** [w3ctag/design-reviews#915]
こんにちは TAG-さん!

I'm requesting a TAG review of Animating font-palette.

The [CSS font-palette property](https://w3c.github.io/csswg-drafts/css-fonts/#font-palette-prop) allows selection of a specific palette used to render a font. For this property, [CSS Fonts 4](https://www.w3.org/TR/web-animations/#animation-type) defined the animation behavior of this property as discrete, which is insufficient to achieve a smooth transition between two selected palettes. Similar to other color transitions in CSS animating the font-palette property should happen by interpolating each of the color record values between start and end palette.

  - Explainer¹ (minimally containing user needs and example code): [Explainer: Animating font-palette](https://docs.google.com/document/d/1XMTrKH003KBOes6hxzI-3E7LTwp5YwFC-rnzoFpFrfw/edit?usp=sharing)
  - Specification URL: https://drafts.csswg.org/css-fonts-4/#font-palette-prop
  - Tests: 
      -  https://wpt.fyi/results/css/css-fonts/animations/font-palette-interpolation.html?label=experimental&label=master&aligned
      -  https://wpt.fyi/results/css/css-fonts/palette-mix-computed.html?label=experimental&label=master&aligned

  - User research: -
  - Security and Privacy self-review²: n/a
  - Primary contacts (and their relationship to the specification):
      - Munira Tursunova, @tursunova, Google
      - Dominik Röttsches, @drott, Google
  - Organization(s)/project(s) driving the specification: CSS WG
  - Key pieces of existing multi-stakeholder review or discussion of this specification: 
      - Proposal: https://github.com/w3c/csswg-drafts/issues/8922
      - CSS WG resolution: https://github.com/w3c/csswg-drafts/issues/8922#issuecomment-1720930646
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): 
      - https://chromestatus.com/feature/5177171439517696
      - https://crbug.com/1400620

Further details:

  - ✅  I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the work on this specification is currently being done: CSS WG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): CSS WG
  - Major unresolved issues with or opposition to this specification: none
  - This work is being funded by: Google

You should also know that...

We'd prefer the TAG provide feedback as (please delete all but the desired option): 

  💬 leave review feedback as a **comment in this issue** and @-notify @tursunova, @drott

**Comment by drott** [comment]
> * Security and Privacy self-review²: n/a

This incremental improvement to the Fonts spec falls under the security and privacy self-review of the CSS Fonts Level 4 spec [as published here in sections 14 and 15](https://drafts.csswg.org/css-fonts-4/#security).

**Comment by LeaVerou** [comment]
Hi there,

This looks great to us. Doesn't add any new syntax, and just enables existing syntax to work — easily a win!

Thank you for flying TAG!

**Comment by drott** [comment]
Thanks for the review and positive feedback, @LeaVerou and others.
