### ISSUE TITLE
@page margin boxes

### ISSUE THREAD

**Issue by mstensho** [w3ctag/design-reviews#918]
TAG、コード コマンドの芸術。 タグを付けてタペストリーを織ります。

I'm requesting a TAG review of @page margin boxes.

Page margin boxes can be defined in paged media (such as printing or when generating PDFs) by authors, to define content outside the page area, i.e. in the margin area. This is the area where the browser normally puts headers and footers (which typically may include the document title, URL, time stamp, page number and total number of pages), if enabled. @page margin boxes enable an author to customize this part of the page - not just at the top and at the bottom, but also on the left and right sides, as well as the corners. The spec defines 16 margin areas - 4 corners, and 3 parts (beginning, middle, end) on each of the 4 sides. Each area is defined via an @-rule nested inside an @page rule.

  - Explainer: https://github.com/mstensho/page-margin-boxes
  - Specification URL: https://drafts.csswg.org/css-page-3/#margin-boxes
  - Tests: WPTs will eventually be found under css/css-page/
  - Security and Privacy self-review: None - https://drafts.csswg.org/css-page-3/#priv-sec
  - Primary contacts (and their relationship to the specification):
      - [Morten Stenshorne](mstensho), [Google] (implementor)
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5195769732923392

Further details:

No browsers are currently known to implement this feature, but it is supported by certain PDF generators, such as Prince XML [1] and Antenna House Formatter [2].

[1] https://www.princexml.com/doc/css-at-rules/
[2] https://www.antenna.co.jp/AHF/help/en/ahf-css6.html

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify mstensho

**Comment by atanassov** [comment]
The feature is well understood and supported by the CSSWG as well as already implemented by UA such as Prince XML. Thank you for opening the review. We are happy to see further improvements worked on by the CSSWG and adoption by browsers.
