### ISSUE TITLE
Streams General issue

### ISSUE THREAD

**Issue by torgo** [w3ctag/design-reviews#92]
As minuted at TPAC 2015 wrap-up session: https://pad.w3ctag.org/p/30-10-2015-minutes.md

**Comment by torgo** [comment]
discussed 11-11 – we need to get someone like @domenic and Chris Wilson on the same call... F2F time would be good. Analysis document needed. "Streams in the Web" ...

**Comment by travisleithead** [comment]
We are looking for a document that clearly defines the different high-level categories of streams: byte streams, timed streams, object streams. We want the document to clearly define some terminology that can be reused among various folks talking about streams (e.g., WebRTC media streams, etc.), and potential conversion patterns between each type of stream (since they can be converted and have specific conversion paradigms). This would help frame some of the existing streams conversations.

**Comment by torgo** [comment]
Taken up at [London F2f](https://github.com/w3ctag/meetings/blob/gh-pages/2016/03-london/agenda.md)

**Comment by travisleithead** [comment]
Taking a look at : https://streams.spec.whatwg.org/

**Comment by travisleithead** [comment]
The above-mentioned document can start with a spec-review of the Streams spec...

**Comment by torgo** [comment]
Taken up at [Stockholm f2f](https://github.com/w3ctag/meetings/blob/gh-pages/2016/07-stockholm/agenda.md). Yes we will produce something. @ylafon will start a document and we will work on this and review at a TPAC.

**Comment by travisleithead** [comment]
Goal:
* Get the various streams straightened out
* understand the use cases
* Write it all down (or at least the good parts) into our Design guidelines.

**Comment by torgo** [comment]
Agreed we make a start on this. @travisleithead @slightlyoff @cynthia to make a start at a break-out session on Thursday.

**Comment by travisleithead** [comment]
Additional relevant meeting minutes: https://pad.w3ctag.org/p/2016-07-30

**Comment by travisleithead** [comment]
OK, new plan:

Per my [previous comment](https://github.com/w3ctag/design-reviews/issues/92#issuecomment-297888293), one of the main goals of this work is to produce text to go into the design-guidelines. We will be moving the bulk of this issue from the design-reviews repo into https://github.com/w3ctag/design-principles/issues/86.

The other part of this work was to do archiology to existing parts of the web platform that aren't using streams but should be. @cynthia will be drafting a blog post, where we will try to crowdsource this question (along with Promises).

**Comment by travisleithead** [comment]
And now, thank you for flying TAG..
