### ISSUE TITLE
Adding a close event to MessagePort API

### ISSUE THREAD

**Issue by nononokam** [w3ctag/design-reviews#923]
こんにちは TAG-さん!

I'm requesting a TAG review of a close event of MessagePort API.

This is a proposal to add a close event which notifies one of the MessagePorts that the other port has been disentangled (i.e., close() is called, an owning document is destroyed, or the port is garbage collected).

  - Explainer¹ (minimally containing user needs and example code): https://github.com/fergald/explainer-messageport-close
  - Specification URL: [MessagePort API:add a close event whatwg/html#9933](https://github.com/whatwg/html/pull/9933)
  - Tests:  https://chromium-review.googlesource.com/c/chromium/src/+/5083156
  - User research: [Add onclose event to MessagePort whatwg/html#1766 (comment)](https://github.com/whatwg/html/issues/1766#issuecomment-1775156012)
  - Security and Privacy self-review²: https://github.com/fergald/explainer-messageport-close?tab=readme-ov-file#tag-security--privacy-questionnaire-answers
  - GitHub repo (if you prefer feedback filed there): [url]
  - Primary contacts (and their relationship to the specification):
      - Nonoka Muraki(@nononokam, Google)
      - Rakina Zata Amni(@rakina, Google)
      - Fergal Daly(@fergald, Google)
  - Organization(s)/project(s) driving the specification: Google
  - Key pieces of existing multi-stakeholder review or discussion of this specification: [Add onclose event to MessagePort whatwg/html#1766](https://github.com/whatwg/html/issues/1766)
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):https://chromestatus.com/feature/5086799659794432

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: My intern term will end on 1/19, so It would greatly benefit our efforts if we could receive reviews as soon as possible.
  - The group where the work on this specification is currently being done: WHATWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): WHATWG
  - Major unresolved issues with or opposition to this specification: N/A
  - This work is being funded by: Google

You should also know that...

[please tell us anything you think is relevant to this review]

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

  ☂️ open a single issue in our GitHub repo **for the entire review**

  💬 leave review feedback as a **comment in this issue** and @-notify @nononokam

**Comment by hober** [comment]
Hi @nononokam!

@torgo @LeaVerou @matatk and I looked at this today and we think this looks pretty good! I'm a little worried about this sort-of exposing GC timing sometimes, but you've already considered that and have ended up in a reasonable place.
