### ISSUE TITLE
Gamepad Trigger Rumble Extension

### ISSUE THREAD

**Issue by gabrielsanbrito** [w3ctag/design-reviews#934]
こんにちは TAG-さん!

I'm requesting a TAG review of Gamepad Trigger Rumble.

Currently, there are gamepads, like the [Microsoft's Xbox](https://www.xbox.com/en-us/accessories/controllers/xbox-wireless-controller#white) and the [Razer Wolverine Ultimate](https://www.razer.com/console-controllers/razer-wolverine-ultimate/RZ06-02250100-R3U1) Controllers, which comes equipped with "impulse triggers" capable of providing trigger-rumble feedback to the user. While the [GamepadHapticActuator](https://w3c.github.io/gamepad/#gamepadhapticactuator-interface), part of the [Gamepad API](https://w3c.github.io/gamepad/), already provides support for dual-rumble effect, it does not allow developers to have access to trigger-rumble yet. This extension will allow game developers to equip their web applications with a wider set of haptics feedback options, making it possible for their users to have a richer and more engaging experience on the web.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/GamepadHapticsActuatorTriggerRumble/explainer.md
  - Specification URL: https://w3c.github.io/gamepad/
  - Tests: [wpt folder(s), if available]
  - User research: None
  - Security and Privacy self-review²: Didn't think it was necessary. Please let me know if it is.
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/gamepad/issues/138
  - Primary contacts (and their relationship to the specification):
      - [name] ([github username]), [organization/s] (repeat as necessary, we recommend including group chairs and editors in this list)
      - Marcos caceres, @marcoscaceres, Apple (chair)
      - Matt Reynolds, @nondebug, Google (editor)
      - Gabriel Brito, @gabrielsanbrito, Microsoft (editor)
      - Steve Becker, @SteveBeckerMSFT, Microsoft (editor)
  - Organization(s)/project(s) driving the specification: Microsoft
  - Key pieces of existing multi-stakeholder (e.g. developers, implementers, civil society) support, review or discussion of this specification:
    - Chromium comments: https://chromestatus.com/feature/5162940951953408
    - Mozilla comments: https://github.com/mozilla/standards-positions/issues/656
    - WebKit comments: https://github.com/WebKit/standards-positions/issues/1
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):

Further details:

  - [X] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: [please provide]
  - The group where the work on this specification is currently being done: [Web Applications Working Group](https://www.w3.org/groups/wg/webapps/)
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): [Web Applications Working Group](https://www.w3.org/groups/wg/webapps/)
  - Major unresolved issues with or opposition to this specification:
  - This work is being funded by:

You should also know that...

Both Chromium and WebKit already have this extension implemented and working behind a feature flag. Moreover, this is an extension to what the Gamepad API spec maintainers now view as a legacy API and we expect future haptic effects will use a new API.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @gabrielsanbrito, @SteveBeckerMSFT

Thanks!

**Comment by torgo** [comment]
Hi @gabrielsanbrito thanks for this - can you clarify where this stands in the working group process at this point? Is this due to be merged with the gamepad spec and is there is consensus in the group to do so?

**Comment by gabrielsanbrito** [comment]
Hi @torgo, thanks for having a look! Yes, there is consensus in the group to include this in the specification (the proposed changes can be found at https://github.com/w3c/gamepad/pull/195). We would still like TAG to have a "horizontal" look on our proposal. However, any type of comment is welcome. 
/cc @stevebeckerMSFT

**Comment by torgo** [comment]
Hi @gabrielsanbrito thanks for this response. On this basis we are happy to close and to see the work go forward.

**Comment by gabrielsanbrito** [comment]
Hi, @torgo Thank you very much for looking into this!
