### ISSUE TITLE
Spec review for Snap Events

### ISSUE THREAD

**Issue by DavMila** [w3ctag/design-reviews#943]
こんにちは TAG-さん!

I'm requesting a TAG review of Snap Events.

[CSS scroll snap](https://drafts.csswg.org/css-scroll-snap-1/#scroll-snap) points are often used as a mechanism to create interactive scroll "selection" components, giving authors control over what areas of its content a scrolling container can settle. This proposal adds 2 JavaScript events, “snapchanging” and “snapchanged”, which fire in response to the scrolling/snapping of containers which snap. snapchanging is a JavaScript event that aims to let the web page know, as early as possible, that a scrolling operation will result in a change in the element the container being scrolled is snapped to. snapchanged is a JavaScript event that fires when a scrolling operation is complete and the scroller has snapped to a different element than it was previously snapped to.

  - Explainer¹ (minimally containing user needs and example code): 
Snapchanged: https://github.com/argyleink/ScrollSnapExplainers/tree/main/js-snapChanged 
Snapchanging: https://github.com/argyleink/ScrollSnapExplainers/tree/main/js-snapChanging 

  - Specification URL: https://drafts.csswg.org/css-scroll-snap-2/#snap-events
  - Tests: [wpt folder(s), if available]
https://wpt.fyi/results/css/css-scroll-snap-2/snapchanging
https://wpt.fyi/results/css/css-scroll-snap-2/snapchanged

  - User research: [url to public summary/results of research]
N/A
  - Security and Privacy self-review²:
As [indicated](https://github.com/argyleink/ScrollSnapExplainers/tree/main/js-snapChanging#privacy) in the explainer, there are no known privacy or security issues.
  - GitHub repo (if you prefer feedback filed there):
  - Primary contacts (and their relationship to the specification):
      - David Awogbemila (@DavMila), Google
      - Robert Flack (@flackr), Google

  - Organization(s)/project(s) driving the specification: CSSWG
  - Key pieces of existing multi-stakeholder (e.g. developers, implementers, civil society) support, review or discussion of this specification:
    - Chromium comments: [url]
    - Mozilla comments: https://github.com/mozilla/standards-positions/issues/1008 
    - WebKit comments: https://github.com/WebKit/standards-positions/issues/333
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):
    - [snapchanging chromestatus](https://chromestatus.com/feature/5159140364386304)
    - [snapchanged chromestatus](https://chromestatus.com/feature/5826089036808192)

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: Interested in shipping when possible
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue):
  - Major unresolved issues with or opposition to this specification:
    - csswg-drafts issue [#10173](https://github.com/w3c/csswg-drafts/issues/10173): Should snap events fired at the document bubble?
    - csswg-drafts issue [#10175](https://github.com/w3c/csswg-drafts/issues/10175):  Should pseudo-elements show up as null SnapEvent.snapTargetBlock/Inline?
    - csswg-drafts issue [#9697](https://github.com/w3c/csswg-drafts/issues/9697): Use present tense for snap event names.
  - This work is being funded by: Google

**Comment by martinthomson** [comment]
Discussed with @hober.  This looks like it is on track.  The choices made all seem appropriate.

Thanks for the detailed explainer.
