### ISSUE TITLE
Early review request for "Explicit JavaScript Compile Hints"

### ISSUE THREAD

**Issue by marjakh** [w3ctag/design-reviews#947]
こんにちは TAG-さん!

I'm requesting a TAG review of "Explicit JavaScript Compile Hints".

This proposal introduces a new magic comment that signals to browsers that the functions in a JavaScript file are likely to be needed by the website. This allows the browser to parse and compile them eagerly, which can improve page load times.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/explainers-by-googlers/explicit-javascript-compile-hints-file-based
  - User research: None
  - Security and Privacy self-review: The feature only affects performance; no privacy implications.
  - GitHub repo (if you prefer feedback filed there): https://github.com/explainers-by-googlers/explicit-javascript-compile-hints-file-based/
  - Primary contacts (and their relationship to the specification):
      - [Marja Hölttä](https://github.com/marjakh), V8 / Google
  - Organization/project driving the design: V8 / Google
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): None

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): Not set up yet
  - The group where standardization of this work is intended to be done ("unknown" if not known): Unknown; as it doesn't change JavaScript semantics, TC39 is likely not the right venue.
  - Existing major pieces of multi-stakeholder review or discussion of this design: No artifacts; see https://github.com/explainers-by-googlers/explicit-javascript-compile-hints-file-based/blob/main/README.md#stakeholder-feedback--opposition based on informal discussions.
  - Major unresolved issues with or opposition to this design: See above
  - This work is being funded by: Google

Thanks in advance!

**Comment by torgo** [comment]
In general, the TAG is skeptical of introducing a pattern which introduces semantics in comments. It would be more useful to use decorators or another pattern that cannot be stripped. It seems like this is more general than just browsers, so we feel this probably should be a topic for TC39. We're going to close this for now and we encourage you to bring this to TC39 and come back to us.
