### ISSUE TITLE
ServiceWorkerAutoPreload

### ISSUE THREAD

**Issue by sisidovski** [w3ctag/design-reviews#963]
こんにちは TAG-さん!

I'm requesting a TAG review of ServiceWorkerAutoPreload .

ServiceWorker fetch handlers are used for various reasons but there are many cases where developers use them with the intention of serving resources faster than the network, however in some cases ServiceWorker could be slower because of its startup. To fulfill their intention, this document proposes the introduction of “ServiceWorkerAutoPreload”, a new loading strategy for ServiceWorker. ServiceWorkerAutoPreload is a mode where the browser issues a network request (i.e. a regular request which may result in a HTTP cache hit or an actual fetch) in parallel with the ServiceWorker bootstrap, and consumes the network request result inside the fetch handler.

  - Explainer¹ (minimally containing user needs and example code): [url](https://github.com/explainers-by-googlers/service-worker-auto-preload)
  - User research: it is a well-studied phenomenon that faster sites are better for users, but we have not conducted any user studies specifically on this feature.
  - Security and Privacy self-review²: [url](https://github.com/explainers-by-googlers/service-worker-auto-preload/blob/main/security-privacy-questionnaire.md)
  - GitHub repo: [url](https://github.com/explainers-by-googlers/service-worker-auto-preload)
  - Primary contacts (and their relationship to the specification):
      - Shunya Shishido (@sisidovski), Google.
  - Organization/project driving the design: Chrome browser loading team.
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status):
    - https://chromestatus.com/feature/5194817700364288

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): W3C Service Workers Working Group
  - The group where standardization of this work is intended to be done ("unknown" if not known): W3C Service Workers Working Group
  - Existing major pieces of multi-implementer review or discussion of this design:
    - https://github.com/mozilla/standards-positions/issues/1036
    - https://github.com/WebKit/standards-positions/issues/359
  - Major unresolved issues with or opposition to this design: Still not widely heard feedback from the community, we don't see major issues and oppositions yet.
  - This work is being funded by: Google

**Comment by martinthomson** [comment]
Hi @sisidovski, the TAG just took a brief look at this and - on the surface - this looks pretty reasonable.  However, as a personal proposal (backed by Google or not), it is a little early to be seeking TAG feedback.  We encourage you to take this to the Service Workers Working Group, just as you identified, and discuss it further there.
