### ISSUE TITLE
A layer attribute for layering of linked CSS style sheets in HTML

### ISSUE THREAD

**Issue by mirisuzanne** [w3ctag/design-reviews#970]
こんにちは TAG-さん!

I'm requesting a TAG review of an HTML `layer` attribute for the `<link>` tag.

One of the primary use-cases for CSS Cascade Layering is to manage the priority of third-party CSS (libraries and design systems) in relation to site-specific styles. It's currently possible to manage this layering on the CSS `@import` rule, as defined in [CSS Cascading and Inheritance Level 5](https://www.w3.org/TR/css-cascade-5/). However, there are many situations where authors do not want to use `@import` for performance reasons, or cannot use `@import` because of build tooling. Providing this functionality on the HTML `<link>` tag would bring it in better alignment with the CSS import functionality.

There seems to be broad consensus on this aspect of the feature, and I wanted to get formal review in order to hopefully move the conversation forward.

  - Explainer¹ (minimally containing user needs and example code): https://css.oddbird.net/layers/link-layer/
  - Primary contacts (and their relationship to the specification):
      - Miriam Suzanne (@mirisuzanne), Invited Expert (explainer author & Cascade L5 co-editor)
      - Simon Pieters (@zcorpan), Mozilla (WHATWG contact)
      - Alan Stearns (@astearns), Adobe (CSSWG Co-Chair)
  - Organization/project driving the design: CSSWG/WHATWG
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): None yet

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): CSSWG & WHATWG
  - The group where standardization of this work is intended to be done ("unknown" if not known): WHATWG
  - Existing major pieces of multi-implementer review or discussion of this design:
    - (WHATWG #7540)
      [Allow authors to apply new css features (like cascade layers) while linking stylesheets](https://github.com/whatwg/html/issues/7540)
    - (CSSWG #5853)
      [Provide an attribute for assigning a `<link>` to a cascade layer](https://github.com/w3c/csswg-drafts/issues/5853)
  - Major unresolved issues with or opposition to this design: The discussions have generally stalled in trying to provide an additional 'support' condition to stylesheet links, which I will split into a separate explainer.
  - This work is being funded by: Some of my work on the feature has been funded by Google Chrome

**Comment by jyasskin** [comment]
We discussed this in a breakout session with the conclusion that we like it, and we're happy for the WHATWG to figure out the exact name and details. Thanks for working on it!
