### ISSUE TITLE
Before 6 August 2023 -- Guidance on Applying WCAG 2 to Non-Web Information and Communications Technologies (WCAG2ICT) - Google Chrome - Daniel (w3.org)

### ISSUE THREAD

**Issue by daniel-montalvo** [w3ctag/design-reviews#973]
こんにちは TAG-さん!

I'm requesting a TAG review of Guidance on Applying WCAG 2 to Non-Web Information and Communications Technologies (WCAG2ICT).

Guidance on Applying WCAG 2 to Non-Web Information and Communications Technologies (WCAG2ICT) describes how the Web Content Accessibility Guidelines (WCAG) can be applied to non-web information and communications technologies (ICT), including documents and software. 

  - Explainer¹ (minimally containing user needs and example code): https://www.w3.org/WAI/standards-guidelines/wcag/non-web-ict/
  - Specification URL: https://www.w3.org/TR/wcag2ict-22/
  - Tests: [wpt folder(s), if available]
  - User research: [url to public summary/results of research]
  - Security and Privacy self-review²: https://www.w3.org/TR/wcag2ict-22/#privacy-considerations https://www.w3.org/TR/wcag2ict-22/#security-considerations
  - GitHub repo: https:///www.github.com/w3c/wcg2ict/
  - Primary contacts (and their relationship to the specification):
      - Mary Jo Mueller (maryjom), IBM, TF Facilitator
      - Daniel Montalvo (daniel-montalvo), W3C, Staff Contact
      - Phil Day (pday1), NCR Atleos, Editor
      - Chris Loiselle (ChrisLoiselle), Oracle Corporation, Editor
  - Organization(s)/project(s) driving the specification: IBM, NCR, Oracle, 
  - Key pieces of existing multi-stakeholder (e.g. developers, implementers, civil society) support, review or discussion of this specification
  - Key pieces of multi-implementer support:
    - Chromium comments: [url]
    - Mozilla comments: https://github.com/mozilla/standards-positions/issues/NNN
    - WebKit comments: https://github.com/WebKit/standards-positions/issues/NNN
    - etc...
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):

Further details:

  - [X] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: please provide you comments before 6 August 2024
  - The group where the work on this specification is currently being done: https://www.w3.org/groups/wg/ag/
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue):
  - Major unresolved issues with or opposition to this specification:
  - This work is being funded by:

You should also know that...

[please tell us anything you think is relevant to this review]

**Comment by matatk** [comment]
Thanks for your review request, and to the WCAG2ICT TF for this update. We discussed this in our plenary, noted [APA WG's review](https://github.com/w3c/wcag2ict/labels/a11y-needs-resolution), and so decided we do not have anything further to add.

**Comment by daniel-montalvo** [comment]
Thanks much @matatk for updating this issue with your conclusions.
