### ISSUE TITLE
FYI Private State Token API Permissions Policy Default Allowlist Wildcard

### ISSUE THREAD

**Issue by arichiv** [w3ctag/design-reviews#990]
こんにちは TAG-さん!

I'm requesting a TAG review of Private State Token API Permissions Policy Default Allowlist Wildcard.

Access to the Private State Token API is gated by Permissions Policy features. We proposed to update the default allowlist for both `private-state-token-issuance` and `private-state-token-redemption` features from self to * (wildcard).

  - Explainer: https://github.com/WICG/trust-token-api/blob/main/README.md
  - Specification: https://github.com/WICG/trust-token-api/pull/306
  - WPT Tests: https://github.com/web-platform-tests/wpt/tree/master/permissions-policy
  - User research: https://github.com/WICG/trust-token-api/issues/106
  - Security and Privacy self-review: https://docs.google.com/document/d/1KPa5OQtp-n6wmf5PTDNSd-pGP993sOtZfl0LbT5fopk/edit#heading=h.95atawj7yqzu
  - GitHub repo: https://github.com/WICG/trust-token-api/tree/
  - Primary contacts:
      - @arichiv, Google Chrome
      - @aykutbulut, Google Chrome
      - @dvorak42, Google Chrome
      - @krgovind, Google Chrome
  - Organization/project driving the specification: Google Chrome
  - Multi-stakeholder support:
    - Chromium comments: https://issues.chromium.org/u/1/issues/353738486
    - Mozilla comments: https://github.com/mozilla/standards-positions/issues/1066
    - WebKit comments: https://github.com/WebKit/standards-positions/issues/391
  - Status/issue trackers for implementations: https://chromestatus.com/feature/5205548434456576

Further details:

  - [X] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: None
  - The group where the work on this specification is currently being done: WICG
  - Major unresolved issues with or opposition to this specification: None
  - This work is being funded by: Google Chrome

Past Evaluation: https://github.com/w3ctag/design-reviews/issues/414

**Comment by jyasskin** [comment]
I left some questions in https://groups.google.com/a/chromium.org/g/blink-dev/c/5jI8kLLdIFw/m/_810WhKGAwAJ, and we should wait for a reply before discussing in the TAG.

**Comment by martinthomson** [comment]
We discussed this in a breakout and have a couple concerns:
  
* This change increases the by-default exposure of the page to entities that might "use up" its limit of 2 issuers. You've suggested that the top-level page should call the API to explicitly pick its issuers, before allowing 3p script to run. We're skeptical that that's a practical defense. You're right that it's a pre-existing issue with the API, but because this change makes the risk worse, it would be good to improve the defense before making this change.
  
* We're not the right body to judge whether the privacy implications are reasonable. Could you ask the Privacy WG to review this system?

**Comment by anderagakura** [comment]
Trying to understand the [blink discussion](https://groups.google.com/a/chromium.org/g/blink-dev/c/5jI8kLLdIFw) and the privacy side : 
- In case of the user denies giving consent to X vendors / tech via the CMP (Consent Management Platform), will the token be shared cross site if a wildcard is set anyway? The question also works with the Global privacy control
- Is there a way to prevent any adtech to redeem the token to display an ads anywhere outside? (But I think this question is already in the blink discussion)
- Not related but somehow related, if the token is considered First party tracking ([Potential risk noted in the spec](https://github.com/WICG/trust-token-api/blob/main/README.md#first-party-tracking-potential)) then combined with the wildcard, you have a cross site tracking : How to prevent that?
