### ISSUE TITLE
TAG Review for CSS Values & Units Level 5

### ISSUE THREAD

**Issue by fantasai** [w3ctag/design-reviews#993]
안녕하세요 TAG씨!

I'm requesting a TAG review of [CSS Values & Units Level 5](https://www.w3.org/TR/css-values-5/).

This specification is the next level over [CSS Values & Units Level 4](https://www.w3.org/TR/css-values-4/) and introduces a variety of new functional notations as well as a syntax variation, see [Changes/Additions List vs CSS Values and Units 4](https://www.w3.org/TR/css-values-5/#additions-L4). (Note: Some aspects of this spec have received independent TAG review already, such as `calc-size()`.)

  - Explainer¹: No single document, but see the following per-feature issues:
      * [Interpolation (`mix()`/`progress()`](https://github.com/w3c/csswg-drafts/issues/6245)
      * ["Comma upgrading"](https://github.com/w3c/csswg-drafts/issues/9539)
      * [`random()`/`random-item()`](https://github.com/w3c/csswg-drafts/issues/2826)
      * [`first-valid()`](https://github.com/w3c/csswg-drafts/issues/5055)
      * [`sibling-count()`/`sibling-index()`](https://github.com/w3c/csswg-drafts/issues/4559)
  - Specification: [CSS Values & Units Level 5](https://www.w3.org/TR/css-values-5/).
  - WPT Tests: Some in https://wpt.live/css/css-values/
  - User research: Not much, mostly ad-hoc.
  - Security and Privacy self-review²: See https://www.w3.org/TR/css-values-5/#security
  - GitHub repo: https://github.com/w3c/csswg-drafts/issues
  - Primary contacts:
      - Tab Atkins (@tabatkins), Google, editor
      - Elika Etemad (@fantasai), Apple, editor
  - Organization/project driving the specification: CSS Working Group
  - Multi-stakeholder support³: See issues above. CSSWG works under strong consensus rules, and includes participation from Apple, Google, Mozilla, and others.
  - Status/issue trackers for implementations⁴:

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: Some features are currently under active development.
  - The group where the work on this specification is currently being done: CSSWG
  - The group where standardization of this work is intended to be done (if different from the current group):
  - Major unresolved issues with or opposition to this specification: No opposition, just a pile of issues and suggestions.
  - This work is being funded by: CSSWG Members

**Comment by torgo** [comment]
We feel as this is a core competency for the working group and with our brief review we don't see anything that needs our further review.
