### ISSUE TITLE
CSS Scoping; :has-slotted

### ISSUE THREAD

**Issue by keithamus** [w3ctag/design-reviews#999]
こんにちは TAG-さん!

I'm requesting a TAG review of `:has-slotted`.

The :has-slotted pseudo-class matches [slot](https://html.spec.whatwg.org/multipage/scripting.html#the-slot-element) elements which have a non-empty list of [slotted nodes](https://dom.spec.whatwg.org/#find-slotables). When [:has-slotted](https://drafts.csswg.org/css-scoping-1/#selectordef-has-slotted) matches a slot with fallback content, we can conclude that the fallback content is not being displayed.

  - Explainer¹:https://drafts.csswg.org/css-scoping-1/#the-has-slotted-pseudo
  - Specification:https://drafts.csswg.org/css-scoping-1/#the-has-slotted-pseudo
  - WPT Tests: https://wpt.fyi/results/css/css-scoping?label=experimental&label=master&aligned
  - User research:
  - Security and Privacy self-review²:
  - GitHub repo: https://github.com/w3c/csswg-drafts
  - Primary contacts:
      - Keith Cirkel (@keithamus), Microsoft/GitHub, Implementer
      - Lea Verou (@LeaVerou), W3C Invited Expert, Specifier
  - Organization/project driving the specification: Font Awesome / GitHub ?
  - Multi-stakeholder support³:
    - Chromium comments:
    - Mozilla comments: https://github.com/mozilla/standards-positions/issues/1079
    - WebKit comments: https://github.com/WebKit/standards-positions/issues/404
    - {{...include feedback/review from developers, implementers, civil society, and others}}
  - Status/issue trackers for implementations⁴:

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines:
  - The group where the work on this specification is currently being done:
  - The group where standardization of this work is intended to be done (if different from the current group):
  - Major unresolved issues with or opposition to this specification:
  - This work is being funded by:

You should also know that...

**Comment by jyasskin** [comment]
We discussed this in a breakout today and we don't see any architectural concerns with this, so we're happy for this to move forwards. Thank you!
